### ISSUE TITLE
Tuple format leak in temporary spaces

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#9719] opened 2024-02-20 19:41 UTC
This snippet quickly makes Tarantool run out of tuple formats.
```Lua
box.cfg{}
require('fiber').set_max_slice(1000000000)
for i = 1, 100000 do
    space = box.schema.space.create('test', {type = 'temporary'})
    space:drop()
end
```
```
---
- error: 'Tuple format limit reached: 65536'
...
```
Collecting Lua garbage doesn't help, the formats still linger somewhere.

**Comment by igormunkin** [comment] 2024-02-21 06:42
> Collecting Lua garbage doesn't help, the formats still linger somewhere.

@Gerold103, this is might wrong for the example above. JFYI, the created Lua object `space` is anchored by `_G` in your snippet, so I suggest to add `local` keyword for the `space` variable initialization and re-check your statement regarding Lua GC.

**Comment by Gerold103** [comment] 2024-02-21 17:33
Nope, nothing changed. The lua space objects don't even reference the format. They only store space id.

**Comment by gmoshkin** [comment] 2024-02-22 18:49
Duplicate of https://github.com/tarantool/tarantool/issues/9296

**Closed** 2024-03-25 10:53 UTC
Labels: bug, ddl
