### ISSUE TITLE
test: flaky box-tap/key_def.test.lua test on Fedora 28

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5049] opened 2020-06-05 08:59 UTC
Tarantool version:
 Tarantool 2.5.0-99-gf5dfde5ca
 Target: Linux-x86_64-RelWithDebInfo
 Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
 Compiler: /usr/bin/cc /usr/bin/c++
 C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
 CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type

OS version:
Fedora 28

Bug description:
https://gitlab.com/tarantool/tarantool/-/jobs/582734857
https://gitlab.com/tarantool/tarantool/-/jobs/582697366
https://gitlab.com/tarantool/tarantool/-/jobs/582450305
https://gitlab.com/tarantool/tarantool/-/jobs/580425002

```
 [414] box-tap/key_def.test.lua                                        [ fail ]
 [414] Test failed! Output from reject file box-tap/key_def.reject:
 [414] TAP version 13
 [414] 1..24
 [414] ok - Pass no key parts
 [414] ok - Pass a garbage instead of key parts
 [414] ok - Pass a field on an unknown type
 [414] ok - Try to use collation_id before box.cfg{}
 [414] ok - Try to use collation before box.cfg{}
 [414] ok - Try to use both collation_id and collation
 [414] ok - Unknown collation_id
 [414] ok - Unknown collation name
 [414] ok - Bad parts parameter type
 [414] ok - No parameters
 [414] ok - Two parameters
 [414] ok - Invalid JSON path
 [414] ok - Multikey JSON path
 [414] ok - Success case; one part
 [414] ok - Success case; one part with a JSON path
 [414] ok - Success case; `field` is alias to `fieldno`
 [414] ok - Field and fieldno can not be set both
 [414]     # extract_key()
 [414]     1..13
 [414]     ok - case 1
 [414]     ok - case 2
 [414]     ok - JSON path (tuple argument)
 [414]     ok - JSON path (table argument)
 [414]     ok - short tuple with a nullable part
 [414]     ok - short tuple with a non-nullable part (case 1)
 [414]     ok - short tuple with a non-nullable part (case 2)
 [414]     ok - short tuple with a non-nullable part (case 3)
 [414]     ok - wrong field type
 [414]     ok - invalid JSON structure
 [414]     ok - tuple with optional parts - case 1
 [414]     ok - tuple with optional parts - case 2
 [414]     ok - tuple with optional parts - case 3
 [414]     # extract_key(): end
 [414] ok - extract_key()
 [414]     # compare()
 [414]     1..8
 [414]     ok - case 1: great (tuple argument)
 [414]     ok - case 2: less (tuple argument)
 [414]     ok - case 3: less (tuple argument)
 [414]     ok - case 4: equal (tuple argument)
 [414]     ok - case 1: great (table argument)
 [414]     ok - case 2: less (table argument)
 [414]     ok - case 3: less (table argument)
 [414]     ok - case 4: equal (table argument)
 [414]     # compare(): end
 [414] ok - compare()
 [414]     # compare_with_key()
 [414]     1..2
 [414]     ok - table
 [414]     ok - tuple
 [414]     # compare_with_key(): end
 [414] ok - compare_with_key()
 [414]     # totable()
 [414]     1..2
 [414]     ok - case 1
 [414]     ok - case 2
 [414]     # totable(): end
 [414] ok - totable()
 [414]     # __serialize()
 [414]     1..2
 [414]     ok - case 1
 [414]     ok - case 2
 [414]     # __serialize(): end
 [414] ok - __serialize()
 [414]     # tostring()
 [414]     1..2
 [414]     ok - case 1
 [414]     ok - case 2
 [414]     # tostring(): end
 [414] ok - tostring()
 [414]     # merge()
 [414]     1..6
 [414]     ok - case 1: verify with :totable()
 [414]     ok - case 1: verify with :extract_key()
 [414] 
 [414] Last 15 lines of Tarantool Log file [Instance "app_server"][/build/usr/src/debug/tarantool-2.5.0.99/test/var/414_box-tap/key_def.test.lua.tarantool.log]:
 [414] 2020-06-05 04:47:35.566 [34192] main/103/key_def.test.lua C> Tarantool 2.5.0-99-gf5dfde5ca
 [414] 2020-06-05 04:47:35.566 [34192] main/103/key_def.test.lua C> log level 5
 [414] 2020-06-05 04:47:35.566 [34192] main/103/key_def.test.lua I> mapping 268435456 bytes for memtx tuple arena...
 [414] 2020-06-05 04:47:35.566 [34192] main/103/key_def.test.lua I> mapping 134217728 bytes for vinyl tuple arena...
 [414] 2020-06-05 04:47:35.572 [34192] main/103/key_def.test.lua I> instance uuid 9aa2109b-f8c5-49d7-99f0-e449e4b0d48b
 [414] 2020-06-05 04:47:35.573 [34192] main/103/key_def.test.lua I> initializing an empty data directory
 [414] 2020-06-05 04:47:35.587 [34192] main/103/key_def.test.lua I> assigned id 1 to replica 9aa2109b-f8c5-49d7-99f0-e449e4b0d48b
 [414] 2020-06-05 04:47:35.587 [34192] main/103/key_def.test.lua I> cluster uuid 63d413c9-4685-4333-9e1e-c235df331f42
 [414] 2020-06-05 04:47:35.589 [34192] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
 [414] 2020-06-05 04:47:35.591 [34192] snapshot/101/main I> done
 [414] 2020-06-05 04:47:35.592 [34192] main/103/key_def.test.lua I> ready to accept requests
 [414] 2020-06-05 04:47:35.592 [34192] main/105/checkpoint_daemon I> scheduled next checkpoint for Fri Jun  5 05:55:11 2020
 [414] 2020-06-05 04:47:35.594 [34192] main utils.c:1045 E> LuajitError: builtin/fun.lua:958: attempt to call local 'gen_x' (a nil value)
 [414] 2020-06-05 04:47:35.594 [34192] main F> fatal error, exiting the event loop
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment] 2020-06-05 09:14
Duplicate of #4252.

**Closed** 2020-06-05 13:26 UTC
Labels: flaky test, qa
