### ISSUE TITLE
Strange behaviour of master-master replica

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1893] opened 2016-11-03 14:24 UTC
using 1.6
Start first node without replication_source
Start three another nodes with replication_source = first_node (and maybe other nodes)
Set replication_source in first node and restart it
Finally there is a cluster of 4 nodes with replication_source={all nodes}
If somebody restarts the older nodes - they successfully catch up and go on.
The problem:
If the first node is restarted - other replicas stop with a message:
```
replication:
status: stopped
idle: 436.87727499008
message: 'Missing .xlog file between LSN 529939408 {1: 529939106
```
Details can be obtained in avito chat

**Comment by rtsisyk** [comment] 2016-11-11 05:53
Probably duplicate of #748

**Comment by rtsisyk** [comment] 2016-11-14 17:10
Caused by #1912

**Closed by rtsisyk** 2016-11-14 17:10 UTC
Labels: bug, customer, prio1
