### ISSUE TITLE
Add packages for brand new UBUNTU 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by no1seman** [tarantool/tarantool#7062] opened 2022-04-21 19:47 UTC
Since brand new UBUNTU 22.04 Jammy Jellyfish released seems need to add packages for it into CI and publish debs

**Comment by Totktonada** [comment] 2022-04-22 09:34
Duplicate of https://github.com/tarantool/tarantool-qa/issues/160.

**Comment by NickVolynkin** [comment] 2022-04-22 10:30
Duplicate of https://github.com/tarantool/tarantool-qa/issues/160

**Closed by NickVolynkin** 2022-04-22 10:30 UTC
Labels: feature, teamX
