### ISSUE TITLE
No info to fix replication

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#2811] opened 2017-10-09 16:07 UTC
If you will have master-master replication and get duplcate data like that:

```
Duplicate key exists in unique index 'id' in space 'test'
```

You can't fix your replica. Logs rotated and not enough info which row duplicated. If you will reload data you can lost data from another master node.

**Comment by rtsisyk** [comment] 2017-10-09 17:26
Duplicate of https://github.com/tarantool/tarantool/issues/2779

**Closed by rtsisyk** 2017-10-09 17:26 UTC
Labels: duplicate
