### ISSUE TITLE
Allow to initialize logging before box.cfg

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#4304] opened 2019-06-21 20:42 UTC
In some cases it is needed to delay the call to box.cfg{} until you receive configuration from an external source (say consul or etcd). And it is also possible that somewhere along the way you'll get an error that will cause your tarantool instance to shut down or fail. This message will not get logged, because the log file gets initialized during the call to box.cfg{}.

What I propose is to be able to call `log.init()` before box.cfg{}.

Here's how it can be used:

```lua
tarantool> log.init(nil, 5, false, 'json', false)
---
...

tarantool> log.info('asdf')
{"time": "2019-06-21T23:35:03.231+0300", "level": "INFO", "message": "asdf", "pid": 74232 , "cord_name": "main", "fiber_id": 102, "fiber_name": "interactive", "file": "[C]", "line": -1}
---
...
```

Here's a patch that roughly accomplishes this

```diff
diff --git a/extra/exports b/extra/exports
index b8c42c0df..b86f92873 100644
--- a/extra/exports
+++ b/extra/exports
@@ -69,6 +69,7 @@ log_type
 say_set_log_level
 say_logrotate
 say_set_log_format
+say_logger_init
 tarantool_uptime
 tarantool_exit
 log_pid
diff --git a/src/lib/core/say.c b/src/lib/core/say.c
index 0b2cf2c34..38ce6324e 100644
--- a/src/lib/core/say.c
+++ b/src/lib/core/say.c
@@ -196,7 +196,6 @@ say_set_log_format(enum say_format format)

        switch (format) {
        case SF_JSON:
-               assert(log_default->type != SAY_LOGGER_SYSLOG);
                format_func = say_format_json;
                break;
        case SF_PLAIN:
diff --git a/src/lua/log.lua b/src/lua/log.lua
index 312c14d5e..fb4688ba0 100644
--- a/src/lua/log.lua
+++ b/src/lua/log.lua
@@ -30,6 +30,10 @@ ffi.cdef[[
     extern void
     say_logrotate(struct ev_loop *, struct ev_signal *, int);

+    void
+    say_logger_init(const char *init_str, int level, int nonblock,
+        const char *format, int background);
+
     enum say_level {
         S_FATAL,
         S_SYSERROR,
@@ -155,6 +159,10 @@ local compat_v16 = {
     end;
 }

+local function init(init_str, level, nonblock, format, background)
+    ffi.C.say_logger_init(init_str, level, nonblock, format, background)
+end
+
 return setmetatable({
     warn = say_closure(S_WARN);
     info = say_closure(S_INFO);
@@ -165,6 +173,7 @@ return setmetatable({
     pid = log_pid;
     level = log_level;
     log_format = log_format;
+    init = init;
 }, {
     __index = compat_v16;
 })
```

**Comment by Gerold103** [comment] 2019-06-26 21:45
Duplicate of https://github.com/tarantool/tarantool/issues/689

**Comment by kyukhin** [comment] 2019-07-18 11:49
Closing as duplicate. Moving #689 out of /dev/null

**Closed by kyukhin** 2019-07-18 11:49 UTC
