### ISSUE TITLE
Iterator types are not validated in request

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1467] opened 2016-05-05 16:08 UTC
For example, I can use `BITSET_ALL_SET` on `HASH` index types in IProto.

**Comment by bigbes** [comment] 2016-05-05 16:19
`TREE` index is not affected

**Comment by rtsisyk** [comment] 2016-05-31 20:34
Confirmed:
```
box.space.test:select({}, {iterator = 'BITS_ALL_SET' } )
<HANGS>
```

Probably 1.6.8 regression caused by my buggy refactoring.

**Comment by rtsisyk** [comment] 2016-06-09 10:07
Fixed in 1.6.8-702-g3136f5e

**Closed by rtsisyk** 2016-06-09 10:07 UTC
Labels: bug, regression
