### ISSUE TITLE
vinyl: auto_increment

### ISSUE THREAD

**Issue by dedok** [tarantool/tarantool#1843] opened 2016-10-14 14:34 UTC
Client works in parallels around 20 threads

-- Client ha an error: Duplicate key exists in unique index 'primary' in space 'nodes'
function a(...)
  return auto_increment{...}
end

-- Client has an error: Transaction has been aborted by conflict
function b(...)
  box.begin()
  local res = auto_increment{...}
  box.commit()
  return res
end

**Comment by kostja** [comment] 2017-04-02 05:52
A proper support for auto-increment in vinyl requires multi-engine transactions or isolated transactions.
We could do isolated transactions perhaps, we're going to need them for SQL/PSM anyway.

**Comment by rtsisyk** [comment] 2017-05-18 09:50
The primary problem that there is no way to use some key in memtx space for autoincrement  because 1.7.x doesn't have cross-engine transactions in 1.7.x (see #1958).  Moreover, even with the proposed new cross-engine transaction manager such types of transactions will be aborted by conflicts due to limitations of the transaction manager. Kostja suggests to implement autonomous transactions and perform this increment outside of the calling transaction. 

From https://oracle-base.com/articles/misc/autonomous-transactions:

> Autonomous transactions allow you to leave the context of the calling transaction, perform an independent transaction, and return to the calling transaction without affecting it's state. The autonomous transaction has no link to the calling transaction, so only commited data can be shared by both transactions.

Since active transaction is currently bounded to the fiber, I have no idea how to implement two or more simultaneous transactions in the same fiber. This ticket is complicated and requires significant research.

**Comment by kostja** [comment] 2017-06-13 06:09
For vinyl, we will implement it using an autonomous transaction in memtx. For memtx, we will continue using a single-engine transaction. All other comments on this will be added in scope of gh-389

**Comment by kostja** [comment] 2017-06-29 20:47
Closing as duplicate of gh-389

**Closed by kostja** 2017-06-29 20:47 UTC
Labels: bug, prio3, vinyl
