### ISSUE TITLE
CLI mode, missing working dir .rocks in package.path & package.cpath

### ISSUE THREAD

**Issue by albenik** [tarantool/tarantool#2979] opened 2017-12-03 11:12 UTC
I created and launched database as described in documentation https://tarantool.org/en/doc/1.7/book/getting_started/using_binary.html#creating-a-database

1. `mkdir ~/tarantool_sandbox`
2. `cd ~/tarantool_sandbox`
3. `tarantoolctl rocks install queue`
3. `tarantool`
4. `box.cfg{listen = 3301}`
5.  `require 'queue'`

At step 5 I has a `file not found` error

But after manually added

```
package.path = "/Users/macuser/tarantool_sandbox/.rocks/share/tarantool/?.lua;" .. package.path
package.path = "/Users/macuser/tarantool_sandbox/.rocks/share/tarantool/?/init.lua;" .. package.path
```

problem was gone away

## System info

```
brew info tarantool
tarantool: stable 1.7.5.184 (bottled), HEAD
In-memory database and Lua application server
https://tarantool.org/
/usr/local/Cellar/tarantool/1.7.5.184 (90 files, 3.1MB) *
  Poured from bottle on 2017-11-20 at 17:38:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tarantool.rb
==> Dependencies
Build: cmake ✘
Required: icu4c ✔, openssl ✔, readline ✔
```

```
  System Version:	macOS 10.13.1 (17B1003)
  Kernel Version:	Darwin 17.2.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  User Name:	Veniamin Albaev (valbaev)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
```

**Comment by kostja** [comment] 2018-01-09 06:42
I believe this is a duplicate of https://github.com/tarantool/tarantool/issues/2767 Please try again.

**Closed by kostja** 2018-01-09 06:42 UTC
