### ISSUE TITLE
`space:truncate()` + `space:count()` do not work with mvcc

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6007] opened 2021-04-14 21:39 UTC
```Lua
fiber = require('fiber')
box.cfg{memtx_use_mvcc_engine = true}
s = box.schema.create_space('test')
_ = s:create_index('pk')

s:replace{1}

fiber.create(function()
    box.begin()
    s:truncate()
    print(s:count())
    fiber.sleep(10000000)
end) print(s:count())
```
Both print 0, but the print out of the transaction should print 1. I suspect something similar might also happen in vinyl, but its manager is in a worse state with more serious problems now, I didn't test this particular case.

**Comment by alyapunov** [comment] 2021-04-21 16:34
`truncate` is internally an alter, so that's already known issue.
Will be fixed in: create/alter space/index in transaction #600

**Comment by alyapunov** [comment] 2021-04-29 15:17
Blocked by #600

**Comment by mkostoevr** [comment] 2023-09-08 11:10
The issue us not reproducible since #6228 is merged. Now, if a transaction contains a DDL operation, it can't yield at all.

**Closed by mkostoevr** 2023-09-08 11:10 UTC
Labels: bug, blocked, memtx, mvcc
