### ISSUE TITLE
Race condition in replication setup + box.once

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1615] opened 2016-07-14 09:31 UTC
In case if replication is set up with a guest user, it is possible that multiple nodes will execute box.once at the same time. As we don't have synchronous replication, this leads to race condition.

This doesn't happen when password authentication is used, because until the master node sets up users, others won't be able to connect.

**Comment by kostja** [comment] 2016-09-27 12:36
Duplicate of gh-1589

**Closed by kostja** 2016-09-27 12:36 UTC
Labels: bug, prio1
