### ISSUE TITLE
Vinyl crash on ddl in tx manager

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3479] opened 2018-06-25 11:24 UTC
```
038] vinyl/ddl.test.lua                                              
[038] 
[038] [Instance "vinyl" killed by signal: 6 (SIGABRT)]
[038] 
[038] Last 15 lines of Tarantool Log file [Instance "vinyl"][/Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl.log]:
[038] 2018-06-25 14:07:03.758 [21021] main/104/vinyl.scheduler I> dumped 61752 bytes in 0.0 sec
[038] 2018-06-25 14:07:03.758 [21021] main/126/console/unix/: I> vinyl checkpoint completed
[038] 2018-06-25 14:07:03.762 [21021] main/126/console/unix/: I> removing /Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl/00000000000000004236.snap
[038] 2018-06-25 14:07:03.762 [21021] main/126/console/unix/: I> removing /Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl/00000000000000003564.vylog
[038] 2018-06-25 14:07:03.763 [21021] wal/101/main I> removing /Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl/00000000000000004236.xlog
[038] 2018-06-25 14:07:03.785 [21021] main/104/vinyl.scheduler I> 548/1: dump started
[038] 2018-06-25 14:07:03.786 [21021] vinyl.writer.0 I> writing `/Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl/548/1/00000000000000000705.run'
[038] 2018-06-25 14:07:03.790 [21021] vinyl.writer.0 I> writing `/Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl/548/1/00000000000000000705.index'
[038] 2018-06-25 14:07:03.791 [21021] main/104/vinyl.scheduler I> 548/1: dump completed
[038] 2018-06-25 14:07:03.791 [21021] main/104/vinyl.scheduler I> 548/0: dump started
[038] 2018-06-25 14:07:03.791 [21021] vinyl.writer.1 I> writing `/Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl/548/0/00000000000000000707.run'
[038] 2018-06-25 14:07:03.792 [21021] vinyl.writer.1 I> writing `/Users/v.shpilevoy/Work/Repositories/tarantool/test/var/038_vinyl/vinyl/548/0/00000000000000000707.index'
[038] 2018-06-25 14:07:03.793 [21021] main/104/vinyl.scheduler I> 548/0: dump completed
[038] 2018-06-25 14:07:03.793 [21021] main/104/vinyl.scheduler I> dumped 0 bytes in 0.0 sec
[038] Assertion failed: (xm->lsn < lsn), function vy_tx_commit, file /Users/v.shpilevoy/Work/Repositories/tarantool/src/box/vy_tx.c, line 594.
[038] [ fail ]
```

**Comment by locker** [comment] 2018-08-19 20:57
I can't reproduce the issue, neither can I figure out how it could occur by looking at the code. Theoretically, it could be explained by memory corruption caused by #3420. Closing it as invalid. If you ever run into it again, feel free to reopen it.

**Closed by locker** 2018-08-19 20:57 UTC
Labels: bug, crash, ddl, vinyl
