### ISSUE TITLE
Support builds and CI/CD for  RHEL9/CentOS9/AlmaLinux9 in Tarantool 2.11 LTS

### ISSUE THREAD

**Issue by winmaxdev** [tarantool/tarantool#9641] opened 2024-02-01 20:18 UTC
As part of the task (https://jira.vk.team/browse/MNT-434179), part of the cloud components will be migrated to AlmaLinux9 OS. On the site: https://www.tarantool.io/ru/download/os-installation/rhel-centos/
Says that only RHEL7/8 is supported, need to add a version for RHEL9.
In general I checked 2.10 builds except for one network test, 2.11 RC2 crashes at libsalad build stage.

**Comment by ylobankov** [comment] 2024-02-02 07:40
This is a duplicate of https://github.com/tarantool/tarantool/issues/9434.

**Closed by ylobankov** 2024-02-02 07:40 UTC
Labels: feature
