### ISSUE TITLE
vinyl: split vy_range.hc out from vinyl.hc

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2403] opened 2017-05-03 11:39 UTC
Move vy_range into an own file. vy_slice is a logical entitty and should either be moved to an own file as well, or to vy_range.c. Currently it resides in vy_run.h

**Comment by rtsisyk** [comment] 2017-05-26 07:03
Duplicate of #1906

**Closed by rtsisyk** 2017-05-26 07:03 UTC
Labels: prio3, refactoring, vinyl
