### ISSUE TITLE
Last survivor in Raft doesn't know that leader is dead

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/tarantool#6690] opened 2021-12-08 12:21 UTC
**Bug description**

If we lost quorum in Raft, the last survivors wouldn't know that their leader was dead. They'll still be thinking that their leader is a previous alive leader.

**Steps to reproduce**

- Create replicaset with three instances (two candidates and one voter)
  - id1 - leader, id2 - follower, id3 - follower 
- Kill both id1 and id2

**Actual behavior**

- id3 is thinking that the leader is id1:
  - `box.info.election`: `{leader = 1}` 

**Expected behavior**

- id3 reports that it has no leader:
  - `box.info.election`: `{leader = 0}`

**Comment by R-omk** [comment] 2021-12-08 14:21
Same as https://github.com/tarantool/tarantool/issues/6661 but from other side (follower|leader)

**Comment by Gerold103** [comment] 2021-12-08 23:01
If the survivor is a candidate, it will notice the leader's death. If the survivor is a voter, then it can't do anything by design. The only way to overthrow the leader is bump the term which voter can't do. So the voter will see the leader until the term is bumped by somebody else. This is how the voter role works.

**Comment by R-omk** [comment] 2021-12-08 23:56
> id1 - leader, id2 - follower, id3 - follower

id3 needs be changed to  `voter` as described above

**Comment by sergepetrenko** [comment] 2021-12-13 15:27
But we can still track leader death on voter: let it reset leader to 0 once leader death timeout expires.
This doesn't contradict anything. Does it?

**Comment by Gerold103** [comment] 2021-12-13 21:15
> But we can still track leader death on voter: let it reset leader to 0 once leader death timeout expires.
> This doesn't contradict anything. Does it?

If you set it to 0 and then later connectivity is restored, you will set it to non-zero again. So during the same term the leader is changed from 0 to non-zero when election is won, then to 0 back on death timeout, and then to non-zero again like in the example above. All in one term. I thought it might look surprising to users that the leader looks like 're-elected' during the same term. But I don't have any concrete examples of what could get broken if we do so.

**Comment by sergepetrenko** [comment] 2021-12-14 10:03
> If you set it to 0 and then later connectivity is restored, you will set it to non-zero again. So during the same term the leader is changed from 0 to non-zero when election is won, then to 0 back on death timeout, and then to non-zero again like in the example above. All in one term. I thought it might look surprising to users that the leader looks like 're-elected' during the same term. But I don't have any concrete examples of what could get broken if we do so.

I don't see what could go wrong either.
But this looks strange, indeed.

Looks like we'll have to track leader "death" on voters for the sake of pre-voting support.

**Comment by sergepetrenko** [comment] 2022-08-17 10:44
Starting with 421a096894cf each node has `box.info.election.leader_idle` field. When the leader is unreachable, `leader_idle` grows well past `box.cfg.replication_timeout`. Actually, the nodes consider the leader dead once `leader_idle` surpasses `4 * box.cfg.replication_timeout`.
Output for a voter with a dead leader would look like:
```
tarantool> box.info.election
---
- leader_idle: 10.153831
  state: follower
  vote: 1
  term: 3
  leader: 1
...

```
@yngvar-antonsson, does this suit you?

**Comment by yngvar-antonsson** [comment] 2023-11-03 12:59
> Starting with [421a096](https://github.com/tarantool/tarantool/commit/421a096894cf173757365b86a884e1ba35c57247) each node has `box.info.election.leader_idle` field. When the leader is unreachable, `leader_idle` grows well past `box.cfg.replication_timeout`. Actually, the nodes consider the leader dead once `leader_idle` surpasses `4 * box.cfg.replication_timeout`. Output for a voter with a dead leader would look like:
> 
> ```
> tarantool> box.info.election
> ---
> - leader_idle: 10.153831
>   state: follower
>   vote: 1
>   term: 3
>   leader: 1
> ...
> ```
> 
> @yngvar-antonsson, does this suit you?

Yes, I think so. Propose to close this issue.

**Comment by sergepetrenko** [comment] 2023-11-03 14:39
Thanks for your answer!
Closing then.

**Closed by sergepetrenko** 2023-11-03 14:39 UTC
Labels: bug
