### ISSUE TITLE
luamp_encode logic for sparse arrays

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1167] opened 2015-11-26 14:04 UTC
luamp_encode() should try to pack stack as an array if it's first index is integer 1. This works better with sparse arrays. If it meets a string index, it may fall back to map.

Example:

function f() local res = {} res[1] =  1 res[20] = 1 return res end

This fails with error Tuple is Not Array in CALL

**Comment by rtsisyk** [comment] 2016-01-25 12:23
* luaL_tofield tries to classify table into one of four kinds
	 * during encoding:
	 *
	 *  + map - at least one table index is not unsigned integer.
	 *  + regular array - all array indexes are available.
	 *  + sparse array - at least one array index is missing.
	 *  + excessively sparse arrat - the number of values missing
	 * exceeds the configured ratio.
	 *
	 * An array is excessively sparse when **all** the following
	 * conditions are met:
	 *
	 *  + encode_sparse_ratio > 0.
	 *  + max(table) > encode_sparse_safe.
	 *  + max(table) > count(table) * encode_sparse_ratio.
	 *
	 * luaL_tofield will never consider an array to be excessively sparse
	 * when encode_sparse_ratio = 0. The encode_sparse_safe limit ensures
	 * that small Lua arrays are always encoded as sparse arrays.
	 * By default, attempting to encode an excessively sparse array will
	 * generate an error. If encode_sparse_convert is set to true,
	 * excessively sparse arrays will be handled as maps.

My code is more flexible and works for most cases. Even Redis uses the same code for detecting Lua arrays.  I can tune up `encode_sparse_ratio` and `encode_sparse_safe`. Is it enough?

**Comment by rtsisyk** [comment] 2016-01-27 13:13
Duplicate of #291.

I've made a prototype where CALL never throw "tuple is not array" exceptions.
This prototype supports ALL use-cases from #291. I was able to do that without extra overhead.
#291 re-scheduled for 1.6.8.

**Closed by rtsisyk** 2016-01-27 13:13 UTC
Labels: bug, need feedback
