### ISSUE TITLE
Box.once should wait before the server enters RW mode

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1075] opened 2015-09-28 11:32 UTC
```lua
local function bootstrap()
    s = box.schema.space.create('tester')
end

box.cfg{listen=3000, replication_source='sh2.tarantool.org:3000'}

box.once('bootstrap', bootstrap) -- complains about RO mode
```

**Comment by kostja** [comment] 2015-11-13 19:06
This should be fixed by now. Please add a test.

**Comment by rtsisyk** [comment] 2016-01-07 14:09
This bug is a duplicate of #999.
Kostja'a comment was about #1101.

**Comment by rtsisyk** [comment] 2016-01-07 15:54
Discussed with @kostja.  Nov 13, 2015 comment is a mistake. This ticket is similar to #999, but for 1.6.x and should be fixed in the different way. box.cfg{}/box_init() should wait for LSN returned by SUBSCRIBE (see #691) before exiting to the caller.

Unfortunately, required synchronization primitives for applier were pushed to 1.7 and won't be ported back to 1.6.8. Please try find a primitive workaround to wait for LSN in box_init().

**Comment by rtsisyk** [comment] 2016-01-27 14:58
Fixed in 1.6.8-396-g32ff24d

**Closed by rtsisyk** 2016-01-27 14:58 UTC
Labels: bug, customer, review
