### ISSUE TITLE
sql: support tarantool's number type (integral+floating point)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3811] opened 2018-11-16 05:57 UTC
Tarantool has 'number' space format / index format type encoded as one of msgpack type: int8/16/32/64 / uint8/16/32/64 / float32/64. So it can precisely represent integral values as well as IEEE floating-point single/double precision values (including inifinities and NaN). We need to support corresponding type in Tarantool/SQL.

There is the following ways to support it:

1. Change REAL / FLOAT / DOUBLE type(s).
2. Introduce a new Tarantool/SQL type.

https://tarantool.io/en/doc/2.1/book/box/data_model/#indexed-field-types

**Comment by Korablev77** [comment] 2018-11-16 13:22
AFAIK chosen path is to follow ANSI specification. Hence, we should introduce in Tarantool kind of REAL and FLOAT subtypes. On the other hand, later we can extend basic types with NUMBER which would represent and behave as native Tarantool's NUMBER, but this feature seems to be very optional (in contrast to supporting floating point types).

**Comment by Totktonada** [comment] 2018-11-16 13:54
There are two tracks, both are important. The first one is integrate ANSI SQL facilities into Tarantool (ANSI SQL types in this context). The second one is provide native Tarantool facilities via SQL (native Tarantool types in this context). #3812 is about the first track, but this issue is about the second one.

ANSI SQL is more important when some kind of interability with external tools or applicaitons is needed. Integration with Tarantool is important to provide user possibilities to expand existing application using SQL.

BTW, are not that is about DD integration?

**Comment by Korablev77** [comment] 2018-11-16 14:50
> BTW, are not that is about DD integration?

Because it is already done - data dictionaries have been merged. This label should be deleted, but several follow-ups are still remained. You may create label like "sql integration", but it is not about DD.

**Comment by ImeevMA** [comment] 2019-11-14 12:38
I suggest introducing a new type of field - DOUBLE. According to
ANSI, we must have floating point numbers in SQL. In addition, we
need this to be able to cast integers to floating point numbers
using the CAST operator after we repair NUMBER field type.
Currently, NUMBER in SQL works in most cases as DOUBLE, and this
is incorrect, since it must be a union of all numeric types. In
fact, we can repair NUMBER and convert integers to floating point
numbers using something like "... + 0.0" from "... * 1.0", but it
does not look like a viable solution.

Since we must introduce a new field type not only in SQL, but also
in Lua, I have three ways to do this:
1) Create DOUBLE in the same way as the NUMBER field type. This
means that all numbers that cannot be represented as DOUBLE cannot
be inserted into a space. If the user tries to insert such a
number, we will throw an error. This is fairly easy to do in Lua,
but we need to convert the elements of this field type to floating
point numbers in SQL.
2) The same as the previous one, but if the inserted number cannot
be represented as double, we convert it to double and recreate the
tuple. Since large numbers have the size of 9 bites and doubles of
the same size, the tuples before and after will be the same size.
The problem is the same - this type will not be the “true” type
DOUBLE, we must convert the elements of this field type to
floating-point numbers in SQL.
3) Recreate the tuple and replace all INTEGER / UNSIGNED with
floating point numbers where necessary.

At the moment, I plan to go the third way. I feel this may affect
performance, but I think it should be checked after the patch is
ready.

**Comment by ImeevMA** [comment] 2019-12-21 12:29
The main points of this issue, as I understand it:
1) Create the NUMBER type in SQL (solved, #4192 via 36bdfbb24f00b84c2b8d1fa3231537d9f60ae298).
2) Create a DOUBLE type in Tarantool (in process, #3812).

Although the NUMBER type was created in SQL, it does not work as expected. This should be fixed in #4233.

Since there is nothing to do in this issue, it should be closed.

**Closed by ImeevMA** 2019-12-21 12:29 UTC
Labels: feature, sql, sql static types
