### ISSUE TITLE
Tarantool crashes while inserting row without a single field

### ISSUE THREAD

**Issue by iproha94** [tarantool/tarantool#2736] opened 2017-09-01 17:25 UTC
tarantool version 1.8.2-2-g366c8b2a1

```
$ box.cfg{}
$ box.sql.execute("create table test(id INTEGER PRIMARY KEY NOT NULL, k INTEGER NOT NULL);")
$ box.sql.execute("insert into test(k) values (10)")
sqlite3VdbeExec: Assertion `memIsValid(&aMem[pOp->p3])' failed
```

**Comment by TheAviat0r** [comment] 2017-10-20 20:03
Same as #2786, fixed now

**Comment by kyukhin** [comment] 2017-10-23 10:45
Duplicate of #2786

**Closed by kyukhin** 2017-10-23 10:45 UTC
Labels: bug, crash, sql
