### ISSUE TITLE
urlencode/urldecode

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#3720] opened 2018-10-05 14:52 UTC
It would be nice to have urlencode/urldecode functions in string library. As variant this functions can be used from libcurl (https://curl.haxx.se/libcurl/c/curl_easy_unescape.html)

**Comment by bigbes** [comment] 2018-10-05 14:53
duplicate of https://github.com/tarantool/tarantool/issues/3682

**Comment by kyukhin** [comment] 2018-10-25 16:50
Closing then.

**Closed by kyukhin** 2018-10-25 16:50 UTC
Labels: feature
