### ISSUE TITLE
vinyl: allow changing index options using box.space.<space-name>.<index-name>:alter()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1931] opened 2016-11-18 15:46 UTC
Currently all forms of alter() are disabled in vinyl and lead to a runtime error "not implemented".
Make it possible to change index options with :alter(), in particular, such options as page size and range size. 
The change of options should not lead to index rebuild.

**Comment by Gerold103** [comment] 2017-05-12 13:27
Duplicate of #2109

**Closed** 2017-05-18 18:55 UTC
Labels: feature, vinyl
