### ISSUE TITLE
[4pt] build: enable out-of-source build on read-only file system

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4874] opened 2020-04-10 08:09 UTC

**Comment by avtikhon** [comment] 2020-04-10 08:14
Waiting sub-task at:
https://github.com/curl/curl/pull/5213

**Comment by avtikhon** [comment] 2020-04-21 14:38
Main activity at #4258

**Comment by ligurio** [comment] 2020-04-23 06:47
closed as  main activity is in #4258

**Comment by avtikhon** [comment] 2020-05-22 10:45
Major task of the issue #4258 changed, so let's continue OOS build here

**Comment by avtikhon** [comment] 2020-05-22 10:48
For OOS build cURL build based on cmake is needed, check #4968

**Comment by avtikhon** [comment] 2020-05-26 07:55
Depends on #4968

**Comment by rosik** [comment] 2020-06-05 14:35
I'd like this issue to be fixed too.

The problem isn't only about curl, there is also `src/box/bootstrap.h` which is created in source dir.

The following script shows unnecessary files created after performing out-of-source build with default cmake args. And I guess other flags could bring more surprises.

```console
$ git clean -dxn && git submodule foreach --recursive git clean -dxn
Would remove src/box/bootstrap.h
Entering 'src/lib/msgpuck'
Entering 'src/lib/small'
Entering 'test-run'
Entering 'test-run/lib/msgpack-python'
Entering 'test-run/lib/tarantool-python'
Entering 'test-run/lib/tarantool-python/test-run'
Entering 'test-run/lib/tarantool-python/test-run/lib/msgpack-python'
Entering 'test-run/lib/tarantool-python/test-run/lib/tarantool-python'
Entering 'third_party/c-ares'
Entering 'third_party/curl'
Would remove Makefile.in
Would remove aclocal.m4
Would remove aclocal.m4.bak
Would remove autom4te.cache/
Would remove compile
Would remove config.guess
Would remove config.sub
Would remove configure
Would remove depcomp
Would remove docs/Makefile.in
Would remove docs/cmdline-opts/Makefile.in
Would remove docs/examples/Makefile.in
Would remove docs/libcurl/Makefile.in
Would remove docs/libcurl/opts/Makefile.in
Would remove include/Makefile.in
Would remove include/curl/Makefile.in
Would remove install-sh
Would remove lib/Makefile.in
Would remove lib/curl_config.h.in
Would remove ltmain.sh
Would remove m4/libtool.m4
Would remove m4/ltoptions.m4
Would remove m4/ltsugar.m4
Would remove m4/ltversion.m4
Would remove m4/lt~obsolete.m4
Would remove missing
Would remove packages/Makefile.in
Would remove packages/vms/Makefile.in
Would remove scripts/Makefile.in
Would remove src/Makefile.in
Would remove test-driver
Would remove tests/Makefile.in
Would remove tests/certs/Makefile.in
Would remove tests/certs/scripts/Makefile.in
Would remove tests/data/Makefile.in
Would remove tests/libtest/Makefile.in
Would remove tests/server/Makefile.in
Would remove tests/unit/Makefile.in
Entering 'third_party/decNumber'
Entering 'third_party/libyaml'
Entering 'third_party/luafun'
Entering 'third_party/luajit'
Entering 'third_party/luarocks'
Entering 'third_party/serpent'
Entering 'third_party/zstd'
```

**Closed** 2020-10-16 06:53 UTC
