### ISSUE TITLE
Deprecate box.session.push

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#8802] opened 2023-06-22 11:08 UTC
[PM link](https://www.notion.so/tarantool/Drop-session-push-in-3-0-cadf0e7c02be452e91be382e25dc07d7)

`box.session.push` is broken, see #6107.

In the scope of this ticket we decided to:
- Print a warning to the log once on any attempt to use `box.session.push`.
- Add a comat module option that disables `box.session.push` if set to 'new'. The default value is 'old' for now.
- File tickets for all Tarantool projects that use `box.session.push` to drop it.

The next steps are:
- Switch the compat module option to 'new' in 4.0.
- Drop `box.session.new` completely in 5.0.

Filed tickets in projects that fail integration CI if `box.session.push` is disabled:
- https://github.com/tarantool/tarantool-c/issues/170
- https://github.com/tarantool/tarantool-python/issues/305
- https://github.com/tarantool/go-tarantool/issues/324
- https://github.com/tarantool/vshard/issues/427

**Comment by Totktonada** [comment] 2023-08-01 21:45
The linked document just says 'there are problems that can't be solved'. It doesn't even list the problems. I would auto-decline such ideas from the product management team.

I'll quote it here, so everyone can see how deeply it is investigated:

> После многочисленных споров, в виду неизлечимости проблем в session.push, а так же появившихся инструментов поддержки Pub/Sub принято решение удалить в версии 3 механизм session.push.

That's all.

Aside of lack of any investigation about the problems, it, of course, lacks of motivation why the proposed change should be made and why it worth the effort.

I wonder why the development team don't just passed it back to someone in the product team to work on and provide reasons. They can ask the development team to investigate and estimate opportunities to rework the API, if needed.

It is just normal process. Please, don't hesitate to pass tasks back to the product team if more work is needed from their side. Just like you're doing on review of a patchset. (I suggest to ignore emotional responses and keep asking to do the necessary work.)

Anyway, my points are below.

There are three problems around about `box.session.push()` that were described by @Gerold103 in #6107.

* **Push requires a fiber on the storage side.** In fact, this point is about an attempt to use `box.session.push()` outside of a request context, because there was no other way to send a message by server's initiative to a client. Now there is `box.watch()` and there is no sense to attempt to use `box.session.push()` outside of a request context.
* **Netbox is_async and pushes are not very compatible.** AFAIU it is `net.box` API problem. I doubt that there are any design problems that would prevent us from adding a new more convenient client side API.
* **Back-pressure.** Let's just expose metrics and implement ability to set thresholds (per request, per connection and/or global). I see no conceptual issues here.

More on back-pressure: I doubt that it is the only place, where enormous amount of data/repeated actions lead to enormous memory consumption. If I'm so brave that I'm sending a whole space through iproto, what stops me from doing the same using usual response, not `box.session.push()`?

Such problems are about observability improvements (logs, metrics and tracing) and about proper limiting (time/size/quantity based). There is nothing specific in the API of the topic in this regard.

OTOH, `box.session.push()` is usable for:

1. Notifications about a status of a long running request.
2. Send a large response piece-by-piece as long as the pieces are ready.

And, given existence of the outside world, the pros are:

3. Support in a wide variety of tarantool versions. It also includes support in REPL that is quite useful for the notifications use case.
4. Support in many existing language connectors.

**Comment by locker** [comment] 2023-08-02 08:09
@Totktonada, I and @alyapunov talked to @unera. His arguments (as I understand them) are below:
- The back-pressure problem is impossible to solve without extending the protocol. Introducing the sever-side buffer limit would just shift the OOM problem from the server to the client. Per connection limits wouldn't help because the typical use-case is multiplexing clients in the same IPROTO connection. The best we could do is stop *all* on the same connection if *any* of them doesn't manage to process response chunks in time. The proper fix requires a way for the client to notify the server that it can't accept new chunks for now.
- The `box.session.push` API is bad because it implies keeping an active fiber at the server side. It would be better if the server function could register a callback that would be invoked when the client is ready to accept the next chunk. It could look like this:
  ```Lua
  -- Return the next response chunk to the client.
  local function next_chunk(ctx) ... end
  -- Send response to the client in chunks.
  local function chunked_response() return next_chunk, ctx end
  ```
- @unera surveyed our delivery and pre-sale teams and he claims that nobody uses `box.session.push`. This is his responsibility as a product manager - I don't see a reason to question this.

So we have a broken deep in the protocol functionality with a bad API that nobody uses. There's no reason to try fixing it. Better design it from the scratch.

@unera's arguments look convincing to me.

> If I'm so brave that I'm sending a whole space through iproto, what stops me from doing the same using usual response, not `box.session.push()`?

Sending a whole space is a misuse because it'd block the tx thread for too long. With the fiber slice limits, long requests are aborted. `box.session.push` is a different story - it looks like it's safe to send a lot of data in chunks with it while in fact it isn't.

**Comment by Totktonada** [comment] 2023-08-03 08:41
Well, we can't freeze a particular client's request, only the whole connection. That's OK. A connection is used by one application and it is in its responsibility to read answers to get more of them (or open a second connection). It is what we can do based on the TCP's ACKs and we should.

Nothing really blocks us from agree with a modern client about a protocol of application level confirmations to stop sending chunks from particular stream/request, if sent chunks were not confirmed. It can be done in a backward compatible way.

Regarding fibers vs promises: in my understanding the promise mechanism is a way to express cooperative multitasking in a language that initially had no such functionality. We're in the nice situation, when ugly constructions are not needed to express sequencial logic with IO multiplexing. If fibers works poorly comparing to promises it worth to investigate opportunities to make fibers better: the API of the question is not the only, which leans on fibers.

As regarding 'nobody uses it' -- OK, it works in both ways. Nobody base several applications on one client connection. So, pause of the entire connection is OK.

P. S. Usage example: https://github.com/centrifugal/centrifuge/pull/176 + https://github.com/centrifugal/centrifuge/pull/310.

**Comment by R-omk** [comment] 2023-08-03 15:39
>  It can be done in a backward compatible way.

- Add something like 'quota' (message count, byte length)  to request headers
- Send this header on the initiating request
- Send this header again with the same SYNC to reset the quota to new values (new requet type)

for backward compatibility, we assume that if the quota is not specified, then it is unlimited

**Comment by R-omk** [comment] 2023-08-03 17:34
moreover, I suggest to combine quotas and deadline/timeouts, this will allow the client to dynamically expand the execution time.

https://github.com/tarantool/tarantool/issues/4429

**Comment by FZambia** [comment] 2023-08-10 06:11
Hello! As mentioned by @Totktonada we are using box.session.push in https://github.com/centrifugal/tarantool-centrifuge/blob/edffc500371df8385c0282543efc8f05442c6d8a/centrifuge.lua#L534. I am not an experienced Tarantool user, can you please clarify some things:

1. Why having a separate fiber for pushes is a bad thing? I was thinking that fiber is lightweight enough to not worry about having several extra of the to serve pushes. The number of such fibers is limited to the small number of connections used for push delivery.
2. Why backpressure is a problem which should result into feature removing? For push systems you can have some politics which drop connection on Tarantool side if quotas exceeded. For example, Redis PUB/SUB connections have an internal buffer 16 MB which when exceeded results into connection drop.
3. Having session pushes to work only in the context of the request is totally fine for our use case - while I think you consider this a problem. Consider GRPC unidirectional streaming - streams exists in the context of streaming request and it's totally fine.

> После многочисленных споров, в виду неизлечимости проблем в session.push, а так же появившихся инструментов поддержки Pub/Sub

Could you point me to the new instruments for PUB/SUB support?

**Comment by locker** [comment] 2023-08-10 08:03
> 1. Why having a separate fiber for pushes is a bad thing? I was thinking that fiber is lightweight enough to not worry about having several extra of them to serve pushes. The number of such fibers is limited to the small number of connections used for push delivery.

If there's one or two such fibers, it isn't a problem. If there are hundreds of fibers pushing data back to the client with this mechanism, it may lead to stopping all requests, see [`box.cfg.net_msg_max`](https://www.tarantool.io/en/doc/latest/reference/configuration/#cfg-networking-net-msg-max).

The problem is `box.session.push` *looks* like it's designed for pushing a lot of data in chunks but if used like that it may result in performance or OOM issues. Using it for pub/sub with one dispatching fiber on the server should probably be fine but there's the new pub/sub system implemented recently in Tarantool, which is easier to use and doesn't have any of `box.session.push` issues.

> 2. Why backpressure is a problem which should result into feature removing? For push systems you can have some politics which drop connection on Tarantool side if quotas exceeded. For example, Redis PUB/SUB connections have an internal buffer 16 MB which when exceeded results into connection drop.

Because Tarantool clients may use multiplexing: there may be hundreds of clients sharing the same connection with the *same* buffer. Stopping input on one of them would stop them all. While this would definitely prevent OOM, it could result in stopping the world from time to time, which isn't much better.

> 3. Having session pushes to work only in the context of the request is totally fine for our use case - while I think you consider this a problem. Consider GRPC unidirectional streaming - streams exists in the context of streaming request and it's totally fine.

I don't consider this to be a problem per se. However, request context isn't necessary for pub/sub and the new pub/sub system doesn't use it.

> 
> > После многочисленных споров, в виду неизлечимости проблем в session.push, а так же появившихся инструментов поддержки Pub/Sub
> 
> Could you point me to the new instruments for PUB/SUB support?

https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_events/

**Comment by R-omk** [comment] 2023-08-10 08:25
> the new pub/sub system implemented recently in Tarantool, which is easier to use and doesn't have any of box.session.push issues.

But it has its own issues , it is completely unsuitable for streaming, and most importantly, it does not guarantee At-least-once delivery.  In any case, the current implementation in net.box ensures that only the last event is delivered.

**Comment by Totktonada** [comment] 2023-08-10 14:52
I would like to summarize some f2f discussions with @locker and @alyapunov.

* My point 'stopping of bad clients is OK' was beaten by 'a router/frontend instace may multiplex many connections'. As result we can stop many completely unrelated clients.
* My point 'we should ensure that we can't fix the problem in the backward-compatible way and only then remove existing things' was mostly addressed by a composition of the following facts.
  * We neither remove it, nor disable it by default in Tarantool 3.0.
  * Designing the new replacement functionality for server-to-client notifications and chunked responses would take quite lot of time.
  * We have two years to change our minds and un-deprecate the pushes.

All the discussions around fibers vs futures/promises/callbacks don't end with anything certain.

Taking this I would agree that marking this functionality as not recommended is OK, but I still think that in the ideal world it would be better to propose a replacement first.

**Closed** 2023-08-11 12:39 UTC
Labels: feature, 3.0

**Comment by FZambia** [comment] 2023-08-12 06:44
> If there's one or two such fibers, it isn't a problem.

That's exactly my use case.

> but there's the new pub/sub system implemented recently in Tarantool, which is easier to use and doesn't have any of box.session.push issues.

It seems from the discussion that it has a different semantics to only return the last value instead of stream of values. So I do not understand why it can be mentioned as a possible alternative to box.session.push? It seems to be designed for different use cases like being notified about last state only.

Overall, I am not convinced why the feature must be deprecated without a clear and ready-to-use alternative to it. This simply adds uncertainty about the future. I do not want the code I am suggesting to my users rely on deprecated things.
