### ISSUE TITLE
box.execute no longer can be used to query since 3.x?

### ISSUE THREAD

**Issue by kokizzu** [tarantool/tarantool#10077] opened 2024-05-30 20:55 UTC
**Bug description**

* OS: Linux
* OS Version: Pop!_OS 22.04/Ubuntu
* Architecture: amd64

tarantool run using docker-compose

Place `tarantool --version` output here.
```
Tarantool 3.1.0-0-g96f6d88597
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/tarantool/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: GNU-8.3.1
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -static-libstdc++ -fno-common -msse2  -fmacro-prefix-map=/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -static-libstdc++ -fno-common -msse2  -fmacro-prefix-map=/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2
```

**Steps to reproduce**

Run two tarantool instances iteractively.

1. create space "users" with any fields
2. box.execute [[ SELECT * FROM "users" ]]

**Actual behavior**

```
 box.execute [[ SELECT * FROM "users" LIMIT 1 ]]
---
- null
- Scanning is not allowed for 'users'
...
```

**Expected behavior**

can query like normal

**Comment by kokizzu** [comment] 2024-05-30 21:03
also code that previously works now no longer works

```
row, err := u.Adapter.Connection.Do(
		tarantool.NewReplaceRequest(u.SpaceName()).
			Tuple(arr),
	).Get()
	if err == nil {
		if len(row) > 0 {
			if cells, ok := row[0].([]any); ok && len(cells) > 0 {
				u.Id = X.ToU(cells[0])
			}
		}
	}
```

that "users" table have unique index "email" and primary key "id"

```
 box.space.users
---
- engine: memtx
  before_replace: 'function: 0x7f0e9ec1d5e8'
  field_count: 0
  is_sync: false
  is_local: false
  on_replace: 'function: 0x7f0e9ec1d5b0'
  temporary: false
  index:
    0: &0
      parts:
      - fieldno: 1
        sort_order: asc
        type: unsigned
        exclude_null: false
        is_nullable: false
      sequence_id: 3
      id: 0
      space_id: 514
      unique: true
      hint: true
      type: TREE
      name: id
      sequence_fieldno: 1
    1: &1
      unique: true
      parts:
      - fieldno: 2
        sort_order: asc
        type: string
        exclude_null: false
        is_nullable: false
      hint: true
      id: 1
      type: TREE
      space_id: 514
      name: email
    email: *1
    id: *0
  type: normal
  enabled: true
  name: users
  id: 514
...
```

**Comment by drewdzzz** [comment] 2024-05-31 07:41
All scanning queries (even with limit) raise an error without [SEQSCAN](https://www.tarantool.io/en/doc/latest/how-to/sql/sql_tutorial/#the-seqscan-keyword) keyword. It is needed to avoid accidental scans. If you don't like it, you can disable it for current session with `SET SESSION "sql_seq_scan" = true;` or for all sessions with `compat` [option](https://www.tarantool.io/en/doc/latest/reference/reference_lua/compat/sql_seq_scan_default/).

P.S. SEQSCAN wasn't required in Tarantool 2.x because the combat option is set to `old` there.

It's expected behavior, so I'm closing the issue.

**Closed by drewdzzz** 2024-05-31 07:41 UTC
Labels: bug
