### ISSUE TITLE
When setting snap_io_rate_limit snapshoting gets stuck

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#2328] opened 2017-04-13 14:53 UTC
1. Run a database (1.6.9-80)
2. Set snap_io_rate_limit=40 on the fly
3. Start snapshoting by any way (signal, console, daemon)

Got: snapshoting stucks with zero-size .snap.inprogress
Expected: snapshoting works

**Comment by GeorgyKirichenko** [comment] 2017-04-14 11:13
If snap_io_rate_limit was set while snapshoting then write speed will be recalculated from begin of snapshot.
For example, if 1mb of snapshot was written, then tarantool will wait for 1mb/40 seconds after io_rate_limit was set.

**Comment by rtsisyk** [comment] 2017-04-19 10:49
@Mons can we close this ticket?

**Comment by rtsisyk** [comment] 2017-04-19 13:33
OK, we'll try to reproduce this problem again.

**Comment by GeorgyKirichenko** [comment] 2017-04-20 06:22
Can't reproduce on last 1.6

**Comment by rtsisyk** [comment] 2017-05-03 15:08
Please re-open if problem still exists.

**Closed by rtsisyk** 2017-05-03 15:08 UTC
Labels: bug, need feedback, prio1
