### ISSUE TITLE
Segmentation fault if I delete a collation

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4544] opened 2019-10-03 21:48 UTC
I have Ubuntu 18.04. I have Tarantool 2.3, pulled from source today.

I execute these requests:
```
box.execute([[CREATE TABLE things (id STRING COLLATE "unicode" PRIMARY KEY);]])
box.space._collation:delete(1)
box.execute([[SELECT * FROM things WHERE id = 'a';]])
```
Result = Segmentation fault ... SEGV_MAPERR

I think the simplest solution is to disallow deleting collations.

**Comment by kyukhin** [comment] 2019-11-11 07:13
This crash should be very rare and unusual. Moving it to the next MS.

**Comment by Korablev77** [comment] 2019-11-11 13:50
I disagree with Kirill. Any segfault (especially so easy to reproduce) is vital. So I've sent fix to it. Please, re-schedule to 2.3.1 (it should be back-ported to 2.1.3 as well).

**Comment by Gumix** [comment] 2023-07-05 14:33
Reproducible even without SQL:

```lua
local s = box.schema.space.create('test')
s:format{{name = 'a', type = 'string', collation = 'unicode_af_s1'}}
s:create_index('pk', {parts = {{'a', 'string'}}})
box.space._collation:delete(4)
s:insert{''}
```

```
tarantool: ./src/lib/coll/coll.c:145: coll_icu_hint: Assertion `coll->type == COLL_TYPE_ICU' failed.
zsh: abort (core dumped)
```

Note `unicode_af_s1`. There are no aborts for `unicode` or `unicode_ci`, because Tarantool creates them during startup in `tarantool_lua_utf8_init()`. Then, `unicode` or `unicode_ci` are referenced for the second time during snapshot recovery.

https://github.com/tarantool/tarantool/blob/ef6335e862ac9110e4bf1d146a839cb9c35b7ecd/src/lua/utf8.c#L452-L459

**Comment by Gumix** [comment] 2023-07-05 16:19
Another similar crash:

```lua
local kd = key_def.new{{field = 1, type = 'string', collation = 'unicode_af_s1'}}
box.internal.collation.drop('unicode_af_s1')
kd:compare({'a'}, {'b'})
```

```
Thread 1 "tarantool" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e25c3a in ucol_strcollUTF8_67 () from /lib/x86_64-linux-gnu/libicui18n.so.67
(gdb) bt
#0  0x00007ffff7e25c3a in ucol_strcollUTF8_67 () from /lib/x86_64-linux-gnu/libicui18n.so.67
#1  0x0000555555a9034f in coll_icu_cmp (...) at ./src/lib/coll/coll.c:87                                                                                                               #2  0x0000555555a5a13f in mp_compare_str_coll (...) at ./src/box/tuple_compare.cc:378
#3  0x0000555555a5a516 in tuple_compare_field (...) at ./src/box/tuple_compare.cc:485
```

**Closed** 2023-08-10 09:44 UTC
Labels: crash, bug, 2.10
