### ISSUE TITLE
Missing entries in secondary index on vinyl

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#6045] opened 2021-04-23 08:59 UTC
This issue is derived from QA activity: https://github.com/tarantool/tarantool-qa/issues/13 and put here since there's no more work expected from QA.

Vinyl can miss keys from the secondary index when it is created under DML load.

Bisect definitely points to this commit (introduced during 1.10.4/2.2.1 development): https://github.com/tarantool/tarantool/commit/0e37af311356b2ef1d375ff59b92505c5db0bade

Here's the reproducer.

OS (this might be important since I was unable to reproduce this on Ubuntu 18): Ubuntu 20
Compile: stock compiler
Configuration: `cmake ../src` (I use out of source build)

Code:
```
test$ cat ./engine/ddl_simple.test.lua
test_run = require('test_run')
inspector = test_run.new()
engine = inspector:get_cfg('engine')

--
-- Check that all modifications done to the space during index build
-- are reflected in the new index.
--
math.randomseed(os.time())

s = box.schema.space.create('test', {engine = engine})
_ = s:create_index('pk')
inspector:cmd("setopt delimiter ';'")

last_val = 10;
box.begin()
for i = 1, last_val do box.space.test:replace{i, i, i} end
box.commit();

function gen_load()
    local s = box.space.test
    for i = 1, 10 do
        local key = math.random(last_val)
        local val1 = math.random(last_val)
        local val2 = last_val + 1
        last_val = val2
        pcall(s.upsert, s, {key, val1, val2}, {{'=', 2, val1}, {'=', 3, val2}})
    end
end;

function check_fiber()
    _ = fiber.create(function() gen_load() ch:put(true) end)
    _ = box.space.test:create_index('sk', {unique = false, parts = {2, 'unsigned'}})

    assert(ch:get(10) == true)

    local index = box.space.test.index
    if index.pk:count() ~= index.sk:count() then
        require('log').error("Error on fiber check: failed '1st step secondary keys' check on equal" ..
                             " pk = " .. index.pk:count() .. " and k = " .. index.sk:count())
        return false
    end

    return true
end;

inspector:cmd("setopt delimiter ''");

fiber = require('fiber')
ch = fiber.channel(1)
check_fiber()

box.space.test:drop()
```

Cook result file as follows:
```
./test-run.py --builddir ../../bld engine/ddl_simple.test.lua --update-result
```

Invoke test in a loop.
```
c=0 ; while ./test-run.py --conf vinyl --builddir ../../bld -j1 engine/ddl_simple.test.lua ; do date ; sync ; c=$(($c+1)) ; echo PASSED ======================== : $c ; done ; echo ================= FAILED: $c
```

The test usually fails within 150 iterations with the following output:
```
E> Error on fiber check: failed '1st step secondary keys' check on equal pk = 14 and k = 13
```

**Comment by Korablev77** [comment] 2021-05-24 18:20
Single-run reproducer:

```
box.cfg{}
s = box.schema.space.create('test', {engine = 'vinyl'})
_ = s:create_index('pk')

last_val = 10;
box.begin()
for i = 1, last_val do box.space.test:replace{i, i, i} end
box.commit();

function gen_load()
    local s = box.space.test
    pcall(s.replace, s, {10, 10, 11})
    pcall(s.replace, s, {10, 10, 12})
end;


function check_fiber()
    fiber = require('fiber')
    local ch = fiber.channel(1)
    _ = fiber.create(function() gen_load() ch:put(true) end)
    _ = box.space.test:create_index('sk', {unique = false, parts = {2, 'unsigned'}})
    ch:get()
    local index = box.space.test.index
    local pk_cnt = index.pk:count()
    local sk_cnt = index[1]:count()
    if index.pk:count() ~= index[1]:count() then
        assert(false)
    end
end;

check_fiber()
```

**Comment by Korablev77** [comment] 2021-05-25 15:30
Ok, I found out the reason of missing entries in secondary index after construction. Consider example above:
We are starting building secondary index. This step consists of following steps:
1. Setup new lsm (check path access, create new range, update vylog);
2. Create temporary on_replace trigger, which forwards DML requests issued during the build;
3. Copy tuple-by-tuple keys from PK to secondary index being created and skip those tuples which have lsn > lsn of lsm tree at the start of build.

Also we have optimization which annihilates DELETE+INSERT and INSERT+DELETE statements in the same write-set of lsm (see https://github.com/tarantool/tarantool/commit/0e37af311356b2ef1d375ff59b92505c5db0bade).

on_replace trigger fires almost right after start of transferring keys from PK to SC, so that SC doesn't contain key `10`. In on_replace trigger replace splits into DELETE+INSERT statements. In `vy_tx_set_entry` INSERT becomes no-op due to mentioned optimization. However, in PK tuples is updated, so PK contains tuple ` {10, 10, 11}` with bumped lsn. Ergo tuple ` {10, 10, 11}` is skipped and key is not transferred to the SC. In this respect, tuple becomes phantom and doesn't appear via SC search.

There are several possible ways to fix it.
1. Get rid of DELETE+INSERT annihilation at all. Sounds sad since it is likely to be useful and worth workaround for this single test case;
2. Track index build status and in case index is under construction do not apply optimization; 
3. Introduce separate tuple flag in order to mark tuples possible affected by optimization and consider them as candidates to be inserted into SC even if their lsn > lsn of the tree;
4. Instead of using flags we may lookup key in on_replace trigger, but it sounds way much slower than third option.

**Closed** 2021-06-03 11:21 UTC
Labels: 5sp, bug, teamC, vinyl
