### ISSUE TITLE
Raft: turn on sync replication on `_space`, `_schema` system spaces

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5448] opened 2020-10-28 12:46 UTC
Actually I need more comments from @Gerold103 and @Mons about this feature. Where and why should we turn on synchro on these spaces.

**Comment by Gerold103** [comment] 2020-10-28 23:11
I don't remember us discussing `_space` being synchronous. Why should it be? Raft is not going to use it for anything.

`_cluster` should be synchronous when Raft is enabled. When Raft is disabled, the space is async like it is now.

When Raft mode is set to something except `off`, and a leader is elected, it should make the `_cluster` space synchronous. So to add a new instance or delete one it would be necessary to collect a quorum on that.

**Comment by NeraverinTarantool** [comment] 2022-05-17 14:23
Maybe we should only write doc, describing that user should enable syc replication for system spaces himself

**Comment by kostja** [comment] 2023-07-18 18:09
It still makes sense within a single replicaset to provide DDL/DML linearizability.

**Comment by sergepetrenko** [comment] 2024-05-29 12:27
Duplicate of https://github.com/tarantool/tarantool/issues/9723

**Closed by sergepetrenko** 2024-05-29 12:27 UTC
Labels: feature, replication, qsync replication, raft
