### ISSUE TITLE
vinyl: run files left from dropped index are never removed

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2007] opened 2016-12-22 10:47 UTC
Branch 1.7 a4bb85a9

Run files left from a dropped index are not removed on snapshot:
```
box.cfg{}
s = box.schema.space.create('test', {engine='vinyl'})
i = s:create_index('pk')
s:insert{1}
box.snapshot()
s:drop()
box.snapshot()
os.exit(0)
```
```
$ ls 512/0
0000000000000002.0000000000000001.0.index  0000000000000002.0000000000000001.0.run
```

**Comment by rtsisyk** [comment] 2016-12-23 10:36
Duplicate of #1806

**Closed by rtsisyk** 2016-12-23 10:36 UTC
Labels: bug, vinyl
