### ISSUE TITLE
test: write new result files only when it is requested

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4258] opened 2019-05-29 14:35 UTC
When running testing w/ out-of-source build some TAP tests fail.
Reproduce:
```
/export/tarantool/src/test$ ./test-run.py --builddir ../../bld --force --long -j 48
```

What's wrong:
```
[012] unit/merger.test                                                                                                                                                          
[012] TAP13 parse failed: Missing plan in the TAP source                                                                                                                        
[012] [ new ]
```

**Comment by avtikhon** [comment] 2019-10-28 07:33
The issue occurs in the following way:
1. checkout master at sources;
2. go to build path and run build - the test files appears at build path, like 'test/unit/json.test';
3. check that source path is clean and checkout 1.10 there also check that no files like 'test/unit/json.*' appeared;
4. go to build path and run build with testing like 'make -j && make test' - the first issue occurred here:
[017] TAP13 parse failed: Missing plan in the TAP source
[017] [ new ]
test-run tool searches at the build path and finds files like 'test/unit/json.test' but doesn't find the it's result files at the sources and regenerates it at the source path (next test run will not show the issue due to files already exist);
5. go to source path and check that the path is dirty with previous results files - try to checkout 2.1 which fails with:
error: The following untracked working tree files would be overwritten by checkout:
	test/unit/checkpoint_schedule.result
	test/unit/json.result
	test/unit/sio.result
	test/unit/swim.result
	test/unit/swim_proto.result
Please move or remove them before you switch branches.
Aborting

List of tests that occurred and failed the checkout:
```
 unit/checkpoint_schedule.result
 unit/crypto.result
 unit/decimal.result
 unit/json.result
 unit/luaL_iterator.result
 unit/luaT_tuple_new.result
 unit/merger.result
 unit/sio.result
 unit/swim.result
 unit/swim_errinj.result
 unit/swim_proto.result
```
Seems that the test-run need to be changed to avoid it from default regeneration of the missed results files - it can be done with additional option.

**Comment by avtikhon** [comment] 2019-11-07 10:59
Also found that on Gitlab-CI workspaces leaves some extra files from tests from the submodules like
src/lib/small/* which produce warning messages at the Gitlab-CI run log, to avoid of it the following fix is needed:
```
diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
index 04bb4b1cc..91326b218 100644
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,9 @@ stages:
 variables:
   GITLAB_MAKE: "make -f .gitlab.mk"
 
+before_script:
+  - git submodule foreach git clean -xfd
+
 # Jobs templates
 
 .release_only_template: &release_only_definition
```

**Comment by avtikhon** [comment] 2019-11-07 11:08
Reproduced the issue when the tests from master branch fails/warning on 1.10. If the build path wasn't recreated than test/unit/CMakeFiles/ path includes directories not exist at the 1.10 branch which produce fail on 'make test' command either warning on './test-run.py' command. To avoid of it the build root path must be always removed before check outing the other branch.

**Comment by avtikhon** [comment] 2019-11-07 12:09
Decided to fix the issue basing on the axiom that source are based on RO file system.

**Comment by Totktonada** [comment] 2019-11-07 12:22
> Decided to fix the issue basing on the axiom that source are based on RO file system.

I see no dependency between the problem you show above and sources on read only file system. Please, file another issue for that.

**Comment by Totktonada** [comment] 2019-11-28 14:52
The problem in short: test-run may write result file into a repository directory when it is not asked for this. Proposed to add an option in test-run to do so only when asked. I think it also should be wrapped into an appropriate make target on tarantool side.

I'll change the header of the issue.

**Comment by avtikhon** [comment] 2020-04-20 12:28
Temporary added skip condition for app-tap/http_client.test.lua test to make the build available. The issue will be left opened till it will be fixed.

**Comment by ligurio** [comment] 2020-04-23 06:47
Status:

- [ ]  build: enable out-of-source build #4874 
- [ ]  support out-of-source build in curl https://github.com/curl/curl/pull/5213

**Comment by ligurio** [comment] 2020-05-19 10:35
[Tarantool-patches] [PATCH v2] Add option to update file with reference output
https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016853.html

**Comment by ligurio** [comment] 2020-05-28 12:08
Duplicate of #194

**Closed by ligurio** 2020-05-28 12:08 UTC
Labels: need feedback, qa, test-run.py
