### ISSUE TITLE
travis-ci: need to switch add force flag at release either even at all travis-ci test jobs

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4101] opened 2019-04-05 07:31 UTC
Tarantool version:
All

OS version:
All

Bug description:
It is needed to add force flag at Tarantool release either even at all tarvis-ci test jobs, to be able to show all failings tests.

Steps to reproduce:
Run on travis-ci

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment] 2019-05-27 08:18
Dupe of #4131. Already fixed.

**Closed by Totktonada** 2019-05-27 08:18 UTC
Labels: flaky test
