### ISSUE TITLE
FreeBSD build error: no SSL support

### ISSUE THREAD

**Issue by kbelyavs** [tarantool/tarantool#3750] opened 2018-10-17 13:35 UTC
On 1.10, FreeBSD 11.1 cmake fails with following error:
-- Performing Test CURL_SUPPORTS_SSL - Failed

**Comment by Totktonada** [comment] 2018-11-02 11:31
Tried to build from source on FreeBSD 11.2 and all seems to be fine. Are you have any other information how to reproduce the issue?

**Comment by Totktonada** [comment] 2018-11-02 14:13
Reproduced on FreeBSD 10.4.

**Comment by Totktonada** [comment] 2018-11-02 14:17
```
/usr/bin/cc  -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -DCURL_SUPPORTS_SSL    CMakeFiles/cmTC_d99a3.dir/src.c.o  -o cmTC_d99a3 -Wl,-rpath,/usr/local/lib /usr/local/lib/libcurl.so /usr/lib/libssl.so /usr/lib/libcrypto.so -lpthread -ldl 
/usr/bin/ld: cannot find -ldl
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by locker** [comment] 2018-11-03 06:30
Fixed by 46e4c702b09dc3ad03d528d5bf8447a41b8c9d6d

**Closed by locker** 2018-11-03 06:30 UTC
Labels: build, freebsd
