### ISSUE TITLE
replication_connect_quorum breaks bootstrap

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#4321] opened 2019-07-02 11:40 UTC
I have two instances, with the following settings:
```
box.cfg{listen=3303,
    replication={ "3303", "3304" },
    replication_connect_quorum=0
}
box.schema.user.grant('guest', 'read,write,execute', 'universe', nil, {if_not_exists=true})

require('console').start()
```

```
box.cfg{listen=3304,
    replication={ "3303", "3304" },
    replication_connect_quorum=0
}
box.schema.user.grant('guest', 'read,write,execute', 'universe', nil, {if_not_exists=true})
require('console').start()
```

I have two empty data directories. They boot just fine for the first time and for subsequent times.

If I remove replication_connect_quorum=0, the initial bootstrap fails. The leader of the bootstrap successfully creates the snapshot but waits for the other replica to fully sync before leaving boostrap. The other replica can't sync because the leader hasn't granted it permissions to connect. 

The fix should make a special case in replication_connect_quorum for the bootstrap case, and make sure the leader considers all replicas connected as soon as it bootstraps in such case.

**Comment by locker** [comment] 2019-07-31 10:55
I can't reproduce this issue. Neither on 2.x, nor on 1.10.

AFAICS bootstrap leader never waits for sync to complete, see https://github.com/tarantool/tarantool/blob/dc92c5315f645e0e1587ac7e00001f43260704c3/src/box/box.cc#L2179

**Comment by bofm** [comment] 2019-07-31 15:33
Please check this docker-compose environment for the test case.
https://gist.github.com/bofm/acef0013bfae1bd3fa126af697aa4463

**Comment by locker** [comment] 2019-07-31 16:13
Thanks. I managed to reproduce the problem locally with the aid of the script you provided.

**Comment by locker** [comment] 2019-07-31 16:51
@bofm It looks like there's a mistake in your docker-compose script. The second instance (t2) doesn't grant privileges to the guest so if it happens to become a bootstrap leader, the first instance (t1) won't be able to connect to it.

You should add

```Lua
box.once('guest', box.schema.user.grant, 'guest', 'super')
```

after `box.cfg()` in both scripts.

Doing that solved the problem for me.

**Comment by locker** [comment] 2019-08-06 11:52
Looks like a configuration issue, not a bug. Closing it now. Feel free to reopen it if you disagree and have anything else to say.

**Comment by bofm** [comment] 2019-08-27 17:20
Please reopen

To reproduce please do the following:
1. Create an empty dir and cd into it
2. Run 
   ```
   echo 'H4sIAAZcZV0AA+1ZbW/aMBDmc37FKaoKrSDEdgJSp+2vIDcx1CI4WewMKsp/39mBDnV0XT+E0s0PUvxy5/P5LnlyQDTudY44jqdxDK6dpK6NadK2ewBhKSM0TW0/JmTCkh6k3bvW6zXa8Bpd0aJeiMfX9VBtPv+Dnf05nttPgmhsaNe3gM17mv5d/idpgvmnlFCf/3MA888uMv/M5/8ciMZ1oyL90OUeb+WfJvQo/5b/WUzx+Y+7dOqA/zz/87IGCVIBAQrsC+RlAIgsB3MlXVcXQlSwH2CsuDJlWVhxVDQcrr+13XIB14eloyAvlQiCdimNg2ApiwKuBpUGvnla1Dj7y9ITuAlr7An4egn9bVVLZeCK7Po3wUdH6N9GNM4KwbtlgDf5P5m8qP8YnUz9838O1Cswt+PbSCteBYfBBp/m54Htf7SXHl0B6z9ykfUf8fXfOeDyb4h9lXe2B8ZjkiSv5h/Znh3yz/AWcPzPfP13FtyXmyibL7ZYus2FyO95tpwJxe8LkcNXmPNCiyHKsEArZMaNLNUsK5USmZkZuRJlY1CNvKbyvSnrZoUasdWQCoOoMjFrGmmth3yP0YnLHiQ8sq2Fec9aHr7wC9dtXY0aEjqNYvyQO8bido+Xs/TkLHOzO3sppDbC2jxlrRY8n5WqeES5qRsM4i4IXLBNEa25NLN6PbgJgtEIKlFjFb6CdS2NgBKHzlmnXWK4BqHOHsSKRz9ItLBFc7RohDaRblA1HILV22s0eBe3OkMInRbKw1bx5qRBXfFMRKbVnDcqs1ujY/bko5FrijLjBWg8yNFO7boMj2nQnlvfLtJ39jDcDNpIW2yhL/P+EPqN0nKhRN5vA/gszbnhVq5xI14/S3cHi+02M6lysRmE1RJd3ULFa2Odaq3DzqoLlfsvDO+C+/3HsA/m/+SI/2nL/4nn/3Pg0vmffTr+Z7/x/z6K/gXgXwAXB/f/j6GXUv+TSTxt+Z95/j8HLp3/6afjf+rrf0//Hh4eHh4eF42f0iwoyQAoAAA=' | base64 -D > test.tar.gz
   ```
3. Run `tar -xzf test.tar.gz`
4. There will be this dir structure
    ```
    .
    ├── clean.sh
    ├── run.sh
    ├── t1
    │   ├── t1.log
    │   └── t1.lua
    ├── t2
    │   ├── t2.log
    │   └── t2.lua
    └── t3
        ├── t3.log
        └── t3.lua
    ```
5. Run `./run.sh` and wait 20 seconds.
6. Check the logs in t1, t2, t3 dirs. t2 won't bootstrap.

**Comment by kostja** [comment] 2019-08-27 17:23
my initial analysis was wrong, as is indicated by this test case. we do not take into account rread only mode when electing a leader, and thus an elect leader gets stuck in read only.

**Closed** 2019-09-12 05:12 UTC
Labels: bug, replication
