### ISSUE TITLE
Some operations with temporary spaces are replicating

### ISSUE THREAD

**Issue by morokin** [tarantool/tarantool#3453] opened 2018-06-11 15:24 UTC
Master 1
test0.lua
```
box.cfg {
  listen = 3301,
  replication = {
    'repl:password@127.0.0.1:3301', -- master
    'repl:password@127.0.0.1:3302' -- master
  },
  read_only = false,
  log_level = 5,
}

box.once("init_users", function()
  box.schema.user.create('repl', {password = 'password'})
  box.schema.user.grant('repl', 'replication')
  box.schema.user.grant('guest', 'read,write,execute', 'universe')
end)
```

```
box.info
---
- version: 1.9.1-25-ge38d276
  id: 1
  ro: false
```

Master 2
test1.lua
```
box.cfg {
  listen = 3302,
  replication = {
    'repl:password@127.0.0.1:3301', -- master
    'repl:password@127.0.0.1:3302' -- master
  },
  read_only = false,
  log_level = 5,
}

box.once("init_users", function()
  box.schema.user.create('repl', {password = 'password'})
  box.schema.user.grant('repl', 'replication')
  box.schema.user.grant('guest', 'read,write,execute', 'universe')
end)
```

```
box.info
---
- version: 1.9.1-25-ge38d276
  id: 2
  ro: false
```

Space created on Master 1 with:
`box.schema.space.create('temporary', {temporary=true})`
appears on Master 2

Index created on Master 1 with:
`box.space.temporary:create_index('uuid', {unique = true, parts = {1, 'string'}})` 
appears on Master 2

Operation truncate() executed on Master 1 like this:
`box.space.temporary:truncate()`
truncates temporary space on Master 2

Operation drop() executed on Master 1 like this:
`box.space.temporary:drop()`
drops relevant temporary space on Master 2

Operations like put and insert are not replicating (so far).

**Comment by kyukhin** [comment] 2018-07-05 09:49
This is not a bug.
Currently, all DDLs related to temporary spaces are replicated.
Any DQL is not.

Please see https://tarantool.io/en/doc/1.9/book/replication/repl_architecture/

Closing.

**Closed by kyukhin** 2018-07-05 09:49 UTC
