### ISSUE TITLE
vinyl: allow building indexes on a non-empty space

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2448] opened 2017-05-18 14:45 UTC
Currently it is impossible to add a secondary key in vinyl on a non-empty space.
Allow this, by building the index in the background.

**Comment by rtsisyk** [comment] 2017-05-18 16:27
Probably we need to implement online alter for memtx first.

**Comment by locker** [comment] 2018-05-29 14:56
Duplicate of #1653

**Closed by locker** 2018-05-29 14:56 UTC
Labels: feature, vinyl
