### ISSUE TITLE
Halting a statement when a table is deleted from another session

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#2246] opened 2017-03-24 10:43 UTC
If table `T` is deleted, prepared statement `S` working with `T` must halt. If `S` is invoked again it must fail to start execution.

There's a schema version check in-pace. However this check only happens before entering the interpretor. If statements are interleaved in a more complex fashion, i.e. concurrent fibers or triggers or row callbacks, this breaks.

Vanilla SQLite didn't allow to `DROP` anything when there was any statement currently executing. This safeguard was broken when Tarantool storage was grafted instead of SQLite's native one.

This ticket requires some serious design work. Assorted thoughts:

 * Proper transaction support for schema will fix the issue for concurrent sessions. It make take long before the feature becomes available.

 * #2245 may help to find affected statements.

Right now, the issue manifests itself in `table-14.2` subtest.

**Comment by kostja** [comment] 2017-07-04 11:19
A duplicate of gh-2024

**Closed** 2017-07-04 11:21 UTC
Labels: sql
