### ISSUE TITLE
[centos] Luarocks not found packages

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#1978] opened 2016-12-08 10:04 UTC
Centos can't find packages if install packages from luarocks.

That line fixed that issues at the moment but more better fix it in tarantool.
```
package.cpath = '/usr/share/lua/5.1/?.lua;' .. package.cpath
```

**Comment by rtsisyk** [comment] 2016-12-08 12:02
Duplicate of #1702

**Closed** 2017-01-10 11:03 UTC
