### ISSUE TITLE
Wrong error message in console when function has transaction

### ISSUE THREAD

**Issue by aensidhe** [tarantool/tarantool#3318] opened 2018-04-04 19:37 UTC
Expected: 'unique key violation`, etc.

````
$ tarantoolctl connect admin:PASSWORD@localhost:3301
connected to localhost:3301
localhost:3301> box.space.test:select{}
---
- []
...

localhost:3301> g()
---
...

localhost:3301> g()
---
- error: Transaction is active at return from function
...

localhost:3301> box.space.test:select{}
---
- - [1]
...

localhost:3301> box.info
---
- version: 1.10.0-0-g42612ec04
  id: 1
  ro: false
  vinyl: []
  vclock: {1: 6}
  uptime: 21
  lsn: 6
  memory: []
  cluster:
    uuid: ff4df059-bf7f-4b5b-b807-e6d549fad06d
  pid: 1
  status: running
  signature: 6
  replication:
    1:
      id: 1
      uuid: 625a6872-af83-49e2-92df-c8a75ce9816f
      lsn: 6
  uuid: 625a6872-af83-49e2-92df-c8a75ce9816f
...
````

lua file:
````
#!/usr/bin/env tarantool

box.cfg
{
    pid_file = nil,
    background = false,
    log_level = 5,
    log_format = 'json'
}

g = function()
    box.begin()
    box.space.test:insert{1}
    box.commit()
end

box.schema.create_space('test', { if_not_exists=true })
box.space.test:create_index('primary', { unique=true, parts={1}, if_not_exists=true })
````

**Comment by kyukhin** [comment] 2018-07-09 08:19
Duplicate of #1148.
Feel free to + the original issue.

**Closed by kyukhin** 2018-07-09 08:19 UTC
Labels: bug
