### ISSUE TITLE
Fix online try console to allow multiple commands

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#4584] opened 2019-10-24 09:05 UTC
https://www.tarantool.io/en/try-dev/

Error when copy-pasting multiple commands (e.g. from `tutorial()` screen 3, like in https://github.com/tarantool/doc/issues/954). Works ok with a local tarantool 1.10.3.

**Comment by Totktonada** [comment] 2019-10-27 15:57
This is not exactly same issue, but related: https://github.com/tarantool/try/issues/29

**Comment by Gerold103** [comment] 2019-11-19 22:23
Talking of this concrete case, looks it the problem is that you can't put a variable to print to the end of a command. For example, consider this one-line, which also does not work on try, and on 1.10.3:
```
result_table = {} n = 5.1 for i=1,2,1 do result_table[i] = n * i end result_table 
```
It expects more input, when I try locally. And raise the same error as multiline on the site.
But when I do this, it works:
```
result_table = {} n = 5.1 for i=1,2,1 do result_table[i] = n * i end result_table = {}
```
Not the same, but works.

**Comment by Gerold103** [comment] 2019-11-19 22:25
I think we should just fix the online tutorial.

**Comment by Totktonada** [comment] 2019-11-20 12:27
I would propose box.session.push() (or console.print() after #4393) to write results to a console. However it looks as a problem for me anyway (maybe try's one): why it is matter whether we put a bunch on commands one-by-one or using copy-paste? I think we should elaborate despite whether we'll work it around or will not.

**Comment by Gerold103** [comment] 2020-02-17 21:19
I am not sure what to elaborate here. The problem is not related to push. This is just the language. Syntax. It is not like C. Expression block does not have value of the last expression. And clearly this is exactly what is expected in the example.
You can't in Lua write
```
test = {1, 2, 3}
test2 = {}
for k, v in pairs(test) do test2[k] = v end test2
```
And expect that the 3rd line would have value of the table `test2`. This does not work in a console, nor in a file.

**Comment by patiencedaur** [comment] 2022-02-18 13:13
@ artur-barsegyan says it's resolved. Closing.

**Closed by patiencedaur** 2022-02-18 13:13 UTC
Labels: bug, needs feedback
