### ISSUE TITLE
JIT slowdown on tarantool_lua_ibuf

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2039] opened 2017-01-23 16:01 UTC
while ./test-run.py wal_off/iterator_lt_gt; do sleep 0.1; done

```
wal_off/iterator_lt_gt.test.lua                                 [ fail ]

Test failed! Result content mismatch:
--- wal_off/iterator_lt_gt.result       Mon Jan 23 18:56:05 2017
+++ wal_off/iterator_lt_gt.reject       Mon Jan 23 18:57:08 2017
@@ -81,7 +81,7 @@
 ...
 too_longs
 ---
-- []
+- - 'Some of the iterators takes too long to position: 0.13003'
 ...
 s:drop()
```

I bisected and found this problem is caused by e7750168ff900292b29f4862bfbdd3f8f0a453e3, which break JIT compilation of `for .. in` loop in the test.

before e7750168ff900292b29f4862bfbdd3f8f0a453e3:

```
[TRACE   3 buffer.lua:44 return]
[TRACE   4 "for i=1,10000 do s:insert{1, i} end ":1 stitch C:55ecc9fe0f32]
[TRACE   5 "for i=1,10000 do s:insert{1, i} end ":1 -> 4]
[TRACE   6 0x41fdf5e8:893 return]
[TRACE   4 socket.lua:80 return]
[TRACE --- buffer.lua:60 -- leaving loop in root trace at socket.lua:596]
[TRACE --- console.lua:187 -- inner loop in root trace at socket.lua:712]
[TRACE --- fiber.lua:13 -- leaving loop in root trace at socket.lua:637]
[TRACE   5 0x41fd9310:636 return]
[TRACE   7 fun.lua:56 return]
[TRACE   8 msgpackffi.lua:56 return]
[TRACE --- msgpackffi.lua:487 -- leaving loop in root trace at msgpackffi.lua:489]
[TRACE   9 0x4038e8c0:1 loop]
[TRACE  10 (9/30) 0x41ea83b8:606 -> 9]
[TRACE  11 (9/63) 0x4038e8c0:1 -> 9]
[TRACE  12 (9/33) 0x41ea83b8:604 -> 9]
[TRACE  13 (4/0) socket.lua:81 stitch C:55ecca012573]
[TRACE  14 socket.lua:260 return]
[TRACE --- fiber.lua:13 -- leaving loop in root trace at socket.lua:637]
[TRACE --- buffer.lua:89 -- leaving loop in root trace at socket.lua:641]
[TRACE  15 0x41ea8078:197 return]
```

after e7750168ff900292b29f4862bfbdd3f8f0a453e3:
```
[TRACE   3 buffer.lua:45 return]
[TRACE   4 console.lua:61 stitch loadstring]
[TRACE   5 console.lua:71 stitch loadstring]
[TRACE   6 "for i=1,10000 do s:insert{1, i} end ":1 stitch C:55f46bdc9f82]
[TRACE   7 "for i=1,10000 do s:insert{1, i} end ":1 -> 6]
[TRACE   8 0x419b6780:893 return]
[TRACE   9 socket.lua:80 return]
[TRACE  10 console.lua:73 stitch debug.getinfo]
[TRACE --- buffer.lua:61 -- leaving loop in root trace at socket.lua:639]
[TRACE --- (3/0) buffer.lua:46 -- symbol not in cache at 0x419b25e8:733]
[TRACE --- (3/0) buffer.lua:46 -- loop unroll limit reached at 0x419b25e8:739] <!-- OMG
[TRACE --- (3/0) buffer.lua:46 -- loop unroll limit reached at 0x419b25e8:739]
[TRACE --- (3/0) buffer.lua:46 -- loop unroll limit reached at 0x419b25e8:739]
[TRACE   6 (3/0) buffer.lua:46 -- fallback to interpreter]
[TRACE   7 buffer.lua:98 return]
[TRACE  11 msgpackffi.lua:56 return]
[TRACE  12 buffer.lua:76 return]
[TRACE  13 0x40bd5870:1 loop]
[TRACE  14 (13/30) 0x419acfa8:606 -> 13]
[TRACE  15 (13/63) 0x40bd5870:1 -> 13]
[TRACE  16 (13/33) 0x419acfa8:604 -> 13]
[TRACE  17 (9/0) socket.lua:81 stitch C:55f46bdfb5e1]
[TRACE --- fiber.lua:13 -- leaving loop in root trace at socket.lua:988]
[TRACE --- (17/2) socket.lua:88 -- loop unroll limit reached at buffer.lua:63]
[TRACE --- msgpackffi.lua:487 -- leaving loop in root trace at msgpackffi.lua:489]
[TRACE  18 socket.lua:711 return]
[TRACE  19 socket.lua:131 return]
```

relevant parts of diff (see e7750168ff900292b29f4862bfbdd3f8f0a453e3):

```
+extern struct ibuf *tarantool_lua_ibuf;

 struct ibuf
 {
@@ -175,6 +176,6 @@ end

 return {
     ibuf = ibuf_new;
-    IBUF_SHARED = ibuf_new();
+    IBUF_SHARED = ffi.C.tarantool_lua_ibuf; <!-- relevant part
     READAHEAD = READAHEAD;
}
```

**Comment by Buristan** [comment] 2020-06-12 09:32
I suppose that this issue is not related to JIT problem, I couldn't find the root case but I have the wild guess that this issue corresponds with number of Lua GCobjects.
First of all it is possible to get `loop unroll limit reached` before commit [`e775016`](https://github.com/tarantool/tarantool/commit/e7750168ff900292b29f4862bfbdd3f8f0a453e3) too (see jit dumps **[2]** below) and also the regression can be reproduced when using `jit.off()`, so it's looks like not critical to faced with `LJ_TRERR_LUNROLL` here.

But regression still exists so I wrote pure lua reproducer **[3]** without using of `test-run`. I decreased number of tuples at space up to 3 (because it isn't interesting to us here) and test only one iterator (I suppose that it's not necessary to use exactly iterators or tuples here - it will be enough only some generated cdata with `__gc` metafield, but iterators (I used `"GE"`, but it doesn't really matter) that returns tuples showed themselves pretty well at this). Also I increased number of iterations to be able to see really difference at long distance.
I bench it with Debug build because the difference was more meaningful, but results reproduced with Release build too.

Before using collect_garbage in the reproducer script I had very unstable results: (same or difference up to 35 seconds). However, degradation of about 2-8% could be observed. But after looking at flamegraphs **[1]** which showed a significant time difference I noticed that pretty much all extra samples are inside `lj_gc_step`.
So I decided to count GC objects after and before the commit, and at longer runtime I have much bigger amount of Lua memory given by `collectgarbage "count"`. So I suppose that the reason somewhere around GC. Moreover I couldn't reproduce the regression after usage of `collectgarbage "collect"`. Amount of Lua memory usage after bootstrap is unstable so it is hard to tell where the excess of objects is formed _and whether it forms at all_. My only guess is that when we start tarantool instance and push tuples to Lua it generates garbage as fast as collect this and extra increase of Lua GCobjects appears.

The output of this test shows only amount of memory usage of Lua in Kb, not number of objects, but I think that their total amount is about the same. I couldn't reproduce the problem with almost the same values of `collectgarbage "count"`.
Inaccuracy is about 1% (5/480 seconds).

Before commit:
```
../src/tarantool --version && ../src/tarantool my_test.lua
Tarantool 1.6.8-43-ga3ef67191
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_TRACE=ON -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fno-common -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -fno-gnu89-inline
CXX_FLAGS: -fno-common -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -Wno-invalid-offsetof

Generating objects
objs:   900001
Start bench
Iterator GE take 483.0 seconds, for 50000000 tests

Generating objects
objs:   900008
Start bench
Iterator GE take 484.7 seconds, for 50000000 tests

Generating objects
objs:   900020
Start bench
Iterator GE take 481.9 seconds, for 50000000 tests
```

And after commit:
```
../src/tarantool --version && ../src/tarantool my_test.lua
Tarantool 1.6.8-44-ge7750168f
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_TRACE=ON -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fno-common -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -fno-gnu89-inline
CXX_FLAGS: -fno-common -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -Wno-invalid-offsetof

Generating objects
objs:   900007
Start bench
Iterator GE take 485.1 seconds, for 50000000 tests

Generating objects
objs:   900019
Start bench
Iterator GE take 480.3 seconds, for 50000000 tests
10:12:28 jobs:0 burii@root:~/builds_workspace/tarantool/e775016/test$

Generating objects
objs:   900008
Start bench
Iterator GE take 483.8 seconds, for 50000000 tests
```


**[1]**: [flamegraphs.tar.gz](https://github.com/tarantool/tarantool/files/4769875/flamegraphs.tar.gz)
**[2]**: [jitdumps.tar.gz](https://github.com/tarantool/tarantool/files/4769876/jitdumps.tar.gz)
**[3]**: [reproducer.tar.gz](https://github.com/tarantool/tarantool/files/4769877/reproducer.tar.gz)

**Comment by igormunkin** [comment] 2023-07-06 08:19
@Buristan, thanks for investigation! AFAIU, no regression has been found nearby the mentioned commit (NB: `collectgarbage('collect')` calls make benchmarks more predictable, that was not done in the original measures).

Closing then.

**Closed by igormunkin** 2023-07-06 08:19 UTC
Labels: bug, regression, luajit
