### ISSUE TITLE
Replica's LSN updated before the triggers run

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1049] opened 2015-09-18 10:54 UTC
This happens with replication/cluster test. Here's the relevant snippet from the test:

``` python
master.admin('box.space._cluster:delete{%d}' % replica_id)
replica.wait_lsn(master_id, master.get_lsn(master_id))
replica.admin('box.info.server.id')
replica.admin('box.info.server.ro')
replica.admin('box.info.server.lsn') # -1
replica.admin('box.info.vclock[%d]' % replica_id)
# replica is read-only
replica.admin('box.space._schema:replace{"test", 48}')
```

The (augmented) replica log:

```
2015-09-05 14:52:14.753 [61260] main/104/replica/localhost:4516 I> on_replace_dd_cluster
2015-09-05 14:52:14.754 [61260] main/108/console/127.0.0.1:34800 I> pre eval (box.info.vclock)
2015-09-05 14:52:14.755 [61260] main/108/console/127.0.0.1:34800 I> eval (box.info.vclock)
2015-09-05 14:52:14.755 [61260] main/108/console/127.0.0.1:34800 I> pre eval (box.info.server.id)
2015-09-05 14:52:14.755 [61260] main/108/console/127.0.0.1:34800 I> post eval (box.info.server.id)
2015-09-05 14:52:14.755 [61260] main/108/console/127.0.0.1:34800 I> pre eval (box.info.server.ro)
2015-09-05 14:52:14.756 [61260] main/108/console/127.0.0.1:34800 I> post eval (box.info.server.ro)
2015-09-05 14:52:14.756 [61260] main/108/console/127.0.0.1:34800 I> pre eval (box.info.server.lsn)
2015-09-05 14:52:14.756 [61260] main/108/console/127.0.0.1:34800 I> post eval (box.info.server.lsn)
2015-09-05 14:52:14.756 [61260] main/108/console/127.0.0.1:34800 I> pre eval (box.info.vclock[2])
2015-09-05 14:52:14.756 [61260] main/108/console/127.0.0.1:34800 I> post eval (box.info.vclock[2])
2015-09-05 14:52:14.756 [61260] main/108/console/127.0.0.1:34800 I> pre eval (box.space._schema:replace{"test", 48})
2015-09-05 14:52:14.756 [61260] main/104/replica/localhost:4516 I> on_commit_dd_cluster
```

**Comment by rtsisyk** [comment] 2016-11-14 10:54
I have made a branch which fixes this problem: remove-tx-vclock

**Comment by rtsisyk** [comment] 2016-11-22 07:58
This problem will be fixed by #1865.

**Comment by rtsisyk** [comment] 2017-04-11 06:38
@kostja I planned to use vclock from WAL for box.info.vclock() in order to fix this problem. Lately we decided to use dirty replicaset_vclock for box.info.vclock(). How is this bug supposed to be fixed? Can I close it with "wontfix"?

**Comment by kostja** [comment] 2017-04-17 17:28
Duplicate of g-2283

**Closed by kostja** 2017-04-17 17:28 UTC
Labels: bug, need feedback
