### ISSUE TITLE
Tarantool does not start on reboot on Ubuntu 17.04

### ISSUE THREAD

**Issue by isopov** [tarantool/tarantool#2533] opened 2017-06-20 18:33 UTC
Installed Tarantool following instructions on the site. After install it started. But after every restart it does not start with the rest of the system.
```
$ sudo service tarantool status
● tarantool.service - Tarantool Database Server
   Loaded: loaded (/lib/systemd/system/tarantool.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```
Workaround - manual `sudo service tarantool start` after reboot solves the problem.

**Comment by isopov** [comment] 2017-06-20 18:36
Maybe it will be helpful. On reboot with tarantool running in /var/log/tarantool/example.log there is

```
2017-06-18 16:04:43.877 [6912] main C> got signal 15 - Terminated
2017-06-18 16:04:43.877 [6912] main main.cc:478 !> failed to remove pid file '/var/run/tarantool/example.pid': No such file or directory
```

**Comment by amdei** [comment] 2017-06-20 19:23
Isn't it the same as #2513?

**Comment by isopov** [comment] 2017-06-20 19:45
I think yes. Should I close it as duplicate, or leave it for testing on Ubuntu?

**Comment by amdei** [comment] 2017-06-20 19:55
Well, after reading first comment again I think the issue is different - in case of #2513 tarantool even not attempt to start, as service is not enabled when package build.
But in this case - there is something in the logs, at least.

**Comment by isopov** [comment] 2017-06-21 07:44
`failed to remove pid file` is on stopping and is not an attempt to start, AFAIU

**Comment by rtsisyk** [comment] 2017-08-17 06:15
Duplicate of #2190

**Closed by rtsisyk** 2017-08-17 06:15 UTC
