### ISSUE TITLE
Support graceful shutdown in IProto

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#5924] opened 2021-03-19 15:30 UTC
**The Problem I**: Under any load every planned instance shutdown inevitable leads to broken requests (that leads to client errors on upper levels). Even if the instance is completely stateless, like proxy or vshard balancer and there are lots of them.
**Th Problem II**: From Tarantool side there is no possibility to cause client to lose it's connection or ant way force it to reconnect.

**The Solution**: implement support for shutdown challenge.

### Common flow for shutdown:

1. Instance is signaled via SIGTERM (or by `os.exit`) to shutdown.
At that moment there could be:
    + Listen sockets, than accept new connections
    + Active opened connections
    + Some fibers, that currently processing requests (incl long requests with `box.session.push` scenario)
    + Some requests "in the fly", that was already sent by client into this connection, but yet not accepted by Tx.
    + Some responses "in the fly", that was already replied by Tx and are in state of sending data
2. Server should stop accept io and close listen sockets. This will lead that new connections would not created, but existing ones continue to work
3. Server should iterate over all it's open connections and:
    - invoke `box.session.on_shutdown` trigger (to be implemented), to notify lua world
    - if connection support shutdown (to be discussed), then:
        + send to it `SHUTDOWN` packet
    - if connection does not support shutdown, then:
        + read current socket until iproto packet boundary
        + then `shutdown(s, SHUT_RD)` this connection to prevent further reads
4. Server should wait (within shutdown_timeout) on connections for:
    - if connection support shutdown (TBD), then:
        + wait for `SHUTDOWN` packet from client side
        + upon receival do `shutdown(s, SHUT_RD)` to connection.
        + watch active requests count. when it comes to `0`, close this connection
    - if connection does not support shutdown, then:
        + watch active requests count. when it comes to `0`, close this connection
    - when open connection count comes to `0`, shutdown is done.

Upon receival `SHUTDOWN` from any client server should:
* mark connection as `support shutdown` if not yet
* invoke `box.session.on_shutdown` trigger
* perform `shutdown(s, SHUT_RD)` on connection
* when active requests count comes to `0` send `SHUTDOWN` back to client and close connection.

### Common flow for single connection shudown from lua:

1. Userland code invokes `box.session.shutdown()` or `session:shutdown()`
2. Server performs steps 3 & 4 of shutdown flow for given single connection

### Per connection shutdown support

It is not possible to implement graceful shutdown support with a config option. One server could serve clients with and without support for it.
So, we should support it on a per-connection basis.
Within connection there is already a mechanism, called [`_session_settings`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/_session_settings/): special pseudospace, that reflects current session settings. We could allocate new value `graceful_shutdown`, so any client, that support graceful shutdown shuld set it to `true` after connection establishment.

**Comment by Mons** [comment] 2021-03-19 15:37
It seems, that for the first we should implement Lua API .shutdown/.on_shutdown per session.
Then, with a little addition of `list all active sessions` method and `on_shutdown` trigger rest of the logic could easily be implemented with Lua.

**Comment by akudiyar** [comment] 2021-03-19 15:37
What is the reason for a separate SHUTDOWN packet, if there's an `on_shutdown` trigger? Why just closing the connection isn't enough?

**Comment by Mons** [comment] 2021-03-19 16:02
> What is the reason for a separate SHUTDOWN packet, if there's an `on_shutdown` trigger? Why just closing the connection isn't enough?

`Problem I`: There could be active requests, that will inevitable fail.

**Comment by Totktonada** [comment] 2021-03-19 16:23
So, if a connection does not support shutdown, requests in the fly will be finished (within a timeout), but when the connection supports shutdown, there will be no waiting for requests to finish?

BTW, when exactly shutdown is supported / not supported (do you know some cases / conditions at least)?

**Comment by alyapunov** [comment] 2021-03-30 13:25
1. I don't like `shutdown(SHUT_RD)`. It does not notify peer. It only makes the socket marked as read-ready (you'll get event) and makes reads from the socket to return 0. It's not the thing that a programmer usually whats to. Actually we need to stop the read watcher, and `shutdown(SHUT_RD)` might be an additional fool-tolerance step.
2. I don't like `SHUTDOWN` packet from client side. Graceful shutdown from client usually implies `shutdown(SHUT_WR)` from client and reading until got zero result. It think tarantool should follow this rule (maybe it follows already). Having that I don't see another way to make exactly the same but via IPROTO.
3. How to determine whether the client support this feature or not? I bet we would need a special IPROTO command for that, or other protocol changes.. A matter of discussion.
4. Up to the moment we didn't need to know what the client supports or not. I would prefer if we continue to support simple version-less protocol.
5. I think that `box.session.on_shutdown` should be implemented separately. Or even should not be implemented. If a server is shutting down - we already have `box.ctx.on_shutdown`, if a client wants to shutdown - it can call anything it wants by itself.

**Comment by Mons** [comment] 2021-03-30 16:37
> I don't like shutdown(SHUT_RD). It does not notify peer. It only makes the socket marked as read-ready (you'll get event) and makes reads from the socket to return 0. It's not the thing that a programmer usually whats to. Actually we need to stop the read watcher, and shutdown(SHUT_RD) might be an additional fool-tolerance step.

And it should not notify a peer. It's a common way for graceful socket shutdown. Stopping read watcher is implied.

> I don't like SHUTDOWN packet from client side. Graceful shutdown from client usually implies shutdown(SHUT_WR) from client and reading until got zero result. It think tarantool should follow this rule (maybe it follows already). Having that I don't see another way to make exactly the same but via IPROTO.

It is required not for generic request/response case but for pub/sub scenario, when infinite request/`box.session.push` are used.

> How to determine whether the client support this feature or not? I bet we would need a special IPROTO command for that, or other protocol changes.. A matter of discussion.

We already have `_session_settings` for it.

> Up to the moment we didn't need to know what the client supports or not. I would prefer if we continue to support simple version-less protocol.

It is impossible to implement a graceful shutdown with current protocol implementation. You need a way to say to your peer: "Hey, stop sending requests and just wait for your pending responses".

> I think that box.session.on_shutdown should be implemented separately. Or even should not be implemented. If a server is shutting down - we already have box.ctx.on_shutdown, if a client wants to shutdown - it can call anything it wants by itself.

I thought we may implement graceful shutdown by implementing only `box.session.shutdown`/`box.session.on_shutdown`/`box.session.list` and connecting them with `box.ctx.on_shutdown` in lua userland, like
```lua
box.ctx.on_shutdown(function()
    local cond = fiber.cond()
    local active = 0
    for _, session in box.session.list() do
        active = active + 1
        fiber.create(function()
            box.session.shutdown([ timeout ]) -- this will yield until session shutdown or timeout
            active = active - 1
            if active == 0 then
                cond:send()
            end
        end)
    end
    if active > 0 then
        cond:wait()
    end
end)
```

**Comment by Mons** [comment] 2021-03-31 08:52
**Discussed by voice**.

>> I don't like SHUTDOWN packet from client side. Graceful shutdown from client usually implies shutdown(SHUT_WR) from client and reading until got zero result. It think tarantool should follow this rule (maybe it follows already). Having that I don't see another way to make exactly the same but via IPROTO.
> It is required not for generic request/response case but for pub/sub scenario, when infinite request/box.session.push are used.

Decided not to do it now. Also don't implement `box.session.on_shutdown`. `box.session.push` anyway needs redesign

**Comment by iskander232** [comment] 2021-05-11 11:46
### How client that support `graceful shutdown` can handle `shutdown` from server via `net.box`

1. `net.box.shutdown` - send `shutdown` package to server
2. `net.box.set_shutdown_handler` - set handler to run when `shutdown` from server is received. By default this handler is `net.box.shutdown`

**Comment by iskander232** [comment] 2021-06-11 10:25
**Discussed by voice**.

1. Make `graceful_shutdown(struct iproto_thread *iproto_thread)`. SIGTERM, os.exit, ... should call graceful_shutdown(struct iproto_thread *iproto_thread) for each `iproto_thread`.
2.  Make `join` instead of `cancel` in case of stopping the thread
3. Think about the timeout for `graceful shutdown`.
4. Appeared the question - what from implementation of `graceful shutdown` we want to see in Lua-world.

**Comment by alyapunov** [comment] 2021-06-21 12:35
Summary of huge offline discussion.
First of all, in any case we have to do the following:
1. Ensure that sever handle properly part of request followed by connection close.
2. Ensure that net.box client handle properly part of response followed by connection close. I would also check that we have test for EPIPE/ECONNRESET handling in net.box.

Then, we should admin that the described graceful shutdown procedure is not so simple to implement and support. That makes us to question: is graceful shutdown worth the cost of implementation and support? What do we have:
1. Graceful shutdown guarantees that tarantool doesn't introduce more errors into client-server communication due to server shutdown. That means that if network and application don't produce errors without shutdown, there would be no errors in case of shutdown.
2. On the other hand even with graceful shutdown feature a client (in general meaning) must be ready to reconnect and retry a request in case of network or timeout error. And if is ready ready to handle a error and retry - it will handle tarantool's shutdown  with EOF error without any additional support on server side.

So the question is - are tarantool users really require the issue and need graceful shutdown and why?

**Comment by iskander232** [comment] 2021-06-21 13:06
Old pull request is not relevant, because it has lots of architectural problems and new pull request is tries to solve them

**Comment by Mons** [comment] 2021-06-21 21:20
Remove `net.box` from consideration. There are dozens of connectors. You can't influence them. Therefore, the solution was described for the scenario without modifying any connector.

The graceful shutdown does not guarantee the absence of errors. It provides an opportunity to dramatically reduce their number. Ideally, down to 0. I.e., with the correct implementation of the client and server API. The current implementation and protocol do not provide such capabilities. I.e. it is basically impossible.

**Comment by Gerold103** [comment] 2021-06-28 22:25
I was asked to repeat what I said in the face-to-face discussion about why this issue is not needed and is even harmful when it comes to the code complexity.

The whole point of the issue is to make client's life easier, right? To allow them not to worry about timeouts and retries when the instance is being shutdown gracefully. The main problem of the design and of the patchset regardless of how and who implements it is that these issues won't go away. Whatever you are doing, the client still needs to be able to handle network issues, timeouts, and sudden socket closures even if they are done by the server "gracefully" via `close()`.

I elaborate below:

**Number of errors is still the same**
You wanted to reduce number of errors during shutdown? The present design won't help with that. In the best case it probably could reduce their frequency. But not get rid of them. This simple fact means that the client won't be able to remove any code from its connector about handling network break, but will need to add more code to support the shutdown. Because you are changing the protocol.

The errors we are talking about: network sudden breakage when the server is terminated (either graceful via close() on the server side, or not if it was a real network problem); and request timeouts. After your patch/design you will also have shutdown timeout. So this means +1 possible error source at least.

Now about the frequency of the errors. Lets face it, we work with Tarantool, so often (I don't know how often though, just hear about crashes a lot) an instance is terminated not quite gracefully (crash, OOM, panic). But even if we consider both graceful and non-graceful termination, it happens extremely rare. Once a day? Once a week? Once a month, year? What number of network errors your graceful shutdown is going to cover then? I mean a percentage, with examples maybe.

Is it worth complicating the protocol, the client side, and one of the most complicated server subsystems (iproto) just for this?

**Protocol change = connector change**
You are changing the protocol. You make it possible for the server to send a packet on its own, not bound to any request. In order to support that you need to patch all the connectors. Mons said above:

> Remove net.box from consideration. There are dozens of connectors. You can't influence them. Therefore, the solution was described for the scenario without modifying any connector.

Exactly. This just proves the point - you can't patch all the connectors. And I doubt people will do that. Since the graceful shutdown does not solve any issues as I explained above, in the previous section.

Now this issue's complexity grows to a next order - all the connectors become involved in order to make it work. The server alone is not enough.

**The feature is turned off by default**
Since it does not solve any real issue, and is turned off by default, users simply won't know about it. Hence that would make the feature as abandoned as the error marshaling session setting. I am 99% sure that still nobody uses it (shame on me, I didn't investigate that though), because the error objects are encoded perfectly fine as Lua tables, so there is no anyone who would want to change that and break the connectors.

The same here - all works fine without this graceful shutdown thing. Therefore there won't be any users, but the code on the server side will get complicated forever.

**The last part of the connection lifetime is not graceful**

Another part of my rant is that the last step of the graceful shutdown protocol is not "graceful". When all session's requests are finished, you send the last response, close the socket, terminate the process. Look at this step in the issue description:

> watch active requests count. when it comes to 0, close this connection

You can't guarantee the last response or pack of responses delivery after the socket is closed. They can get lost if the network breaks now or the TCP layer simply decides to drop the socket right away, without waiting for confirmations. If it is done in a cloud, the entire machine might be terminated when Tarantool process ends, so the delivery won't happen, like if it was a power-off. Or it can happen because the kernel somewhy decided to free some memory. This would mean you need another round of ping-pong with IPROTO_SHUTDOWN to confirm the responses receipt. Yet another complication.

**Feedback**
I am trying to collect feedback from people who liked the ticket now. If I get any meaningful reasons why it is needed, I will post them here in "real time".

@R-omk
Thanks to one of the most involved users, who provided a first bit of feedback - @R-omk. He says that plenty of graceful shutdowns and timeouts exist in Kubernetes. And it has some uses in Kafka. He also said the ping-pong of the protocol looks strange indeed. And advised to go look at the other graceful shutdown protocols. Maybe they invented something better.

He said an instance might be shutting down even for half an hour sometimes (but I suppose it is rather an exception). Also he said the shutdown has its uses with subscriptions. When an instance terminates, you can gracefully terminate the subscriptions and let the clients re-subscribe in another place.

He also said that having shutdown properly supported locally on the server is important. So as you could finish local work during a given timeout. Although local shutdown triggers are already done AFAIK, and are not a part of this ticket.

I buying the argument about subscriptions. But I would say, that we should better fix `box.session.push()` which is not unusable mostly (#6107). This would solve the subscription cancellation via local shutdown triggers, from which you could just walk the subscriptions and cancel them. And would work not only during shutdown.

**Comment by alyapunov** [comment] 2021-06-29 13:31
> The last part of the connection lifetime is not graceful
> You can't guarantee the last response or pack of responses delivery after the socket is closed.

This part really confuses and even bothers me. Could you please provide any technical specification that confirms that? Or that is your personal assumption of how TCP/IP work?
As I know if you don't play with SO_LINGER the guarantees of send followed by close are quite the same as send without close. I've never met any warnings about send+close safety. Even for virtualization I bet closed sockets must be supported by host.

As for other parts I'll try to be laconic.

Of course we cannot avoid network and user errors. And it's a user responsibility to handle them. But as I see users don't want to meet packet drops due to server shutdown, which is is confirmed by your feedback investigation. And we can fix it.

The proposed (full graceful) scheme of course requires support in connector. But even without change of connectors, we can provide some guarantees. The guarantees below are written with an assumption that send+close is safe.
**Now**: We have network errors + user errors + shutdown errors. Shutdown can lead to response drop for both processed and not processed requests.
**Graceful shutdown without connector support**. We have network errors + user errors + less shutdown errors. Shutdown can lead to response drop for non-processed requests; all processed requests will be answered.
**Graceful shutdown with connector support**. We have network errors + user errors. Shutdown itself can't lead to response drop; all requests will be answered.
So, as you say, "the number of errors is still the same" only if there are no shutdown errors.

I personally still can't make any assumptions about profit of the feature for real users. I usually believe product managers and real users that marks this issue with 'like'. I'm not sure but it seems that Mons still supports the idea.

**Comment by alyapunov** [comment] 2021-06-29 13:46
Our current changes in original proposal:
1. A client instead of replying to IPROTO_SHUTDOWN should just shutdown(SHUT_WR). That's a common behavior.
2. We need to carefully handle shutdown(SHUT_WR) correctly in any time.
3. We don't support session.on_shutdown because box.ctl.on_shutdown can be used for stopping any server side activity.
4. We should make session enumeration and session shutdown in lua in separate issue (if there be a request for it). It's not required for the main goal and sophisticates the solution.

**Comment by Gerold103** [comment] 2021-06-29 16:08
>This part really confuses and even bothers me. Could you please provide any technical specification that confirms that? Or that is your personal assumption of how TCP/IP works?

Well, it is not about TCP/IP, it is about how the kernel handles the closed sockets. Regardless of the protocol. You can try to make a test, if you don't believe me, or google it. There is a post with examples which shows that after `close()`, even if the network is just fine, you can't be sure the data will be delivered. https://blog.netherlabs.nl/articles/2009/01/18/the-ultimate-so_linger-page-or-why-is-my-tcp-not-reliable

I would better count on that anything can happen, than on your happy rainbow scenario when all works fine after `close()`, on top of which you start building a new protocol. It simply won't work in the real world, when the kernel might sometimes give up to deliver the data of a closed socket.

If we stop assuming the socket after `close()` works like nothing happened, the design even after your amendments still does not work for the last pieces of data, And that was important when I talked to people who liked the ticket. Like you said, *"and real users that marks this issue with 'like'"*. The updated design also won't help them even if the network is fine.

> So, as you say, "the number of errors is still the same" only if there are no shutdown errors.

There are. Like I said in my post, shutdown has a timeout. If it ends before the requests are finished, the gracefulness is gone.

> Even for virtualization I bet closed sockets must be supported by host.

*"Is this your personal opinion on how virtualization works?"* :) When the virtual machine is terminated, it is like a power off. There is no anybody to support the delivery, there is no a "host" anymore. Exactly that might happen when, for instance, Tarantool would run in a cloud.

> I personally still can't make any assumptions about profit of the feature for real users

Maybe you should? I see you even just fine discuss it with me now, but you could "redirect" your suspicions to the original design from the beginning, couldn't you? We already passed it with xtm, which in the first version appeared not to be usable in any real world case due to number of crutches you needed on top of it. Maybe something must be changed in the processes? For instance, give more pressure and challenges to the designs of big features. So as to avoid the situation when a 2-month patch must be reworked.

No negativity and nothing personal. I only want to make the feature work instead of lying there not used by anybody due to being broken by design.

**Comment by Gerold103** [comment] 2021-06-29 16:41
A guy in this post managed to implement a graceful connection termination with all data being delivered using `shutdown(RW)`: https://stackoverflow.com/questions/8874021/close-socket-directly-after-send-unsafe. Maybe you could try to use it in the last step of the connection close instead of closing the socket right away. But it is done on the server side, not on the client side like you said in the updated design. Because on the last step it is the server who wants to ensure the delivery, not the client.

**Comment by Gerold103** [comment] 2021-06-29 16:45
`IPROTO_SHUTDOWN` packet wouldn't be needed, if you would return a special error with a documented error code to all the requests arriving after the shutdown has started. Then you need this ping-pong thing only at the last step. To deliver responses to the already running requests. And the last ping-pong can be done without protocol changes, using just `shutdown(RW)` on the server + wait until `recv()` returns 0, also on the server.

**Comment by unera** [comment] 2021-07-27 12:59
Hi, it would be nice if GFS uses one-time subscriptions to send events.

https://github.com/tarantool/tarantool/issues/6257

**Closed** 2022-01-26 07:30 UTC
Labels: feature, iproto, teamC
