### ISSUE TITLE
Add box.txn(fun, ...) function

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1038] opened 2015-09-14 08:40 UTC
I suggest to add box.txn() function:

`status, result1, result2, ... = box.txn(fun, ..)` - execute `fun(...)` in pcall +  transaction and return results. A transaction is automatically committed at the end of execution.  Any exception automatically rollbacks transaction.

**Comment by kostja** [comment] 2015-09-14 10:24
This is a duplicate of an older issue.

**Closed** 2015-09-17 19:00 UTC
Labels: feature
