### ISSUE TITLE
httpc: client silently modifies headers when value is not a "string" or a "number"

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#3679] opened 2018-09-11 14:25 UTC
```
 function start()
    function handler(req)
      print(require('json').encode(req.headers))
      return { status = 200 }
    end
    http = require('http.server')
    server = http.new('localhost', '4444')
    server:route({path = '/'}, handler)
    server:start()
 end

require('fiber').create(start)
httpc = require('http.client').new()

tarantool> httpc:request('GET', 'localhost:4444', nil, {headers = {aaa = true}})
GET /
{"host":"localhost:4444","accept":"*\/*","aaa":"(null)","connection":"close"}

tarantool> httpc:request('GET', 'localhost:4444', nil, {headers = {aaa = {}}})
GET /
{"host":"localhost:4444","accept":"*\/*","aaa":"(null)","connection":"close"}

tarantool> httpc:request('GET', 'localhost:4444', nil, {headers = {aaa = box.NULL}})
GET /
{"host":"localhost:4444","accept":"*\/*","aaa":"(null)","connection":"close"}

tarantool> httpc:request('GET', 'localhost:4444', nil, {headers = {aaa = 10ULL}})
GET /
{"host":"localhost:4444","accept":"*\/*","aaa":"(null)","connection":"close"}
```
But it also allows numbers
```
tarantool> httpc:request('GET', 'localhost:4444', nil, {headers = {aaa = 10}})
GET /
{"host":"localhost:4444","accept":"*\/*","aaa":"10","connection":"close"}
```

**Comment by opomuc** [comment] 2018-09-11 15:33
Discussed with @Totktonada and I propose:

- if header value is a `table`, then check if it has `__tostring` method in its metatable
  - if yes: return `tostring(value)`
  - if no: throw an error
- if header value is neither a `table` nor a `string` then throw an error

**Comment by romanhabibov** [comment] 2018-12-17 15:47
@opomuc, I can't reproduce
`
tarantool> function start()
         >     function handler(req)
         >       print(require('json').encode(req.headers))
         >       return { status = 200 }
         >     end
         >     http = require('http.server')
         >     server = http.new('localhost', '4444')
         >     server:route({path = '/'}, handler)
         >     server:start()
         >  end

tarantool> require('fiber').create(start)
2018-12-17 18:39:56.148 [32042] main/112/lua utils.c:939 E> LuajitError: [string "function start()..."]:2: assign to undeclared variable 'handler'
the fiber is dead
`

**Comment by opomuc** [comment] 2018-12-17 22:45
@romanhabibov I can perfectly run the above code. Are you certain those 2 are the only operations you've done?

**Comment by Totktonada** [comment] 2019-07-22 15:35
It does not work for a table with __tostring field in a metatable.

```sh
$ ./src/tarantool -e "require('http.client').new():get('https://www.google.com', {verbose = true, headers = {foo = 'bar'}}) os.exit()" |& grep foo
foo: bar
$ ./src/tarantool -e "require('http.client').new():get('https://www.google.com', {verbose = true, headers = {foo = setmetatable({}, {__tostring = 'bar'})}}) os.exit()" |& grep foo
foo: (null)
```

We should either remove this ability (I doubt it is really needed) and allow only strings or fix the behaviour.

**Closed** 2019-07-31 10:10 UTC
Labels: bug, httpclient, ready for review, tmp
