### ISSUE TITLE
Joining the cancelled fiber does not return control after execution

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#4525] opened 2019-09-26 13:51 UTC
Tarantool version: Tarantool Enterprise 1.10.3-89-g412e943

OS version: Ubuntu 19.04

Bug description:
Joining the cancelled fiber does not return control after execution, program hangs after return or yield.

Steps to reproduce:
Calling the `lua_reproducer` function from Tarantool:
```
static int fiber_f(va_list args)
{
	struct fiber_cond *cond = va_arg(args, struct fiber_cond *);

	while (!fiber_is_cancelled()) {
		printf("before fiber_cond_wait\n");
		fiber_cond_wait(cond);
		printf("atfer fiber_cond_wait\n");
	}
	printf("fiber_is_cancelled\n");

	return 0;
}

static int lua_reproducer()
{
	struct fiber_attr *attr = fiber_attr_new();
	fiber_attr_setstacksize(attr, 256 * 1024);
	struct fiber *fiber = fiber_new_ex("fiber", attr, fiber_f);
	fiber_attr_delete(attr);

	struct fiber_cond *cond = fiber_cond_new();

	fiber_start(fiber, cond);

	fiber_cancel(fiber);
	printf("fiber_cancel\n");
	fiber_join(fiber);
	printf("return\n");
	return 0;
}
```
results in the following output:
```
tarantool> module.reproduce()
before fiber_cond_wait
fiber_cancel
atfer fiber_cond_wait
fiber_is_cancelled

```
and Tarantool hangs (can be stopped with Ctrl-C). The same effect can be obtained when using the following fiber function:
```
static int fiber_f(va_list args)
{
	struct fiber_cond *cond = va_arg(args, struct fiber_cond *);

	while (!fiber_is_cancelled()) {
		printf("before fiber_cond_wait\n");
		fiber_cond_wait(cond);
		printf("atfer fiber_cond_wait\n");
	}
	printf("fiber_is_cancelled\n");

	printf("before yield\n");
	fiber_yield();
	printf("after yield\n");

	return 0;
}
```
with output
```
tarantool> module.reproduce()        
before fiber_cond_wait
fiber_cancel
atfer fiber_cond_wait
fiber_is_cancelled
before yield

```
and the same hanging effect.

**Comment by eljashm** [comment] 2019-12-19 13:08
According to doc fiber_object:join() method

> works only if the fiber was created with fiber.new() and was made joinable with fiber_object:set_joinable().

Thus, the resulting behavior is not a bug and can be fixed by simply adding 

```fiber_set_joinable(fiber, true);```

before joining the fiber in your lua_reproducer() function.

**Closed by eljashm** 2019-12-19 13:08 UTC
Labels: bug
