### ISSUE TITLE
Incorrect index base for upsert operations

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#2059] opened 2017-02-06 08:36 UTC
Upsert operation applies to next field for usert with index base = 0.
Reproduces with php and python drivers.
[https://github.com/tarantool/tarantool-php/issues/111](url)

**Comment by bigbes** [comment] 2017-02-06 09:16
duplicate of https://github.com/tarantool/tarantool/issues/2055

**Closed** 2017-02-06 10:39 UTC
Labels: bug, customer, regression
