### ISSUE TITLE
crash when invoking _G

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#815] opened 2015-04-24 12:45 UTC
kostja@atlas ~/work/tarantool/src
 % ./tarantool
./tarantool: version 1.6.5-11-g38f08ae
type 'help' for interactive help
tarantool> _G
Segmentation fault
Current time: 1429879497
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x4210a0 in sig_fatal_cb(int)+191
#1  0x7f7a2a84c340 in ?
#2  0x45b70a in lbox_info_vclock(lua_State*)+27
#3  0x45b9b9 in lbox_info_call(lua_State*)+116
#4  0x4f22fa in lj_BC_FUNCC+52
zsh: abort (core dumped)  ./tarantool

**Comment by rtsisyk** [comment] 2015-04-29 12:21
Duplicate of #266.

**Closed by rtsisyk** 2015-04-29 12:21 UTC
Labels: bug, crash

**Comment by kostja** [comment] 2015-04-29 13:13
Yes, but an ugly one :)
