### ISSUE TITLE
Test subsystem prints but ignores crashes

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1269] opened 2016-01-12 15:36 UTC
I've made a test, that definitely leads to tarantool crash; during test run I've seen backtrace by then [pass] and return code of test runner code is 0. It is inconvenient because during pre commit test run I could look at another console and push crashing patch
```
================================================================================
TEST                                            PARAMS		RESULT
---------------------------------------------------------------------------
app/cfg.test.lua                                                [ pass ]
app/cfgup.test.lua                                              [ pass ]
app/clock.test.lua                                              [ pass ]
app/console.test.lua                                            [ pass ]
app/csv.test.lua                                                [ pass ]
app/info.test.lua                                               [ pass ]
app/init_script.test.lua                                        [ pass ]
app/inspector.test.lua                                          [ pass ]
app/json.test.lua                                               [ pass ]
app/logger.test.lua                                             [ pass ]
app/minimal.test.lua                                            [ pass ]
app/module_api.test.lua                                         [ pass ]
app/msgpack.test.lua                                            [ pass ]
app/msgpackffi.test.lua                                         [ pass ]
app/pcall.test.lua                                              [ pass ]
app/session.test.lua                                            [ pass ]
app/snapshot.test.lua                                           Segmentation fault
Current time: 1452611141
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x42844a in ?
#1  0x7fb6ed7c0340 in ?
#2  0x481dfb in ?
#3  0x482ad2 in ?
#4  0x48afd2 in ?
#5  0x4893c6 in ?
#6  0x46ceab in ?
#7  0x46c50a in ?
#8  0x44ce80 in ?
#9  0x44e2a2 in ?
#10 0x44e609 in ?
#11 0x4791bf in ?
#12 0x5429bb in ?
[ pass ]
app/tap.test.lua                                                [ pass ]
app/trigger_atexit.test.lua                                     [ pass ]
app/uri.test.lua                                                [ pass ]
app/yaml.test.lua                                               [ pass ]
---------------------------------------------------------------------------
[INFO/MainProcess] process shutting down
user@comp:~/Work/tarantool/test$ echo $?
0
```

**Comment by rtsisyk** [comment] 2016-01-13 10:33
Please move this ticket to test-run.

**Comment by rtsisyk** [comment] 2016-04-01 14:54
Duplicate of https://github.com/tarantool/test-run/issues/19

**Closed by rtsisyk** 2016-04-01 14:54 UTC
Labels: test-run.py
