### ISSUE TITLE
crash in http module

### ISSUE THREAD

**Issue by webching** [tarantool/tarantool#4075] opened 2019-03-24 05:26 UTC
Tarantool 1.10.2-189-gcf8df87ea
Target: FreeBSD-amd64-Debug

[code]

#!/usr/bin/env tarantool

local http = require('http.client').new()
local r = http:request('GET', 'http://tarantool.io', nil, {
    verbose = true,
})
print(r.body)

[display]
* Connected to tarantool.io (188.93.56.54) port 443 (#1)
Segmentation fault
  code: SEGV_ACCERR
  addr: 0x80168b510
  context: 0x7fffffffd300
  siginfo: 0x7fffffffd670

and tarantool.core generated.

**Comment by avtikhon** [comment] 2019-03-26 10:49
uname -a
FreeBSD freebsd 12.0-BETA3 FreeBSD 12.0-BETA3 r340039 GENERIC  amd64

tarantool branches checked:
master (2.1.1-434-g506ae5898)  - not reproduced
1.10  - not reproduced

version from the issue checked:
1.10 (1.10.2-189-gcf8df87ea) - not reproduced

**Comment by webching** [comment] 2019-03-26 11:17
in virtualbox, 1GB ram, 
# uname -a
FreeBSD fb 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64



(gdb) core tarantool.core
[New LWP 100066]
Core was generated by `tarantool test_http.lua'.
Program terminated with signal SIGABRT, Aborted.
#0  0x000000080133345a in ?? ()

**Comment by kyukhin** [comment] 2019-05-28 02:44
We still cannot reproduce that.

**Comment by Totktonada** [comment] 2019-05-28 11:20
I suppose it is duplicate of #4179, which was fixed in the following revisions:

* 1.10.3-30-g1a7476e6b (1a7476e6b082b7a53a58045b1acfb59aaee68365)
* 2.1.2-49-gc413011cc (c413011cc2110d844aba197c2f3ae8b7c5efabfc)
* 2.2.0-233-g47bd51b55 (47bd51b55b03a851c1cf4724ffc967d402c822a9)

@webching Can you please verify whether the issue was resolved?

**Comment by webching** [comment] 2019-05-30 03:34
still coredump, but i find that only for https. ok for url with 'http://'.

**Comment by Totktonada** [comment] 2019-05-30 05:51
What is the version of libcurl?

**Comment by webching** [comment] 2019-05-30 08:01
curl-7.65.0_1




------------------ 原始邮件 ------------------
发件人: "Alexander Turenko"<notifications@github.com>; 
发送时间: 2019年5月30日(星期四) 中午1:51
收件人: "tarantool/tarantool"<tarantool@noreply.github.com>; 
抄送: "Ching"<8494002@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tarantool/tarantool] crash in http module (#4075)




What is the version of libcurl?
 
&mdash;

**Comment by webching** [comment] 2019-05-30 08:02
curl-7.65.0_1

**Comment by avtikhon** [comment] 2019-06-03 10:05
Finally found the issue using the VirtualBox image, investigating the issue.

**Comment by avtikhon** [comment] 2019-06-04 11:06
Found that the issue occurs when tarantool linked to 2 different libssl libraries, then you need to rebuild openssl and tarantool after it, like:
```
# openssl if needed
git clone https://github.com/openssl/openssl.git openssl
cd openssl
###
./config
# or setup yourself
./Configure
./Configure debug-test-64-clang
###
make -j
sudo make install
ll /usr/local/lib/libssl*
```
before tarantool rebuild need to reset the default link of the libssl library, like:
```
cd /usr/local/lib/
sudo rm -f /usr/local/lib/libssl.so
sudo ln -s libssl.so.3 /usr/local/lib/libssl.so
```

**Comment by webching** [comment] 2019-06-04 15:02
tested ok now 👍

**Comment by Totktonada** [comment] 2019-06-04 15:51
AFAIK FreeBSD provides tarantool port. Whether it is affected by the problem?

**Comment by webching** [comment] 2019-06-05 04:51
there is a precomiled version of the tarantool port, currently it is: tarantool-1.10.2_3
# pkg info tarantool
Name           : tarantool
Version        : 1.10.2_3
Origin         : databases/tarantool
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : databases
Licenses       : BSD2CLAUSE
Maintainer     : sunpoet@FreeBSD.org

----------
to fix this bug, i think it should be upgraded to 1.10.3,
as i tested it and encoutered this bug for this version(1.10.2_3).

**Comment by Totktonada** [comment] 2019-06-05 09:43
Nope, it seems that there is no difference in finding libssl version to link against between those tarantool versions. Possibly we should choose libssl which is used in libcurl (fix cmake files on our side). Don't sure, need to investigate the issue deeper.

**Comment by Totktonada** [comment] 2019-12-23 09:29
@avtikhon Can you verify the issue after ea5929db4d400f5013a1c521870b9e14a8edcf85, please?

**Comment by avtikhon** [comment] 2021-04-01 05:55
> @avtikhon Can you verify the issue after [ea5929d](https://github.com/tarantool/tarantool/commit/ea5929db4d400f5013a1c521870b9e14a8edcf85), please?

No issue found for now, closing.

**Closed by avtikhon** 2021-04-01 05:55 UTC
Labels: need feedback
