### ISSUE TITLE
The command `os.execute` works inconsistently

### ISSUE THREAD

**Issue by a1div0** [tarantool/tarantool#8627] opened 2023-05-05 04:57 UTC
**Bug description**

* OS: Linux
* OS Version: Ubuntu 22.04.2 LTS
* Architecture: amd64

Place `tarantool --version` output here.
```
Tarantool Enterprise 2.10.4-0-g59fba21ad-r523-nogc64
```

**Steps to reproduce**
``` lua
local result = os.execute('ls')
```

**Actual behavior**
Question 1: what will be in the variable?
Answer 1: zero.
Question 2: Where will the list of files be?
Answer 2: in stdout.

**Expected behavior**
In result contain string with file list.

**Comment by igormunkin** [comment] 2023-05-05 07:14
This is definitely not a bug, just rtfm for [`os.execute`](https://www.lua.org/manual/5.1/manual.html#pdf-os.execute). You're looking for either [`io.popen`](https://www.lua.org/manual/5.1/manual.html#pdf-io.popen) or rather [`popen`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/popen/). Closing.

**Closed by igormunkin** 2023-05-05 07:14 UTC
Labels: bug
