### ISSUE TITLE
A library for function parameter validation

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3053] opened 2018-01-18 11:18 UTC
I often need to check the type of arguments in a function and return a sane error. This is a recurring pattern in most of our libraries.

Cases:
- check that first parameter of object's method is really 'self' and warn the user that they should call the method as obj:method() instead of obj.method()
- check that parameter is a table
- check that parameter is string or nil
- etc...

It would be extremely useful to have argument checking onboard.
Most of the closed-source projects can live with the hand-rolled implementation, but stand-alone modules can't afford to write it from scratch every time.

**Comment by Totktonada** [comment] 2018-01-18 11:26
Related doc re decorators in lua: http://lua-users.org/wiki/LuaTypeChecking

**Comment by alyapunov** [comment] 2018-01-18 13:38
* Konstantin Nazarov <notifications@github.com> [18/01/18 14:20]:
> I often need to check the type of arguments in a function and return a sane error. This is a recurring pattern in most of our libraries.
> 
> Cases:
> - check that first parameter of object's method is really 'self' and warn the user that they should call the method as obj:method() instead of obj.method()
> - check that parameter is a table
> - check that parameter is string or nil
> - etc...
> 
> It would be extremely useful to have argument checking onboard.
> Most of the closed-source projects can live with the hand-rolled implementation, but stand-alone modules can't afford to write it from scratch every time.

We already have this in box.schema, we could generalize it into a
library.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by alyapunov** [comment] 2018-01-18 13:39
* Konstantin Nazarov <notifications@github.com> [18/01/18 14:20]:
> I often need to check the type of arguments in a function and return a sane error. This is a recurring pattern in most of our libraries.
> 
> Cases:
> - check that first parameter of object's method is really 'self' and warn the user that they should call the method as obj:method() instead of obj.method()
> - check that parameter is a table
> - check that parameter is string or nil
> - etc...
> 
> It would be extremely useful to have argument checking onboard.
> Most of the closed-source projects can live with the hand-rolled implementation, but stand-alone modules can't afford to write it from scratch every time.
> 

Ultimately, you should use avro-schema. 

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by racktear** [comment] 2018-01-18 14:57
@alyapunov are you serious?

**Comment by Totktonada** [comment] 2018-08-03 23:01
Now we have https://github.com/tarantool/checks


@kyukhin Is this issue can be closed?

**Comment by racktear** [comment] 2018-08-04 12:33
We do have `checks`, but I believe something like `checks` should be onboard. Checking public module contract is just a nice coding style, and is done all over the internal tarantool's Lua code. If we do it ourselves, then it should be a no-brainer to standardize and document the API, so there is only one recommended way to do it.

**Comment by DifferentialOrange** [comment] 2023-02-07 12:02
Duplicate of #7726

**Closed by DifferentialOrange** 2023-02-07 12:02 UTC
Labels: feature, good first issue
