### ISSUE TITLE
Failed to write to disk

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#3100] opened 2018-01-30 11:03 UTC
tarantool: version: 1.7.6-15-g033160e
linux ubuntu 16.04

```
2018-01-30 14:00:07.707 [1101] main/145/main txn.c:261 E> ER_WAL_IO: Failed to write to disk
2018-01-30 14:00:11.662 [1101] wal/101/main xlog.c:703 !> SystemError file '/var/lib/tarantool/test/00000000000000000114.xlog' already exists: File exists
2018-01-30 14:00:11.663 [1101] main/146/main txn.c:261 E> ER_WAL_IO: Failed to write to disk
```

After reboot  I see that is issue

**Comment by kostja** [comment] 2018-02-07 10:46
This is a duplicate of https://github.com/tarantool/tarantool/issues/3076

**Closed by kostja** 2018-02-07 10:46 UTC
