### ISSUE TITLE
sql: remove sqlite authorization code

### ISSUE THREAD

**Issue by TheAviat0r** [tarantool/tarantool#2868] opened 2017-10-26 19:36 UTC
All authorization issues should be solved by Tarantool user grants, so all kind of code like
`sqlite3AuthCheck(db, ...)` is unnecessary now. Moreover, it's already disabled by SQLITE_OMIT_AUTHORIZATION define.

That code is unnecessary, so it should be removed.

**Comment by Korablev77** [comment] 2018-02-27 20:06
I guess, this ticket is related to #3119: "Remove code under OMIT_AUTHORIZED ifndef"

@kyukhin should we close this as a duplicate?

**Comment by kyukhin** [comment] 2018-05-18 15:21
Duplicate of #3119

**Closed by kyukhin** 2018-05-18 15:21 UTC
Labels: good first issue, need feedback, refactoring, sql
