### ISSUE TITLE
VERBOSE - a new log level between INFO and DEBUG

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1055] opened 2015-09-22 10:00 UTC
Add a new log level between `LOG_INFO` and `LOG_DEBUG` - `LOG_VERBOSE`.
Try to don't break compatibility in box.cfg { log_level= xx }.

Depends on #1054.

**Comment by kostja** [comment] 2017-05-30 16:47
Duplicate of gh-2467

**Closed by kostja** 2017-05-30 16:47 UTC
Labels: feature
