### ISSUE TITLE
sql: sqlite still uses it's btree to store epemeral and autoindex tables

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2721] opened 2017-08-30 08:57 UTC
We should replace it with temporary memtix spaces, because it is the last thing preventing us from deleting sqlite's btrees and reformatting index and table structures.

It leads to store temp tables in memory and increases its consumption.

**Comment by kyukhin** [comment] 2017-11-09 13:44
This is duplicate of #2680

**Closed by kyukhin** 2017-11-09 13:44 UTC
