### ISSUE TITLE
Deadlock bootstrapping m-m replication

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4097] opened 2019-04-03 12:06 UTC
Tarantool version: 1.10.3-1-gfc6d6a338

OS version: Ubuntu 18.04

Bug description:

I'm not sure it's a bug, but @GeorgyKirichenko told me to open an issue.

Essentially, two tarantool instances can't be started simultaneously with replication enabled: they deadlock

Steps to reproduce:

Start two instances from scratch:

1. `tarantool -e "box.cfg({listen=4401, work_dir='1', replication= {4402}})"`
2. `tarantool -e "box.cfg({listen=4402, work_dir='2', replication= {4401}})"`

Both of them say

```
2019-04-03 15:04:06.279 [1653] main/105/applier/ I> can't join/subscribe
2019-04-03 15:04:06.279 [1653] main/105/applier/ xrow.c:907 E> ER_LOADING: Instance bootstrap hasn't finished yet
```

And hang forever

**Comment by sharonovd** [comment] 2019-04-03 15:33
Basically, this is the example from our documentation.

**Comment by locker** [comment] 2019-04-08 09:38
Duplicate of #965.

**Closed by locker** 2019-04-08 09:38 UTC
