### ISSUE TITLE
Implement join of replica w/o sophia's snapshot

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1134] opened 2015-11-06 13:48 UTC
Fork from branch 1.6
1st step:
Dima S.: Change SophiaEngine::join behaviour: instead of sending existing snapshot make a new snapshot, iterate data from sophia engine and delete snapshot.
2nd step:
Me: provide appropriate transmitting of LSN and send needed WAL records.
Dima S.: Change SophiaEngine::join behaviour: instead of making a snapshot make a checkpoint and dirty iterate data from sophia engine

The primary goal is to fix replication, but I believe we can simplify recovery as well.

**Comment by rtsisyk** [comment] 2015-12-30 13:13
=> Split #999 feature from this patch and push to 1.7.

**Comment by kostja** [comment] 2016-01-07 11:38
Closing this as a duplicate of gh-1114, which is an earlier report of the same issue.

**Closed by kostja** 2016-01-07 11:38 UTC
Labels: customer, sophia
