### ISSUE TITLE
Tarantool 1.10.11 failed to load modules if /tmp is mounted with noexec flag

### ISSUE THREAD

**Issue by dmitry-j-mikhin** [tarantool/tarantool#6412] opened 2021-09-02 13:37 UTC
**Bug description**

/tmp is mounted with noexec flag. Module failed to load with error at tarantool startup:
```
Failed to dynamically load module 'wallarm': /tmp/tntL2bJHS/wallarm.so: failed to map segment from shared object: Operation not permitted
```

* OS: Linux
* OS Version: Debian 9
* Architecture: amd64

```
$ tarantool --version
Tarantool 1.10.11-0-gf0b0e7ecf
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-1.10.11.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-1.10.11.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**More Info**
This error was triggered by https://github.com/tarantool/tarantool/commit/8a2f8179c44a909c94b3fddb4cdbe34ea2c9f162, before this commit module loading works OK even when /tmp was mounted with noexec flag.
In https://github.com/tarantool/tarantool/commit/366b2de7cb244fcafeb6d3bc57ed444169b2c433#diff-77697aecedb5c6c83e18114e85a296f83fc4664f13033c2dcddf61fa17977cb9R267 was added functionality to set directory where temporary copies of modules to be loaded will be created using $(TMPDIR) environment variable. Unfortunately this functionality wasn't  backported to 1.10.x branch. This could help us to resolve this error by specifying other directory outside mountpoint with noexec flag.

**Comment by kyukhin** [comment] 2021-09-03 07:39
The issue is that Tarantool always copies DSO of a module to load into `/tmp` in order to allow hot-reload.
That's why the directory should be marked as executable.

There's a workaround though: you can set `TMPDIR` env var to point to any directory with exec rights and
modules will be copied there instead of `/tmp` before the actual load.

**Comment by dmitry-j-mikhin** [comment] 2021-09-03 07:52
> There's a workaround though: you can set TMPDIR env var to point to any directory with exec rights and
modules will be copied there instead of /tmp before the actual load.

This workaround can be applied only for Tarantool >= 2.5.1. In 1.10.x branch /tmp folder is hard-coded - https://github.com/tarantool/tarantool/blob/f0b0e7ecfa46e747fbb15498ac18655ee193bdb1/src/box/func.c#L244

**Comment by dmitry-j-mikhin** [comment] 2021-09-03 08:53
Could you backport https://github.com/tarantool/tarantool/commit/366b2de7cb244fcafeb6d3bc57ed444169b2c433 to 1.10 branch? Because now we are tied to a 1.10.x LTS versions of Tarantool.

**Comment by kyukhin** [comment] 2021-09-09 07:48
Done by https://github.com/tarantool/tarantool/pull/6419

**Closed by kyukhin** 2021-09-09 07:48 UTC
Labels: bug, teamC
