### ISSUE TITLE
`tarantoolctl start` does not work for scripts with delayed box.cfg call

### ISSUE THREAD

**Issue by printercu** [tarantool/tarantool#4411] opened 2019-08-07 10:07 UTC
Tarantool version: 1.10, 2.2

`tarantoolctl start` fails when main instance script does not call `box.cfg` before script is finished: https://github.com/tarantool/tarantool/blob/302bb32418924dd9ddf02f7db951443735f3bed8/extra/dist/tarantoolctl.in#L551-L554

This prevents using this tool to manage apps made with `cluster` rock and other apps which has delayed `box.cfg` call. This apps can be managed instances which receive replication configuration over network (ui or api). As of replication config can not be changed after initial `box.cfg` call, it's not possible to use "dummy" setup on startup and apply actual configuration later.

In current implementation `box.cfg` is required to be called because it's used to daemonize running tarantool instance enforcing `backgground = true` option.

Executing `fork` inside `tarantoolctl` itself instead of relying on `box.cfg` will solve the issue. Fork can be done before or after main script. However 2nd option brings limitations or may be completely broken because multiple threads could be created in main script and only main thread is about to be forked. So fork must be called before executing main script.

There are some additional requirements for fork process:
- it should not exit main process immediately to make it keep focus until forked instance  successfully starts,
- it should not close FDs in a child until main script finishes. This is required to show errors during startup to keep backward compatibility.

Fork can be done via ffi or via exported C function. There is already `daemonize` in `main.cc`, however it should be modified not to quit parent and not to close FDs to match requirements. Hijacking FDs to `/dev/null` is not possible to do with lua code and also requires `ffi.C.dup2` call. So it looks more reasonable to use ffi approach now. Later `popen` may be used to remove ffi code.

One more thing to decide is how to find out the moment when child process finishes main script and let the parent exit. There is already support for `NOTIFY_SOCKET` feature in tarantool: when this envar is present, tarantool sends `READY=1` into corresponding once entering event-loop. `tarantoolctl` can create socket, pass it to forked instance, and then wait for `READY=1` signal.

Related PRs:
- #4380 Enable support for NOTIFY_SOCKET on macOS
- #4381 Implementation of described approach

**Comment by olegrok** [comment] 2019-08-07 19:33
#3953 Also related

**Comment by kyukhin** [comment] 2019-08-23 13:37
Duplicate of #4435

**Closed by kyukhin** 2019-08-23 13:37 UTC
