### ISSUE TITLE
Add an ability to run sql script files

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#4017] opened 2019-02-25 16:37 UTC
```
cat schema.sql

CREATE TABLE title (
    id integer NOT NULL PRIMARY KEY,
    title text NOT NULL,
    imdb_index character varying(12),
    kind_id integer NOT NULL,
    production_year integer,
    imdb_id integer,
    phonetic_code character varying(5),
    episode_of_id integer,
    season_nr integer,
    episode_nr integer,
    series_years character varying(49),
    md5sum character varying(32)
);
```
It would be nice to run simple SQL scripts as is. Proposed format:
```
Tarantool 2.1.1-202-g1bc1fcdad
type 'help' for interactive help
tarantool> \set language sql
---
- true
...
tarantool> @schema.sql
---
- executing: CREATE TABLE title (...);
...
```

**Comment by Korablev77** [comment] 2019-02-25 16:51
Duplicate of #3917

**Closed** 2019-02-25 16:53 UTC
Labels: feature, sql
