### ISSUE TITLE
tarantool/websocket module doesn't start

### ISSUE THREAD

**Issue by Salt111** [tarantool/tarantool#4465] opened 2019-08-29 11:17 UTC
Tarantool version: **1.10.3-71-gbeb4c0ce6**
OS version: **Ubuntu 18.04**
Bug description:    **tarantool/websocket module and the examples fail**
Steps to reproduce:

**vv@ubuntu16:~/Documents/wbs$ tarantoolctl rocks list**
```
Installed rocks:
----------------

websocket
   0.0.2-1 (installed) - /home/vv/Documents/wbs/.rocks/share/tarantool/rocks

```
**vv@ubuntu16:~/Documents/wbs$ tarantool**
```
Tarantool 1.10.3-71-gbeb4c0ce6
type 'help' for interactive help
tarantool> 
---
...

```
**tarantool> do
         >     frame = require'websocket.frame'          -- ok
         >     handshake = require'websocket.handshake'  -- ok
         >     ssl = require'websocket.ssl'              -- error
         > end**
```
---
- error: '...v/Documents/wbs/.rocks/share/tarantool/websocket/ssl.lua:96: tarantool:
    undefined symbol: SSL_library_init'
...

```

**Comment by Totktonada** [comment] 2019-09-26 08:48
Duplicate of https://github.com/tarantool/websocket/issues/5

**Closed by Totktonada** 2019-09-26 08:48 UTC
