### ISSUE TITLE
HMAC support

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#1903] opened 2016-11-09 14:03 UTC
Support HMAC in tarantool like [resty-hmac](https://github.com/neomantra/lua-resty-hmac/blob/master/lib/resty/hmac.lua).

**Comment by bigbes** [comment] 2016-11-09 15:24
Closing as duplicate of https://github.com/tarantool/tarantool/issues/725 .

**Closed by bigbes** 2016-11-09 15:24 UTC
