### ISSUE TITLE
Interactive transactions over network connections

### ISSUE THREAD

**Issue by zilveer** [tarantool/tarantool#4386] opened 2019-07-27 01:04 UTC
Hi,
I would like have the ability to run interactive transactions over network with Tarantool.

For example:
Try {
START TRANSACTION
make a bunch of queries 
COMMIT
} Catch(){
ROLLBACK
}

And this without writing stored procedures or running the code itself in the Tarantool server. 

Thanks for your hard work !

Regards

**Comment by Gerold103** [comment] 2019-07-27 18:55
Perhaps linked with https://github.com/tarantool/tarantool/issues/2016.

**Comment by kyukhin** [comment] 2019-07-31 10:50
I bet this is a duplicate of #2016

**Comment by zilveer** [comment] 2019-07-31 12:34
@Gerold103 and @kyukhin so is interactive transactions possible currently?

**Comment by alyapunov** [comment] 2020-12-03 10:14
> 
> 
> @Gerold103 and @kyukhin so is interactive transactions possible currently?

Not yet. See #2016.

**Closed** 2021-07-13 10:32 UTC
Labels: cluster_api, duplicate, need feedback
