### ISSUE TITLE
Enable parallel test-run for whole test suites

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3232] opened 2018-03-13 07:15 UTC
test-run now works in parallel in most test suites, but not for all.

Need to enable it everywhere or carefully explain why it is not possible
in each case.

**Comment by Totktonada** [comment] 2018-09-28 11:16
Dupe of #2436, but the description here is more clear.

**Comment by Totktonada** [comment] 2019-03-13 17:40
Only vinyl have `is_parallel = False` now.

**Comment by ligurio** [comment] 2020-03-23 14:18
There were many commits regarding parallel test runs. Can we consider task as done? // CC: @avtikhon, @Totktonada

**Comment by Totktonada** [comment] 2020-03-23 14:36
Yep. Thanks for catching it.

**Closed by Totktonada** 2020-03-23 14:36 UTC
Labels: qa, test-run.py
