### ISSUE TITLE
Tarantool  on FreeBSD don't find iconv and don't link with that library. Was #3073

### ISSUE THREAD

**Issue by stofel** [tarantool/tarantool#3441] opened 2018-06-03 11:28 UTC
In fresh freebsd ports

]>tarantool -v
Tarantool 1.9.1-0

Target: FreeBSD-amd64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=false
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS:-O2 -pipe -fstack-protector -fno-strict-aliasing -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts
CXX_FLAGS:-O2 -pipe -fstack-protector -fno-strict-aliasing -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts

~]>tarantool
PANIC: unprotected error in call to Lua API (builtin/iconv.lua:33: Undefined symbol "libiconv_open")

**Comment by Totktonada** [comment] 2018-07-04 08:50
Dupe of #3046?

**Comment by stofel** [comment] 2018-07-04 11:06
Думаю они связаны как то, но не дубль

**Comment by Totktonada** [comment] 2018-07-18 15:29
@kbelyavs aggreed to take this task.

**Comment by locker** [comment] 2018-08-21 14:56
Fixed by dcac64afd2b71ff720153e141283f2ceffcff546

**Closed by locker** 2018-08-21 14:56 UTC
Labels: build, ready for review
