### ISSUE TITLE
vinyl: assert in vy_cache_on_write

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5053] opened 2020-06-05 12:45 UTC
Tarantool version: 1.10.6.15

<details>
<summary>backtrace</summary>

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `tarantool tagger_018_03.lua <running> '.
Program terminated with signal 6, Aborted.
#0 0x00007f261b3a0387 in raise () from /lib64/libc.so.6
#0 0x00007f261b3a0387 in raise () from /lib64/libc.so.6
#1 0x00007f261b3a1a78 in abort () from /lib64/libc.so.6
#2 0x00007f261b3991a6 in __assert_fail_base () from /lib64/libc.so.6
#3 0x00007f261b399252 in __assert_fail () from /lib64/libc.so.6
#4 0x0000000000488bc8 in vy_cache_on_write (cache=0x7f1feabf16e8, stmt=0x7f22c71ffef0, deleted=0x0) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/vy_cache.c:468
#5 0x0000000000475202 in vy_tx_write (lsm=0x7f1feabf1450, mem=0x7f234fc60650, stmt=0x7f22c71ffef0, region_stmt=0x7f1abe8ff8c8) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/vy_tx.c:526
#6 0x0000000000475b2d in vy_tx_prepare (tx=0x7f2610d89990) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/vy_tx.c:777
#7 0x0000000000446fc1 in vinyl_engine_prepare (engine=0x1f06cf0, txn=0x7f1b07810038) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/vinyl.c:2374
#8 0x00000000004bd8f6 in engine_prepare (engine=0x1f06cf0, txn=0x7f1b07810038) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/engine.h:267
#9 0x00000000004bec4c in txn_commit (txn=0x7f1b07810038) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/txn.c:339
#10 0x00000000004bf25c in box_txn_commit () at /build/usr/src/debug/tarantool-1.10.6.15/src/box/txn.c:480
#11 0x00000000004e4f03 in lbox_commit (L=0x41a54860) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/lua/init.c:92
#12 0x00000000005411ab in lj_BC_FUNCC () at buildvm_x86.dasc:809
#13 0x00000000004e6c31 in execute_lua_call (L=0x41a54860) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/lua/call.c:302
#14 0x00000000005411ab in lj_BC_FUNCC () at buildvm_x86.dasc:809
#15 0x00000000005562ca in lua_pcall (L=0x41a54860, nargs=<optimized out>, nresults=<optimized out>, errfunc=<optimized out>) at lj_api.c:1158
#16 0x0000000000505444 in luaT_call (L=0x41a54860, nargs=1, nreturns=-1) at /build/usr/src/debug/tarantool-1.10.6.15/src/lua/utils.c:979
#17 0x00000000004e717e in box_process_lua (request=0x7f2612013d60, base=0x7f1abe8ffe30, handler=0x4e6b03 <execute_lua_call>) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/lua/call.c:442
#18 0x00000000004e71c4 in box_lua_call (request=0x7f2612013d60, port=0x7f1abe8ffe30) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/lua/call.c:452
#19 0x00000000004e4ac4 in box_process_call (request=0x7f2612013d60, port=0x7f1abe8ffe30) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/call.c:199
#20 0x0000000000416dcc in tx_process_call (m=0x7f2612013cf0) at /build/usr/src/debug/tarantool-1.10.6.15/src/box/iproto.cc:1595
#21 0x00000000005208de in cmsg_deliver (msg=0x7f2612013cf0) at /build/usr/src/debug/tarantool-1.10.6.15/src/cbus.c:375
#22 0x00000000005218b8 in fiber_pool_f (ap=0x7f261300a398) at /build/usr/src/debug/tarantool-1.10.6.15/src/fiber_pool.c:64
#23 0x0000000000410aca in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x521725 <fiber_pool_f>, ap=0x7f261300a398) at /build/usr/src/debug/tarantool-1.10.6.15/src/fiber.h:678
#24 0x000000000051a9d2 in fiber_loop (data=0x0) at /build/usr/src/debug/tarantool-1.10.6.15/src/fiber.c:713
#25 0x00000000006ab563 in coro_init () at /build/usr/src/debug/tarantool-1.10.6.15/third_party/coro/coro.c:110 
```
</details>

**Comment by alyapunov** [comment] 2020-07-21 11:46
Not reproducible.

**Comment by alyapunov** [comment] 2020-07-21 11:46
https://jira.mail.ru/browse/TNT-17

**Comment by locker** [comment] 2022-06-16 10:00
Looks like this crash and #5054 were caused by the same bug. Closing it for the same reason, see https://github.com/tarantool/tarantool/issues/5054#issuecomment-1157471141.

**Closed by locker** 2022-06-16 10:00 UTC
Labels: crash, bug, vinyl
