### ISSUE TITLE
msgpack: error_unpack: Assertion `*data == end' on decoding incorrect value

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5200] opened 2020-07-23 14:37 UTC
### Tarantool version:

2.6.0-12-gbc58c0679

### Steps to reproduce:

```
sergeyb@pony:~/sources/MRG/tarantool$ ./build/src/tarantool 
Tarantool 2.6.0-12-gbc58c0679
type 'help' for interactive help
tarantool> msgpack = require('msgpack')
---
...

tarantool> msgpack.decode('\xd4\x03\x02')
tarantool: /home/sergeyb/sources/MRG/tarantool/src/box/mp_error.h:70: error_unpack: Assertion `*data == end' failed.
Aborted (core dumped)
```

**Comment by Totktonada** [comment] 2020-07-23 15:04
Duplicate of #5014.

**Closed** 2020-07-23 15:13 UTC
Labels: bug, crash, duplicate, lua
