### ISSUE TITLE
Duplicate key exists in unique index 'primary' in space '_index'

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#1760] opened 2016-09-10 08:42 UTC
Running [tube:truncate()](https://github.com/tarantool/queue#driver-api) not always, but often results in a `Duplicate key exists in unique index 'primary' in space '_index'` error.

Tarantool & queue are installed with `docker build -t tarantool/tarantool github.com/tarantool/tarantool-docker#:1.7`.

**Comment by bigbes** [comment] 2016-09-12 05:22
duplicate of https://github.com/tarantool/tarantool/issues/618

**Closed by bigbes** 2016-09-12 05:22 UTC
Labels: duplicate
