### ISSUE TITLE
Continuous backporting of new commits from Luajit - set up procedure

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#5534] opened 2020-11-19 08:57 UTC
Document describing the procedure: how often, testing procedure, exceptions (crit bugs).

**Comment by Totktonada** [comment] 2020-12-19 23:01
I have some thoughts how we can start with tracking of the backporting status.

1. Enable issues in https://github.com/tarantool/luajit/
2. Collect all commits since the common base and file an issue for each (159 commits excluding merges ATM if I'm doing it right).
3. Setup automation that will open an issue per upstream commit.

After this we can start to eat the pie piece by piece:

1. Start to set appropriate labels (architecture, component, complexity, bug/feature, priority, time estimation).
2. Start to investigate and add results to the issues.
3. Track those activity on a planning board (using GitHub projects).

This way, I hope, we will have a rough roadmap soon.

**Comment by igormunkin** [comment] 2021-02-05 16:40
@Totktonada, thanks for your inputs! I am both for and against enabling issues in our LuaJIT repo:
* Your proposal for tracking new patches is neat (except the fact I have no idea how to implement it technically)
* One can start using this queue for other tickets and there will be a mess between Tarantool queue and this one

The latter bothers me more for now, but we can discuss it, so I can change my mind as a result.

Anyway, in scope of this issue I would like to write the procedure for backporting Here is my plan below. It's not a formal document but rather a guide to check one is doing everything right. Feel free to share your ideas regarding it.

---

# Backporting plan

This doc should guide developer through the procedure of backporting the patches from the LuaJIT upstream. All patches not presented in our fork are classified into two queues: primary and backlog. In the future the postponed changes originally placed to backlog can be re-prioritized and scheduled to be applied to the trunk.

## Backporting the patch

Every bullet of this list is obligatory, but the order is not strict. If one is missing, please consult the maintainer.
* You have a **patch**. Otherwise there is nothing to backport.
* You have a **problem** ([GitHub issue or pull request](https://github.com/LuaJIT/LuaJIT/issues?q=) or [thread in LuaJIT mailing list](https://www.freelists.org/archive/luajit/)). Otherwise this is unlikely a patch, but rather enhancement or refactoring that are .
* You have a **test** (i.e. reproducer for the problem). Otherwise the backported changes are likely to be broken later. Again.
* You have a **rationale** for backporting. Otherwise drop this and do something more vital today.

If everything is done, you can send a series to our [mailing list](https://lists.tarantool.org/), so the maintainer apply it to the trunk.

Please, leave the commit subject unchanged, do not drop the original commit message and mention the changes you've done (see the examples [here](https://github.com/tarantool/luajit/commit/1672bdc0ffbee9f32fadb6943909d6af7eb9a7b1) and [here](https://github.com/tarantool/luajit/commit/1672bdc0ffbee9f32fadb6943909d6af7eb9a7b1)). If you can make the commit message more verbose, feel free to do it.

## Bugs backporting priority

This section describes the procedure to fill the primary queue with the patches having a quite high relevance for backporting. Here are the approximate priorities:
* The most important patches are those related to VM and runtime. As for JIT it can be disabled, which can't be done for other platform components.
* Talking about host architectures, the priority list is the following:
  + `x86_64` w/o `LJ_GC64`  -- this is the most popular choice for the Tarantool installations today
  + `x86_64` w/ `LJ_GC64` -- this is used only on OSX on developers laptops (at least I have seen no production on it)
  + `aarch64` -- this platform to be fully supported in the nearest future
  + Other host architectures
* Talking about OS, the priority list is the following:
  + `GNU/Linux` -- this is the most popular choice for the Tarantool installations today
  + `OSX` and `*BSD` -- these are also used, but not such widely as Linux
  + Other marginal operating systems
  
## Backlog queue

This is a secondary queue that contains the changes lacking one of the bullets from the checklist above: [fixes with no tests](https://github.com/LuaJIT/LuaJIT/issues/624), [enhancements](https://github.com/LuaJIT/LuaJIT/commit/ff34b48ddd6f2b3bdd26d6088662a214ba6b0288) and [refactoring](https://github.com/LuaJIT/LuaJIT/commit/8ae5170cdc9c307bd81019b3e014391c9fd00581). They can be moved to the primary one when all four bullets are checked, so there should be a regular activity for this.

## FAQ

This section will grow when we start the backporting process for the existing patches. I have no questions for now.

**Comment by Totktonada** [comment] 2021-02-06 16:43
I don't insist on tracking in GitHub issues, but I would like to know where I can look results of upstream patches review and the overall status of backporting (how long non-analyzed queue is, how many patches that looks desired, but have no tests yet, and so on). Say, if you considered a patch as unrelevant to our current goals, I want to know a reason. At least I don't want to be in the situation, when I need to ask the team each time I wonder about a particular patch — whether someone analyzed it? or it was missed unintentionally? or it is in the queue to analyze?.

I have another example of status tracking: we did track the [remaining tasks](https://github.com/tarantool/tarantool-java/wiki/JDBC-status) and [overall status](https://github.com/tarantool/tarantool-java/wiki/JDBC-API) using GitHub wiki. The situation is quite similar: the predefined large scope of work and wish to understand where we're on the way.

**Comment by kyukhin** [comment] 2021-02-11 14:21
LGTM, but add triggering event.

**Comment by igormunkin** [comment] 2021-02-11 17:19
@kyukhin, thanks!

> LGTM, but add triggering event.

Updated the FAQ.

**Comment by igormunkin** [comment] 2021-02-11 17:44
@Totktonada,

> I don't insist on tracking in GitHub issues, but I would like to know where I can look results of upstream patches review and the overall status of backporting (how long non-analyzed queue is, how many patches that looks desired, but have no tests yet, and so on). Say, if you considered a patch as unrelevant to our current goals, I want to know a reason. At least I don't want to be in the situation, when I need to ask the team each time I wonder about a particular patch — whether someone analyzed it? or it was missed unintentionally? or it is in the queue to analyze?

I've thought a bit about your proposal for a Wiki page with all the info you mentioned above and honestly, I like it: the append only page with a strict format, versioned with Git -- the one thing we lack for now is the machinery to track new patches in upstream and append them to the doc. These automatics will be implemented in scope of the third bullet in #5483.

Did I miss something vital from your comment to be included to the guide above? If nothing's lost, I'll ask @sergos to take a look on it and then I'll move it to our GitHub Wiki repo.

**Comment by sergos** [comment] 2021-02-14 22:00
I will just rename "Bugs backporting" into something more profitable to backport.

Otherwise looks good.

**Comment by Totktonada** [comment] 2021-02-15 06:20
> Did I miss something vital from your comment to be included to the guide above? If nothing's lost, I'll ask @sergos to take a look on it and then I'll move it to our GitHub Wiki repo.

The guide is how to make a decision whether to backport a particular patch. I have no complains regarding current wording. My comments were mostly how to track status of backporting and it is quite orthogonal question.

**Comment by igormunkin** [comment] 2021-02-16 15:04
@Totktonada, 
> My comments were mostly how to track status of backporting and it is quite orthogonal question.

I'll move all your remaining inputs to #5483.

---

I've finally collected everything to the single doc in our [Wiki](https://github.com/tarantool/tarantool/wiki/LuaJIT-backporting-guidelines). Closing the issue.

**Closed by igormunkin** 2021-02-16 15:04 UTC
Labels: 5sp, feature, luajit, prio7, teamL
