### ISSUE TITLE
test: replication join_vclock fails on huge load

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4160] opened 2019-04-15 14:30 UTC
Tarantool version:
All

OS version:
All

Bug description:
[015] replication/join_vclock.test.lua                vinyl           [ fail ]
[015] 
[015] Test failed! Result content mismatch:
[015] --- replication/join_vclock.result	Fri Apr 12 14:49:26 2019
[015] +++ replication/join_vclock.reject	Mon Apr 15 17:10:13 2019
[015] @@ -72,7 +72,7 @@
[015]  ...
[015]  box.space.test.index.primary:max()[1] == cnt - 1
[015]  ---
[015] -- true
[015] +- false
[015]  ...
[015]  test_run:cmd("switch default")
[015]  ---
[015] 
[015] Last 15 lines of Tarantool Log file [Instance "master"][/home/avtikhon/Workspaces/tarantool_empty/test/var/015_replication/master.log]:

Steps to reproduce:
./test-run.py --force -j 50 `for r in {1..50} ; do echo replication/join_vclock.test.lua ; done`

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by avtikhon** [comment] 2019-09-27 08:00
After mentioned at issue #4528 commit the failure became more often.

**Comment by PersDep** [comment] 2019-12-24 18:20
This issue requires slightly different fixes on master and 1.10 with 2.2.
On master the main problem is that since 6332aca655ae7f95d391bdc0109e79915f6e6ad0 (relay: join new replicas off read view) wrong vclock could have been obtained on join under high load, which meant that some tuples could be lost on replica. This problem is fixed with a52f81ffc89e6a518c1d389e30c60c04d2463547 (relay: fix vclock obtainment on join) patch.
The next problem exists both on master and 1.10 with 2.2. It is in the join_vclock test: to provide consistent verification of the fact that changes are being applied on replica in the correct order, max index and index count have to be requested atomically, in single line. It is fixed with 84eb1c53c2878020d88cb0a7f930937fb018b0a9 (test: fix flaky join_vclock test) patch.
However, after these fixes it turned out that there is still at least one more problem both on master and 1.10 with 2.2. Although tuple are not being missed on replica any more, join_vclock test still fails under high load as far as changes on replica are not really being applied in the correct order. This also has to be fixed and awaits for one more patch on master, 1.10 & 2.2.

**Comment by Totktonada** [comment] 2019-12-24 21:25
Thanks, now it is more clear. It seems that we should fix the test problem on master/2.2/1.10 and fix the regression on master, right? The test is named 'join_vclock', so I guess the intention was to verify that no changes are lost rather then order of those changes. So I would make the test immutable for order of changes (let's wait for all changes and then check :max() vs :count()) and file an issue re ordering: it deserves its own test when it will be investigated and fixed. Sounds valid?

Re order of applying changes: is it possible that, say, insert + update will be reordered and so update + insert will be applied on a replica (and the update will fail)?

**Comment by PersDep** [comment] 2019-12-29 21:36
After further investigation it turned out that there is no order problem.

There will be patchset out of 3 patches. First one will be the fix for master, and other 2 will include all needed test updates (join_vclock will be changed so that it will be immutable to order and new replica_apply_order test will be introduced) and so far are intended to be pushed to all branches.

**Closed** 2019-12-31 08:11 UTC
Labels: flaky test, qa, ready for review
