### ISSUE TITLE
Squash assert asserts

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#2144] opened 2017-03-05 20:38 UTC
```
box.cfg{}

space = box.schema.space.create('test', { engine = 'vinyl' })
index = space:create_index('primary')

box.begin()
space:upsert({2, 1, 1}, {{'+', 2, 10}})
space:upsert({2, 1, 1}, {{'-', 3, 20}})
space:upsert({2, 1, 1}, {{'=', 2, 20}})
box.commit()

```
will assert vinyl

**Comment by GeorgyKirichenko** [comment] 2017-03-05 20:42
```
ox.cfg{}

space = box.schema.space.create('test', { engine = 'vinyl' })
index = space:create_index('primary')

space:upsert({2, 1, 1}, {{'+', 2, 10}})
space:upsert({2, 1, 1}, {{'-', 3, 20}})
space:upsert({2, 1, 1}, {{'=', 2, 20}})


box.snapshot()
```

will assert to

**Comment by rtsisyk** [comment] 2017-03-14 05:31
Duplicate of #2104

**Closed by rtsisyk** 2017-03-14 05:31 UTC
Labels: bug, crash, vinyl
