### ISSUE TITLE
box.schema.user.create and box.schema.role.create interfere with each other

### ISSUE THREAD

**Issue by zlobspb** [tarantool/tarantool#867] opened 2015-06-10 10:29 UTC
the doc says that roles are saved in the _user space
but it's still frustrating why are the following call interfere

```lua
box.schema.user.create('testuser', {password = 'testuser'})
---
...
box.schema.role.create('testuser')
---
- error: Role 'testuser' already exists
```

```lua
box.schema.role.create('testuser1')
---
...
box.schema.user.create('testuser1', {password = 'testuser1'})
---
- error: User 'testuser1' already exists
```

**Comment by zlobspb** [comment] 2015-06-10 10:34
one more
```lua
box.schema.role.create('test')
---
...
box.schema.role.info('test')
---
- []
...
box.schema.user.drop('test')
---
...
box.schema.role.info('test')
---
- error: User 'test' is not found
```

**Comment by Sulverus** [comment] 2015-06-10 10:58
Please update tarantool to latest version.

**Comment by zlobspb** [comment] 2015-06-10 11:14
1.6.5-174 helps with 
```lua
box.schema.role.create('test')
box.schema.user.drop('test')

box.schema.user.drop('test')
box.schema.role.create('test')
```

but still
what about box.schema.user.create and box.schema.role.create

and this one:
```lua
box.schema.user.create('test')
box.schema.role.info('test')
---
- - - execute
    - role
    - public
...
```

and here is an error message says "User" instead of "Role"
```lua
box.schema.role.info('foo')
---
- error: User 'foo' is not found
...
```

**Comment by kostja** [comment] 2015-06-10 20:48
This is by design,  users and roles share the namespace

**Comment by zlobspb** [comment] 2015-06-11 11:11
Yes I know that. Check all my examples through carefully please.

**Comment by kostja** [comment] 2015-07-01 14:51
Apparently ppl began to use info() method, let's fix it.

**Comment by kostja** [comment] 2015-09-08 14:37
Ok to push

**Comment by Sulverus** [comment] 2015-09-08 16:21
merged

**Closed by Sulverus** 2015-09-08 16:21 UTC
Labels: bug
