### ISSUE TITLE
Populate index with keydef

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#7356] opened 2022-07-04 16:51 UTC
[PM link](https://www.notion.so/tarantool/Populate-index-with-keydef-0f9ffacefc7144ed8750567935ef18ba)

**The problem**

Currently, extracting key part from a tuple is not so simple.
Also, there is a handy keydef module.

Currently user have to create keydef for the index
```lua
local keydef = require('tuple.keydef')
local ix = box.space[ ... ].index[ ... ]
local kd = pcall(keydef.new, ix.parts)
```
And then use keydef to extract key from tuple
```lua
local key = kd:extract_key( tuple )
```

(And also keydef is not working with rtree)

**The proposition**

I propose to extend index object with it's keydef and then use it like
```
local key = box.space[ ... ].index[ ... ].keydef:extract_key( tuple )
```

**Comment by olegrok** [comment] 2022-07-04 17:21
Duplicate of https://github.com/tarantool/tarantool/issues/4955

**Comment by Totktonada** [comment] 2022-07-22 20:14
There are two primary applications of key_def objects: comparing tuples (usually for ordering) and extracting a key from a tuple (usually for pagination). Different key_def objects are used for those goals if the index is non-unique:

```lua
-- Sort.
--
-- Input: tuples.
local index = box.space.s.index.secondary
local kd = key_def.new(index.parts)
if not index.unique then
    local primary_index = box.space.s.index[0]
    kd = key_def:merge(key_def.new(primary_index.parts))
end
table.sort(tuples, function(a, b)
    return kd:compare(a, b) < 0
end)
-- Output: tuples.
```

```lua
-- Extract a key.
--
-- Input: tuple.
local index = box.space.s.index.secondary
local kd = key_def.new(index.parts)
local key = kd:extract_key(tuple)
-- Output: key.
```

My doubt is that it may be not so obvious that the key_def object provided by a non-unique index will not impose the same ordering as the index itself.

OTOH, it is applicable to the manually constructed `key_def.new(index.parts)` as well. So my doubt is not an objection.

**Comment by Gumix** [comment] 2023-01-23 15:03
> I propose to extend index object with it's keydef and then use it like
> local key = box.space[ ... ].index[ ... ].keydef:extract_key( tuple )

So the index object will contain 2 similar fields:
* `parts` — a table without methods (current implementation);
* `key_def` — the new cdata field, which behaves like the object created by
  ```lua
  require('key_def').new(box.space.T.index.I.parts)
  ```

E.g.:
```lua
tarantool> box.space.T.index.I
---
- parts:
  - type: string
    is_nullable: false
    fieldno: 3
  - type: unsigned
    is_nullable: false
    fieldno: 1
  id: 0
  space_id: 512
  key_def:
  - type: string
    is_nullable: false
    fieldno: 3
  - type: unsigned
    is_nullable: false
    fieldno: 1
  unique: true
  hint: true
  type: TREE
  name: I
...

tarantool> box.space.T.index.I.key_def:extract_key{1, 99.5, 'X', box.NULL, 99.5}
---
- ['X', 1]
...
```

Maybe join them into a single one? How to call it — `parts`/`key_def`/`keydef`? @Mons, @unera

**Comment by Mons** [comment] 2023-01-24 10:03
Let's add behavior of keydef to parts, if it is possible without breaking things

**Comment by unera** [comment] 2023-01-24 10:33
My opinion is we don't need to add index.key_def, we could only add a method: `index:key_by_tuple(tuple)`

But I may not have enough information about user tasks. So, maybe @Mons's opinion is more reasoned. Let's ask him :)

**Comment by Totktonada** [comment] 2023-03-22 14:41
Whether the issue means only box's index object or net.box's index object as well?

**Closed** 2023-04-18 08:42 UTC
Labels: feature, 3.0
