### ISSUE TITLE
libmysqlcient_r

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1447] opened 2016-04-23 14:40 UTC
I have Ubuntu 16.04, which is advertised as
"the first stable distro with MySQL 5.7"
http://mysqlserverteam.com/ubuntu-16-04-first-stable-distro-with-mysql-5-7/
I have done "sudo apt-get libmysqlclient-dev".
This brings in /usr/lib/x86_64-linux-gnu/libmysqlclient.so
but not libmysqlclient_r.
That library "was removed in MySQL 5.5 and replaced with a symlink
to the underlying libmysqlclient library"
http://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-6.html
but in this situation even the symlink is absent.

In FindMySQL.cmake there is a line
    NAMES mysqlclient_r
Therefore
git clone https://github.com/tarantool/mysql.git tarantool-mysql
cd tarantool-mysql && cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo
will fail, saying

CMake Error at cmake/FindMySQL.cmake:22 (message):
  Could not find mysql development files

**Comment by GeorgyKirichenko** [comment] 2016-04-26 20:32
New version of tarantool mysql driver will use only one thread for each connection, so we can safely use libmysqlclient.so instead of thread safe _r version even for early versions of mysql.

**Comment by GeorgyKirichenko** [comment] 2016-04-26 20:33
New mysql driver version pushed, please try it now

**Comment by pgulutzan** [comment] 2016-04-28 16:39
I notice that the file mysql-scm-1.rockspec also contains a reference to mysqlclient_r. Does it matter, and if so, should it be classified as a separate issue?

**Comment by GeorgyKirichenko** [comment] 2016-04-28 16:46
Hi,

I think this should be a same issue. I will check and fix it tomorrow.
Thanks for reporting.

Regards,
Georgy
28 апр. 2016 г. 19:39 пользователь "Peter Gulutzan" <
notifications@github.com> написал:

I notice that the file mysql-scm-1.rockspec also contains a reference to
mysqlclient_r. Does it matter, and if so, should it be classified as a
separate issue?

—
You are receiving this because you were assigned.

Reply to this email directly or view it on GitHub
<https://github.com/tarantool/tarantool/issues/1447#issuecomment-215488774>

**Comment by GeorgyKirichenko** [comment] 2016-04-28 19:37
Thanks for reporting, rockspec was fixed

**Comment by rtsisyk** [comment] 2016-05-31 20:42
The problem is resolved, can I close this ticket?

**Comment by rtsisyk** [comment] 2016-06-08 20:30
Fix in tarantool/mysql

**Closed by rtsisyk** 2016-06-08 20:30 UTC
Labels: bug, in progress
