### ISSUE TITLE
Feature request for a new  collation

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4007] opened 2019-02-15 19:13 UTC
This is a feature request for a new pre-defined collation.

This is proposed because a customer is concerned about a difference
between 'Е' (Russian letter IE not Latin letter E) and 'Ё'
(Russian letter IO not Latin letter E + diaeresis).

Alternative 1: Use the Kyrgyz locale with strength = primary
Kyrgyz collation is the same as Russian collation, except that
Ё comes after Е, according to this CLDR page:
http://unicode.org/repos/cldr/tags/release-27/common/collation/ky.xml
(Belarus collation does this too but it also changes Ў and the customer only asked about Ё.)
Therefore the customized collation looks like this:
box.internal.collation.create('unicode_ky_s1', 'ICU', 'ky_KY', {strength='primary'});

Alternative 2: use the default locale with strength = secondary
In the DUCET 'E' = 'Ё' with primary weight, but 'E' < 'Ё' with secondary weight.
Proposed locale = 'standard' (I have written an email with an objection
about using '' but again I am not insisting, and 'ru_RU' would work too).
Proposed opts = {strength='secondary' (this is done solely so that we
will have a distinction with strength = 2 but not strength = 3).
Of course this also affects many other letters that have an accent
mark, but my assumption is that this customer does not use them.
And the difference between 'И' and 'Й' is primary according to a CLDR page.
Therefore the customized collation looks like this:
box.internal.collation.create('unicode_s2', 'ICU', 'ru_RU', {strength='secondary'});

I have made this test with Tarantool 2.1 pulled from source today ...

box.internal.collation.create('unicode_s2', 'ICU', 'ru_RU', {strength='secondary'});
\set language sql
\set delimiter ;
DROP TABLE t;
CREATE TABLE t (ch CHAR(5) COLLATE "unicode_s2" PRIMARY KEY);
INSERT INTO t VALUES ('Ё');
INSERT INTO t VALUES ('Е');
INSERT INTO t VALUES ('е');

Insertion of 'Е' does not fail (i.e. it is not equal).
The insertion of 'е' fails (i.e. it is equal).
That is what I hoped.

Alternative 3: Change the Tarantool source code

According to ICU documentation "tailoring" can be done.
http://userguide.icu-project.org/collation/customization
describes how to define a collation where only a few rules are changed
from the DUCET.

With customization, one declares that everything is in DUCET order except
this single letter is treated as a separate letter at the primary level.
There's an analogous rule for Spanish which has a single letter between n and o.
So I just looked up the official CLDR customization rule for Spanish, here:
http://unicode.org/repos/cldr/trunk/common/collation/es.xml
It is
&N<ñ<<<Ñ
Therefore the rule for a tailored Russian collation is
&Е < ё <<< Ё

Now, in Tarantool's coll.c file, I look at how collation is initialized.
It calls "ucol_open(def->locale, &status);" which is
not useful because we don't have a locale. We want
a different routine, which we can pass the rules to.
I think it is ucol_openRules(). It is described in this file
http://icu-project.org/apiref/icu4c/ucol_8h.html#aa128ea0ed3869415c1c96a9a2c997c2d
And there is an example for C in this file
http://userguide.icu-project.org/collation/api
in section "Instantiating Collators Using Custom Rules"

So the alternative is: if the value of the locale argument
in box.internal.collation.create() is 'Russian_with_io_after_ie':
Do not use ucol_open
Use ucol_openRules as in the "Using Custom Rules" example
... except that the rules value is "&Е < ё <<< Ё", 12

What about the name?

We want to have a standardized naming convention.
It might contain the prefix "unicode" and it might contain some
indication about the locale and the options, especially strength.
That will have to be the subject of a different discussion, soon.
See dev mailing list topic = List of collations.

**Comment by stanztt** [comment] 2019-02-20 13:55
Could you please clarify what exactly the problem is? Should we treat the letters 'Е' and 'Ё' as equal, or  should not?
E.g. below is an output from Tarantool 1.10.2-146-gf1ff0b507

```
tarantool> s1 = box.schema.space.create('t1')
---
...
tarantool> s1:format({{name='s1', type='string', collation = 'unicode'}})
---
...
tarantool> s1:create_index('pk', {unique = true, type='tree', parts={{'s1', collation = 'unicode'}}})
---
- unique: true
  parts:
  - type: string
    is_nullable: false
    collation: unicode
    fieldno: 1
  id: 0
  space_id: 519
  name: pk
  type: TREE
...
tarantool> s1:insert{'Ё'}
---
- ['Ё']
...
tarantool> s1:insert{'ё'}
---
- ['ё']
...
tarantool> s1:insert{'Е'}
---
- ['Е']
...
tarantool> s1:insert{'е'}
---
- ['е']
...
tarantool> s1:select{}
---
- - ['е']
  - ['Е']
  - ['ё']
  - ['Ё']
...
```

And for case insensitive version:
```
tarantool> s2 = box.schema.space.create('t2')
---
...
tarantool> s2:format({{name='s1', type='string', collation = 'unicode_ci'}})
---
...
tarantool> s2:create_index('pk', {unique = true, type='tree', parts={{'s1', collation = 'unicode_ci'}}})
---
- unique: true
  parts:
  - type: string
    is_nullable: false
    collation: unicode_ci
    fieldno: 1
  id: 0
  space_id: 518
  name: pk
  type: TREE
...
tarantool> s2:insert{'Ё'}
---
- ['Ё']
...
tarantool> s2:insert{'ё'}
---
- error: Duplicate key exists in unique index 'pk' in space 't2'
...
```

Is this behaviour correct or not?

**Comment by pgulutzan** [comment] 2019-02-20 15:41
That is correct behaviour but add one more request to the
example that you call "case_insensitive". That is, execute this:

s2 = box.schema.space.create('t2')
s2:format({{name='s1', type='string', collation = 'unicode_ci'}})
s2:create_index('pk', {unique = true, type='tree', parts={{'s1', collation = 'unicode_ci'}}})
s2:insert{'Ё'}
s2:insert{'ё'}
s2:insert{'Е'}

The attempt to add 'Е' will fail.

**Comment by stanztt** [comment] 2019-02-20 15:56
Got it. 
Thank you, Peter.

**Comment by Totktonada** [comment] 2019-04-03 00:30
Libicu behaviour differs between different versions of the library for some of collations that we had added recently within scope of this issue. It seems that we need to restrict collations to some 'stable' subset.

A brief plan from @kostja (in my interpretation):

* Remove collation definitions that are known to be unstable (in other words, that are provide different sorting order in different libicu versions).
* Add tests for all remaining collations: the test should fails if a sorting order will be changed with a new version of libicu.
* Don't allow to set these collations via `create table <...> collate <...>`.
* What with :create_index() / :alter()?

Sorry, I have no enough context about this issue, so correct me if I interpret some parts of the plan incorrectly.

Don't forget to enable the test back when the issue will be fixed.

BTW, I see that the issue has 1.10.4 milestone, but was not pushed to 1.10. Is it was intentional?

**Comment by kostja** [comment] 2019-04-03 07:50
I did not cherry-pick by mistake. Let's cherry-pick when the solution is stable enough.

**Comment by kostja** [comment] 2019-04-03 07:51
Another reason I did not cherry-pick is that cherry-picking bootstrap.snap is a pain. Let's change the milestone.

**Comment by pgulutzan** [comment] 2019-04-19 23:33
Re "Libicu behaviour differs between different versions of the library" -- yes, we've known that a long time and discussed it in emails (mostly with A. Lyapunov) and see also the comments on Issue#2021. The conclusion then was that we wouldn't worry because English and Russian have been stable for a while.
Re the list: I see that there is no unicode_ru and this is good, I worried that some users would pick it thinking it is somehow better than the default (when actually the only difference is that Cyrillic comes before Latin Greek etc.), and this would cause unnecessary incompatibility. So I hope this is deliberate.

**Closed** 2019-05-09 08:56 UTC
Labels: feature, ready for review
