### ISSUE TITLE
Support JSON in SQL.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2239] opened 2017-03-24 06:07 UTC
Introduce new JSON type.

Not 1.8.0 feature.

> I think that MySQL and PostgreSQL didn't do JSON quite right
http://ocelot.ca/blog/blog/2015/11/26/standard-sqljson-and-mysql-5-7-json/
and I think that doing it right would require some discussion.
In the meantime I believe JSON data should not be in a new
JSON data type, it should just be in a VARCHAR.

**Comment by kyukhin** [comment] 2017-11-10 11:24
There's also set for working with JSON documents in SQL 2016

**Comment by Gerold103** [comment] 2018-04-17 20:06
Duplicate of #2369

**Closed** 2018-04-17 20:07 UTC
Labels: duplicate, feature, sql
