### ISSUE TITLE
sql: transactions are broken in console

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3374] opened 2018-04-24 20:36 UTC
```
box.cfg{}
\set language sql
CREATE TABLE t1(id PRIMARY KEY);
BEGIN;
INSERT INTO t1 VALUES(1);
SELECT * FROM t1;
---
- []
...
COMMIT;
---
- error: cannot commit - no transaction is active
...
SELECT * FROM t1;
---
- []
...
```

As one can see, tuple disappears for no reason. It is clear, that the reason of such behaviour is the fact that console causes yield, but at least some error message should be raised.

**Comment by kyukhin** [comment] 2018-06-20 10:52
Looks like this is not a bug. This is just current behaviour.
Every type <return> was hit current transaction is rolled back.
But this occurs when actual update occured.

For memtx such trigger set here:
```
memtx_engine_begin(struct engine *engine, struct txn *txn)
{
        (void)engine;
        /*
         * Register a trigger to rollback transaction on yield.
         * This must be done in begin(), since it's
         * the first thing txn invokes after txn->n_stmts++,
         * to match with trigger_clear() in rollbackStatement().
         */
        if (txn->is_autocommit == false) {

                trigger_create(&txn->fiber_on_yield, txn_on_yield_or_stop,
                                NULL, NULL);
                trigger_create(&txn->fiber_on_stop, txn_on_yield_or_stop,
                                NULL, NULL);
```
So, if no insertions were performed, no rollback will be fired on console's
fiber yield.

E.g.:
```
tarantool> commit;
---
...

tarantool> begin;
---
...

tarantool> select 1;
---
- - [1]
...

tarantool> commit
---
...
```
However:
```
tarantool> begin
---
...

tarantool> insert into t1 values (1)
---
...

tarantool> commit
---
- error: cannot commit - no transaction is active
...
```

This issue should be fixed when common transaction manager will be introduced.
See #1958

**Comment by sergos** [comment] 2021-03-03 09:49
not relevant, current behavior:
```
tarantool> start transaction;
---
- row_count: 0
...

tarantool> INSERT INTO t1 VALUES(2);
---
- row_count: 1
...

tarantool> SELECT * FROM t1;
---
- metadata:
  - name: ID
    type: integer
  rows:
  - [1]
...

tarantool> commit;
2021-03-03 12:48:58.752 [35185] main/103/interactive txn.c:697 E> ER_TRANSACTION_YIELD: Transaction has been aborted by a fiber yield
---
- null
- Transaction has been aborted by a fiber yield
...

```

**Closed by sergos** 2021-03-03 09:49 UTC
Labels: bug, sql
