### ISSUE TITLE
automatically failover

### ISSUE THREAD

**Issue by lexoff92** [tarantool/tarantool#4298] opened 2019-06-19 14:02 UTC
Tarantool version: 2.1
OS version: CentOS 7

I have a master-replica cluster configured.
When a master fails, you need to manually switch the master role, according to the documentation https://www.tarantool.io/en/doc/2.1/book/replication/repl_bootstrap/#controlled-failover

Can a Tarantool do it automatically? If so, how to implement it?

**Comment by kyukhin** [comment] 2019-07-18 13:30
That is duplicate of #3055 and friends.

**Closed by kyukhin** 2019-07-18 13:30 UTC
Labels: duplicate
