### ISSUE TITLE
an option to prevent net.box.connect() from schema fetching

### ISSUE THREAD

**Issue by parihaaraka** [tarantool/tarantool#6812] opened 2022-01-27 20:02 UTC
subj
1) custom iproto-servers doesn't contain `box` and so on;
2) some users may intend to use `call` and/or `eval` only.

**Comment by Gerold103** [comment] 2022-01-27 23:00
Duplicate of https://github.com/tarantool/tarantool/issues/4789.

**Comment by parihaaraka** [comment] 2022-01-28 07:32
> Duplicate of #4789.
yep.. sorry
this 5 min issue looks like abandoned :/

**Closed** 2022-02-01 10:39 UTC
Labels: feature, duplicate
