### ISSUE TITLE
Strange behavior of ffi in 1.7.4 

### ISSUE THREAD

**Issue by IlyaMarkovMipt** [tarantool/tarantool#2443] opened 2017-05-17 14:34 UTC
Having following script

```
local ffi = require('ffi')
local log = require('log')

-- Add C gettimeofday

ffi.cdef[[
    typedef long time_t;
    typedef struct timeval {
        time_t tv_sec;
        time_t tv_usec;
    } timeval;
    int gettimeofday(struct timeval *t, void *tzp);
]]

-- Function for getting current time
for i = 1, 20, 1 do
	local t = ffi.new("timeval")
	ffi.C.gettimeofday(t, nil)
	log.info("sec: %i, usec: %i", tonumber(t.tv_sec), tonumber(t.tv_usec))
end
os.exit(0)
```
On 1.7.4 version(version 1.7.4-1-g13dd8a4) I got output:
```
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
sec: 1495030341, usec: 0
```
As you see, the second field of `timeval` structure is always zero.

But if launch the same script for tarantool earlier version (e.g 1.7.2-146-g021d36b). Output is following:

```
sec: 1495030932, usec: 317462
sec: 1495030932, usec: 317494
sec: 1495030932, usec: 317504
sec: 1495030932, usec: 317524
sec: 1495030932, usec: 317533
sec: 1495030932, usec: 317541
sec: 1495030932, usec: 317555
sec: 1495030932, usec: 317562
sec: 1495030932, usec: 317572
sec: 1495030932, usec: 317580
sec: 1495030932, usec: 317590
sec: 1495030932, usec: 317603
sec: 1495030932, usec: 317611
sec: 1495030932, usec: 317621
sec: 1495030932, usec: 317628
sec: 1495030932, usec: 317636
sec: 1495030932, usec: 317645
sec: 1495030932, usec: 317653
sec: 1495030932, usec: 317662
sec: 1495030932, usec: 317671
```

The field `tv_usec` is changing.

**Comment by rtsisyk** [comment] 2017-05-17 14:35
Looks like a regression caused by LuaJIT upgrade. Moving to 1.7.5 prio1.

**Comment by rtsisyk** [comment] 2017-05-18 11:53
This problem is caused by buggy time_t definition in pwd.lua

**Closed** 2017-05-18 18:55 UTC
Labels: bug, prio1, regression
