### ISSUE TITLE
libyaml segfault

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1302] opened 2016-01-27 21:48 UTC
OS: Mac OS X, El Capitan

How to repeat: https://gist.github.com/anonymous/3b82193b405140adb7ef

Backtrace:
```
tarantool(65047,0x7fff71dfa000) malloc: *** error for object 0x103780: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Process 65047 stopped
* thread #1: tid = 0x683d99, 0x00007fff88583002 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff88583002 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff88583002 <+10>: jae    0x7fff8858300c            ; <+20>
    0x7fff88583004 <+12>: movq   %rax, %rdi
    0x7fff88583007 <+15>: jmp    0x7fff8857dbdd            ; cerror_nocancel
    0x7fff8858300c <+20>: retq
(lldb) bt
* thread #1: tid = 0x683d99, 0x00007fff88583002 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff88583002 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff845d85c5 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff93a866e7 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fff8416c070 libsystem_malloc.dylib`free + 425
    frame #4: 0x0000000100084165 tarantool`yaml_event_delete + 184
    frame #5: 0x0000000100085f02 tarantool`yaml_emitter_emit + 810
    frame #6: 0x000000010006fb71 tarantool`dump_node(lua_yaml_dumper*) + 1270
    frame #7: 0x000000010006fa86 tarantool`dump_node(lua_yaml_dumper*) + 1035
    frame #8: 0x000000010006fa86 tarantool`dump_node(lua_yaml_dumper*) + 1035
    frame #9: 0x000000010006f2bb tarantool`l_dump(lua_State*) + 346
    frame #10: 0x000000010009a617 tarantool`lj_BC_FUNCC + 52
    frame #11: 0x0000000100066ac7 tarantool`run_script(__va_list_tag*) + 660
    frame #12: 0x00000001000036ee tarantool`fiber_cxx_invoke(void (*)(__va_list_tag*), __va_list_tag*) + 14
    frame #13: 0x000000010007282a tarantool`fiber_loop + 52
    frame #14: 0x0000000100132166 tarantool`coro_init + 80
```

I'm not sure if i can repeat it outside of Tarantool.

**Comment by rtsisyk** [comment] 2016-01-28 08:56
Duplicate of  #883

**Closed by rtsisyk** 2016-01-28 08:56 UTC
