### ISSUE TITLE
vinyl/recovery_quota.test.lua fails sporadically

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3600] opened 2018-08-02 08:39 UTC
This test fails regularly on at least 2.0 and 1.10 branches.

**Comment by locker** [comment] 2019-03-15 14:59
I can't reproduce this test failure locally. The issue description doesn't provide any details I could use for investigation. Closing the issue as invalid. Feel free to reopen if you ever run into it again.

**Closed by locker** 2019-03-15 14:59 UTC
Labels: flaky test
