### ISSUE TITLE
xlogs and snapshots reader for tarantool 1.6

### ISSUE THREAD

**Issue by derElektrobesen** [tarantool/tarantool#1782] opened 2016-09-20 17:32 UTC
Need to read xlogs and snapshots like `tarantool --cat` in tarantool 1.5.

**Comment by bigbes** [comment] 2016-09-20 17:33
closing as duplicate of https://github.com/tarantool/tarantool/issues/1131

**Closed by bigbes** 2016-09-20 17:33 UTC
Labels: duplicate
