### ISSUE TITLE
Different sorting order in SELECT statements with LIMIT clause

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#6664] opened 2021-12-01 09:54 UTC
SELECT statements with LIMIT clause and different sorting order in GROUP BY are disabled now (see #4038):

```sql
tarantool> box.execute([[select "processUid", "started" from "event" order by "processUid" asc, "started" desc limit 10]])
---
- null
- ORDER BY with LIMIT does not support different sorting orders
...
```

This is an important feature. It's necessary to implement it.

**Comment by tsafin** [comment] 2021-12-28 12:05
Kinda duplicate of #3309

**Closed** 2022-02-24 08:39 UTC
Labels: feature, sql, 8sp, teamL
