### ISSUE TITLE
XlogGapError: Missing .xlog file between LSN 63 {1: 63} and 64 {1: 64}

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4078] opened 2019-03-25 18:27 UTC
Occasionally occurs at bootstrap of a full mesh cluster.

I created the reproducer on `Totktonada/reproduce-create-cluster-fail` branch: checkout and run `./run.sh`. It starts 100 tests in 30 parallel jobs, each try to bootstrap a full-mesh cluster of 3 instances. Each instance calls box.cfg{listen = <...>, replication = <...>}, creates a space and inserts several tuples.

It does not reproduce with 2 instances, but reproduces with 3 ones.

**Comment by Totktonada** [comment] 2019-04-07 16:39
It seems that a simpler reproducer is provided and the reason is described in #4106. So this issue can be closed. @locker?

**Comment by Totktonada** [comment] 2019-04-07 16:45
It is interesting that after a99d7a0c0f6a16f0f51be532f0543e3fe1f9c97b ('Feature request for a new collation') I need to increase amount of inserts after an instance bootstrap from 100 to 500 to trigger the problem.

**Comment by Totktonada** [comment] 2019-04-07 17:46
Anyway, updated the branch on top of current master.

**Comment by kyukhin** [comment] 2019-04-08 10:33
Duplicate of #4106

**Closed by kyukhin** 2019-04-08 10:33 UTC
Labels: bug, replication
