### ISSUE TITLE
Add characters to strip to string.rstrip and string.lstrip

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#3622] opened 2018-08-14 13:08 UTC
I want to be able to do roughly this:

```lua
string.rstrip('/my/path/', '/')
```

And have `/` removed from the right. This is how python or penlight do this for example. By default they remove whitespace characters, and if the second parameter is passed, they remove all characters mentioned in that parameter.

**Comment by Totktonada** [comment] 2018-08-14 15:31
Dupe of your #2977.

**Comment by kyukhin** [comment] 2018-08-15 12:33
Duplicate of #2977

**Closed by kyukhin** 2018-08-15 12:33 UTC
