### ISSUE TITLE
vinyl: pagepointer assertion

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#1530] opened 2016-06-08 07:08 UTC
tarantool: /home/georgy/projects/tarantool4/src/box/phia.c:6133: sd_pagepointer: Assertion `(sizeof(struct sdv) * p->h->count) + v->offset <= p->h->sizeorigin' failed.

may be caused by compression bug (it happens after compression err)

**Comment by rtsisyk** [comment] 2016-08-17 15:46
Duplicate of #1527

**Closed by rtsisyk** 2016-08-17 15:46 UTC
Labels: bug, crash, vinyl
