### ISSUE TITLE
Found uncommitted sync transactions from other instance with id 1

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#7592] opened 2022-08-19 16:03 UTC
**Bug description**

While debugging a test we've encountered the error:

```
Found uncommitted sync transactions from other instance with id 1
```

It appears after the instance is restarted with an uncommitted sync transaction, during another transaction to a local space.

It looks related to https://github.com/tarantool/tarantool/issues/5440. We don't have to wait for rw, but we wait for leaving orphan mode.

Tarantool version: 2.10.0-29-g1ec2a9d15

**Steps to reproduce**

I only have a picodata-based repro: https://git.picodata.io/picodata/picodata/picodata/-/issues/129

The test is flaky. Sometimes it also reproduces another problem - https://github.com/tarantool/tarantool/issues/7590.

**Comment by sergos** [comment] 2022-10-24 08:41
The problem is node #3 (the i2 in the log) is starting with RAFT disabled, hence making some transaction, while it receives message that the node 1 is a leader in the current term 4:
```
*** i2  | 2022-10-19 15:17:40.462 [40236] main/123/applier/127.0.0.1:3301 I> RAFT: message {term: 4, vote: 1, leader: 1, state: leader} from 1                                                            
*** i2  | 2022-10-19 15:17:40.462 [40236] main/123/applier/127.0.0.1:3301 I> RAFT: vote request is skipped - RAFT is disabled                                      
i2  | 2022-10-19 15:17:40.462 [40236] main/111/raft_main_loop V> persisted index 14, raft_id: 3                                                                    
i3  | 2022-10-19 15:17:40.462 [40154] main/145/main V> Sending from 2 to 1, msg: msg_type: MsgAppendResponse to: 1 index: 14 commit: 13, to: 1, from: 2, raft_id: 2
i1  | 2022-10-19 15:17:40.462 [40144] relay/127.0.0.1:42662/101/main I> recover from `/tmp/pytest-of-root/pytest-3/test_2_of_3_writable0/i1/00000000000000000000.xlog'
i1  | 2022-10-19 15:17:40.463 [40144] main/239/main V> committing index 14, index: 14, raft_id: 1                                                             
i3  | 2022-10-19 15:17:40.463 [40154] main/116/raft_main_loop V> persisted index 14, raft_id: 2                                                                        
i2  | 2022-10-19 15:17:40.463 [40236] main/122/applier/127.0.0.1:3303 I> RAFT: message {term: 4, vote: 1, leader: 1, leader is seen: true, state: follower} from 2     
i2  | 2022-10-19 15:17:40.463 [40236] main/122/applier/127.0.0.1:3303 I> RAFT: vote request is skipped - RAFT is disabled                                     
i1  | 2022-10-19 15:17:40.463 [40144] main/239/main V> Sending from 1 to 2, msg: msg_type: MsgAppend to: 2 log_term: 2 index: 14 commit: 14, to: 2, from: 1, raft_id: 1                               
i1  | 2022-10-19 15:17:40.463 [40144] main/239/main V> Sending from 1 to 3, msg: msg_type: MsgAppend to: 3 log_term: 2 index: 14 commit: 14, to: 3, from: 1, raft_id: 1                               
i3  | 2022-10-19 15:17:40.464 [40154] relay/127.0.0.1:44124/101/main I> recover from `/tmp/pytest-of-root/pytest-3/test_2_of_3_writable0/i3/00000000000000000018.xlog'                                
i2  | 2022-10-19 15:17:40.465 [40236] main/103/interactive V> broadcast, event: raft.status-changed                                                           
i1  | 2022-10-19 15:17:40.465 [40144] main/111/raft_main_loop V> broadcast, event: raft.topology-changed                                                                                              
i2  | 2022-10-19 15:17:40.465 [40236] main/110/main V> Sending from 3 to 1, msg: msg_type: MsgAppendResponse to: 1 index: 14 commit: 14, to: 1, from: 3, raft_id: 3
i3  | 2022-10-19 15:17:40.465 [40154] main/145/main V> Sending from 2 to 1, msg: msg_type: MsgAppendResponse to: 1 index: 14 commit: 14, to: 1, from: 2, raft_id: 2                                   
*** i2  | 2022-10-19 15:17:40.465 [40236] main/111/raft_main_loop node.rs:668 E> Transaction failed: Unknown: Found uncommitted sync transactions from other instance with id 1
i2  | thread 'main' panicked at 'This shouldn't be', src/traft/node.rs:668:9                                                                                                                          
i2  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                           
```

To avoid such problems you should start node with RAFT enabled, so the node will be readonly if leader is available.

**Comment by gmoshkin** [comment] 2022-11-01 11:36
@sergos what do you mean by `start node with RAFT enabled`, if we start with `election_mode = 'manual'` the same error happens

**Comment by sergepetrenko** [comment] 2022-11-08 09:25
> I can't figure out right away if local space writes on replicas should wait for synchronous transaction commit or not, but the issue is here, indeed.

It seems all writes to local spaces should bypass the synchro queue and commit without waiting. See https://github.com/tarantool/tarantool/issues/7903#issuecomment-1306892543

**Comment by Gerold103** [comment] 2022-11-08 22:34
That would violate serializability. The local txns done after the sync ones might depend on the sync ones in data. The rollback is intentional. The only thing which can be "optimized" here safely is commit local txns even if the synchro queue owner is different but the queue has to be empty then.

**Comment by rosik** [comment] 2022-11-09 23:14
_That_ doesn't violate serializability, the reason is different. You've already provided one example of bad code, here is another one, even simpler:

```lua
local dirt
box.begin()
dirt = box.space.test:insert({90, "dirty"})
box.rollback()

box.space.test:replace(dirt)
```

There are a million ways to commit a dirty read at the application level. And MVCC helps eliminating dirty reads quite well. In the end, it all depends on the code the developer wrote, but it's not an excuse for rolling back all subsequent transactions.

**Comment by sergepetrenko** [comment] 2022-11-10 07:29
@Gerold103
> The only thing which can be "optimized" here safely is commit local txns even if the synchro queue owner is different but the queue has to be empty then.

This optimisation won't be enough: imagine the majority of nodes is lost, leaving some pending transactions in limbo. Imagine also noone rolls back the transactions (because we are going to set `replication_synchro_timeout` to infinity and deprecate it. To be closer to Raft). We are in a situation when noone is writeable, noone can clear the limbo. But we promised the user that a read-only replica **can** write to local spaces.

IMO keeping a promise that local spaces can be written to by read-only replicas is more important than breaking serializability in this particular case.

Besides, cross-engine transactions will be implemented soon, AFAICS. And once this is done, you will either place everything you need in one transaction, or use MVCC to prevent consistency violations. Or simply not mix local and synchronous spaces in one transaction.

**Comment by Gerold103** [comment] 2022-11-10 23:30
I don't mind whatever solution will be done. Breaking linearization promises or "writing to local spaces" promises. I am not a user anyway. In that case there is probably not much point in blocking async txns too, indeed. They can break the cluster anyway - just make any of them on an outdated leader which didn't discover a new leader yet. Then would mean only sync txns go to the limbo.

**Comment by sergepetrenko** [comment] 2022-11-11 06:29
> In that case there is probably not much point in blocking async txns too, indeed

I'm not sure but I suppose that might break some of our expectations about synchro or leader's journal being "ahead" of followers' journals. If we allow async txns, this means we let everyone be writable. Not to sync spaces, though. Again, I haven't formulated any strong arguments yet, but this looks suspicious. Probably because async txns are visible to others, unlike local txns.

I like the idea "only the synchro owner is writable" more.

**Comment by rosik** [comment] 2022-11-11 07:04
> If we allow async txns, this means we let everyone be writable

It seems to me that deduction is false. Everybody doesn't have to be writable. There remains only one leader (except an outdated one). The only thing changes is that it doesn't block async txns.

As for outdated leader problem, I suggest considering the following setup. A cluster with election_mode voter has two leaders (one in outdated term). Both of them would be writable. If there are no sync spaces, async txns could cause a replication conflict (as it's always been this way). A good intention to fix it in fact results in making all async txns synchronous implicitly. But that's not what sync transactions promised to users.

**Comment by sergepetrenko** [comment] 2022-11-15 14:06
> That would violate serializability. The local txns done after the sync ones might depend on the sync ones in data. The rollback is intentional. The only thing which can be "optimized" here safely is commit local txns even if the synchro queue owner is different but the queue has to be empty then.

After some more discussions with the team we decided to go with @Gerold103's proposal: let local writes into synchro queue, but don't commit them out of order.

Letting the user commit local space data out of order is too big of a change. We would have to forbid touching local spaces in non-local transactions, and vice versa, touching non-local spaces (writing or reading, doesn't matter) in local transactions. Otherwise serializability would be easily broken (at least without MVCC).

For example, if a local transaction `box.space.loc:replace{2, 'b'}` is committed while transaction `box.space.sync:replace{1} box.space.loc:insert{2, 'a'}` is waiting in the synchro queue, the possible rollback of synchronous transaction will rewrite the committed local space data with `nil`. Because from sync transaction's POV, it's rollback should replace {2, 'a'} with nil. Even though the space already holds `{2, 'b'}`.

**Closed** 2022-11-21 21:57 UTC
Labels: bug, qsync replication, teamS, 2.10
