### ISSUE TITLE
Master doesn't send heartbeats to replica while scanning wals

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#4461] opened 2019-08-28 12:44 UTC
I've got a situation when a replica couldn't recover from a master because it scans WALs too long before sending the first row. It doesn't send heartbeats to replica while scanning, so replication disconnect timeout occurred in a replica.

It seems that in my case the first row to start to recover from is located at the end of the 00000000000003991061.xlog.

```
019-08-28 11:29:33.793 [21848] main/4851/main I> subscribed replica ffdaa1d1-c57c-4795-9bb7-33179fadfbe0 at fd 15, aka 10.246.1.39:3301, peer of 10.246.1.6:36686
2019-08-28 11:29:33.793 [21848] main/4851/main I> remote vclock {1: 4376075, 2: 5} local vclock {1: 4376095, 2: 5}
2019-08-28 11:29:33.800 [21848] relay/10.246.1.6:36686/101/main I> recover from `/var/lib/tarantool/xtaz_2//00000000000003991061.xlog'
2019-08-28 11:29:39.845 [21848] relay/10.246.1.6:36686/101/main I> done `/var/lib/tarantool/xtaz_2//00000000000003991061.xlog'
2019-08-28 11:29:39.846 [21848] relay/10.246.1.6:36686/101/main I> recover from `/var/lib/tarantool/xtaz_2//00000000000004376090.xlog'
2019-08-28 11:29:39.846 [21848] relay/10.246.1.6:36686/101/main I> done `/var/lib/tarantool/xtaz_2//00000000000004376090.xlog'
2019-08-28 11:29:39.846 [21848] relay/10.246.1.6:36686/101/main coio.cc:370 !> SystemError unexpected EOF when reading from socket, called on fd 15, aka 10.246.1.39:3301, peer of 10.246.1.6:36686: Broken pipe
2019-08-28 11:29:39.846 [21848] relay/10.246.1.6:36686/101/main C> exiting the relay loop
```

**Comment by sergos** [comment] 2022-06-20 15:55
Closing as duplicate of #6706

**Closed by sergos** 2022-06-20 15:55 UTC
Labels: bug, replication, teamS
