### ISSUE TITLE
txn_limbo_write_confirm_rollback: Assertion `lsn > 0' failed.

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5185] opened 2020-07-17 16:50 UTC
### Bug description:

Test executes fiber that switches on and off sync mode in a space in a loop and runs loop with writes to a leader. Right on the test start assert `lsn > 0` triggered.

### Steps to reproduce:

```lua
env = require('test_run')
test_run = env.new()
engine = test_run:get_cfg('engine')
fiber = require('fiber')
math = require('math')
math.randomseed(os.time())

orig_synchro_quorum = box.cfg.replication_synchro_quorum
orig_synchro_timeout = box.cfg.replication_synchro_timeout

NUM_INSTANCES = 2
BROKEN_QUORUM = NUM_INSTANCES + 1

test_run:cmd("setopt delimiter ';'")
disable_sync_mode = function()
    local s = box.space._space:get(box.space.sync.id)
    local new_s = s:update({{'=', 6, {is_sync=false}}})
    box.space._space:replace(new_s)
end;
test_run:cmd("setopt delimiter ''");

test_run:cmd("setopt delimiter ';'")
enable_sync_mode = function()
    local s = box.space._space:get(box.space.sync.id)
    local new_s = s:update({{'=', 6, {is_sync=true}}})
    box.space._space:replace(new_s)
end;
test_run:cmd("setopt delimiter ''");

test_run:cmd("setopt delimiter ';'")
set_sync_mode = function(mode)
    local s = box.space._space:get(box.space.sync.id)
    local new_s = s:update({{'=', 6, {is_sync=mode}}})
    box.space._space:replace(new_s)
end;
test_run:cmd("setopt delimiter ''");

set_random_mode = function()                    \
    if (math.random(1, 10) > 5) then            \
        enable_sync_mode()                     \
    else                                        \
        disable_sync_mode()                      \
    end                                         \
end

box.schema.user.grant('guest', 'replication')

-- Setup an async cluster with two instances.
test_run:cmd('create server replica with rpl_master=default,\
                                         script="replication/replica.lua"')
test_run:cmd('start server replica with wait=True, wait_load=True')

-- Write data to a leader and enable and disable sync mode in background in a
-- loop.
-- Testcase setup.
test_run:switch('default')
box.cfg{replication_synchro_quorum=2, replication_synchro_timeout=0.1}
_ = box.schema.space.create('sync', {is_sync=true, engine=engine})
_ = box.space.sync:create_index('pk')
-- Testcase body.
f1 = fiber.create(function() while true do set_random_mode() end end)
f1.status()
for i = 1,10 do if pcall(box.space.sync:insert{i}) then test_run:switch('replica') assert(i == box.space.sync:select{}) test_run:switch('default')
 fiber.sleep(0.1) end end
test_run:switch('replica')
box.space.sync:select{}
-- Testcase cleanup.
test_run:switch('default')
box.space.sync:drop()

-- Teardown.
test_run:cmd('switch default')
test_run:cmd('stop server replica')
test_run:cmd('delete server replica')
test_run:cleanup_cluster()
box.schema.user.revoke('guest', 'replication')
box.cfg{                                                                        \
    replication_synchro_quorum = orig_synchro_quorum,                           \
    replication_synchro_timeout = orig_synchro_timeout,                         \
}
```

```
2020-07-17 16:31:42.573 [19460] main/110/main I> initial data sent.
2020-07-17 16:31:42.573 [19460] main I> assigned id 2 to replica eb70c553-2470-4795-9e26-01f5f4cf1ee1                                            
2020-07-17 16:31:42.575 [19460] relay/unix/:(socket)/101/main I> recover from `/home/s.bronnikov/tarantool/build/test/var/002_replication/master/00000000000000000000.xlog'
2020-07-17 16:31:42.576 [19460] main/110/main I> final data sent.
2020-07-17 16:31:42.591 [19460] main/110/main I> subscribed replica eb70c553-2470-4795-9e26-01f5f4cf1ee1 at fd 23, aka unix/:(socket), peer of unix/:(socket)
2020-07-17 16:31:42.591 [19460] main/110/main I> remote vclock {1: 2} local vclock {1: 2}                                                        
2020-07-17 16:31:42.593 [19460] relay/unix/:(socket)/101/main I> recover from `/home/s.bronnikov/tarantool/build/test/var/002_replication/master/00000000000000000000.xlog'
2020-07-17 16:31:42.626 [19460] main/124/console/unix/: I> set 'replication_synchro_timeout' configuration option to 0.1                         
2020-07-17 16:31:42.626 [19460] main/124/console/unix/: I> set 'replication_synchro_quorum' configuration option to 2                            
tarantool: /home/s.bronnikov/tarantool/src/box/txn_limbo.c:262: txn_limbo_write_confirm_rollback: Assertion `lsn > 0' failed.    
```

**Comment by Gerold103** [comment] 2020-07-29 21:42
The test is broke in many ways: unstable, has syntax errors, unreachable code. Here is the closest version of the test which can actually fail. It is also unstable, but just run it with `--force` and collect crashes.
```
env = require('test_run')
test_run = env.new()
engine = test_run:get_cfg('engine')
fiber = require('fiber')
math = require('math')
math.randomseed(os.time())

orig_synchro_quorum = box.cfg.replication_synchro_quorum
orig_synchro_timeout = box.cfg.replication_synchro_timeout

NUM_INSTANCES = 2
BROKEN_QUORUM = NUM_INSTANCES + 1

test_run:cmd("setopt delimiter ';'")
disable_sync_mode = function()
    local s = box.space._space:get(box.space.sync.id)
    local new_s = s:update({{'=', 6, {is_sync=false}}})
    box.space._space:replace(new_s)
end;
test_run:cmd("setopt delimiter ''");

test_run:cmd("setopt delimiter ';'")
enable_sync_mode = function()
    local s = box.space._space:get(box.space.sync.id)
    local new_s = s:update({{'=', 6, {is_sync=true}}})
    box.space._space:replace(new_s)
end;
test_run:cmd("setopt delimiter ''");

test_run:cmd("setopt delimiter ';'")
set_sync_mode = function(mode)
    local s = box.space._space:get(box.space.sync.id)
    local new_s = s:update({{'=', 6, {is_sync=mode}}})
    box.space._space:replace(new_s)
end;
test_run:cmd("setopt delimiter ''");

set_random_mode = function()                    \
    if (math.random(1, 10) > 5) then            \
        enable_sync_mode()                     \
    else                                        \
        disable_sync_mode()                      \
    end                                         \
end

box.schema.user.grant('guest', 'replication')

-- Setup an async cluster with two instances.
test_run:cmd('create server replica with rpl_master=default,\
                                         script="replication/replica.lua"')
test_run:cmd('start server replica with wait=True, wait_load=True')

-- Write data to a leader and enable and disable sync mode in background in a
-- loop.
-- Testcase setup.
test_run:switch('default')
box.cfg{replication_synchro_quorum=2, replication_synchro_timeout=0.1}
_ = box.schema.space.create('sync', {is_sync=true, engine=engine})
_ = box.space.sync:create_index('pk')
-- Testcase body.
f1 = fiber.create(function() while true do set_random_mode() end end)
f1.status()
for i = 1,10 do                                                                 \
    pcall(box.space.sync.insert, box.space.sync, {i})                           \
    fiber.sleep(0.1)                                                            \
end
test_run:switch('replica')
box.space.sync:select{}
-- Testcase cleanup.
test_run:switch('default')
box.space.sync:drop()

-- Teardown.
test_run:cmd('switch default')
test_run:cmd('stop server replica')
test_run:cmd('delete server replica')
test_run:cleanup_cluster()
box.schema.user.revoke('guest', 'replication')
box.cfg{                                                                        \
    replication_synchro_quorum = orig_synchro_quorum,                           \
    replication_synchro_timeout = orig_synchro_timeout,                         \
}
```

The original crash could not reproduce, but got some more. First crash is in rollback writing: since confirmation write yields, it can happen, that a confirm LSN1 write is started, then some pending sync transaction with LSN = LSN1 times out, and it starts writing rollback for the same LSN. It should not - it should wait for confirmation write end, and then proceed to successful completion.
```C
static void
txn_limbo_write_rollback(struct txn_limbo *limbo, int64_t lsn)
{
	assert(lsn > limbo->confirmed_lsn);
	assert(!limbo->is_in_rollback);
	limbo->is_in_rollback = true;
	txn_limbo_write_confirm_rollback(limbo, lsn, false);
	limbo->is_in_rollback = false;
}
```
In the code sample the line `assert(lsn > limbo->confirmed_lsn);` causes a crash.

**Comment by Gerold103** [comment] 2020-07-31 22:32
Couldn't reproduce any new crashes after I fixed the one mentioned above. Neither the crash in the ticket header. If it won't appear again in some near future, I will close the issue.

**Comment by Gerold103** [comment] 2020-09-10 21:52
I guess we can close it now.

**Closed by Gerold103** 2020-09-10 21:52 UTC
Labels: bug, crash, qsync replication
