### ISSUE TITLE
fiber.top() on aarch64 platform

### ISSUE THREAD

**Issue by first-leon** [tarantool/tarantool#6735] opened 2021-12-22 14:44 UTC
There is no functionality on the aarch64 platform fiber.to (), fiber.to_enable(), fiber.top_disable().
A convenient tool, I would like to have it on the aarch64 platform.

**Comment by sergos** [comment] 2022-03-18 08:45
Seem like will be fixed with https://github.com/tarantool/tarantool/issues/5869

**Comment by Gumix** [comment] 2022-05-25 18:11
Duplicate of #4573

**Closed by Gumix** 2022-05-25 18:11 UTC
Labels: feature, teamC
