### ISSUE TITLE
Secondary Index support for phia backend

### ISSUE THREAD

**Issue by crudbug** [tarantool/tarantool#1327] opened 2016-02-11 22:26 UTC
From - http://tarantool.org/doc/book/box/sophia_diff.html#sophia-diff 

Are there any plans to support secondary indexes with Sophia backend ?

**Comment by pmwkaa** [comment] 2016-02-12 10:43
Hi, yes it is planned. I believe the secondary indexes support will be available for testing in following 1-2 month time. thanks

**Comment by pmwkaa** [comment] 2016-02-12 10:44
related task: https://github.com/tarantool/tarantool/issues/623

**Comment by rtsisyk** [comment] 2016-07-20 18:49
This ticket is duplicate of #623

**Closed by rtsisyk** 2016-07-20 18:49 UTC
Labels: duplicate
