### ISSUE TITLE
TAP tests fail when running w/ out-of-source build

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4259] opened 2019-05-29 14:36 UTC
When running testing w/ out-of-source build some TAP tests fail.
Reproduce:
```
/export/tarantool/src/test$ ./test-run.py --builddir ../../bld --force --long -j 48
```

What's wrong:
```
[012] unit/merger.test                                                                                                                                                          
[012] TAP13 parse failed: Missing plan in the TAP source                                                                                                                        
[012] [ new ]
```

**Comment by Totktonada** [comment] 2019-05-29 14:52
Dupe of #4258.

**Closed by Totktonada** 2019-05-29 14:52 UTC
Labels: qa, test-run.py
