### ISSUE TITLE
Error message suggests create failed but the object exists

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#5394] opened 2020-10-08 00:52 UTC
I have Ubuntu 18.04.
I have Tarantool 2.5, pulled from source today.

I execute these requests:
box.schema.user.create('user1')
box.schema.user.grant('user1','create','universe')
box.schema.user.grant('user1','read,write','space','_user')
box.session.su('user1')
box.schema.user.create('user2')
box.session.su('admin')
box.space._user:select()

The attempt to create user2 causes an error message
"error: Write access to space '_priv' is denied for user 'user1'"
This is expected and not a problem.
The problem is that the select succeeds -- it says user2 exists
(without privileges of course).
I am hoping that the error message could add
"... but user was created anyway".

**Comment by kyukhin** [comment] 2021-07-13 13:26
Should be a one-liner.

**Comment by alyapunov** [comment] 2021-09-08 14:25
What about deleting back the user in such a case? That would be something like exception safe code. Just a raw idea.

**Comment by unera** [comment] 2021-09-22 11:05
I think the ticket should be closed as "Not a bug" or moved to wishlist.

**Comment by olegrok** [comment] 2021-09-22 12:48
> I think the ticket should be closed as "Not a bug" or moved to wishlist.

Actually it should be resolved after https://github.com/tarantool/tarantool/issues/4348 will be implemented. As well as e.g. https://github.com/tarantool/tarantool/issues/6120. As customer I expect that such actions will be atomic.

**Comment by AnastasMIPT** [comment] 2021-09-27 09:04
This ticket is not a bug. Read @olegrok and @unera for more information.

> @AnastasMIPT Please, clarify a reason of closing the issue.



> > I think the ticket should be closed as "Not a bug" or moved to wishlist.
> 
> Actually it should be resolved after #4348 will be implemented. As well as e.g. #6120. As customer I expect that such actions will be atomic.

**Closed by AnastasMIPT** 2021-09-27 09:04 UTC
Labels: feature, good first issue, 2sp, teamC
