### ISSUE TITLE
alternative delimiter doesn't work on admin port connection

### ISSUE THREAD

**Issue by zlobspb** [tarantool/tarantool#2027] opened 2017-01-11 18:18 UTC
it is not possible now to send multiline to admin port of tarantool (used by admins in monitoring)

```
$ rlwrap telnet -e ^D 127.0.0.1 39002
Telnet escape character is '^D'.
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^D'.
Tarantool 1.7.3-32-g0dd09b1 (Lua console)
type 'help' for interactive help
console = require('console'); console.delimiter('#')
---
...
2+2#
3+3#
asdf
```

```
$ rlwrap telnet -e ^D 127.0.0.1 39002
Telnet escape character is '^D'.
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^D'.
Tarantool 1.6.9-11-gf4619d0 (Lua console)
type 'help' for interactive help
console = require('console'); console.delimiter('#')
---
...
2+2#
asdf
```

**Comment by rtsisyk** [comment] 2017-01-13 09:05
Confirmed. 

This problem reproduces only with `#` , `.` and other special characters.  Please choose a different character as a workaround. We'll fix this problem later.

**Comment by rtsisyk** [comment] 2017-01-13 09:09
This problem doesn't block @zlobspb anymore, so I'm moving this ticket to "prio3".

**Comment by kshcherbatov** [comment] 2019-02-20 16:25
The reason for this behavior is that telnet sends a sequence \r\n as a separator. When you run the default values, \n is used as the line separator; however, if you change it to a different # character, the new separator becomes #\n. And the line that came from telnet contains bytes#\r\n, which does not correspond to #\n.

**Closed** 2019-03-07 10:54 UTC
Labels: bug, ready for review
