### ISSUE TITLE
Reuse CI workflow files

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#8496] opened 2023-03-24 12:08 UTC
Currently, most CI workflow files are identical and are basically copy-paste: this makes it hard maintaining them, as any change requires to be duplicated.

Consider using the [reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) feature of GitHub workflows.

**Comment by Totktonada** [comment] 2023-03-24 12:16
Duplicate of #6604.

**Closed** 2023-03-24 12:38 UTC
Labels: qa, refactoring, code health
