### ISSUE TITLE
iproto: is nullable type attribute wanted by API

### ISSUE THREAD

**Issue by alg1973** [tarantool/tarantool#3373] opened 2018-04-24 16:21 UTC
ODBC API need to now: are current columns in a tuple is allowed to have NULL values or not? It's also useful to know by any client API connectors since is nullable or not is a part of type definitions actually.

**Comment by Gerold103** [comment] 2018-04-26 17:58
Duplicate of this #2620

**Comment by kyukhin** [comment] 2018-07-11 07:59
Closed as duplicate.

**Closed by kyukhin** 2018-07-11 07:59 UTC
Labels: feature, need feedback
