### ISSUE TITLE
Triggers in SQL -- WHEN clauses can't have column names

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2505] opened 2017-06-06 23:03 UTC
I have Ubuntu 14.04. I have Tarantool 1.8, pulled from source today.
I execute these statements:
CREATE TABLE table1 (column1 INT PRIMARY KEY);
CREATE TABLE table2 (column1 INT PRIMARY KEY);
CREATE TRIGGER trigger_on_table1_1 AFTER INSERT ON table1 FOR EACH ROW
WHEN column1 > 0 BEGIN INSERT INTO table2 VALUES (1); END;
INSERT INTO table1 VALUES (1);
The result is: error: 'no such column: column1'
If I change the WHEN condition to WHEN 1 > 0 there is no error.
Incidentally in standard SQL a triggered WHEN clause looks like: WHEN (condition), not WHEN condition.

**Comment by kyukhin** [comment] 2017-08-03 14:20
Confirmed.
Issue is that Tarantool's SQL requires to specify new/old tables.
This works for me:
```
CREATE TRIGGER trigger_on_table1_1 AFTER INSERT ON table1 FOR EACH ROW WHEN new.column1 > 0 BEGIN INSERT INTO table2 VALUES (1); END;
```

**Comment by SudoBobo** [comment] 2019-02-08 12:35
@pgulutzan can you please explain what is the exact issue? As far as I understand requirement to specify OLD/NEW table is a common requirement among DBMS (at least, it's true for IBM DB2 and PostgreSQL)

**Comment by pgulutzan** [comment] 2019-02-11 20:33
The above comments are correct, new.column1 is legal and my example was bad, sorry.
And I don't see a reason to care whether the parentheses are optional or old.column1 fails.
So I suppose it could be closed as "not a bug".

**Comment by kyukhin** [comment] 2019-02-12 14:05
Closing then.

**Closed by kyukhin** 2019-02-12 14:05 UTC
Labels: ansi sql, bug, sql, wontfix
