### ISSUE TITLE
Iproto over websockets

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3274] opened 2018-03-22 10:43 UTC
It would be nice to have an iproto implementation over websockets, so that tarantool connections can be proxied through regular http proxies.

This will allow tarantool to be deployed on many PaaS providers as a microservice.

websockets are very low overhead and pretty much behave like regular sockets after connection upgrade.

**Comment by filonenko-mikhail** [comment] 2018-09-22 13:10
previous discussion

https://github.com/tarantool/tarantool/issues/1028

**Comment by kyukhin** [comment] 2022-09-20 14:56
Looks like a duplicate of #1028.

**Closed by kyukhin** 2022-09-20 14:56 UTC
Labels: feature
