### ISSUE TITLE
Replication Error. Master Master

### ISSUE THREAD

**Issue by seet61** [tarantool/tarantool#4143] opened 2019-04-12 06:27 UTC
Tarantool version:
Tarantool 1.10.3-7-gece1576e7

OS version:
Debian 9.8

Bug description:
Replication error for master master after desinchronizations.

Steps to reproduce:
We have 4 instances at 2 servers with replication between them. HAPrxoy balance request. Insert request only go to master of 1 server. Another instances get data by replication. 

After desinchronizations between instances( error: 
`2019-04-11 21:00:48.469 [16852] main/106/applier/replicator@tarantuldb-t coio.cc:370 !> SystemError unexpected EOF when reading from socket, called on fd 47, aka 10.78.221.89:33740: Broken pipe
2019-04-11 21:01:19.527 [16852] main/106/applier/replicator@tarantuldb-t box.cc:324 E> error applying row: {type: 'INSERT', replica_id: 2, lsn: 1785164, space_id: 513, index_id: 0, tuple: ["95baseSERVICE1;2;3;4;972;2896;2916;3492;3555;50
37;5327;5370;5530;7335;7734;9852;9854;9901;9904;1043;1143;1243;1343;1450;11279;12094;", "<?xml version='1.0' encoding='UTF-8'?><SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http:\/\/schemas.xmlsoap.org\/soap\/envelope\/\"><SOAP-ENV:Body xmlns:ber-
ns0=\"http:\/\/www.bercut.com\/schema\/commonInVoiceAPI\" xmlns:ber-ns1=\"http:\/\/www.bercut.com\/cc\/sa\/dictionarymanagement\"><ber-ns1:getDictionariesResponse><Dictionaries><ber-ns0:id>1<\/ber-ns0:id><ber-ns0:name>Телефония<\/ber-ns0:name><\/Dictionaries><Dictionaries><ber-ns0:id>2<\/ber-ns0:id><ber-ns0:name>SMS отправка<\/ber-ns0:name><\/Dictionaries><Dictionaries><ber-ns0:id>3<\/ber-ns0:id><ber-ns0:name>USSD<\/ber-ns0:name><\/Dictionaries><Dictionaries><ber-ns0:id>4<\/ber-ns0:id><ber-ns0:name>GPRS<\/ber-ns0:name><\/Dictionaries><Dictionaries><ber-ns0:id>972<\/ber-ns0:id><ber-ns0:name>Я на связи<\/ber-ns0:name><\/Dicti
`
 ) we remove memtx dir and master on second server and it running correctly. But slave on the same server can't start. Debug log attached. 

For this space was added trigger before_replace, but it not help.

Optional (but very desirable):
[cache_slave2.log.zip](https://github.com/tarantool/tarantool/files/3071821/cache_slave2.log.zip)

**Comment by GeorgyKirichenko** [comment] 2019-06-04 15:37
Unfortunatelly the attached log is newer than fragment in your message. As this fragment seems truncated there is no clear understanding of primary cause of the initial failure.
Hovewer, attached log contains strings aka main/107/applier/replicator@tarantuldb-t xrow.c:943 E> ER_PROC_LUA: Missing .xlog file between LSN 5137088 {1: 240379, 2: 4750534, 5: 146175} and 5137379 {1: 240379, 2: 4750825, 5: 146175} which means that master lost one or more of their xlog files, please check it.
If you really lost files then replica could be reinitialized after a snapshot on a master (to set new point from which replica would be initialized).

**Comment by seet61** [comment] 2019-06-10 05:44
The problem was repeated at the test area.
root@tarantuldb-tst4:/var/log/tarantool# tarantool -v
Tarantool 1.10.3-71-gbeb4c0ce6
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++

Slave instance on the same server with master:
`2019-06-10 08:19:12.067 [2714] main/107/applier/replicator@tarantuldb-t xrow.c:949 E> ER_PROC_LUA: Missing .xlog file between LSN 69464450 {1: 49308194, 2: 12297496, 6: 7858687, 8: 73} and 76939528 {1: 54407488, 2: 12297496, 6: 10234544}
2019-06-10 08:19:12.068 [2714] main/101/slave2 box.cc:146 E> ER_READONLY: Can't modify data because this instance is in read-only mode.
2019-06-10 08:19:12.068 [2714] main/101/slave2 tarantoolctl:532 E> Start failed: Can't modify data because this instance is in read-only mode.
2019-06-10 08:19:14.580 [2742] main/107/applier/replicator@tarantuldb-t xrow.c:949 E> ER_PROC_LUA: Missing .xlog file between LSN 69464450 {1: 49308194, 2: 12297496, 6: 7858687, 8: 73} and 76939528 {1: 54407488, 2: 12297496, 6: 10234544}
2019-06-10 08:19:14.581 [2742] main/101/slave2 box.cc:146 E> ER_READONLY: Can't modify data because this instance is in read-only mode.
2019-06-10 08:19:14.581 [2742] main/101/slave2 tarantoolctl:532 E> Start failed: Can't modify data because this instance is in read-only mode.
2019-06-10 08:19:17.234 [2768] main/107/applier/replicator@tarantuldb-t xrow.c:949 E> ER_PROC_LUA: Missing .xlog file between LSN 69464450 {1: 49308194, 2: 12297496, 6: 7858687, 8: 73} and 76939528 {1: 54407488, 2: 12297496, 6: 10234544}
2019-06-10 08:19:17.235 [2768] main/101/slave2 box.cc:146 E> ER_READONLY: Can't modify data because this instance is in read-only mode.
2019-06-10 08:19:17.235 [2768] main/101/slave2 tarantoolctl:532 E> Start failed: Can't modify data because this instance is in read-only mode.
2019-06-10 08:19:21.551 [2794] main/107/applier/replicator@tarantuldb-t xrow.c:949 E> ER_PROC_LUA: Missing .xlog file between LSN 69464450 {1: 49308194, 2: 12297496, 6: 7858687, 8: 73} and 76939528 {1: 54407488, 2: 12297496, 6: 10234544}
2019-06-10 08:19:21.552 [2794] main/101/slave2 box.cc:146 E> ER_READONLY: Can't modify data because this instance is in read-only mode.
2019-06-10 08:19:21.552 [2794] main/101/slave2 tarantoolctl:532 E> Start failed: Can't modify data because this instance is in read-only mode.`

xlog files from instance directory:  [https://cloud.mail.ru/public/2SDW/QviJdWwBF](url)
I can't find file with 76939528 {1: 54407488, 2: 12297496, 6: 10234544}.

**Comment by seet61** [comment] 2019-06-20 06:57
@GeorgyKirichenko @kyukhin ?

**Comment by sergepetrenko** [comment] 2019-07-18 14:03
@seet61 please also provide .snap files from the instance directory, it's impossible to start tarantool and repeat the issue without these.

**Comment by kostja** [comment] 2020-04-08 08:28
Looks like a duplicate of #4114

**Comment by kyukhin** [comment] 2020-04-22 18:16
No feedback for months, closing.

**Closed by kyukhin** 2020-04-22 18:16 UTC
Labels: bug, need feedback
