### ISSUE TITLE
Unserializable read tracked incorrectly after transaction rollback in vinyl

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#7344] opened 2022-07-04 08:32 UTC
<details>
<summary>Details</summary>

</details>

**Steps to reproduce**
```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local ffi = require('ffi')
local log = require('log')
local txn_proxy = require('txn_proxy')
local yaml = require('yaml')

ffi.cdef('bool flag;')

box.cfg{memtx_use_mvcc_engine = true}

box.schema.space.create('s', {engine = 'vinyl'})
box.space.s:create_index('pk')

local tx1 = txn_proxy:new()
local tx2 = txn_proxy:new()
local tx3 = txn_proxy:new()

tx1('box.begin()')
tx2('box.begin()')
tx3('box.begin()')

tx1('box.space.s:replace{0, 0}')

tx2('box.space.s:delete{0}')
tx2('box.space.s:replace{1, 0}')
tx1('box.rollback()')

tx3('box.space.s:insert{0, 1}')
tx3:commit()
log.info('%s', yaml.encode(tx2:commit()))

os.exit()
```
**Actual behavior**
```console
 ---
...
```
**Expected behavior**
```console
 ---
- {'error': 'Transaction has been aborted by conflict'}
...
```

**Comment by locker** [comment] 2022-07-04 10:21
Thought it was a dup of #1944, but it isn't quite so, although the issue is related.

The problem here is that, in contrast to memtx, in Vinyl `delete` [doesn't return the deleted tuple](https://www.tarantool.io/en/doc/latest/book/box/engines/memtx_vinyl_diff/) (because it doesn't read the deleted tuple unless there is a secondary index). So the example above is in fact serializable:
1. tx3 commits first and inserts {0, 1} into the space.
2. tx2 commits second; it deletes {0, 1} and inserts {1, 0} into the space.

Since the `delete` statement doesn't return anything to tx2, tx2 may be committed after tx3 even if the `delete` statement was executed before tx3 was committed and {0, 1} was inserted.

**Closed by locker** 2022-07-04 10:21 UTC
Labels: bug, vinyl
