### ISSUE TITLE
Please fix build warnings when building public C API manual

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1020] opened 2015-09-01 15:28 UTC

**Comment by rtsisyk** [comment] 2015-09-15 12:45
```
src/trivia/tarantool.h:98: warning: unable to resolve link to `say_level' for \link command
src/trivia/tarantool.h:760: warning: unable to resolve link to `iterator_type' for \link command
src/trivia/tarantool.h:891: warning: unable to resolve link to `iterator_type' for \link command
src/trivia/tarantool.h:969: warning: unable to resolve link to `box_error_code' for \link command
```

There warnings are caused by
```
commit 0b17f366a0aae82bd63791c76b9b3b887588f392
Author: Konstantin Osipov <kostja@tarantool.org>
Date:   Thu Sep 10 21:10:37 2015 +0300

    module api docs: remove double title, fix spelling

diff --git a/src/trivia/tarantool_header.h b/src/trivia/tarantool_header.h
index 2223de9..3a71302 100644
--- a/src/trivia/tarantool_header.h
+++ b/src/trivia/tarantool_header.h
@@ -8,13 +8,7 @@
 #include <stdint.h>
 #include <sys/types.h> /* ssize_t */
 
-
-/**
- * \file
- * Tarantool Module API
- */
-
-/** Extern modificator for all public functions */
+/** Extern modifier for all public functions */
```

```\file``` is mandatory here.

**Comment by rtsisyk** [comment] 2015-09-23 13:40
from @kostja 
```
reading sources... [100%] singlehtml
/home/kostja/work/tarantool/doc/sphinx/reference/capi.rst:21: WARNING: Type must be either just a name or a typedef-like declaration.
Just a name error: Invalid definition: Expected identifier in nested name, got keyword: void [error at 4]
void(* sayfunc_t)(int level, const char *filename, int line, const char *error, const char *format,...)
—--^
Typedef-like expression error: If declId, parameters, and qualifiers {
Invalid definition: Expected identifier in nested name. [error at 4]
void(* sayfunc_t)(int level, const char *filename, int line, const char *error, const char *format,...)
—--^
} else If parenthesis in noptr-declarator {
If declId, parameters, and qualifiers {
Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "l". [error at 22]
void(* sayfunc_t)(int level, const char *filename, int line, const char *error, const char *format,...)
—--------------------^
} else If parenthesis in noptr-declarator {
Invalid definition: Expected ')' in "( ptr-declarator )" [error at 18]
void(* sayfunc_t)(int level, const char *filename, int line, const char *error, const char *format,...)
—----------------^
}
}
/home/kostja/work/tarantool/doc/sphinx/reference/capi.rst:21: WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 8]
ssize_t coio_call(ssize_t(*func)(va_list ap), ...)
—------^
} else if return type {
If declId, parameters, and qualifiers {
Invalid definition: Expected identifier in nested name. [error at 26]
ssize_t coio_call(ssize_t(*func)(va_list ap), ...)
—------------------------^
} else If parenthesis in noptr-declarator {
If declId, parameters, and qualifiers {
Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "a". [error at 41]
ssize_t coio_call(ssize_t(*func)(va_list ap), ...)
—---------------------------------------^
} else If parenthesis in noptr-declarator {
Invalid definition: Expected ')' in "( ptr-declarator )" [error at 33]
ssize_t coio_call(ssize_t(*func)(va_list ap), ...)
—-------------------------------^
}
}
}
```

**Comment by rtsisyk** [comment] 2015-09-23 13:42
I tested doxygen 1.7.6 (precise), 1.8.6 (trusty), 1.8.8 (jessie), 1.8.9 (sid) - the problem didn't reproduced.
I think your local version of Doxygen is buggy.
Please show me `apt-cache policy doxygen`, `apt-cache policy python-breathe`

**Comment by pgulutzan** [comment] 2015-09-23 14:05
I don't know about Konstantin Osipov's arrangement, but here is mine, on Ubuntu 12.04.

doxygen:
  Installed: 1.7.6.1-2ubuntu1
  Candidate: 1.7.6.1-2ubuntu1
  Version table:
 *** 1.7.6.1-2ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status

python-breathe was brought in with "sudo pip install breathe" not apt-get

**Comment by kostja** [comment] 2015-09-23 15:35
kostja@atlas ~ % sudo pip install --upgrade breathe
Requirement already up-to-date: breathe in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: Sphinx>=1.0.7 in /usr/local/lib/python2.7/dist-packages (from breathe)
Requirement already up-to-date: docutils>=0.5 in /usr/local/lib/python2.7/dist-packages (from breathe)
Requirement already up-to-date: six>=1.4 in /usr/local/lib/python2.7/dist-packages (from breathe)

**Comment by rtsisyk** [comment] 2015-11-10 12:41
Fixed by @kostja

**Closed by rtsisyk** 2015-11-10 12:41 UTC
Labels: broken build, bug, documentation
