### ISSUE TITLE
libreadline is GPL

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#437] opened 2014-08-12 08:30 UTC
libreadline (used by REPL) is licensed under GPL.
We need to find a replacement.

I found good solution for us:
http://fperrad.github.io/ljlinenoise/

**Comment by kostja** [comment] 2015-08-12 15:34
A duplicate of gh-747, fixed by @zloidemon

**Closed by kostja** 2015-08-12 15:34 UTC
Labels: feature
