### ISSUE TITLE
Unallocated `serializer_lua` used by `lbox_console_format_lua`

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#7404] opened 2022-07-13 10:58 UTC
**Bug description**

The output varies from run to run:
```
tarantool> \set output lua
true;
tarantool> setmetatable({}, { __serialize = function() print('hello') end})
{};
```

```
tarantool> \set output lua
true;
tarantool> setmetatable({}, { __serialize = function() print('hello') end})
hello
box.NULL;
```

```
Tarantool 2.10.0-beta2-607-gff57a1091
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```

The difference is due to serializer_lua, which points to the unallocated memory.

Note that there are two `static struct luaL_serializer *serializer_lua`:
1. In `src/box/lua/console.c` — allocated in tarantool_lua_console_init an used by lbox_console_format_lua;
2. In `src/box/lua/serialize_lua.c` — allocated in lua_serializer_init and never used.

Somehow the allocation of the second serializer causes deallocation of the first one by LuaJIT:
```
(gdb) r
Breakpoint 1, tarantool_lua_console_init (L=0x40000378) at tarantool/src/box/lua/console.c:697
697             serializer_lua->encode_use_tostring     = 1;
(gdb) watch serializer_lua->encode_load_metatables
Hardware watchpoint 2: serializer_lua->encode_load_metatables
(gdb) c
Continuing.

Hardware watchpoint 2: serializer_lua->encode_load_metatables
Old value = 1
New value = 544175136
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:243
#1  0x000055555583e71c in lj_str_new (...) at tarantool/third_party/luajit/src/lj_str.c:309
#2  0x000055555586c957 in lj_parse_keepstr (...) at tarantool/third_party/luajit/src/lj_parse.c:243
#3  0x000055555586abc2 in lex_string (ls=0x7fffffffdb80, tv=0x7fffffffdb90) at tarantool/third_party/luajit/src/lj_lex.c:280
#4  0x000055555586b8dd in lex_scan (ls=0x7fffffffdb80, tv=0x7fffffffdb90) at tarantool/third_party/luajit/src/lj_lex.c:364
#5  0x000055555586c1b0 in lj_lex_next (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_lex.c:454
#6  0x0000555555873361 in parse_args (ls=0x7fffffffdb80, e=0x7fffffffd1a0) at tarantool/third_party/luajit/src/lj_parse.c:1915
#7  0x0000555555873806 in expr_primary (ls=0x7fffffffdb80, v=0x7fffffffd1a0) at tarantool/third_party/luajit/src/lj_parse.c:1982
#8  0x0000555555874516 in parse_call_assign (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_parse.c:2245
#9  0x0000555555875cdb in parse_stmt (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_parse.c:2689
#10 0x0000555555875d16 in parse_chunk (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_parse.c:2701
#11 0x000055555587309a in parse_body (ls=0x7fffffffdb80, e=0x7fffffffd5c0, needself=0, line=319) at tarantool/third_party/luajit/src/lj_parse.c:1870
#12 0x0000555555874680 in parse_local (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_parse.c:2265
#13 0x0000555555875c55 in parse_stmt (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_parse.c:2665
#14 0x0000555555875d16 in parse_chunk (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_parse.c:2701
#15 0x0000555555876059 in lj_parse (ls=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_parse.c:2734
#16 0x000055555583876d in cpparser (L=0x40000378, dummy=0x0, ud=0x7fffffffdb80) at tarantool/third_party/luajit/src/lj_load.c:41
#17 0x000055555581e199 in lj_vm_cpcall () at buildvm_x86.dasc:1205
#18 0x0000555555838998 in lua_loadx (...) at tarantool/third_party/luajit/src/lj_load.c:58
#19 0x0000555555838e29 in luaL_loadbufferx (...) at tarantool/third_party/luajit/src/lj_load.c:143
#20 0x0000555555838e66 in luaL_loadbuffer (...) at tarantool/third_party/luajit/src/lj_load.c:149
#21 0x0000555555772228 in box_lua_init (L=0x40000378) at tarantool/src/box/lua/init.c:547
#22 0x00005555555954e2 in main (argc=1, argv=0x555555f2ef50) at tarantool/src/main.cc:758
```

**Comment by ligurio** [comment] 2024-08-09 08:45
> The output varies from run to run:

Seems everything fine with patch proposed in #10227.

```lua
Tarantool 3.2.0-entrypoint-192-g7896fe0b26
type 'help' for interactive help
tarantool> \set output lua
true
tarantool> setmetatable({}, { __serialize = function() print('hello') end})
hello
box.NULL
tarantool> setmetatable({}, { __serialize = function() print('hello') end})
hello
box.NULL
tarantool> setmetatable({}, { __serialize = function() print('hello') end})
hello
box.NULL
tarantool> 
```

I'll close as a duplicate of #10177.

**Closed by ligurio** 2024-08-09 08:45 UTC
Labels: bug, lua output, serializers
