### ISSUE TITLE
RIP: MM-replication is dead

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#2975] opened 2017-12-01 09:28 UTC
Config

M1 - server1
M2 - server2

example:
server2 is TEMPORARY down (network, admin, etc)

If admin restarts server1, then server1 is down too.

Admin is forced to break M1<->M2 confuguration.

PS: 1.7.2 works fine

**Comment by rtsisyk** [comment] 2017-12-11 16:01
Duplicate of #2958

**Closed by rtsisyk** 2017-12-11 16:01 UTC
