### ISSUE TITLE
sql: inconsistent identifiers upper-casing in metadata

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4653] opened 2019-11-26 19:31 UTC
I've just noticed a small inconsistency in format of names in meta-information. If a column of resulting set corresponds solely to the identified, then one is upper-cased:

```
tarantool> SELECT a FROM t;
---
- metadata:
  - name: A         <---- Upper-cased
    type: integer
  rows: []
...

```
However, if a column of resulting set is an expression, then the text of expression will contain non upper-cased identifier:

```
tarantool> SELECT a+1 FROM t;
---
- metadata:
  - name: a+1
    type: integer
  rows: []
...
```

On the other hand, for VIEWs names in metadata are upper-cased anyway, even if they are appear in scope of expression:

`CREATE VIEW v15 AS SELECT a + 1 AS x FROM t;
`
```
tarantool> SELECT x+1 FROM v15;
---
- metadata:
  - name: X+1
    type: integer
  rows: []
...
```
We should always return the same case despite VIEW/TABLE relation.

**Comment by kostja** [comment] 2019-12-02 07:50
Upper-casing is a bad idea, even if it is an ANSI. We should be case-insensitive (and if PeterG insists, accent-sensitive, but I doubt anyone wold care), rather than uppercase.

**Comment by pgulutzan** [comment] 2019-12-02 21:44
When there is no AS clause and no view-column-list
and it's not a "single column reference",
this is a matter that in standard SQL is considered to be
"implementation-dependent". So for this particular
situation we could satisfy Konstantin by changing the
view behaviour. Incidentally it's not just the name ...
CREATE TABLE a1 (a STRING PRIMARY KEY);
CREATE VIEW v1 AS SELECT a || a AS "x" FROM a1;
INSERT INTO a1 VALUES ('a');
SELECT upper("x") collate "binary" FROM v1;
The result column name is UPPER("X") COLLATE "BINARY",
I believe that if it were upper("x") collate "binary",
it would not be a disaster.

**Comment by Gerold103** [comment] 2020-03-15 16:31
Should be fixed by https://github.com/tarantool/tarantool/issues/4653.

**Comment by pgulutzan** [comment] 2020-03-24 20:04
@Gerold103: I wonder, perhaps your comment is a typo? This is issue#4653, so I don't see how "Should be fixed by #4653" adds information.

**Comment by Gerold103** [comment] 2020-03-24 20:38
Yeah, sorry. Should be fixed by https://github.com/tarantool/tarantool/issues/3962. Because expressions won't be returned as column names anymore.

**Comment by kyukhin** [comment] 2020-04-22 18:58
Closing as duplicate of #3962

**Closed by kyukhin** 2020-04-22 18:58 UTC
Labels: bug, sql
