### ISSUE TITLE
Performance analysis and relay-from-memory importance

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5207] opened 2020-07-28 08:53 UTC
Need to estimate the importance of relay from memory. Linked issue is #3794

**Comment by cyrillos** [comment] 2020-09-10 14:26
- We’ve done a number of measurements which pointed out that write to the disk is time consuming operation as expected, for this sake WAL functionality is separated into an own thread

 - Disk reading becomes a bottleneck operation when there is a number of outdated (or too slow) relays (remember that anonymous replicas are not even limited in count). Thus we must not move disk read functionality inside WAL thread itself, *never ever*

 - To make a precise measurement we’ve had to implement own telemetry engine to figure out which routines are time consuming ones (system hardware based `perf` utility is not very suitable when you need to estimate time consumption based on some kind of “stages” rather than a particular function with discrete sampling). This engine is still under development and we have to implement a production ready one which would be built-in inside #5289

 - We still need a refactoring for qsync and raft sake #5290

**Comment by cyrillos** [comment] 2020-09-10 14:27
@kyukhin I think we can close this issue

**Comment by kyukhin** [comment] 2020-09-10 20:08
The issue is superseded by #5289 and #5290. Closing.

**Closed by kyukhin** 2020-09-10 20:08 UTC
Labels: replication
