### ISSUE TITLE
Build error (apple/m1)

### ISSUE THREAD

**Issue by dkuk** [tarantool/tarantool#6611] opened 2021-11-16 10:19 UTC
**Bug description**

* OS: MacOS
* OS Version: Monterey (12.0.1 (21A559))
* Architecture: [arm/ apple m1]

2.10.0-beta1

**Steps to reproduce**
 
brew install --HEAD

does not builds
[02.make.log](https://github.com/tarantool/tarantool/files/7545433/02.make.log)

**Comment by Totktonada** [comment] 2021-11-16 10:42
Duplicate of #6576.

**Closed** 2021-11-18 19:41 UTC
Labels: bug
