### ISSUE TITLE
Assertion is triggered: vy_cache_gc_step: Assertion `(*prev_node)->flags & VY_CACHE_RIGHT_LINKED'

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10557] opened 2024-09-11 06:42 UTC
**Bug description**

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-60-ge88d3325e
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

execute test with command-line options below:

```
./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 1000 --test_duration $((1*60*60)) --engine vinyl --verbose --seed 27748
```

**Actual behavior**

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fe1f024526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fe1f02288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fe1f022881b in __assert_fail_base (fmt=0x7fe1f03d01e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x61676725d898 "(*prev_node)->flags & VY_CACHE_RIGHT_LINKED", 
    file=file@entry=0x61676725d809 "./src/box/vy_cache.c", line=line@entry=193, 
    function=function@entry=0x61676725dcf0 <__PRETTY_FUNCTION__.31> "vy_cache_gc_step") at ./assert/assert.c:94
#6  0x00007fe1f023b507 in __assert_fail (assertion=0x61676725d898 "(*prev_node)->flags & VY_CACHE_RIGHT_LINKED", 
    file=0x61676725d809 "./src/box/vy_cache.c", line=193, function=0x61676725dcf0 <__PRETTY_FUNCTION__.31> "vy_cache_gc_step")
    at ./assert/assert.c:103
#7  0x0000616766c4224a in vy_cache_gc_step (env=0x6167681040b8) at /home/ubuntu/tarantool/src/box/vy_cache.c:193
#8  0x0000616766c4239b in vy_cache_gc (env=0x6167681040b8) at /home/ubuntu/tarantool/src/box/vy_cache.c:218
#9  0x0000616766c424dc in vy_cache_add (cache=0x616768146110, curr=..., prev=..., is_first=false, key=..., order=ITER_GT)
    at /home/ubuntu/tarantool/src/box/vy_cache.c:249
#10 0x0000616766c34bb1 in vy_read_iterator_cache_add (itr=0x7fe0df88e200, entry=...)
    at /home/ubuntu/tarantool/src/box/vy_read_iterator.c:981
#11 0x0000616766bf4d98 in vinyl_iterator_primary_next (base=0x7fe0df88e180, ret=0x7fe135180c20)
    at /home/ubuntu/tarantool/src/box/vinyl.c:3727
#12 0x0000616766b89777 in iterator_next (it=0x7fe0df88e180, ret=0x7fe135180c20) at /home/ubuntu/tarantool/src/box/index.cc:639
#13 0x0000616766cc3896 in box_select (space_id=512, index_id=0, iterator=6, offset=30, limit=227, key=0x7fe137914241 "\327\001", 
    key_end=0x7fe137914289 'P' <repeats 200 times>..., packed_pos=0x7fe135180cf8, packed_pos_end=0x7fe135180d00, update_pos=false, 
    port=0x7fe135180d10) at /home/ubuntu/tarantool/src/box/box.cc:3875
#14 0x0000616766ddb958 in lbox_select (L=0x40b75b18) at /home/ubuntu/tarantool/src/box/lua/misc.cc:445
#15 0x0000616766ea9277 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#16 0x0000616766eb6dbb in lua_pcall (L=0x40b75b18, nargs=4, nresults=-1, errfunc=0)
    at /home/ubuntu/tarantool/third_party/luajit/src/lj_api.c:1173
#17 0x0000616766e1a7c0 in luaT_call (L=0x40b75b18, nargs=4, nreturns=-1) at /home/ubuntu/tarantool/src/lua/utils.c:695
#18 0x0000616766e0f4ec in lua_fiber_run_f (ap=0x7fe15588f9e0) at /home/ubuntu/tarantool/src/lua/fiber.c:435
#19 0x0000616766b68143 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x616766e0f42f <lua_fiber_run_f>, 
    ap=0x7fe15588f9e0) at /home/ubuntu/tarantool/src/lib/core/fiber.h:1324
#20 0x0000616766e4b35b in fiber_loop (data=0x0) at /home/ubuntu/tarantool/src/lib/core/fiber.c:1162
#21 0x000061676722a498 in coro_init () at /home/ubuntu/tarantool/third_party/coro/coro.c:108
```

tarantool binary + log + workdir content + coredump: https://drive.google.com/file/d/10tTyTf1Z9u_2EIRo6V8FzOYVnzJU6jKZ/view?usp=sharing

**Expected behavior**

no assert violation

**Comment by locker** [comment] 2024-09-20 09:13
Tarantool crashed because of inconsistencies in the tuple cache. Highly likely to be a duplicate of #10558.

**Closed by locker** 2024-09-20 09:13 UTC
Labels: bug, vinyl
