### ISSUE TITLE
sql: wrong data in _sql_stat* tables leads to SEGMENTATION FAULT

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#3866] opened 2018-12-08 12:20 UTC
Tarantool version: 2.1

OS version: Ubuntu 16.04.5 LTS

Bug description: If wrong data added into empty "_sql_stat1" or "_sql_stat4" table then ANALYZE can invoke segfault.

Steps to reproduce:
box.cfg{}
box.space._sql_stat1:insert{'asd', 'fds', 'asd'}
box.sql.execute('create table t (i int primary key, a int)')
box.sql.execute('analyze t')

```bash
tarantool> box.sql.execute('analyze t')
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x128
  context: 0x7f788a81f640
  siginfo: 0x7f788a81f770
  rax      0x128              296
  rbx      0x4138b4d0         1094235344
  rcx      0x128              296
  rdx      0x1265fd           1205757
  rsi      0x128              296
  rdi      0x128              296
  rsp      0x7f788a81fcf8     140155696577784
  rbp      0x7f788a81fd70     140155696577904
  r8       0x0                0
  r9       0x1                1
  r10      0x0                0
  r11      0x0                0
  r12      0x7d000e           8192014
  r13      0x0                0
  r14      0x4138c000         1094238208
  r15      0x4ff0d6           5238998
  rip      0x7f7891bab746     140155817736006
  eflags   0x10297            66199
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x128              296
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
```

**Comment by Korablev77** [comment] 2020-03-31 16:45
@kyukhin We've temporary disabled ANALYZE command alongside with removing stat spaces (#4069). So it is blocked/unconfirmed until we get back analyze and spaces containing statistics.

**Comment by igormunkin** [comment] 2022-06-23 10:47
Ticket looks irrelevant since there are no `_sql_stat*` spaces since 2.2.0-108-gec93b4a5 (ec93b4a). Closing with wontifx reason.

**Closed by igormunkin** 2022-06-23 10:47 UTC
Labels: crash, bug, sql, blocked
