### ISSUE TITLE
Large lua string allocation bug

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#5790] opened 2021-02-04 17:40 UTC
**Bug description**

```
tarantool> a = ('x'):rep(1024*1024*10000)
---
...
tarantool> #a
---
- 0
...
tarantool> a = ('x'):rep(1024*1024*1000)
---
- error: not enough memory
...
tarantool> a = ('x'):rep(1024*1024)
---
...
tarantool> #a
---
- 1048576
...
```

**Expected**

```
a = ('x'):rep(1024*1024*10000)
error: not enough memory
```

**Other**

- luajit the same case and result

```lua
$ luajit
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> x=('x'):rep(10000*1024*1024)
> x=('x'):rep(1000*1024*1024)
not enough memory
> x=('x'):rep(100*1024*1024)
> print(#x)
104857600
>
```

**Where is the error?**

Tut' https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lib_string.c#L90

**Comment by igormunkin** [comment] 2021-02-04 19:28
Here is one more case found by @Buristan.
```bash
$ luajit -e 'print(("x"):rep(1024):sub(1024*1024*1024*2):len())'
1024
$ luajit -e 'print(("x"):rep(1024):sub(1024*1024*1024):len())' 
0
```

The root cause relates to integer convertion of Lua numeric values in scope of `lj_lib_checkint`, that yields a 32-bit integer value. The compiler machinery is also affected, so this issue leads to a project-wide audit of "size" defining parameters.

**Comment by Buristan** [comment] 2021-03-12 09:08
Here is another one example, that looks like the same issue, but it is not:
```bash
$ lua    -e 'n = 0xfffffffe u = -0x80000000 t = {} t[u] = "surprise" t[-2] = -2 t[-1] = -1  t[0]  = 0  t[n] = "test" print(unpack(t, n, n+2))'
-2      -1      0

$ luajit -e 'n = 0xfffffffe u = -0x80000000 t = {} t[u] = "surprise" t[-2] = -2 t[-1] = -1  t[0]  = 0  t[n] = "test" print(unpack(t, n, n+2))'
surprise
```

The reason is inside `lj_num2int` used `cvttsd2si` instruction:
```
(gdb) list
243       if (LJ_LIKELY(tvisint(o))) {
244         return intV(o);
245       } else {
246         int32_t i = lj_num2int(numV(o));
247         if (LJ_DUALNUM) setintV(o, i);
248         return i;
249       }
250     }
251
252     int32_t lj_lib_optint(lua_State *L, int narg, int32_t def)
(gdb) p /x i
$32 = 0x80000000
(gdb) p /x lj_num2int(o->n)
33 = 0xffffffff
```

According to [this](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf) section of Intel® 64 and IA-32 Architectures Software Developer’s Manual Instruction Set Reference.

> When a conversion is inexact, the value returned is rounded according to the rounding control bits in the MXCSR register.
>
> If a converted result exceeds the range limits of signed doubleword integer (in non-64-bit modes or 64-bit mode with REX.W/VEX.W/EVEX.W=0), the floating-point invalid exception is raised, and if this exception is masked, the indefinite integer value (80000000H) is returned.
>
> If a converted result exceeds the range limits of signed quadword integer (in 64-bit mode and REX.W/VEX.W/EVEX.W = 1), the floating-point invalid exception is raised, and if this exception is masked, the indefinite integer value (80000000_00000000H) is returned.

**Comment by Buristan** [comment] 2021-03-22 10:06
Ticket in LuaJIT LuaJIT/LuaJIT#674 to obtain Mike's feedback.

**Comment by filonenko-mikhail** [comment] 2021-03-29 08:41
Seems Mike's feedback is that `UB`

**Comment by igormunkin** [comment] 2021-07-22 10:40
Considering the resolution in LuaJIT/LuaJIT#674, I would rather close this ticket with wontfix reason (or even luajit misuse label).

If somebody need a workaround to try building such a huge strings, here you are:
```
tarantool> a = ('x'):rep(1024*1024*10000)
---
...

tarantool> #a
---
- 0
...

tarantool> b = ('x'):rep(1024*1024):rep(10000)
---
- error: not enough memory
...

```

**Closed by igormunkin** 2021-07-22 10:40 UTC
Labels: bug, complicated, luajit, teamL
