### ISSUE TITLE
FreeBSD: Crash when assign with incorrect ip address

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#777] opened 2015-03-31 12:05 UTC
Crash tarantool if assign http on incorrect IP address. 

On Linux checking is ok:
```
2015-03-31 11:59:49.510 [2399] main/101/app.lua I> ready to accept requests
2015-03-31 11:59:49.514 [2399] main/101/app.lua F> /usr/local/share/lua/5.1/http/server.lua:1078: Can't create tcp_server: Cannot assign requested address
```

On FreeBSD has a core dump:
```
2015-03-31 15:00:43.650 [87989] main/101/app.lua I> ready to accept requests
Segmentation fault
Current time: 1427803243
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
```

GDB output for run on incorrect ip address.
```
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) core-file tarantool.core 
Core was generated by `tarantool'.
Program terminated with signal 6, Aborted.
Reading symbols from /usr/local/lib/libreadline.so.6...done.
Loaded symbols for /usr/local/lib/libreadline.so.6
Reading symbols from /lib/libncurses.so.8...done.
Loaded symbols for /lib/libncurses.so.8
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/lib/libssl.so...done.
Loaded symbols for /usr/lib/libssl.so
Reading symbols from /lib/libcrypto.so.7...done.
Loaded symbols for /lib/libcrypto.so.7
Reading symbols from /home/vg/.luarocks/lib/lua/5.1/http/lib.so...done.
Loaded symbols for /home/vg/.luarocks/lib/lua/5.1/http/lib.so
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x0000000801cb16ca in thr_kill () from /lib/libc.so.7
[New Thread 802408c00 (LWP 100343/tarantool)]
[New Thread 802408800 (LWP 100203/tarantool)]
[New Thread 802408400 (LWP 100199/tarantool)]
[New Thread 802408000 (LWP 100157/tarantool)]
[New Thread 802407c00 (LWP 100155/tarantool)]
[New Thread 802407800 (LWP 100143/tarantool)]
[New Thread 802407400 (LWP 100120/tarantool)]
[New Thread 802406400 (LWP 100589/tarantool)]
(gdb) thread apply all bt

Thread 8 (Thread 802406400 (LWP 100589/tarantool)):
#0  0x0000000801cb16ca in thr_kill () from /lib/libc.so.7
#1  0x0000000801d86149 in abort () from /lib/libc.so.7
#2  0x0000000000421795 in sig_fatal_cb (signo=11)
    at /home/vg/Develop/Tarantool/tarantool/src/tarantool.cc:212
#3  0x000000080111b47a in swapcontext () from /lib/libthr.so.3
#4  0x000000080111b062 in sigaction () from /lib/libthr.so.3
#5  <signal handler called>
#6  0x000000080182bc1e in __cxa_end_catch () from /lib/libcxxrt.so.1
#7  0x00000000004a9371 in lbox_call (L=0x1378, nargs=0, nreturns=0) at utils.h:445
#8  0x00000000004a9114 in run_script (ap=0x803000150)
    at /home/vg/Develop/Tarantool/tarantool/src/lua/init.cc:441
#9  0x00000000004b9187 in fiber_loop (data=0x0)
    at /home/vg/Develop/Tarantool/tarantool/src/fiber.cc:402
#10 0x00000000005abe94 in coro_init ()
    at /home/vg/Develop/Tarantool/tarantool/third_party/coro/coro.c:96
#11 0x000000000041f304 in geteuid@plt ()
#12 0x5050505050505050 in ?? ()
#13 0x5050505050505050 in ?? ()
#14 0x0000000000854ad0 in users ()
#15 0x0000000000854ad0 in users ()
#16 0x0000000000001000 in ?? ()
#17 0x50500100eec0ffee in ?? ()
#18 0x5050505000000050 in ?? ()
#19 0x0000000300000001 in ?? ()
#20 0x0000000200000140 in ?? ()
#21 0x0000000000472702 in MemtxTree::replace (this=Cannot access memory at address 0xffffffffffffffd8
)
    at /home/vg/Develop/Tarantool/tarantool/src/box/memtx_tree.cc:243
Previous frame inner to this frame (corrupt stack?)

Thread 7 (Thread 802407400 (LWP 100120/tarantool)):
#0  0x00000008011218cc in __error () from /lib/libthr.so.3
#1  0x000000080111fd8e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x0000000000430b7b in wal_writer_pop (writer=0x8561e0, input=0x7fffffbfdec8)
    at /home/vg/Develop/Tarantool/tarantool/src/box/recovery.cc:837
#3  0x0000000000431fff in wal_writer_thread (worker_args=0x80247c000)
    at /home/vg/Develop/Tarantool/tarantool/src/box/recovery.cc:978
#4  0x00000000004ba1b3 in cord_thread_func (p=0x80301f7c0)
    at /home/vg/Develop/Tarantool/tarantool/src/fiber.cc:609
#5  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#6  0x0000000000000000 in ?? ()

Thread 6 (Thread 802407800 (LWP 100143/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024aa1c0) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 5 (Thread 802407c00 (LWP 100155/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024aa380) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 4 (Thread 802408000 (LWP 100157/tarantool)):
---Type <return> to continue, or q <return> to quit---
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024aa540) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 3 (Thread 802408400 (LWP 100199/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024aa700) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 2 (Thread 802408800 (LWP 100203/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024aa8c0) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 1 (Thread 802408c00 (LWP 100343/tarantool)):
#0  0x00000008011218cc in __error () from /lib/libthr.so.3
#1  0x000000080111fd8e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x00000000004ce93e in etp_proc (thr_arg=0x80241c310) at eio.c:2190
#3  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#4  0x0000000000000000 in ?? ()
#0  0x0000000801cb16ca in thr_kill () from /lib/libc.so.7
(gdb) 
```

**Comment by kostja** [comment] 2015-04-05 17:27
Please add a test case.

**Comment by zloidemon** [comment] 2015-04-06 10:04
This code will crash tarantool:

```
#!/usr/bin/env tarantool

box.cfg{slab_alloc_arena=0.2}
hosts = box.space.hosts
if not hosts then
    hosts = box.schema.create_space('hosts')
    hosts:create_index('primary',
            {parts = {1, 'STR'}})
end

local function handler(self)
    local host = self.peer.host
    local response = {
        host = host;
        counter = hosts:inc(host);
    }
    return self:render{ json = response }
end

httpd = require('http.server')

server = httpd.new('127.0.0.1', 8080)
server:route({ path = '/' }, handler)
server:start()

print('___CRASH____')

crash = httpd.new('8.8.8.8', 8080)
crash:route({ path = '/' }, handler)
crash:start()
```

**Comment by rtsisyk** [comment] 2015-06-25 10:54
Duplicate of #786

**Closed by rtsisyk** 2015-06-25 10:54 UTC
Labels: crash
