### ISSUE TITLE
Tarantool 1.9.1 http.client throws exception on https://fcm.googleapis.com/fcm/send

### ISSUE THREAD

**Issue by khaliullov** [tarantool/tarantool#3567] opened 2018-07-25 09:03 UTC
httpc throws exception CURLE_RECV_ERROR (56) "Failure when receiving data from the peer" when sending request to Google FCM server.
```bash
$ cat /etc/os-release | grep -i version=
VERSION="16.04.4 LTS (Xenial Xerus)"
$ apt list --installed | grep tarantool
tarantool/xenial,now 1.7.6.25.g6849d9a-1 amd64 [installed]
tarantool-common/xenial,now 1.7.6.25.g6849d9a-1 all [installed,automatic]
tarantool-dev/xenial,now 1.7.6.25.g6849d9a-1 amd64 [installed,automatic]
tarantool-expirationd/xenial,now 1.0.21-1 all [installed]
tarantool-mqtt/xenial,now 1.2.10-1 amd64 [installed]
```
**Steps to reproduce**:
```lua
http = require('http.client').new()
result = http:request('POST', 'https://fcm.googleapis.com/fcm/send', '{"to":"REDACTED","data":{"test":"OK"}}', { headers =  {['Authorization'] = 'key=REDACTED',  ['Content-Type'] = 'application/json' }})
---
- error: 'curl: Failure when receiving data from the peer'
...
```

if run the same request via curl command all works fine:
```bash
$ curl -H "Authorization: key=REDACTED" -d ' {"to":"REDACTED","data":{"test":"OK"}}' -H "Content-Type: application/json" https://fcm.googleapis.com/fcm/send
{"multicast_id":6661780438845102507,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}
```

**Comment by Totktonada** [comment] 2018-07-25 09:36
I got 401 from tarantool on your example on Gentoo. My libcurl version:

```
$ curl --version
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.0.2o zlib/1.2.11 nghttp2/1.32.0
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```

I suggests to add `verbose` option to http:request and check the output.

**Comment by khaliullov** [comment] 2018-07-25 10:12
@Totktonada this reproduced on Ubuntu 16.04. I've mentioned that in ticket.
for example, docker image tarantool/tarantool (Alpine Linux) works fine.

**Comment by khaliullov** [comment] 2018-07-25 10:39
steps to reproduce via Docker:
```bash
$ docker run --rm -it ubuntu:16.04 /bin/bash
# apt-get update
# apt-get install -y curl apt-transport-https gnupg2
# curl http://download.tarantool.org/tarantool/1.7/gpgkey | apt-key add -
# echo 'deb http://download.tarantool.org/tarantool/1.7/ubuntu/ xenial main' | tee /etc/apt/sources.list.d/tarantool_1_7.list
# apt-get update
# apt-get -y install tarantool
# tarantool
tarantool> http = require('http.client').new()
tarantool> result = http:request('POST', 'https://fcm.googleapis.com/fcm/send', '{"to":"REDACTED","data":{"test":"OK"}}', { headers =  {['Authorization'] = 'key=REDACTED',  ['Content-Type'] = 'application/json'}})
---
- error: 'curl: Failure when receiving data from the peer'
...
```

**Comment by kyukhin** [comment] 2018-08-07 18:52
Tarantool 1.7.6 is not supported anymore.
Could you please try to reproduce your issue w/ 1.9 +

**Comment by khaliullov** [comment] 2018-08-14 15:13
@kyukhin do you need any additional feedback or this is quite enough?

**Comment by khaliullov** [comment] 2018-09-25 10:14
@Totktonada @kyukhin any progress? Should I add something else?

**Comment by Totktonada** [comment] 2019-03-07 17:07
It seems that the problem is because a tarantool package is built against libcurl with GnuTLS backend. Don't sure whether we able to change it in a binary distro.

**Comment by kyukhin** [comment] 2019-07-18 14:57
Closing then.

**Closed by kyukhin** 2019-07-18 14:57 UTC
Labels: bug, need feedback
