### ISSUE TITLE
no ability to dynamically update Lua modules written in C ('*.so' modules)

### ISSUE THREAD

**Issue by man0xff** [tarantool/tarantool#1579] opened 2016-06-29 13:11 UTC
package.loaded.mymodule = nil
    mymodule = require('mymodule')

does not reload '*.so' module

**Comment by rtsisyk** [comment] 2016-06-30 08:18
Duplicate of #910 
#910 re-scheduled to 1.7.x.

**Closed by rtsisyk** 2016-06-30 08:18 UTC
Labels: duplicate

**Comment by bigbes** [comment] 2016-06-30 20:28
It's not duplicate, since it's about Lua C modules, and #910 is about
native C stored procedures, no?

With best regards, Eugene.

2016-06-30 11:18 GMT+03:00 Roman Tsisyk <notifications@github.com>:
