### ISSUE TITLE
fiber is switched while running the compiled code

### ISSUE THREAD

**Issue by neopaf** [tarantool/tarantool#8832] opened 2023-07-03 10:20 UTC
**Bug description**

* OS: linux
* OS Version: 4.18.0-348.el8.0.2.x86_64 
* Architecture: x86_64

```
Tarantool 2.10.6-0-g3990f976b
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: GNU-8.5.0
C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.10.6=. -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.10.6=. -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```

**Steps to reproduce**

Run two in parallel:
```lua
latch:lock()
```

**Actual behavior**

crashes with this in log
```
abc_cluster.storage-12.log:2023-06-23 08:44:25.124 [3021311] main/207/main C> fiber 207 is switched while running the compiled code (it's likely a function with a yield underneath called via LuaJIT FFI)
```

**Expected behavior**

Keeps going.

**Comment by neopaf** [comment] 2023-07-03 10:21
I'm not sure if fixes from https://github.com/tarantool/tarantool/issues/1700 were properly merged to this branch.

**Comment by igormunkin** [comment] 2023-07-04 08:58
@neopaf, thanks for your report! Could you please provide a more precise scenario to reproduce, since at least the snippet is not valid Lua code and "run two in parallel" is quite misguiding whether you're using two Tarantool instances, or two interactive consoles.

**Comment by neopaf** [comment] 2023-07-04 09:31
Igor, alas, I can't find a good small snippet. Would ask a colleague to improve on this report.

Two interactive consoles to 1 instance.

**Comment by neopaf** [comment] 2023-07-04 09:47
my colleague can't find time to detail this :(
we're considering to switch to `fiber:cond` similar mechanism, that people say work more reliably.

suggesting to close this problem, Igor. without good repro case it's useless :(

**Comment by igormunkin** [comment] 2023-07-04 11:49
@neopaf, AFAIU, `latch:lock()` is the code in your project? There should be a backtrace with diagnostics nearby the message you mentioned in the issue: I hope this will help you with investigation. You should check whether you're using something that makes `fiber_yield` within the function being invoked via FFI: it's forbidden since 2.6.1 (and has been never allowed). I doubt there is a related mistake in 2.10, but bugs happen.

If `latch:lock()` is the 3rd party code, I recommend to file a bug against that repo (you can also summon me there).

I close the issue for now, but feel free to reopen it, if you'll face the problem again.

**Closed by igormunkin** 2023-07-04 11:49 UTC
Labels: bug, needs feedback
