### ISSUE TITLE
IPROTO hangs on slow CALL queries

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1889] opened 2016-11-02 08:56 UTC
```lua
#!/usr/bin/tarantool


local fio = require 'fio'
local net = require 'net.box'
local fiber = require 'fiber'

local dir = fio.tempdir()

box.cfg {
    listen      = 9950,
    wal_dir     = dir,
    logger      = fio.pathjoin(dir, 'tarantool.log')
}

box.schema.user.grant('guest', 'read,write,execute', 'universe');

local nbox = require('net.box').new(9950)

if nbox:ping() then
    print("net.box ping ok")
end

function sleep()
    if math.random() * 100 < 1 then
        fiber.sleep(3)
    else
        fiber.sleep(.1)
    end
end

local count = 0

for i = 1, 200 do
    fiber.create(function()
        while true do
            count = count + 1
            nbox:call('sleep')
        end
    end)
end

local begin = fiber.time()
local started = fiber.time()
local total = 0
while true do
    fiber.sleep(0.5)

    local rps = count / (fiber.time() - started)
    started = fiber.time()
    total = total + count
    local avg = total / (fiber.time() - begin)
    count = 0
    print(string.format("RPS: %8.3f, AVG: %8.3f", tostring(rps), tostring(avg)))

    if fiber.time() - begin > 60 then
        break
    end
end

fio.rmdir(dir)
os.exit(0)
```

```
RPS: 1971.059, AVG: 1971.059
RPS:  175.912, AVG: 1073.931
RPS:    0.000, AVG:  715.889
RPS:    0.000, AVG:  536.824
RPS:    0.000, AVG:  429.440
RPS:    0.000, AVG:  357.831
RPS:  407.466, AVG:  364.921
RPS:  954.091, AVG:  438.607
RPS:    0.000, AVG:  389.877
RPS:    0.000, AVG:  350.890
RPS:    0.000, AVG:  318.994
RPS:    0.000, AVG:  292.397
RPS:    5.997, AVG:  270.386
RPS: 1348.793, AVG:  347.378
RPS:    0.000, AVG:  324.222
RPS:    0.000, AVG:  303.953
RPS:    0.000, AVG:  286.072
RPS:    0.000, AVG:  270.170
RPS:    0.000, AVG:  255.953
RPS: 1194.003, AVG:  302.866
RPS:  163.885, AVG:  296.253
RPS:    0.000, AVG:  282.792
RPS:    0.000, AVG:  270.499
RPS:    0.000, AVG:  259.222
RPS:    0.000, AVG:  248.863
RPS:  411.415, AVG:  255.116
RPS: 1348.483, AVG:  295.602
RPS:    0.000, AVG:  285.039
RPS:    0.000, AVG:  275.211
RPS:    0.000, AVG:  266.036
RPS:    0.000, AVG:  257.458
RPS:    3.998, AVG:  249.543
RPS: 1579.394, AVG:  289.805
RPS:  169.935, AVG:  286.283
RPS:    0.000, AVG:  278.102
RPS:    0.000, AVG:  270.370
RPS:    0.000, AVG:  263.063
RPS:    0.000, AVG:  256.136
RPS:  409.733, AVG:  260.072
RPS:  952.108, AVG:  277.385
RPS:    0.000, AVG:  270.620
```

Reported by @unera

**Comment by bigbes** [comment] 2016-11-02 12:38
Duplicate of https://github.com/tarantool/tarantool/issues/946

**Closed** 2016-11-10 14:31 UTC
Labels: duplicate
