### ISSUE TITLE
Unable to build tarantool on macOS

### ISSUE THREAD

**Issue by monoflash** [tarantool/tarantool#2102] opened 2017-02-23 19:12 UTC
```
...
[ 63%] Building C object src/CMakeFiles/tarantool.dir/__/third_party/libutil_freebsd/pidfile.c.o
[ 64%] Linking CXX executable tarantool
Undefined symbols for architecture x86_64:
  "_rl_completion_suppress_append", referenced from:
      _console_completion_handler in libbox.a(console.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/tarantool] Error 1
make[1]: *** [src/CMakeFiles/tarantool.dir/all] Error 2
make: *** [all] Error 2
```

**uname -a**

```
Darwin macOS.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 21:39:33 PST 2016; root:xnu-3789.41.3~2/RELEASE_X86_64 x86_64
```

Verbose version:
```
...
[ 64%] Linking CXX executable tarantool
cd /tarantool/src && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/tarantool.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-unused-value -Wno-char-subscripts -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pagezero_size 10000 -image_base 100000000         -Wl,-exported_symbols_list,/tarantool/extra/exports.Darwin CMakeFiles/tarantool.dir/main.cc.o CMakeFiles/tarantool.dir/title.c.o CMakeFiles/tarantool.dir/__/third_party/libutil_freebsd/flopen.c.o CMakeFiles/tarantool.dir/__/third_party/libutil_freebsd/pidfile.c.o  -o tarantool  box/libbox.a libserver.a libcore.a ../libmisc.a lib/bitset/libbitset.a lib/csv/libcsv.a ../third_party/luajit/src/libluajit.a lib/msgpuck/libmsgpuck.a ../libeio.a ../libgopt.a ../third_party/libyaml/libyaml.a /usr/lib/libreadline.dylib /usr/lib/libcurses.dylib /usr/lib/libform.dylib /opt/local/lib/libssl.dylib /opt/local/lib/libcrypto.dylib ../libzstd.a lib/salad/libsalad.a lib/small/libsmall.a -lpthread ../libev.a -lm ../libcoro.a liburi.a lib/bit/libbit.a 
Undefined symbols for architecture x86_64:
  "_rl_completion_suppress_append", referenced from:
      _console_completion_handler in libbox.a(console.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/tarantool] Error 1
make[1]: *** [src/CMakeFiles/tarantool.dir/all] Error 2
make: *** [all] Error 2
```

Why did you not publish the binaries version in the releases?
That does docker. Conveniently.

**Comment by kostja** [comment] 2017-02-23 19:24
Please specify the server version. Are you using brew?

**Comment by monoflash** [comment] 2017-02-23 19:35
I don't use brew, i use port. (brew is not convenient and creates a lot of debris, is difficult to clean os.)
This in not a server, this in workstation.
OS is macOS Sierra 10.12.3 (16D30a)
Above I wrote a result of the command `uname -a`

**Comment by monoflash** [comment] 2017-02-23 19:47
I forgot to say. This is the result of the build from source.

Commands in order of execution:
```
git clone https://github.com/tarantool/tarantool.git .
git submodule init
git submodule update --init --recursive
cmake .
make
```

**Comment by bigbes** [comment] 2017-02-23 22:39
Try to install readline package with headers/library and provide it to to cmake. using `READLINE_ROOT` variable.

**Comment by monoflash** [comment] 2017-02-24 16:04
It did not resolve problem, I see the same error

**Comment by bigbes** [comment] 2017-02-24 16:46
Please, provide more information. Cmake log, where readline is installed.

**Comment by monoflash** [comment] 2017-02-24 22:02
I don't know where to look this log.
I do not program in C/C++ and I don't know cmake.
That's why I wrote the above, if be you have done together with the release version of binaries version, it's be to convenient, download binary file and not to suffer with the compilation from source.

**Comment by kostja** [comment] 2017-02-25 16:37
Please join telegram or slcak  where we can give you proper support. If you can't C, finding out what went wrong over github issues, minding the time zone difference is going to be painful.

**Comment by rtsisyk** [comment] 2017-02-28 18:50
Duplicate of #1644. Please try to install GNU libreadline from homebrew.

**Comment by rtsisyk** [comment] 2017-02-28 18:51
BTW, it would be nice to support systems without bloated GNU readline.

**Comment by kostja** [comment] 2017-04-17 17:05
Closing as duplicate.

**Closed by kostja** 2017-04-17 17:05 UTC
Labels: build, need feedback, osx
