### ISSUE TITLE
 Fix W611 warnings in test/sql-tap

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5176] opened 2020-07-16 09:53 UTC
## Bug description:

there are a bunch of warnings in `test/sql-tap` supressed in `.luacheckrc`.
it would be nice to fix them.

**Total: 1389 warnings / 0 errors in 264 files**

**Comment by Totktonada** [comment] 2022-04-26 17:16
Duplicate of #5739.

Resolved in bcc964e276c379dbaf72b05aaceda843940e7afd.

**Closed by Totktonada** 2022-04-26 17:16 UTC
Labels: lua, good first issue, teamL
