### ISSUE TITLE
Consider improving testing engine for better usability on test updates

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#4654] opened 2019-11-27 13:12 UTC
Currently when one update a test he has to move `reject` file to `result` manually. It would be much more convenient to automatize this action.

This feature is not anyhow urgent so I made a bug just to not forget as @Totktonada asked.

**Comment by Totktonada** [comment] 2019-11-28 14:55
Maybe we should add one option for updating result files and creating new ones (#4258).

**Comment by ligurio** [comment] 2020-04-21 19:29
[Tarantool-patches] [PATCH v1] Add option to update file with reference output
https://lists.tarantool.org/pipermail/tarantool-patches/2020-March/015077.html

**Comment by ligurio** [comment] 2020-05-19 10:35
[Tarantool-patches] [PATCH v2] Add option to update file with reference output
https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016853.html

**Comment by ligurio** [comment] 2020-05-28 12:08
Duplicate of #194

**Closed by ligurio** 2020-05-28 12:08 UTC
Labels: feature, qa, test-run.py
