### ISSUE TITLE
Vinyl tx manager dirty reads, and difference with memtx tx manager

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5522] opened 2020-11-15 17:25 UTC
Option `memtx_use_mvcc_engine` is supposed to turn on transaction isolation for memtx engine. And it seems to be working. So until a change is committed, it is not visible.

This seems not to be the case for vinyl. Here the dirty reads still happen. Here is an example using synchronous replication:

```Lua
-- Instance 1

-- Step 1
box.cfg{
    listen = 3313,
    replication = {'127.0.0.1:3313', '127.0.0.1:3314'},
    memtx_use_mvcc_engine = true,
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
}
box.schema.user.grant('guest', 'super')

-- Step 3
s = box.schema.create_space('test', {is_sync = true, engine = 'vinyl'})
_ = s:create_index('pk')
s:replace{1}

-- Step 6
fiber = require('fiber')
f = fiber.create(function() s:replace{2} end)
f:status() -- Suspended

-- Step 7
s:get{2} -- !!! THIS SHOULD NOT RETURN ANYTHING, BUT IT RETURNS {2}.
```

```Lua
-- Instance 2

-- Step 2
box.cfg{
    listen = 3314,
    replication = {'127.0.0.1:3313', '127.0.0.1:3314'},
    read_only = true,
    memtx_use_mvcc_engine = true,
}

-- Step 4
box.space.test:get{1} -- Return {1}, ok.

-- Step 5
os.exit(1)
```
The bug is in the step 7. All works as expected when I change space engine to memtx. So for vinyl there is no any way to turn dirty reads off. Honestly, vinyl tx manager is so intricated, that I have no idea how would it behave if I would try to read {2} and change something in a transaction. Would it conflict or not? Anyway, the behaviour above seems to be a bug. It should be at least the same for vinyl and memtx, and ideally - without dirty reads.

The same happens on alive replicas, if there is more than 1.

**Comment by locker** [comment] 2021-08-25 16:20
@Gerold103 The reproducer from the ticket description doesn't work: on step 3 I get an error:

```
tarantool> s:replace{1}
---
- error: The synchronous transaction queue doesn't belong to any instance
...
```

**Comment by olegrok** [comment] 2021-08-25 16:23
@locker

Recently, I faced the same issue.

```
> Oleg Babin:
The synchronous transaction queue doesn't belong to any instance  Но как такое возможно?

> Sergey Petrenko:
box.ctl.promote() теперь надо звать на узле который будет мастером синхры

> Oleg Babin:
Т.е. в общем случае мой единственный rw инстанс в репликасете - это не мастер?

> Sergey Petrenko:
Не, рв отдельно, «владелец лимба» - отдельно
```

Seems you need to add box.ctl.promote() on the first instance.

**Comment by locker** [comment] 2021-08-25 16:29
@olegrok box.ctl.promote helped. Thank you!

**Comment by locker** [comment] 2021-08-25 16:43
So I checked:

1. In memtx, read doesn't return a dirty value outside a transaction, but it does return a dirty value inside a transaction (even read-only) - try to surround s:get with box.begin/commit.
2. In vinyl, read always returns a dirty value, both inside and outside a transaction.

We can make vinyl behave exactly as memtx - it should be fairly easy (use committed read view for iterators outside transactions). Still, this is a little bit inconsistent that a read-only transaction and a standalone statement behave differently.

In my understanding, we can't possibly avoid dirty reads in rw transactions, neither in memtx nor in vinyl, because it conflicts with the cascading rollback paradigm: if a transaction doesn't see a dirty value, which was set by another transaction currently blocked on WAL, we will need to abort it after the dirty value is written to WAL (i.e. ceases to be dirty), but the transaction that saw the dirty value can already start writing its own changes to WAL, in which case we can't abort it.

And there's no way to differentiate rw transactions from ro (a transaction that is currently ro can become an rw).

@alyapunov WDYT?

**Comment by locker** [comment] 2021-11-03 08:06
There's no agreement on the API. @alyapunov described possible ways in [this](https://hackmd.io/T9IZSPB8QhWjVuw7fFuiNw) document.

**Comment by locker** [comment] 2022-04-01 10:42
See https://github.com/tarantool/tarantool/pull/6946

**Comment by locker** [comment] 2022-06-15 10:00
I started working on this issue before transaction isolation levels were introduced. This might be useful: https://github.com/locker/tarantool/commits/gh-5522-vinyl-disable-dirty-reads-in-ro-transactions

**Closed** 2022-10-14 10:23 UTC
Labels: bug, vinyl, memtx, qsync replication, 2.10
