### ISSUE TITLE
Freeze tarantool after run box.cfg{} on OSX and FreeBSD

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#764] opened 2015-03-19 21:35 UTC
If run tarantool by cansole and run box.cfg{}, then you can not do anything because console will freeze.

```
%> lldb tarantool

(lldb) target create "tarantool"
Current executable set to 'tarantool' (x86_64).
(lldb)
Current executable set to 'tarantool' (x86_64).
(lldb) r
Process 44286 launched: '/Users/vg/opt/bin/tarantool' (x86_64)
tarantool: version 1.6.4-490-g3dee846
type 'help' for interactive help
tarantool> box.cfg{}
2015-03-20 00:21:41.594 [44286] main/101/interactive C> version 1.6.4-490-g3dee846
2015-03-20 00:21:41.595 [44286] main/101/interactive C> log level 5
2015-03-20 00:21:41.595 [44286] main/101/interactive I> mapping 1073741824 bytes for a shared arena...
2015-03-20 00:21:41.596 [44286] main/101/interactive I> initializing an empty data directory
2015-03-20 00:21:41.608 [44292] snap/101/dumper I> creating `./00000000000000000000.snap.inprogress'
2015-03-20 00:21:41.608 [44292] snap/101/dumper I> saving snapshot `./00000000000000000000.snap.inprogress'
2015-03-20 00:21:41.609 [44292] snap/101/dumper I> done


Process 44286 stopped
* thread #1: tid = 0x51401, 0x00007fff8c1093fa libsystem_kernel.dylib`__select + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff8c1093fa libsystem_kernel.dylib`__select + 10
libsystem_kernel.dylib`__select + 10:
-> 0x7fff8c1093fa:  jae    0x7fff8c109404            ; __select + 20
   0x7fff8c1093fc:  movq   %rax, %rdi
   0x7fff8c1093ff:  jmp    0x7fff8c104c78            ; cerror
   0x7fff8c109404:  retq
(lldb) bt all
* thread #1: tid = 0x51401, 0x00007fff8c1093fa libsystem_kernel.dylib`__select + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff8c1093fa libsystem_kernel.dylib`__select + 10
    frame #1: 0x0000000100129fed tarantool`select_poll(loop=0x00000001001ade68, timeout=<unavailable>) + 173 at ev_select.c:170
    frame #2: 0x00000001001266f9 tarantool`ev_run(loop=0x00000001001ade68, flags=<unavailable>) + 1113 at ev.c:3143
    frame #3: 0x0000000100052973 tarantool`tarantool_lua_run_script(path=0x001adf6000000000, argc=1, argv=0x00007fff5fbff8a8) + 115 at init.cc:467
    frame #4: 0x000000010000306a tarantool`main(argc=1, argv=0x00007fff5fbff8a8) + 602 at tarantool.cc:651
    frame #5: 0x00007fff8a2955c9 libdyld.dylib`start + 1
    frame #6: 0x00007fff8a2955c9 libdyld.dylib`start + 1

  thread #2: tid = 0x51420, 0x00007fff8c109136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #0: 0x00007fff8c109136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff8fb76e0c libsystem_pthread.dylib`_pthread_cond_wait + 693
    frame #2: 0x00000001000683d6 tarantool`etp_proc(thr_arg=0x000000000010b7f0) + 150 at eio.c:2190
    frame #3: 0x00007fff8fb76268 libsystem_pthread.dylib`_pthread_body + 131
    frame #4: 0x00007fff8fb761e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #5: 0x00007fff8fb7441d libsystem_pthread.dylib`thread_start + 13
```

Crash when accept to box on FreeBSD.
```
 %> gdb tarantool      
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) r
Starting program: /usr/home/vg/opt/bin/tarantool 
[New LWP 100947]
Failed to set locale to C.UTF-8
[New Thread 802406400 (LWP 100947/tarantool)]
/usr/home/vg/opt/bin/tarantool: version 1.6.4-542-g631b961
type 'help' for interactive help
tarantool> box.cfg{slab_alloc_arena=0.1}
2015-03-31 15:09:43.728 [88033] main/101/interactive C> version 1.6.4-542-g631b961
2015-03-31 15:09:43.729 [88033] main/101/interactive C> log level 5
2015-03-31 15:09:43.729 [88033] main/101/interactive I> mapping 107374184 bytes for a shared arena...
2015-03-31 15:09:43.729 [88033] main/101/interactive I> initializing an empty data directory
2015-03-31 15:09:43.756 [88034] snap/101/dumper I> creating `./00000000000000000000.snap.inprogress'
2015-03-31 15:09:43.756 [88034] snap/101/dumper I> saving snapshot `./00000000000000000000.snap.inprogress'
2015-03-31 15:09:43.769 [88034] snap/101/dumper I> done
2015-03-31 15:09:43.771 [88033] main/101/interactive I> ready to accept requests
---
...

tarantool> box.cfg
---
- snapshot_count: 6
  too_long_threshold: 0.5
  slab_alloc_factor: 2
  slab_alloc_maximal: 1048576
  background: false
  slab_alloc_arena: 0.1
  sophia:
    page_size: 131072
    threads: 5
    node_size: 134217728
    memory_limit: 0
  logger_nonblock: true
  snap_dir: .
  coredump: false
  sophia_dir: .
  wal_mode: write
  slab_alloc_minimal: 64
  panic_on_snap_error: true
  panic_on_wal_error: true
  rows_per_wal: 500000
  wal_dir: .
  log_level: 5
  readahead: 16320
  snapshot_period: 0
  wal_dir_rescan_delay: 0.1
...

tarantool> box

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 802406400 (LWP 100947/tarantool)]
0x000000080182bc1e in __cxa_end_catch () from /lib/libcxxrt.so.1
(gdb) thread apply all bt
[New Thread 802408800 (LWP 100613/tarantool)]
[New Thread 802408400 (LWP 100612/tarantool)]
[New Thread 802408000 (LWP 100611/tarantool)]
[New Thread 802407c00 (LWP 100610/tarantool)]
[New Thread 802407800 (LWP 100609/tarantool)]
[New Thread 802407400 (LWP 100604/tarantool)]
[New Thread 802407000 (LWP 100587/tarantool)]

Thread 9 (Thread 802407000 (LWP 100587/tarantool)):
#0  0x00000008011218cc in __error () from /lib/libthr.so.3
#1  0x000000080111fd8e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x00000000004ce93e in etp_proc (thr_arg=0x802432160) at eio.c:2190
#3  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#4  0x0000000000000000 in ?? ()

Thread 8 (Thread 802407400 (LWP 100604/tarantool)):
#0  0x00000008011218cc in __error () from /lib/libthr.so.3
#1  0x000000080111fd8e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x0000000000430b7b in wal_writer_pop (writer=0x8561e0, input=0x7fffff9fcec8)
    at /home/vg/Develop/Tarantool/tarantool/src/box/recovery.cc:837
#3  0x0000000000431fff in wal_writer_thread (worker_args=0x8024c5000)
    at /home/vg/Develop/Tarantool/tarantool/src/box/recovery.cc:978
#4  0x00000000004ba1b3 in cord_thread_func (p=0x80301f7c0)
    at /home/vg/Develop/Tarantool/tarantool/src/fiber.cc:609
#5  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#6  0x0000000000000000 in ?? ()

Thread 7 (Thread 802407800 (LWP 100609/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024d31c0) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 6 (Thread 802407c00 (LWP 100610/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024d3380) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 5 (Thread 802408000 (LWP 100611/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024d3540) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 4 (Thread 802408400 (LWP 100612/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024d3700) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()

Thread 3 (Thread 802408800 (LWP 100613/tarantool)):
#0  0x0000000801d668ba in nanosleep () from /lib/libc.so.7
#1  0x000000080111864c in nanosleep () from /lib/libthr.so.3
#2  0x0000000000569142 in sr_sleep (ns=10000000) at sr_time.c:17
#3  0x0000000000582000 in so_worker (arg=0x8024d38c0) at so_scheduler.c:368
#4  0x00000008011164f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()
---Type <return> to continue, or q <return> to quit---

Thread 2 (Thread 802406400 (LWP 100947/tarantool)):
#0  0x000000080182bc1e in __cxa_end_catch () from /lib/libcxxrt.so.1
#1  0x00000000004af5b8 in lua_field_inspect_ucdata (L=0x1378, cfg=0x4a0c8, idx=7, 
    field=0x80301f0b8) at /home/vg/Develop/Tarantool/tarantool/src/lua/utils.cc:301
#2  0x00000000004af43d in luaL_convertfield (L=0x1378, cfg=0x4a0c8, idx=7, 
    field=0x80301f0b8) at /home/vg/Develop/Tarantool/tarantool/src/lua/utils.cc:556
#3  0x00000000004d6ac5 in luaL_checkfield (L=0x1378, cfg=0x4a0c8, idx=7, 
    field=0x80301f0b8) at utils.h:315
#4  0x00000000004d65d0 in dump_node (dumper=0x80301f6d8)
    at /home/vg/Develop/Tarantool/tarantool/third_party/lua-yaml/lyaml.cc:530
#5  0x00000000004d6e0b in dump_table (dumper=0x80301f6d8, field=0x80301f2a8)
    at /home/vg/Develop/Tarantool/tarantool/third_party/lua-yaml/lyaml.cc:474
#6  0x00000000004d6748 in dump_node (dumper=0x80301f6d8)
    at /home/vg/Develop/Tarantool/tarantool/third_party/lua-yaml/lyaml.cc:557
#7  0x00000000004d6c38 in dump_array (dumper=0x80301f6d8, field=0x80301f4a8)
    at /home/vg/Develop/Tarantool/tarantool/third_party/lua-yaml/lyaml.cc:499
#8  0x00000000004d6730 in dump_node (dumper=0x80301f6d8)
    at /home/vg/Develop/Tarantool/tarantool/third_party/lua-yaml/lyaml.cc:555
#9  0x00000000004d6507 in dump_document (dumper=0x80301f6d8)
    at /home/vg/Develop/Tarantool/tarantool/third_party/lua-yaml/lyaml.cc:632
#10 0x00000000004d5124 in l_dump (L=0x1378)
    at /home/vg/Develop/Tarantool/tarantool/third_party/lua-yaml/lyaml.cc:702
#11 0x000000000052a11a in lj_BC_FUNCC ()
#12 0x00000000004a9216 in lbox_call (L=0x1378, nargs=0, nreturns=0) at utils.h:437
#13 0x00000000004a9114 in run_script (ap=0x803000150)
    at /home/vg/Develop/Tarantool/tarantool/src/lua/init.cc:441
#14 0x00000000004b9187 in fiber_loop (data=0x0)
    at /home/vg/Develop/Tarantool/tarantool/src/fiber.cc:402
#15 0x00000000005abe94 in coro_init ()
    at /home/vg/Develop/Tarantool/tarantool/third_party/coro/coro.c:96
#16 0x000000000041f304 in geteuid@plt ()
#17 0x5050505050505050 in ?? ()
#18 0x5050505050505050 in ?? ()
#19 0x0000000000854ad0 in users ()
#20 0x0000000000854ad0 in users ()
#21 0x0000000000001000 in ?? ()
#22 0x50500100eec0ffee in ?? ()
#23 0x5050505000000050 in ?? ()
#24 0x0000000300000001 in ?? ()
#25 0x0000000200000140 in ?? ()
#26 0x0000000000472702 in MemtxTree::replace (this=Error accessing memory address 0xffffffffffffffd8: Bad address.
)
    at /home/vg/Develop/Tarantool/tarantool/src/box/memtx_tree.cc:243
Previous frame inner to this frame (corrupt stack?)
(gdb) 
(gdb) The program is running.  Exit anyway? (y or n) y
```

**Comment by zloidemon** [comment] 2015-03-31 12:11
I think FreeBSD related to OSX crash.

**Comment by rtsisyk** [comment] 2015-06-25 10:54
Duplicate of #786

**Closed by rtsisyk** 2015-06-25 10:54 UTC
Labels: crash
