### ISSUE TITLE
sql: Analyze works incorrectly

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#3116] opened 2018-02-05 11:14 UTC
https://github.com/tarantool/tarantool/commit/e3ec3d47a0ec520206fbb33d3f16ce448e3ad279?diff=unified#diff-8dc039e198a8fe0a2d70c89a7aca8a18R1105

This is a strange change.
It seems that rows in `_sql_stat4` should be unique and `analyze` should not replace rows which were created by itself just before.

Here are some useful snippets:
Src to repeat key duplicate in `_sql_stat4`
```
CREATE TABLE t1(a primary key ,b);
CREATE INDEX t1b ON t1(b);
insert into t1 values(1,2);
insert into t1 values(2,2);
analyze;
```
Part of analyze vdbe:
```
101>  108 String8          0   50    0 T1B           00 r[50]='T1B'; Analysis for T1.T1B                                                                                            [480/1903]
 101>  109 OpenRead         6 526337    0 k(1,)         00 root=526337; T1B                                                                                                                    
 101>  110 Count            6   48    0               00 r[48]=count()                         
 101>  111 Integer          1   46    0               00 r[46]=1               
 101>  112 Integer          1   47    0               00 r[47]=1                                                                                                                               
 101>  113 Function0        0   46   45 stat_init(3)  03 r[45]=func(r[46..48])                                
 101>  114 Rewind           6  146    0               00                                       
 101>  115 Integer          0   46    0               00 r[46]=0                               
 101>  116 Goto             0  122    0               00                                                                                                                                       
 101>  117 Integer          0   46    0               00 r[46]=0                               
 101>  118 Column           6    1   48               00 r[48]=                                
 101>  119 Ne              48  122   52 (BINARY)      80 if r[52]!=r[48] goto 122              
 101>  120 Integer          1   46    0               00 r[46]=1                               
 101>  121 Goto             0  123    0               00                                       
 101>  122 Column           6    1   52               00 r[52]=                                                                                                                                
 101>  123 Column           6    0   54               00 r[54]=A                                                                                                            
 101>  124 MakeRecord      54    1   47               00 r[47]=mkrec(r[54])                    
 101>  125 Function0        1   45   48 stat_push(3)  03 r[48]=func(r[45..47])                                                                                                                 
 101>  126 Next             6  117    0               00                       
```
Draw extra attention to lines 118, 119 and 122

**Comment by Korablev77** [comment] 2018-02-05 11:58
Actually, they hasn't be unique. Reason for such behaviour is quite simple: SQLite uses rowid for stat tables, meanwhile Tarantool doesn't. Instead, PK consists of two (or three for stat4) columns: table, index and sample (for stat4). However, they might coincide: analyze updates information in stat tables in runtime.
As for your example, approximate execution plan of analyze consists of several stages:
1. For t1b index only one sample exists -- 2.
2. After first row has been procceeded, stat table looks like: ("t1", "t1b", 0, 0, 0, "2").
3. After second row has been handled, new statistic to be inserted is: ("t1", "t1b", 1, 1, 0, "2").
(It may be a little bit different, but the meaning is the same).
As you can see, without replacing we can't update tuple in stat table. That is why replace is used.

As concerning the fact that analyze routine doesn't work in optimal way -- yes, it seems to be not optimal. But we should carefully consider and discuss how to improve it before making some changes. Anyway, by design analyze should be run quite rarely, so I don't think that 'not optimal' execution plan can be a really significant issue.

**Comment by TheAviat0r** [comment] 2018-02-12 17:06
After discussion with @kyukhin we came to decision that 'not optimal execution analyze plan' is temporarily okay for us.

**Comment by igormunkin** [comment] 2022-06-23 10:49
Ticket looks irrelevant since there is no `_sql_stat4` space since 2.2.0-108-gec93b4a5 (ec93b4a). Closing with wontifx reason.

**Closed by igormunkin** 2022-06-23 10:49 UTC
Labels: bug, sql, performance
