### ISSUE TITLE
Node ran with tarantoolctl crashes after 2 minutes on Mac

### ISSUE THREAD

**Issue by qubiq1337** [tarantool/tarantool#8828] opened 2023-06-29 10:03 UTC
**Bug description**

Tarantool crashes after 2 minutes if run via tarantoolctl on Mac.

OS: MacOS 13.4
Tarantool version:
```
Tarantool 3.0.0-entrypoint-439-g47380bb76
Target: Darwin-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: Clang-14.0.0.14000029
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/Users/s.petrenko/Source/sptnt=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/Users/s.petrenko/Source/sptnt=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```

**Steps to reproduce:**
1. Build and install tarantool **without** the bundled libcurl: `cmake . -DENABLE_BUNDLED_LIBCURL=OFF -DENABLE_DIST=ON && make -j install`
2. Create a test file `test.lua`:

```lua
box.cfg{
    listen = '127.0.0.1:3301',
    log = 'test.log'
}
```

3. Run `tarantoolctl start test`
4. Wait for ~ 2 minutes and check the logs:
```
example git:(master) ✗ tail -f test.log 
2023-06-30 17:27:39.783 [99962] main/103/test I> update replication_synchro_quorum = 1
2023-06-30 17:27:39.785 [99962] main/103/test I> replicaset uuid 18cedcba-0723-41d2-9363-2e0e1d066933
2023-06-30 17:27:39.788 [99962] snapshot/101/main I> saving snapshot `./data/test/00000000000000000000.snap.inprogress'
2023-06-30 17:27:39.792 [99962] snapshot/101/main I> done
2023-06-30 17:27:39.794 [99962] main/103/test I> ready to accept requests
2023-06-30 17:27:39.794 [99962] main/105/gc I> wal/engine cleanup is resumed
2023-06-30 17:27:39.795 [99962] main/103/test/box.load_cfg I> set 'log' configuration option to "./test.log"
2023-06-30 17:27:39.796 [99962] main/103/test/box.load_cfg I> set 'listen' configuration option to "127.0.0.1:3301"
2023-06-30 17:27:39.798 [99962] main/106/checkpoint_daemon I> scheduled next checkpoint for Fri Jun 30 19:00:34 2023
2023-06-30 17:27:39.799 [99962] main I> entering the event loop
objc[99962]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[99962]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

Note, the issue isn't reproduced when Tarantool is built **with** bundled libcurl. Current bundled libcurl version is 7.87.0 while the system one on my machine is 7.88.1.

<details><summary>Original description as reported in Vshard repo</summary>

**Bug description**

Tarantool router and storage instances crash after 2-3 minutes of running without any load.

OS: MacOS
OS Version: 13.3 (22E252) (Darwin Kernel Version 22.4.0)
Architecture: amd64
Tarantool 2.11.0-0-g247a9a4 installed via brew
Target: Darwin-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/2.11.0_1 -DENABLE_BACKTRACE=TRUE
Compiler: /usr/bin/clang /usr/bin/clang++
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230615-7372-1i4nu9c/tarantool-2.11.0=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230615-7372-1i4nu9c/tarantool-2.11.0=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Steps to reproduce**
```
cd vshard/example
make
```
Wait 2-3 minutes
```
make logcat
==> data/router_1.log <==
2023-06-29 12:51:20.473 [8945] main/118/vshard.failover._static_router/vshard.router I> New replica storage_1_a(storage@127.0.0.1:3301) for replicaset(uuid="cbf06940-0790-498b-948d-042b62cf3d29", master=storage_1_a(storage@127.0.0.1:3301))
2023-06-29 12:51:20.473 [8945] main/118/vshard.failover._static_router/vshard.router I> Failovering step is finished. Schedule next after 1.000000 seconds
2023-06-29 12:51:20.494 [8945] main/119/vshard.discovery._static_router/vshard.router I> Updated replicaset(uuid="ac522f65-aa94-4134-9f64-51ee384f1a54", master=storage_2_a(storage@127.0.0.1:3303)) buckets: was 0, became 1000
2023-06-29 12:51:20.509 [8945] main/119/vshard.discovery._static_router/vshard.router I> Updated replicaset(uuid="cbf06940-0790-498b-948d-042b62cf3d29", master=storage_1_a(storage@127.0.0.1:3301)) buckets: was 0, became 1000
2023-06-29 12:51:21.474 [8945] main/118/vshard.failover._static_router/vshard.router I> All replicas are ok
2023-06-29 12:51:21.529 [8945] main/119/vshard.discovery._static_router/vshard.router I> Updated replicaset(uuid="ac522f65-aa94-4134-9f64-51ee384f1a54", master=storage_2_a(storage@127.0.0.1:3303)) buckets: was 1000, became 1500
2023-06-29 12:51:21.529 [8945] main/119/vshard.discovery._static_router/vshard.router I> Updated replicaset(uuid="cbf06940-0790-498b-948d-042b62cf3d29", master=storage_1_a(storage@127.0.0.1:3301)) buckets: was 1000, became 1500
2023-06-29 12:51:21.529 [8945] main/119/vshard.discovery._static_router/vshard.router I> Discovery enters idle mode, all buckets are known. Discovery works with 10 seconds interval now
objc[8945]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[8945]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

==> data/storage_1_a.log <==
2023-06-29 12:51:19.227 [8917] main/110/main I> subscribed replica 3de2e3e1-9ebe-4d0d-abb1-26d301b84633 at fd 22, aka 127.0.0.1:3301, peer of 127.0.0.1:53724
2023-06-29 12:51:19.227 [8917] main/110/main I> remote vclock {1: 71} local vclock {1: 71}
2023-06-29 12:51:19.228 [8917] relay/127.0.0.1:53724/101/main I> recover from `./data/storage_1_a/00000000000000000058.xlog'
2023-06-29 12:51:20.147 [8917] main/111/applier/storage@127.0.0.1:3302 I> authenticated
2023-06-29 12:51:20.147 [8917] main/111/applier/storage@127.0.0.1:3302 I> subscribed
2023-06-29 12:51:20.147 [8917] main/111/applier/storage@127.0.0.1:3302 I> remote vclock {1: 3071} local vclock {1: 3071}
2023-06-29 12:51:20.147 [8917] main/111/applier/storage@127.0.0.1:3302 I> RAFT: message {term: 1, state: follower} from 2
2023-06-29 12:51:20.149 [8917] main/111/applier/storage@127.0.0.1:3302 I> leaving orphan mode
objc[8917]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[8917]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

==> data/storage_1_b.log <==
2023-06-29 12:51:20.147 [8924] main/110/main I> remote vclock {1: 3071} local vclock {1: 3071}
2023-06-29 12:51:20.147 [8924] main/105/gc I> wal/engine cleanup is resumed
2023-06-29 12:51:20.148 [8924] relay/127.0.0.1:53738/101/main I> recover from `./data/storage_1_b/00000000000000000071.xlog'
2023-06-29 12:53:19.148 [8924] main/112/applier/storage@127.0.0.1:3301 I> can't read row
2023-06-29 12:53:19.148 [8924] main/112/applier/storage@127.0.0.1:3301 coio.c:349 E> SocketError: unexpected EOF when reading from socket, called on fd 22, aka 127.0.0.1:53724, peer of 127.0.0.1:3301: Broken pipe
2023-06-29 12:53:19.148 [8924] main/112/applier/storage@127.0.0.1:3301 I> will retry every 1.00 second
2023-06-29 12:53:19.148 [8924] relay/127.0.0.1:53738/101/main coio.c:349 E> SocketError: unexpected EOF when reading from socket, called on fd 24, aka 127.0.0.1:3302, peer of 127.0.0.1:53738: Broken pipe
2023-06-29 12:53:19.148 [8924] relay/127.0.0.1:53738/101/main I> exiting the relay loop
objc[8924]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[8924]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

==> data/storage_2_a.log <==
2023-06-29 12:51:20.312 [8931] main/112/applier/storage@127.0.0.1:3304 I> authenticated
2023-06-29 12:51:20.312 [8931] main/112/applier/storage@127.0.0.1:3304 I> subscribed
2023-06-29 12:51:20.312 [8931] main/112/applier/storage@127.0.0.1:3304 I> remote vclock {1: 3071} local vclock {1: 3071}
2023-06-29 12:51:20.312 [8931] main/112/applier/storage@127.0.0.1:3304 I> RAFT: message {term: 1, state: follower} from 2
2023-06-29 12:51:20.313 [8931] main/112/applier/storage@127.0.0.1:3304 I> leaving orphan mode
2023-06-29 12:51:29.326 [8931] main/121/vshard.rebalancer/vshard.storage I> The cluster is balanced ok. Schedule next rebalancing after 3600.000000 seconds
2023-06-29 12:53:19.148 [8931] main/124/127.0.0.1:3301 (net.box)/vshard.replicaset I> disconnected from 127.0.0.1:3301
2023-06-29 12:53:19.148 [8931] main/124/127.0.0.1:3301 (net.box)/box.net_box net_box.lua:358 W> 127.0.0.1:3301: Peer closed
objc[8931]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[8931]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

==> data/storage_2_b.log <==
2023-06-29 12:51:20.312 [8938] main/110/main I> remote vclock {1: 3071} local vclock {1: 3071}
2023-06-29 12:51:20.312 [8938] main/105/gc I> wal/engine cleanup is resumed
2023-06-29 12:51:20.313 [8938] relay/127.0.0.1:53740/101/main I> recover from `./data/storage_2_b/00000000000000000071.xlog'
2023-06-29 12:53:19.312 [8938] main/111/applier/storage@127.0.0.1:3303 I> can't read row
2023-06-29 12:53:19.312 [8938] relay/127.0.0.1:53740/101/main coio.c:349 E> SocketError: unexpected EOF when reading from socket, called on fd 24, aka 127.0.0.1:3304, peer of 127.0.0.1:53740: Broken pipe
2023-06-29 12:53:19.312 [8938] relay/127.0.0.1:53740/101/main I> exiting the relay loop
2023-06-29 12:53:19.312 [8938] main/111/applier/storage@127.0.0.1:3303 coio.c:349 E> SocketError: unexpected EOF when reading from socket, called on fd 21, aka 127.0.0.1:53730, peer of 127.0.0.1:3303: Broken pipe
2023-06-29 12:53:19.312 [8938] main/111/applier/storage@127.0.0.1:3303 I> will retry every 1.00 second
objc[8938]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[8938]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
^Cmake: *** [logcat] Interrupt: 2
```

</details>

**Comment by Totktonada** [comment] 2023-06-30 21:30
It seems, the cause is described here: https://github.com/curl/curl/issues/11252.

**Comment by Totktonada** [comment] 2023-06-30 21:40
It seems, libcurl since 7.77.0 is affected if it is built with the synchronous DNS resolving (without c-ares) -- and there are likely more conditions when the problematic code is in effect. The built-in libcurl in tarantool is built with c-ares.

`tarantoolctl` forks the process to background using `background` box.cfg() option (if it is run not under systemd).

**Comment by Totktonada** [comment] 2023-07-10 10:17
https://github.com/curl/curl/issues/11252 is closed now. I think it worth to wait for the next curl release, wait for the update in homebrew and re-check.

**Comment by sergepetrenko** [comment] 2023-09-21 11:57
The issue is resolved on my side after I updated system libcurl to 8.3.0:
```
curl 8.3.0 (x86_64-apple-darwin22.6.0) libcurl/8.3.0 (SecureTransport) OpenSSL/3.1.2 zlib/1.2.11 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.56.0 librtmp/2.3 OpenLDAP/2.6.6
Release-Date: 2023-09-13
```

**Closed by sergepetrenko** 2023-09-21 11:57 UTC

**Comment by KaymeKaydex** [comment] 2023-11-23 08:45
> The issue is resolved on my side after I updated system libcurl to 8.3.0:
> 
> ```
> curl 8.3.0 (x86_64-apple-darwin22.6.0) libcurl/8.3.0 (SecureTransport) OpenSSL/3.1.2 zlib/1.2.11 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.56.0 librtmp/2.3 OpenLDAP/2.6.6
> Release-Date: 2023-09-13
> ```

it might be worth improving the UX on this front and helping users sign up for what might be a problem with libcurl

I now encountered this problem and sat for some time until I found this issue
