### ISSUE TITLE
Rework transaction flags

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5128] opened 2020-07-01 22:31 UTC
`struct txn` flags field is a mess. It is impossible to set several flags at once, or clear them. It is not possible to create combined flags, when, for example, a new flag would include some other flag + 1 additional bit. Better remove this "nice" API `txn_set/has/clear_flag()` and just use bitwise operators directly + assign concrete values to the `enum txn_flag` consts. The issue is motivated by sync replication, where appear two flags: `TXN_WAIT_ACK` and `TXN_WAIT_SYNC`. The former is supposed to always include the latter.

**Comment by cyrillos** [comment] 2021-02-12 10:42
Given our code style guide restrictions, using plain `flags` access doesn't improve code readability anyhow, but rather make it more complex. Seems we should close this issue as `won't fix`.

**Comment by Gerold103** [comment] 2021-02-12 12:32
I don't understand. What is the problem with the way which was proposed in the mailing list? It wasn't about refactoring API for the sake of refactoring. It was about being able to set and clear many flags at once. And this can easily be fixed by just making the flag constants as bitfields + changing the txn flags API just a little bit.

The issue must not be closed like this. Still can be done.

**Comment by cyrillos** [comment] 2021-02-12 13:11
The problem is not in converting `flags` to bit-field. The problem is that we do tests for single bit present and for multiple bits match. And proper way is to not fiddle with `txn_has|set_flag` helpers but operate with `flags` field directly which in turn leads to some strange code like

`assert((txn->flags & (TXN_IS_DONE | TXN_WAIT_SYNC)) == 0);`

which is more ugly than straight code we use now
```
assert(!txn_has_flag(txn, TXN_IS_DONE));
assert(!txn_has_flag(txn, TXN_WAIT_SYNC));
```

I'm perfectly fine if you manage to implement some elegant solution for this, moreover the patches are flying in ML so indeed this should be fairly easy. Thus feel free to reopen.

**Comment by cyrillos** [comment] 2021-02-12 17:26
By saying

> Thus feel free to reopen.

I didn't mean @kyukhin to reopen but rather Vlad to reopen if he gonna implement these patches.

**Comment by Gerold103** [comment] 2021-02-12 21:39
I asked Kirill do reopen it, as I still think there must be API to be able to set and clear many flags at once.

**Comment by cyrillos** [comment] 2021-02-12 21:56
I see. OK then.

**Closed** 2021-02-24 10:47 UTC
Labels: 3sp, prio6, qsync replication, refactoring, teamR
