### ISSUE TITLE
Truncate not allowed for local table on replica

### ISSUE THREAD

**Issue by a1div0** [tarantool/tarantool#9221] opened 2023-10-05 07:04 UTC
Subj
![image](https://github.com/tarantool/tarantool/assets/4862582/486ac615-eeb5-45c0-8b7b-bb82bf6d05f2)

According to the documentation it should work:
https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_schema/space_create/

![image](https://github.com/tarantool/tarantool/assets/4862582/d4e9895b-24fc-44e2-9aca-256745c3db16)

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64
* Tarantool 2.11.0-rc2-0-g2ae0c94a2

**Steps to reproduce**

Run two tarantool instances iteractively.

1. Create two nodes - master and replica
1. Create local table
1. Run truncate on replica

**Comment by olegrok** [comment] 2023-10-05 07:36
Duplicate of https://github.com/tarantool/tarantool/issues/5616

**Closed** 2023-10-05 10:48 UTC
Labels: bug
