### ISSUE TITLE
test: server stop during dump/compaction produces SIGSEGV

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4170] opened 2019-04-18 08:25 UTC
Tarantool version:
master

OS version:
Ubuntu 18.04

Bug description:
Failed test is the modified subtest from vinyl/errinj test in memtx and vinyl. Server stop command during dump/compaction produces SIGSEGV.

Vinyl:
Core was generated by `tarantool replica_vinyl.lua <running>                                         '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000560ea4132ac8 in matras_view_get_no_check (m=0x560ea58c5b88, v=0x560ea59bcbe0, id=0) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/small/small/matras.h:353
353		return &extent[n1][n2][n3 * m->block_size];
[Current thread is 1 (Thread 0x7f02c77ff700 (LWP 27051))]
#0  0x0000560ea4132ac8 in matras_view_get_no_check (m=0x560ea58c5b88, v=0x560ea59bcbe0, id=0) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/small/small/matras.h:353
#1  0x0000560ea4132b34 in matras_view_get (m=0x560ea58c5b88, v=0x560ea59bcbe0, id=0) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/small/small/matras.h:363
#2  0x0000560ea41335e2 in bps_tree_memtx_tree_restore_block_ver (tree=0x560ea58c5b40, id=0, view=0x560ea59bcbe0) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/salad/bps_tree.h:1285
#3  0x0000560ea4133d4a in bps_tree_memtx_tree_get_leaf_safe (tree=0x560ea58c5b40, itr=0x560ea59bcbd8) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/salad/bps_tree.h:1551
#4  0x0000560ea4134a35 in memtx_tree_iterator_get_elem (tree=0x560ea58c5b40, itr=0x560ea59bcbd8) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/salad/bps_tree.h:1970
#5  0x0000560ea41407d6 in tree_snapshot_iterator_next (iterator=0x560ea59bcbc0, size=0x7f02c68fe61c) at /home/avtikhon/Workspaces/tarantool_empty/src/box/memtx_tree.c:733
#6  0x0000560ea414baf6 in checkpoint_f (ap=0x7f02c6800228) at /home/avtikhon/Workspaces/tarantool_empty/src/box/memtx_engine.c:661
#7  0x0000560ea41154cf in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x560ea414b8fc <checkpoint_f>, ap=0x7f02c6800228)
    at /home/avtikhon/Workspaces/tarantool_empty/src/lib/core/fiber.h:672
#8  0x0000560ea42bb39c in fiber_loop (data=0x0) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/core/fiber.c:694
#9  0x0000560ea4504f14 in coro_init () at /home/avtikhon/Workspaces/tarantool_empty/third_party/coro/coro.c:110

Memtx:
Core was generated by `tarantool replica_memtx.lua <running>                                         '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055c9da5e3d52 in bps_tree_memtx_tree_get_leaf_safe (tree=0x55c9dbb8b340, itr=0x55c9dbbea658) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/salad/bps_tree.h:1553
1553		if (block->type == BPS_TREE_BT_GARBAGE) {
[Current thread is 1 (Thread 0x7f806ffff700 (LWP 27282))]
#0  0x000055c9da5e3d52 in bps_tree_memtx_tree_get_leaf_safe (tree=0x55c9dbb8b340, itr=0x55c9dbbea658) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/salad/bps_tree.h:1553
#1  0x000055c9da5e4a35 in memtx_tree_iterator_get_elem (tree=0x55c9dbb8b340, itr=0x55c9dbbea658) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/salad/bps_tree.h:1970
#2  0x000055c9da5f07d6 in tree_snapshot_iterator_next (iterator=0x55c9dbbea640, size=0x7f806f0fe61c) at /home/avtikhon/Workspaces/tarantool_empty/src/box/memtx_tree.c:733
#3  0x000055c9da5fbb8f in checkpoint_f (ap=0x7f806f000228) at /home/avtikhon/Workspaces/tarantool_empty/src/box/memtx_engine.c:662
#4  0x000055c9da5c54cf in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55c9da5fb8fc <checkpoint_f>, ap=0x7f806f000228)
    at /home/avtikhon/Workspaces/tarantool_empty/src/lib/core/fiber.h:672
#5  0x000055c9da76b39c in fiber_loop (data=0x0) at /home/avtikhon/Workspaces/tarantool_empty/src/lib/core/fiber.c:694
#6  0x000055c9da9b4f14 in coro_init () at /home/avtikhon/Workspaces/tarantool_empty/third_party/coro/coro.c:110

Steps to reproduce:
Unpack into tarantool/test/vinyl path the files from archive:
https://github.com/tarantool/tarantool/files/3093402/errinj.zip

1) Vinyl:

Passes:
./test-run.py vinyl/errinj_vinyl.test.lua

Fails:
ulimit -c unlimited
./test-run.py -j 20 --force `for t in {1..20} ; do echo -n " vinyl/errinj_vinyl.test.lua" ; done`
gdb `which tarantool` `find var -name core | head -n 1` --eval-command=bt

2) Memtx:

Passes:
for f in vinyl/errinj_memtx.test.lua ; do sed 's#10000#1000#g' -i $f ; done
./test-run.py vinyl/errinj_memtx.test.lua

Fails:
ulimit -c unlimited
for f in vinyl/errinj_memtx.test.lua ; do sed 's#1000#10000#g' -i $f ; done
./test-run.py vinyl/errinj_memtx.test.lua
gdb `which tarantool` var/001_vinyl/core --eval-command=bt

Optional (but very desirable):
* coredump
* backtrace
* netstat
[errinj.zip](https://github.com/tarantool/tarantool/files/3093402/errinj.zip)

**Comment by kyukhin** [comment] 2019-04-18 08:31
Connected (or even duplicate of) #3594

**Comment by avtikhon** [comment] 2019-04-18 13:01
Added missed replicas in the first comment:
[replica.zip](https://github.com/tarantool/tarantool/files/3094483/replica.zip)

**Comment by avtikhon** [comment] 2019-04-18 13:06
Added missed replicas in the first comment:
[replica.zip](https://github.com/tarantool/tarantool/files/3094503/replica.zip)

**Comment by Totktonada** [comment] 2019-04-18 14:32
@kyukhin It is not about a tuple size limit.

**Closed** 2019-04-18 18:23 UTC
Labels: bug, qa
