### ISSUE TITLE
No logs if can't start because of no memory

### ISSUE THREAD

**Issue by jirfag** [tarantool/tarantool#1438] opened 2016-04-11 21:35 UTC
How to reproduce:

1. run amazon aws nano instance (512mb of RAM) with ubuntu 14.04
2. install tarantool
3. 
```
$ sudo ln -sf /etc/tarantool/instances.{available,enabled}/example.lua
$ sudo tarantoolctl start example
/usr/bin/tarantoolctl: Starting instance...
/usr/bin/tarantoolctl: mkdir /var/lib/tarantool/example
$ sudo tarantoolctl status example
/usr/bin/tarantoolctl: example is stopped (pid file does not exist)
$ sudo ls -la /var/lib/tarantool/example # nothing
$ tarantool --version | head -1
Tarantool 1.6.8-624-g4178aa2
```

If I change `slab_alloc_arena` from 0.5 to 0.1 everything is ok.
And maybe choose slab_alloc_arena in example depending on machine free memory during package installation?

**Comment by rtsisyk** [comment] 2016-05-31 20:44
Duplicate of #940

**Closed by rtsisyk** 2016-05-31 20:44 UTC
