### ISSUE TITLE
Static binary of tarantool

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#3254] opened 2018-03-20 11:23 UTC
In order to simplify deployment to various clouds/orchestrators and simplify installation for end users, I propose to create a static binary of Tarantool that can be run on any x86_64 Linux system.

This can be achieved by statically linking with most dependencies, except glibc, which can be taken from an old and stable distribution, like CentOS 6.

In addition to producing such a binary, I propose to also include tarantoolctl on board, to package preloads. In order to call it from CLI, users will need to make a symlink named `tarantoolctl` to the tarantool binary. When called through such symlink, tarantool will behave as tarantoolctl.

**Comment by racktear** [comment] 2018-03-20 11:24
Also, we probably should release such binary as a part of our regular release process.

**Comment by kyukhin** [comment] 2018-03-20 11:31
Let's update release process and store such an artefact for all new releases.

**Comment by kostja** [comment] 2018-03-20 15:08
1) It's not possible to do - there are no static versions of some of the libraries we depend on.
	linux-vdso.so.1 =>  (0x00007ffe3c72e000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007f3c35bfd000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f3c35869000)
	libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f3c35623000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f3c35401000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f3c351d8000)
	libform.so.5 => /usr/lib/x86_64-linux-gnu/libform.so.5 (0x00007f3c34fc8000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f3c34d5f000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f3c3491b000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f3c346ae000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3c344aa000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3c342a2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3c33f99000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3c33d7c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3c33b66000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f3c3394b000)
	libunwind-x86_64.so.8 => /usr/lib/x86_64-linux-gnu/libunwind-x86_64.so.8 (0x00007f3c3372c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3c333aa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3c32fe0000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f3c31529000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f3c312f6000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f3c310da000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f3c30ea4000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f3c30b74000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f3c3092a000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f3c3071b000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f3c304ca000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3c302b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3c3605f000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f3c3008e000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f3c2fe5b000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f3c2fbdb000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f3c2f977000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f3c2f764000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f3c2f492000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f3c2f263000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f3c2f05f000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f3c2ee54000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f3c2ec39000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f3c2ea1e000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f3c2e7dd000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f3c2e5d5000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f3c2e3d1000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f3c2e1c8000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f3c2df3e000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f3c2dc9c000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f3c2da69000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f3c2d853000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f3c2d62a000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f3c2d41b000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f3c2d1d0000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f3c2cefb000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f3c2ccc3000)
2) It's not possible to do for a reason: it breaks any sane security policy.

Konstantin, please use docker.

**Comment by racktear** [comment] 2018-03-20 17:20
@kostja I hope you understand that docker is essentially the same: baking everything into a package. You can't update openssl in a docker container without doing a rebuild. Well, you probably can, but then it's not what people will do with Docker.

**Comment by kyukhin** [comment] 2018-07-05 12:56
Duplicate of #3445

**Closed by kyukhin** 2018-07-05 12:56 UTC
Labels: qa
