### ISSUE TITLE
Port the luajit-gdb extension to lldb

### ISSUE THREAD

**Issue by mkokryashkin** [tarantool/tarantool#7794] opened 2022-10-11 19:53 UTC
The GDB is not supported on Apple Silicon Macs, so the LLDB is the only option. Since their scripting APIs are quite different, the luajit-gdb extension should be re-implemented using the provided LLDB Python API.

**Comment by igormunkin** [comment] 2023-05-03 09:26
The issue is closed via tarantool/luajit@62fc84a.

**Closed as completed by igormunkin** 2023-05-03 09:26 UTC
Labels: luajit, devtools, 2.11
