### ISSUE TITLE
Tarantool crashes while box.cfg {}

### ISSUE THREAD

**Issue by iproha94** [tarantool/tarantool#2838] opened 2017-10-16 20:03 UTC
```
Tarantool 1.8.2-173-g567605854
type 'help' for interactive help
tarantool> box.cfg {}
2017-10-16 22:59:08.214 [4861] main/101/interactive C> Tarantool 1.8.2-173-g567605854
2017-10-16 22:59:08.215 [4861] main/101/interactive C> log level 5
2017-10-16 22:59:08.215 [4861] main/101/interactive I> mapping 268435456 bytes for memtx tuple arena...
2017-10-16 22:59:08.216 [4861] main/101/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2017-10-16 22:59:08.235 [4861] main/101/interactive I> recovery start
2017-10-16 22:59:08.235 [4861] main/101/interactive I> recovering from `./00000000000000000000.snap'
tarantool: parse.c:1735: yy_find_reduce_action: Assertion `yy_lookahead[i]==iLookAhead' failed.
Аварийный останов (стек памяти сброшен на диск)

```

**Comment by pgulutzan** [comment] 2017-10-16 21:44
This might be a duplicate of issue#2835.

**Comment by kyukhin** [comment] 2017-10-18 11:20
Duplicate

**Closed by kyukhin** 2017-10-18 11:20 UTC
Labels: crash
