### ISSUE TITLE
Add a failsafe on select with nil argument

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#4506] opened 2019-09-17 08:42 UTC
`box.space.VERY_BIG_SPACE:select({nil})` currently leads to `Out of memory` error if the space has a lot of data. It would be extremely helpful to stop such requests if we see that it is impossible to retrieve more data.

**Preventive failsafe is a must**, no one likes to see coredump on storages...

**Comment by olegrok** [comment] 2019-09-17 08:44
Duplicate of https://github.com/tarantool/tarantool/issues/562

**Comment by opomuc** [comment] 2019-09-17 08:47
Ok, duplicate of #562

**Comment by kyukhin** [comment] 2019-09-26 08:20
Closing as duplicate

**Closed by kyukhin** 2019-09-26 08:20 UTC
