### ISSUE TITLE
key_def: support multikey paths

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4539] opened 2019-10-02 06:03 UTC
key_def module was introduced before multikey indexes. It's powerful tool for tuple comparison. It is also used by merger.

But sometimes you can't use this tool - when you use multikey indexes. It's not completely understandable how to compare arrays. But order between tuples now is kept by tuple hints. And we can use it to compare such tuples.

**Comment by PersDep** [comment] 2020-09-18 14:47
It is now duplicate of #5270

**Closed by PersDep** 2020-09-18 14:47 UTC
Labels: feature
