### ISSUE TITLE
Box.cfg fails with "too many open files" error

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4910] opened 2020-04-21 18:25 UTC
## Tarantool version

Any, I've tested 2.4.0-191-g5d7955273

## The victim

Consider one fat vshard storage. Restarting it takes considerable amount of time and building indexes lasts for tens of minutes. During that tarantool is unresponsive (see #4646), and unable to accept new connections. We can simulate the same behavior with the following script: 

```lua
box.cfg({listen = 3301, custom_proc_title = 'victim'})
box.schema.user.grant('guest', 'super')
while true do os.execute("sleep 1") end
```

## The killer

At the same time another instance creates a netbox connection:

```lua
c = require('net.box').connect('localhost:3301', {
    connect_timeout = 2,
    reconnect_after = 2,
    wait_connected = false,
})
```

Despite tarantool is unresponsive, the kernel does create new socket on every reconnect attempt and after connection times out it remains in CLOSE_WAIT state:

```console
$ lsof -p $(pgrep -f victim) | tail -n 5
tarantool 11511 rosik   30u     IPv4 TCP localhost:3301->localhost:53678 (CLOSE_WAIT)
tarantool 11511 rosik   31u     IPv4 TCP localhost:3301->localhost:53686 (CLOSE_WAIT)
tarantool 11511 rosik   32u     IPv4 TCP localhost:3301->localhost:53696 (CLOSE_WAIT)
tarantool 11511 rosik   33u     IPv4 TCP localhost:3301->localhost:53702 (CLOSE_WAIT)
tarantool 11511 rosik   34u     IPv4 TCP localhost:3301->localhost:53708 (ESTABLISHED)
```

## Сulmination

In our case there were 12 vshard routers, which reconnected every 10.5 seconds. In about 15 minutes it reached default `ulimit` (1024), and after the storage had finished recovery it died saying "can't initialize storage: error reading directory: too many open files".

The end.

**Comment by kostja** [comment] 2020-04-21 19:44
Duplicate of https://github.com/tarantool/tarantool/issues/3776 - isn't it amazing?-)

**Comment by rosik** [comment] 2020-04-21 19:55
Well, at least we've got reproducer now :-)

**Comment by kyukhin** [comment] 2020-04-22 10:56
This one is a duplicate.

**Closed by kyukhin** 2020-04-22 10:56 UTC
Labels: duplicate
