### ISSUE TITLE
sql: length takes not-string values

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4159] opened 2019-04-15 14:26 UTC
```Lua
box.execute('SELECT LENGTH(5)')
```
returns
```YAML
---
- metadata:
  - name: LENGTH(5)
    type: integer
  rows:
  - [1]
...
```

But should raise and error, according to the standard.

**Comment by Korablev77** [comment] 2019-04-15 15:54
I've already mentioned in dev mailing list that several built-in function can accept arguments of wrong types:

```
tarantool> select zeroblob('abc')
---
- metadata:
 - name: zeroblob('abc')
   type: scalar
 rows:
 - ['']
…

tarantool> select abs('abc')
---
- metadata:
 - name: abs('abc')
   type: number
 rows:
 - [0]
…

```
Let's fix them all in scope of this issue.

**Comment by pgulutzan** [comment] 2019-07-02 18:55
I believe this is not a bug. See also comments in issue#3929.

**Comment by ImeevMA** [comment] 2021-08-22 05:03
Fixed by https://github.com/tarantool/tarantool/commit/33d80c8c5822ce8758447ee2abfbe5fb6954dcb7

**Closed by ImeevMA** 2021-08-22 05:03 UTC
Labels: bug, sql, sql static types
