### ISSUE TITLE
Memory leak in tarantool server when client program (trantool instance creator) is not terminated

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool#3997] opened 2019-02-13 19:38 UTC
Tarantool version:
2.1
OS version:
CentOS 7.5
Bug description:
Tarantool Memory leak
Steps to reproduce:
0.) Create memtx database, just use example.lua provided
1.) Create a tarantool server instance in c, make sure its just called once but does not terminate the program, such that
```c
struct tnt_stream *tnt;
struct tnt_stream *tuple;
main(){
		tnt = tnt_net(NULL); // Allocating stream
		tuple = tnt_object(NULL);
		tnt_set(tnt, TNT_OPT_URI, 127.0.0.1:3301); // Setting URI
		if (tnt_connect(tnt) < 0) {                      /* See note = CONNECT */
			printf("Connection refused\n");
			exit(-1);
		}
//other code dont terminate main. maybe sleep.
}
```
2.) Create a loop where tarantool request will set up.
```c
looptheloop(){
    tnt_object_add_array(tuple, 1);
    tnt_object_add_int(tuple, 1);
    tnt_select(tnt, 10, 0, UINT32_MAX, 0, 0, tuple);
    tnt_object_reset(tuple);
    tnt_flush(tnt); // Send ping request
}
```
3.) loop to the eventloop for 100s at 70k times/s, do repeatedly.
4.) tarantool server memory usage start to increase. when you lunch the loop again (without terminating main), memory will pile up.
5.) tarantool memory will return to normal when the c program we created terminates. 

Thoughts:
This means there is a mechanism in tarantool to free ram, but it seems, its holding it back until the connection terminates. But it seems, the memory leak is more related to the request sent to tarantool.

Optional (but very desirable):
I dont know how to get any of these
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment] 2019-02-18 19:56
Whether you look at RSS of tarantool or tarantool-c?

**Comment by jobs-git** [comment] 2019-03-10 12:22
Hi, I was able to reproduce it again, where do I get RSS information?

**Comment by Totktonada** [comment] 2019-03-14 12:13
Like so:

```sh
while true; do ps aux | grep '[R]SS\|[t]arantool'; sleep 1; done
```

But it would be better if you'll provide a full test case.

**Comment by kyukhin** [comment] 2019-05-28 02:40
No answer for months. Closing.

**Closed by kyukhin** 2019-05-28 02:40 UTC
Labels: bug, need feedback

**Comment by Totktonada** [comment] 2019-05-28 22:56
I suspect large readahead and a tarantool version before 1.10.3-17-g87dae8646, 2.1.2-26-g747bd0439 or 2.2.0-167-ga58b9bb8d. See #4061. Now the problem is fixed.
