### ISSUE TITLE
Assertion with undeclared function

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3671] opened 2018-09-07 18:55 UTC
I have Ubuntu 18.04. I have Tarantool 2.0, pulled from source today.
I execute these requests:

s = box.schema.space.create('test')
i = box.space.test:create_index('i')
function f(iterator)
  for request_number, old_tuple, new_tuple, space_id in iterator() do
    printf('request seen')
  end
end
box.begin() s:replace{1,'x'} box.on_commit(f) box.commit()

The result is:
2018-09-07 12:41:02.626 [9223] main/101/interactive utils.c:923 E> LuajitError: [string "function f(iterator)..."]:3: variable 'printf' is not declared
tarantool: /home/pgulutzan/tarantool-2.0/src/box/txn.c:342: txn_commit: Assertion `0' failed.
Aborted (core dumped)

Yes, I admit I have a bad habit of typing printf when I mean print.
But aborting the server for a typing error seems a bit severe.

**Comment by Gerold103** [comment] 2018-09-26 08:53
It is not a bug - you can not throw errors from on_commit triggers. When a transaction is committed, it can not be rolled back by any error.

**Comment by kyukhin** [comment] 2018-10-08 13:29
12 days w/o answer. Closing.

**Closed by kyukhin** 2018-10-08 13:29 UTC
Labels: bug, crash, need feedback
