### ISSUE TITLE
luacheck: add .luacheckrc config to the project

### ISSUE THREAD

**Issue by RunsFor** [tarantool/tarantool#4208] opened 2019-05-13 15:42 UTC
l ran luacheck against latest version of tarantool and got lots of warnings.

```bash
$ luacheck -r src | tail -1
Total: 882 warnings / 0 errors in 40 files
```

I believe it would be useful to define `.luacheckrc`, so the lua code will be consistent throughout the project and more friendly for newcomers.

**Comment by ligurio** [comment] 2020-04-03 12:08
Duplicate of #4681

**Closed by ligurio** 2020-04-03 12:08 UTC
Labels: feature, good first issue
