### ISSUE TITLE
vinyl/replica_quota.test.lua fails regularly

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3601] opened 2018-08-02 08:40 UTC
Here's backtrace. (branch 1.10)
```
[126] vinyl/replica_quota.test.lua
[126] TarantoolInpector.handle() received the following error:
[126] Traceback (most recent call last):
[126]   File "/home/kyukhin/w/tarantool/src/test-run/lib/inspector.py", line 92, in handle
[126]     result = self.parser.parse_preprocessor(line)
[126]   File "/home/kyukhin/w/tarantool/src/test-run/lib/preprocessor.py", line 95, in parse_preprocessor
[126]     return self.server(stype, sname, options)
[126]   File "/home/kyukhin/w/tarantool/src/test-run/lib/preprocessor.py", line 295, in server
[126]     return getattr(self, attr)(ctype, sname, opts)
[126]   File "/home/kyukhin/w/tarantool/src/test-run/lib/preprocessor.py", line 173, in server_start
[126]     wait_load=wait_load, args=args)
[126]   File "/home/kyukhin/w/tarantool/src/test-run/lib/tarantool_server.py", line 556, in start
[126]     color_log(self.version() + "\n", schema='version')
[126]   File "/home/kyukhin/w/tarantool/src/test-run/lib/tarantool_server.py", line 420, in version
[126]     p = subprocess.Popen([cls.binary, "--version"], stdout=subprocess.PIPE)
[126]   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
[126]     errread, errwrite)
[126]   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
[126]     raise child_exception
[126] OSError: [Errno 13] Permission denied
[126]
[126] [ fail ]
[126]
[126] Test failed! Result content mismatch:
[126] --- vinyl/replica_quota.result    Thu May 17 19:54:44 2018
[126] +++ vinyl/replica_quota.reject    Thu Aug  2 11:37:39 2018
[126] @@ -80,20 +80,3 @@
[126]  ---
[126]  ...
[126]  _ = test_run:cmd("start server replica") -- recovery
[126] ----
[126] -...
[126] -_ = test_run:cmd("stop server replica")
[126] ----
[126] -...
[126] -_ = test_run:cmd("cleanup server replica")
[126] ----
[126] -...
[126] -s:drop()
[126] ----
[126] -...
[126] -box.schema.user.revoke('guest', 'replication')
[126] ----
[126] -...
[126] -box.schema.user.revoke('guest', 'read,write,execute', 'universe')
[126] ----
[126] -...
[126]
[126] Last 15 lines of Tarantool Log file [Instance "vinyl"][/home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl.log]:
[126] 2018-08-02 11:37:36.714 [26523] main/164/console/unix/: I> removed /home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/00000000000000005197.vylog
[126] 2018-08-02 11:37:36.715 [26523] main/164/console/unix/: I> removed /home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/537/0/00000000000000000202.index
[126] 2018-08-02 11:37:36.715 [26523] main/164/console/unix/: I> removed /home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/537/0/00000000000000000202.run
[126] 2018-08-02 11:37:36.715 [26523] main/164/console/unix/: I> removed /home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/537/1/00000000000000000200.index
[126] 2018-08-02 11:37:36.715 [26523] main/164/console/unix/: I> removed /home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/537/1/00000000000000000200.run
[126] 2018-08-02 11:37:36.716 [26523] wal/101/main I> removed /home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/00000000000000005223.xlog
[126] 2018-08-02 11:37:36.716 [26523] wal/101/main I> removed /home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/00000000000000005239.xlog
[126] 2018-08-02 11:37:36.774 [26523] main/104/vinyl.scheduler I> 540/0: completed compacting range (-inf..inf)
[126] 2018-08-02 11:37:37.048 [26523] main/162/main I> initial data sent.
[126] 2018-08-02 11:37:37.049 [26523] relay/[::1]:39314/101/main I> recover from `/home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/00000000000000008272.xlog'
[126] 2018-08-02 11:37:37.078 [26523] main/162/main I> final data sent.
[126] 2018-08-02 11:37:38.851 [26523] relay_0x10106e0/101/main I> recover from `/home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/00000000000000008272.xlog'
[126] 2018-08-02 11:37:38.866 [26523] relay_0x10106e0/101/main I> done `/home/kyukhin/w/tarantool/src/test/var/126_vinyl/vinyl/00000000000000008272.xlog'
[126] 2018-08-02 11:37:39.172 [26523] relay/[::1]:39314/101/main C> exiting the relay loop
[126] 2018-08-02 11:37:39.172 [26523] main/169/main coio.cc:370 !> SystemError unexpected EOF when reading from socket, called on fd 141, aka [::1]:38345, peer of [::1]:39314: Broken pipe
```

**Comment by locker** [comment] 2019-03-15 15:21
This doesn't look like a problem in the test. Seems the failure was caused by a dirty test environment. I'm closing the bug now. Feel free to reopen it if you encounter it again.

**Closed by locker** 2019-03-15 15:21 UTC
Labels: flaky test
