### ISSUE TITLE
Remove libstdc++ dependency

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3532] opened 2018-07-13 11:38 UTC
Usage of C++ is really low in Tarantool, and all places where
C++ is actually used involve exceptions.
Seems like those places might be refactored which will allow to remove dependency
on libstdc++.

**Comment by Totktonada** [comment] 2019-11-18 16:26
Duplicate of #3261.

**Comment by locker** [comment] 2022-07-20 07:31
Duplicate of #3261.

**Closed by locker** 2022-07-20 07:31 UTC
Labels: feature, refactoring
