### ISSUE TITLE
lua_field_try_serialize thows bus error

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4777] opened 2020-02-13 15:05 UTC
```lua
Tarantool 2.4.0-23-ge9aa37848
type 'help' for interactive help
tarantool> t = {}
---
...

tarantool> setmetatable(t, {__serialize = function(t) return t end})
[1]    84924 bus error  ./src/tarantool
```

```gdb
frame #4: 0x00000001000dad9c tarantool`luaL_tofield at utils.c:556:3
   553 			struct lua_serialize_status s;
   554 			s.cfg = cfg;
   555 			s.field = field;
-> 556 			lua_pushcfunction(L, lua_field_try_serialize);
   557 			lua_pushvalue(L, idx);
   558 			lua_pushlightuserdata(L, &s);
   559 			if (lua_pcall(L, 2, 1, 0) != 0) {
(lldb) up
frame #5: 0x00000001000dad70 tarantool`luaL_tofield(L=0x000000010311a378, cfg=0x000000010359e530, index=3, field=0x000000010517f608) at utils.c:770
   767 		case LUA_TTABLE:
   768 		{
   769 			field->compact = false;
-> 770 			return lua_field_inspect_table(L, cfg, index, field);
   771 		}
   772 		case LUA_TLIGHTUSERDATA:
   773 		case LUA_TUSERDATA:
(lldb) up
frame #6: 0x00000001000dc62a tarantool`lua_field_try_serialize(L=0x000000010311a378) at utils.c:511:18
   508 			/* copy object itself */
   509 			lua_pushvalue(L, 1);
   510 			lua_call(L, 1, 1);
-> 511 			s->is_error = (luaL_tofield(L, cfg, -1, field) != 0);
   512 			s->is_value_returned = true;
   513 			return 1;
   514 		}
```

**Comment by olegrok** [comment] 2020-02-19 07:55
May be related https://github.com/tarantool/tarantool/issues/3228

**Comment by Totktonada** [comment] 2020-03-06 22:41
Agreed. It looks as duplicate of #3228.

BTW, I guess 1.10 is affected too, so 1.10.x milestone should be here (or wishlist as in the linked issue).

**Closed by Totktonada** 2020-03-06 22:41 UTC
Labels: bug, crash
