### ISSUE TITLE
sql-tap/gh2548-select-compound-limit.test.lua fails on new test-run

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3461] opened 2018-06-13 11:13 UTC
After this test-run pull request: https://github.com/tarantool/test-run/pull/88
test `sql-tap/gh2548-select-compound-limit.test.lua` fails stable.

**Comment by Totktonada** [comment] 2018-06-13 11:19
Cannot reproduce locally. Where do you observe the result? What is the output?

**Comment by Gerold103** [comment] 2018-06-13 11:22
The test is TAP, so it has no result. Below the output is presented:
```
======================================================================================
WORKR TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------------
[001] sql-tap/gh2548-select-compound-limit.test.lua                   [ fail ]
[001] Test failed! Last 15 lines of the result file:
[001] 
[001] Last 15 lines of Tarantool Log file [Instance "app_server"][/Users/v.shpilevoy/Work/Repositories/tarantool/test/var/001_sql-tap/gh2548-select-compound-limit.test.lua.tarantool.log]:
[Main process] Got failed test; gently terminate all workers...
[001] Worker "001_sql-tap" got failed test; stopping the server...
---------------------------------------------------------------------------------
```

**Comment by Gerold103** [comment] 2018-06-13 11:27
Maybe travis is ok, because it runs sql-tap tests in two builds only.

**Comment by Totktonada** [comment] 2018-06-13 11:31
It is okay for me when I run it locally on Gentoo/amd64 on Debug and RelWithDebInfo both. That is why I ask you where do you observe the result. Maybe it is some Mac OS specific. Don't sure.

I tried to run it w/o test-run:

```
$ LUA_PATH='test/sql-tap/lua/?.lua;test/sql/lua/?.lua;;' test/sql-tap/gh2548-select-compound-limit.test.lua
TAP version 13
1..8
ok - Positive COMPOUND UNION
ok - Negative COMPOUND UNION
ok - Positive COMPOUND UNION ALL
ok - Negative COMPOUND UNION ALL
ok - Positive COMPOUND INTERSECT
ok - Negative COMPOUND INTERSECT
ok - Positive COMPOUND EXCEPT
ok - Negative COMPOUND EXCEPT
```

**Comment by Gerold103** [comment] 2018-06-13 11:41
On Mac I got this:
```
msk-wifi-17fap4-v_shpilevoy-v:tarantool v.shpilevoy$ LUA_PATH='test/sql-tap/lua/?.lua;test/sql/lua/?.lua;;' ./src/tarantool test/sql-tap/gh2548-select-compound-limit.test.lua
TAP version 13
1..8
Bus error: 10
```

**Comment by Gerold103** [comment] 2018-06-13 11:42
Even on the reverted test-run ...

**Comment by Gerold103** [comment] 2018-06-13 11:44
.result file after running the test is empty both on reverted and on the last test-run

**Comment by Totktonada** [comment] 2018-06-13 11:50
.result file should not exists normally. The result of TAP13 test will be compared with the empty file that will lead to fail in case of correct TAP13 output. ( Yep, that is annoying; there is the issue: https://github.com/tarantool/test-run/issues/68 )

**Comment by Korablev77** [comment] 2018-06-13 11:51
Is it a duplicate of https://github.com/tarantool/tarantool/issues/3382 ?

**Comment by Gerold103** [comment] 2018-06-13 11:52
No, here I got `Bus error: 10` when running out of test-run.

**Comment by Gerold103** [comment] 2018-06-13 11:52
Funny stack:
```
thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x000000010b6a5e1e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5f030008, pDest=0x000000010e4126b8) at select.c:2442
    frame #1: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5f030008, pDest=0x000000010e4126b8) at select.c:5433
    frame #2: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5f02f408, pDest=0x000000010e412cc8) at select.c:2601
    frame #3: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5f02f408, pDest=0x000000010e412cc8) at select.c:5433
    frame #4: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5f02e808, pDest=0x000000010e4132d8) at select.c:2601
    frame #5: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5f02e808, pDest=0x000000010e4132d8) at select.c:5433
    frame #6: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5f02dc08, pDest=0x000000010e4138e8) at select.c:2601
    frame #7: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5f02dc08, pDest=0x000000010e4138e8) at select.c:5433
    frame #8: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5f02d008, pDest=0x000000010e413ef8) at select.c:2601
    frame #9: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5f02d008, pDest=0x000000010e413ef8) at select.c:5433
    frame #10: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e6269e8, pDest=0x000000010e414508) at select.c:2601
    frame #11: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e6269e8, pDest=0x000000010e414508) at select.c:5433
    frame #12: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e6274d8, pDest=0x000000010e414b18) at select.c:2601
    frame #13: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e6274d8, pDest=0x000000010e414b18) at select.c:5433
    frame #14: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e6276e8, pDest=0x000000010e415128) at select.c:2601
    frame #15: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e6276e8, pDest=0x000000010e415128) at select.c:5433
    frame #16: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e627888, pDest=0x000000010e415738) at select.c:2601
    frame #17: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e627888, pDest=0x000000010e415738) at select.c:5433
    frame #18: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e627a48, pDest=0x000000010e415d48) at select.c:2601
    frame #19: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e627a48, pDest=0x000000010e415d48) at select.c:5433
    frame #20: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e627c18, pDest=0x000000010e416358) at select.c:2601
    frame #21: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e627c18, pDest=0x000000010e416358) at select.c:5433
    frame #22: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e627de8, pDest=0x000000010e416968) at select.c:2601
    frame #23: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e627de8, pDest=0x000000010e416968) at select.c:5433
    frame #24: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e627fb8, pDest=0x000000010e416f78) at select.c:2601
    frame #25: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e627fb8, pDest=0x000000010e416f78) at select.c:5433
    frame #26: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e628188, pDest=0x000000010e417588) at select.c:2601
    frame #27: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e628188, pDest=0x000000010e417588) at select.c:5433
    frame #28: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e628358, pDest=0x000000010e417b98) at select.c:2601
    frame #29: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e628358, pDest=0x000000010e417b98) at select.c:5433
    frame #30: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e628528, pDest=0x000000010e4181a8) at select.c:2601
    frame #31: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e628528, pDest=0x000000010e4181a8) at select.c:5433
    frame #32: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e6286f8, pDest=0x000000010e4187b8) at select.c:2601
    frame #33: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e6286f8, pDest=0x000000010e4187b8) at select.c:5433
    frame #34: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e6288c8, pDest=0x000000010e418dc8) at select.c:2601
    frame #35: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e6288c8, pDest=0x000000010e418dc8) at select.c:5433
    frame #36: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e628a98, pDest=0x000000010e4193d8) at select.c:2601
    frame #37: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e628a98, pDest=0x000000010e4193d8) at select.c:5433
    frame #38: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e628c68, pDest=0x000000010e4199e8) at select.c:2601
    frame #39: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e628c68, pDest=0x000000010e4199e8) at select.c:5433
    frame #40: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e628e38, pDest=0x000000010e419ff8) at select.c:2601
    frame #41: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e628e38, pDest=0x000000010e419ff8) at select.c:5433
    frame #42: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e629008, pDest=0x000000010e41a608) at select.c:2601
    frame #43: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e629008, pDest=0x000000010e41a608) at select.c:5433
    frame #44: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e6291d8, pDest=0x000000010e41ac18) at select.c:2601
    frame #45: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e6291d8, pDest=0x000000010e41ac18) at select.c:5433
    frame #46: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e6293a8, pDest=0x000000010e41b228) at select.c:2601
    frame #47: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e6293a8, pDest=0x000000010e41b228) at select.c:5433
    frame #48: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e629578, pDest=0x000000010e41b838) at select.c:2601
    frame #49: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e629578, pDest=0x000000010e41b838) at select.c:5433
    frame #50: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e629748, pDest=0x000000010e41be48) at select.c:2601
    frame #51: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e629748, pDest=0x000000010e41be48) at select.c:5433
    frame #52: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e629918, pDest=0x000000010e41c458) at select.c:2601
    frame #53: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e629918, pDest=0x000000010e41c458) at select.c:5433
    frame #54: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e629ae8, pDest=0x000000010e41ca68) at select.c:2601
    frame #55: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e629ae8, pDest=0x000000010e41ca68) at select.c:5433
    frame #56: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e629cb8, pDest=0x000000010e41d078) at select.c:2601
    frame #57: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e629cb8, pDest=0x000000010e41d078) at select.c:5433
    frame #58: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e629e88, pDest=0x000000010e41d688) at select.c:2601
    frame #59: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e629e88, pDest=0x000000010e41d688) at select.c:5433
    frame #60: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a058, pDest=0x000000010e41dc98) at select.c:2601
    frame #61: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a058, pDest=0x000000010e41dc98) at select.c:5433
    frame #62: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a228, pDest=0x000000010e41e2a8) at select.c:2601
    frame #63: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a228, pDest=0x000000010e41e2a8) at select.c:5433
    frame #64: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a3f8, pDest=0x000000010e41e8b8) at select.c:2601
    frame #65: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a3f8, pDest=0x000000010e41e8b8) at select.c:5433
    frame #66: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a5c8, pDest=0x000000010e41eec8) at select.c:2601
    frame #67: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a5c8, pDest=0x000000010e41eec8) at select.c:5433
    frame #68: 0x000000010b6a671e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a798, pDest=0x000000010e41f698) at select.c:2601
    frame #69: 0x000000010b6a2aee tarantool`sqlite3Select(pParse=0x000000010e41f8b0, p=0x00007f8f5e62a798, pDest=0x000000010e41f698) at select.c:5433
    frame #70: 0x000000010b64c358 tarantool`yy_reduce(yypParser=0x00007f8f5f03e408, yyruleno=73) at parse.y:388
```

**Comment by Gerold103** [comment] 2018-06-13 11:53
```
(lldb) f 0
frame #0: 0x000000010b6a5e1e tarantool`multiSelect(pParse=0x000000010e41f8b0, p=0x00007f8f5f030008, pDest=0x000000010e4126b8) at select.c:2442
   2439		/* Make sure there is no ORDER BY or LIMIT clause on prior SELECTs.  Only
   2440		 * the last (right-most) SELECT in the series may have an ORDER BY or LIMIT.
   2441		 */
-> 2442		assert(p && p->pPrior);	/* Calling function guarantees this much */
   2443		assert((p->selFlags & SF_Recursive) == 0 || p->op == TK_ALL
   2444		       || p->op == TK_UNION);
   2445		db = pParse->db;
(lldb) p p && p->pPrior
(bool) $5 = true
```

**Comment by Gerold103** [comment] 2018-06-13 12:10
Maybe it is really duplicate of #3382. The backtrace almost the same.

**Comment by Khatskevich** [comment] 2018-10-02 11:11
Test fails on my machine until the b2afe208d12d0e02aa6ede4e3411128e30e87b1b .
Works well after the patch.

**Closed by Khatskevich** 2018-10-02 11:11 UTC
Labels: bug, sql, test-run.py
