### ISSUE TITLE
 ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5603] opened 2020-12-06 16:00 UTC
### Tarantool version:

```
Tarantool 2.7.0-48-g7f22903d6
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/clang /usr/bin/clang++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-gnu-alignof-expression -Werror -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Werror -Werror
```

### OS version:

CentOS Linux release 8.2.2004 (Core)

### Bug description:

Messages ` ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict` appears and most part of produced transactions failed when sync mode changed in loop (see content of test below).

```
[001] 2020-12-06 15:31:56.393 [3439308] main/307/lua vy_tx.c:670 E> ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict
[001] 2020-12-06 15:31:56.393 [3439308] main/309/lua vy_tx.c:670 E> ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict
```

### Steps to reproduce:

Issue can be reproduced with test below. Test also is in a branch `ligurio/gh-4842-qsync-testing` and was sent to mail list as regression test for synchronous replication [1].

1. https://lists.tarantool.org/pipermail/tarantool-patches/2020-November/020636.html

```
env = require('test_run')
test_run = env.new()
engine = test_run:get_cfg('engine')
fiber = require('fiber')

orig_synchro_quorum = box.cfg.replication_synchro_quorum
orig_synchro_timeout = box.cfg.replication_synchro_timeout

box.schema.user.grant('guest', 'replication')

-- Setup an cluster with two instances.
test_run:cmd('create server replica with rpl_master=default,\
                                         script="replication/replica.lua"')
test_run:cmd('start server replica with wait=True, wait_load=True')

-- Write data to a leader and enable/disable sync mode in a loop.
-- Testcase setup.
_ = box.schema.space.create('sync', {is_sync=true, engine=engine})
_ = box.space.sync:create_index('pk')

-- Testcase body.
for i = 1,100 do                                                               \
    box.cfg{replication_synchro_quorum=3, replication_synchro_timeout=1000}    \
    fiber.create(function() box.space.sync:insert{i} end)                      \
    mode = not box.space.sync.is_sync                                          \
    fiber.create(function() box.space.sync:alter{is_sync=mode} end)            \
    box.cfg{replication_synchro_quorum=2, replication_synchro_timeout=0.1}     \
end
box.space.sync:count() -- 100

-- Testcase cleanup.
test_run:switch('default')
box.space.sync:drop()

-- Teardown.
test_run:cmd('switch default')
test_run:cmd('stop server replica')
test_run:cmd('delete server replica')
test_run:cleanup_cluster()
box.schema.user.revoke('guest', 'replication')
box.cfg{                                                                       \
    replication_synchro_quorum = orig_synchro_quorum,                          \
    replication_synchro_timeout = orig_synchro_timeout,                        \
}
```

**Comment by alyapunov** [comment] 2021-07-01 11:56
I've reproduced the problem, but only for vinyl. In memtx it's always work. It seems that it's not a memtx MVCC problem.
<details>

```
======================================================================================
WORKR TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------------
[002] replication/qsync_sync_mode.test.lua            memtx           [ pass ]
[001] replication/qsync_sync_mode.test.lua            vinyl           [ fail ]
```
</details>

**Comment by Gerold103** [comment] 2021-07-02 21:55
Why it worked without qsync really depends on how did you remove qsync from the test. Because the only difference here qsync does is adds a latency to the transaction commit after it is written to WAL. Also qsync is engine-agnostic. That means if it works for memtx but does not for vinyl, the probability -> 100% that it is the problem of vinyl.

I simplified the test to not use qsync at all, and it still passes on memtx, but does not on vinyl. I ever removed the replication entirely. Which already means for sure, that the problem is either in memtx or in vinyl. Or in DDL. I remember there was something done for vinyl to rollback all transactions which are not committed at the moment of DDL start. It might be the reason. Although I don't know why the error reports a conflict then. There can't be conflicts - the keys do not intersect.
```Lua
test_run = require('test_run').new()
engine = test_run:get_cfg('engine')
fiber = require('fiber')

-- Testcase setup.
_ = box.schema.space.create('test', {engine=engine})
_ = box.space.test:create_index('pk')

-- Testcase body.
for i = 1,100 do                                                                \
    fiber.create(function() box.space.test:insert{i} end)                       \
    fiber.create(function() box.space.test:format({}) end)                      \
end
box.space.test:count() -- 100

box.space.test:drop()
```
Here count returns 100 on memtx, but 43 on vinyl:
```
[001] @@ -26,7 +26,7 @@
[001]   | ...
[001]  box.space.test:count() -- 100
[001]   | ---
[001] - | - 100
[001] + | - 43
[001]   | ...
```

**Comment by alyapunov** [comment] 2021-07-05 10:58
Thank for the test, qsync is above suspicion now.

**Comment by locker** [comment] 2021-07-06 08:25
Vinyl explicitly aborts all relevant transactions when a space is modified, see commits https://github.com/tarantool/tarantool/commit/d3e12369565151ba8c0632a84adab4bf90eff23f, https://github.com/tarantool/tarantool/commit/4f62ec2102f49ffb98c551944847d53664da5109. The reason for that is to avoid dereferencing a deleted struct space pointer after yield (any DDL creates a new struct space; all DML/DQL operations are passed a struct space; vinyl might want to use it after a yield caused by a disk read). The rationale for such a simple approach was that DDL is an infrequent operation and nobody should care about DML/DQL operations being aborted by it. The right approach would probably be passing some kind of space_proxy struct to all DML/DQL virtual functions instead of a raw struct space pointer. The space_proxy would look up a space by id in case space_cache_version has changed.

**Comment by locker** [comment] 2021-07-28 07:57
Pondered the problem some more. Ideally, we need schema versioning to fix this issue, but this feature isn't even planned yet. Other possible fixes I see are essentially workarounds:

- Add space_proxy object, which would look up a space by id whenever space_cache_version has changed. Use this object in Vinyl DML so that we don't need to abort operations that yielded on disk read (e.g. to check key uniqueness) whenever a space is updated. This is a way to go, but the code would look rather ugly after this change (all space accesses in vy_replace, vy_insert, etc would have to go through space_proxy_get).
- Do not replace space object on every DDL. Do it only if the set of indexes actually changes. However, this would require a major alter.cc rework. I don't think this bug justifies that.

Is there a better, less intrusive approach? I was thinking of introducing fiber.on_resume trigger and patching space pointers to point to a new space after a yield issued by a DML operation. This would eliminate the space_cache_version check on every space access, but we would still need some wrapper object around a space pointer in Vinyl.

BTW memtx should be affected by this issue as well, because the metmx transaction manager stores pointers to spaces, but to reproduce it, one has to explicitly yield in a transaction. We need to achieve a consistent behavior between the two engines, if possible.

For now, I'm not sure that this bug is critical enough to complicate the DML code. After all, DDL (even changing space options) is a very infrequent operation AFAIU, and aborting some transactions for it should be fine. Besides, even if we do fix this issue, we will still have to abort some transactions for heavy DDL operations, such us creation of a new index or format change.

**Comment by locker** [comment] 2021-07-28 10:10
Another option: copy all data from the space needed to perform a DML operation to the region and inc ref counter of all its indexes.

**Comment by locker** [comment] 2021-07-28 12:15
Another option: instead of aborting DML operations stuck in disk read, we could retry them: make disk read return "need retry" error instead of "aborted"; if such an error is received, look up the space again and retry the operation from the beginning. Ideally, retry would be done on the top level (in box_process).

**Comment by locker** [comment] 2021-07-28 13:50
txn_stmt struct contains a link to the space. It isn't used by Vinyl, but it is accessed by txn_commit_stmt (to run on_replace triggers). If we fix the issue in Vinyl by copying space data, as suggested [here](https://github.com/tarantool/tarantool/issues/5603#issuecomment-888185502), or by introducing a space_proxy, as suggested [here](https://github.com/tarantool/tarantool/issues/5603#issuecomment-888098473), we will get a crash.

**Comment by locker** [comment] 2021-07-28 13:51
Another idea: protect the space cache with an rw lock. Will post the details in a separate ticket.

**Comment by kostja** [comment] 2021-07-30 14:42
Please don't add any hacks around lack of a versioned data dictionary.
A DDL lock will introduce yields in places where they are undesired or make DDL not online.

**Comment by locker** [comment] 2021-08-06 10:56
We aren't going to proceed with DDL lock (see [my comment](https://github.com/tarantool/tarantool/issues/6264#issuecomment-894177160)).

Let's try to replace `space:insert` with `space:replace` in the test. The latter doesn't yield so it should fix it (well, technically it may yield, but only if we are about to hit the memory limit, which shouldn't happen in this test).

**Comment by locker** [comment] 2021-08-12 08:37
Turns out Vinyl transactions yield in this test not because of disk reads - they are in fact throttled by the write rate limiter - so using `replace` instead of `insert` wouldn't help. The test should retry a transaction if it sees `TRANSACTION_CONFLICT` error. Pushed the [fix](https://github.com/tarantool/tarantool/commit/2fa3d652cddb1276a34170fe5ee60f30edc37c78) to branch [ligurio/gh-4842-qsync-testing](https://github.com/tarantool/tarantool/tree/ligurio/gh-4842-qsync-testingligurio/gh-4842-qsync-testing).

**Closed by locker** 2021-08-12 08:37 UTC
Labels: bug, vinyl, qsync replication, 3sp, teamC
