### ISSUE TITLE
Support HASH index type in SQL

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2997] opened 2017-12-14 08:33 UTC
Introduce support for hashing indexes in SQL.
Need to:
1. Introduce most appropriate syntax for definition of index type
2. VDBE should emit DDL which takes index type into account while creating
corresponding Tarantool index

**Comment by Korablev77** [comment] 2021-02-15 14:14
Duplicate of #3752

**Closed by Korablev77** 2021-02-15 14:14 UTC
Labels: feature, sql
