### ISSUE TITLE
ddl: rollback of space:drop() does not revert state of Lua object

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#6470] opened 2021-09-27 08:57 UTC
Note that it has nothing to do with MVCC, bug is reproduced in regular memtx mode:
```
s = box.schema.space.create('test')
_ = s:create_index('primary')
box.begin() s:drop() box.rollback()
s
...
  index: []
  name: test
  id: 512
...

s:select()
---
- error: 'No index #0 is defined in space ''test'''
...

```
Meanwhile `box.space.test:select()` is fine:

```
tarantool> box.space.test:select()
---
- []
...
```

**Comment by locker** [comment] 2022-06-03 14:54
Here's what happens:
1. `box.begin()`.
2. `s:drop()` drops the space index, which triggers update of the Lua state - `box.space.test`. Since `s` is a reference to the `box.space.test` table, the change is reflected to it as well. This is okay, because in the transaction the index doesn't exist anymore and should be inaccessible.
3. `s:drop()` then drops the space, which deletes a reference to `box.space.test` from `box.space`. Again, this is okay, because the space doesn't exist in the transaction anymore.
4. `box.rollback()` restores the Lua state. Since `box.space.test` doesn't exist (was deleted at the previous step), it will create a new table in `box.space`, which will be different from `s` and hence `s` stops working.

We could cook up a quick fix to this issue by temporarily storing the deleted `box.space.test` table somewhere in an internal table until transaction ends and restoring it on rollback. However, the proper way to fix this issue is to introduce multi-version schema (#600), which would make it possible to present different views of the data dictionary in different transactions. Multi-version schema is orthogonal to the quick fix. Since the issue is non-critical and none of our customers ever complained about this behavior, let's close this ticket in favor of #600.

**Closed by locker** 2022-06-03 14:54 UTC
Labels: bug, ddl, 5sp, teamC
