### ISSUE TITLE
Stored procs inconsistency 

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#9010] opened 2023-08-22 12:28 UTC
**Tarantool version:** 2.11.1

**Bug description**

Given two stored procs in C and Lua their result is inconsistent when called via `box.schema.func.call` and `netbox.call`.

```console
tarantool> box.schema.func.call("foo")
---
- true
- a
...

tarantool> box.schema.func.call("libfoo.proc_c")
---
- true
- a
...

tarantool> conn:call("foo")
---
- true
- a
...

tarantool> conn:call("libfoo.proc_c")
---
- [true, 'a']
...
```

See the excessive array in the last case.

**Background**

```lua
box.schema.func.create('libfoo.proc_c', {language = "C"})
box.schema.func.create('foo', {language = "LUA"})
```

```lua
function foo()
     return true, "a"
end
```

```c
int proc_c(box_function_ctx_t *ctx, const char *args, const char *args_end)
{
    const char *mp1 = "\xc3"; // true
    const char *mp2 = "\xa1\x61"; // "a"

    box_return_mp(ctx, mp1, mp1 + 1);
    box_return_mp(ctx, mp2, mp2 + 2);
    return 0;
}
```

**Comment by igormunkin** [comment] 2023-08-22 12:43
Duplicate of #4799.

**Closed by igormunkin** 2023-08-22 12:43 UTC
Labels: bug
