### ISSUE TITLE
Allow to override engine on replica

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2897] opened 2017-11-08 07:00 UTC
User case: master uses memtx, replica uses vinyl. 
Let's try to find a way to support this use case.

**Comment by rtsisyk** [comment] 2017-11-08 07:01
Block Vinyl adoption for Mail.Ru customer.

**Comment by rtsisyk** [comment] 2017-11-08 07:04
raw idea: add an option to force engine globally, then disable _space triggers, update space.engine value, save a snapshot.

**Comment by locker** [comment] 2017-11-13 15:16
Alternatives:
1. Add a new `box.cfg()` option, say `replication_override_engine = [ 'vinyl' | 'memtx' ]`, that would override the engine in all tuples corresponding to user spaces inserted into `_space` by applier threads.
2. Same as 1, but override engine for all user spaces, not just for those created by replication. The option is called `engine_override`.
3. Same as 2, but do not change tuples in `_space`, just override the engine. Ugly as the user can't drop this option even after replication has been disabled and the replica has been set to be used in production.
4. Add a new space trigger that would allow to filter/update tuples inserted into the space it is set on. Then use this trigger to change 'memtx' to 'vinyl' in tuples inserted into the `_space` system space. The problem is the trigger should be set before `box.cfg()`, when `_space` is not available, so we should add a configuration option for setting the trigger anyway. It's unclear if the trigger can be reused for any other purposes.
5. Split join and subscribe replication stages (i.e. allow to perform join without subscribe on replica). After joining a replica, call `space.alter` to change the engine. Then subscribe. Problems: `alter` doesn't allow to change space engine; the configuration procedure is likely to look cumbersome.

I vote for no. 1.

**Comment by kostja** [comment] 2017-11-13 15:29
Why is not logical replication listed among alternatives?

**Comment by locker** [comment] 2017-11-13 16:25
> Why is not logical replication listed among alternatives?

Because logical replication implies that the user calls stored procedures for data manipulation, which is not always the case. AFAIU in the scope of this issue we are talking about an automatic solution that would minimize user efforts.

**Comment by kostja** [comment] 2017-11-29 14:03
I talked @rtsisyk out of this idea, I hope.

**Comment by kostja** [comment] 2018-01-12 07:56
This problem will be fixed with https://github.com/tarantool/tarantool/issues/2993

**Comment by rtsisyk** [comment] 2018-01-29 16:22
> This problem will be fixed with #2993

Please elaborate

**Comment by kostja** [comment] 2018-02-13 17:40
Set a before trigger which skips DDL if box.session.type() == applier.
And create any spaces and indexes you like - they will differ in any way you like.

**Closed by kostja** 2018-02-13 17:40 UTC
Labels: complicated, customer, vinyl
