### ISSUE TITLE
Failed to commit large transaction

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#904] opened 2015-07-08 10:00 UTC
```lua
box.cfg{ wal_mode = 'write' }

space = box.schema.space.create('test', {
    engine = 'memtx',
})

space:create_index('primary', {
    type = 'TREE', parts = {1, 'STR',}
})

function test()
    while true do
        box.begin()
        for i = 1, 500 do
            space:replace{ 'key_' .. tostring(i) }
        end
        box.commit()
    end
end

test()
```

```sh
./tarantool test.lua 
2015-07-08 12:59:21.077 [8996] main/101/test.lua C> version 1.6.5-221-g4929dda
2015-07-08 12:59:21.077 [8996] main/101/test.lua C> log level 5
2015-07-08 12:59:21.077 [8996] main/101/test.lua I> mapping 1073741824 bytes for a shared arena...
2015-07-08 12:59:21.078 [8996] main/101/test.lua I> initializing an empty data directory
2015-07-08 12:59:21.086 [8996] snapshot/101/main I> creating `./00000000000000000000.snap.inprogress'
2015-07-08 12:59:21.086 [8996] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2015-07-08 12:59:21.086 [8996] snapshot/101/main I> done
2015-07-08 12:59:21.093 [8996] main/101/test.lua I> ready to accept requests
2015-07-08 12:59:21.093 [8996] wal I> creating `./00000000000000000000.xlog.inprogress'
2015-07-08 12:59:21.098 [8996] main/101/test.lua txn.cc:154 E> ER_WAL_IO: Failed to write to disk
2015-07-08 12:59:21.098 [8996] main/101/test.lua F> Failed to write to disk
```

**Comment by kostja** [comment] 2015-08-12 21:34
A duplicate of gh-916

**Closed by kostja** 2015-08-12 21:34 UTC
Labels: bug
