### ISSUE TITLE
Tarantool 1.10 build fails on Mac with brew

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#4665] opened 2019-12-03 15:18 UTC
Tarantool version:
1.10 --HEAD

OS version:
MacOS 10.14.6

brew install/reinstall tarantool
==> Reinstalling tarantool
==> Cloning https://github.com/tarantool/tarantool.git
Updating /Users/opomuc/Library/Caches/Homebrew/tarantool--git
==> Checking out branch 1.10
Already on '1.10'
Your branch is behind 'origin/1.10' by 26 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 9d3a6cd97 json: fix stack-use-after-scope in json_decode()
Entering 'src/lib/msgpuck'
Entering 'src/lib/small'
Entering 'test-run'
Synchronizing submodule url for 'lib/msgpack-python'
Synchronizing submodule url for 'lib/tarantool-python'
Entering 'test-run/lib/msgpack-python'
Entering 'test-run/lib/tarantool-python'
Synchronizing submodule url for 'test-run'
Entering 'test-run/lib/tarantool-python/test-run'
Synchronizing submodule url for 'lib/msgpack-python'
Synchronizing submodule url for 'lib/tarantool-python'
Entering 'test-run/lib/tarantool-python/test-run/lib/msgpack-python'
Entering 'test-run/lib/tarantool-python/test-run/lib/tarantool-python'
Entering 'third_party/curl'
Entering 'third_party/libyaml'
Entering 'third_party/luafun'
Entering 'third_party/luajit'
Entering 'third_party/luarocks'
Entering 'third_party/zstd'
Submodule path 'src/lib/small': checked out '086f51f0cc7cb3bf3f7879257bf9df296b5995f4'
Submodule path 'third_party/luajit': checked out 'd4e985a159639e8ad8a83b792e1883a294761c05'
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/src/lib/msgpuck
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/src/lib/small
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/test-run
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/test-run/lib/msgpack-python
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/test-run/lib/tarantool-python
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/test-run/lib/tarantool-python/test-run
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/test-run/lib/tarantool-python/test-run/lib/msgpack-python
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/test-run/lib/tarantool-python/test-run/lib/tarantool-python
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/third_party/curl
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/third_party/libyaml
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/third_party/luafun
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/third_party/luajit
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/third_party/luarocks
/Users/opomuc/Library/Caches/Homebrew/tarantool--git/third_party/zstd
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/HEAD-
==> make
Last 15 lines from /Users/opomuc/Library/Logs/Homebrew/tarantool/02.make:
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -O2 -Wall -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE  -fno-stack-protector  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -Wno-parentheses-equality -Wno-tautological-compare -Wno-misleading-indentation -Wno-varargs -Wno-implicit-fallthrough -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -c -o lib_ffi.o lib_ffi.c
CC        lj_opt_fold.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -O2 -Wall -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE  -fno-stack-protector  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -Wno-parentheses-equality -Wno-tautological-compare -Wno-misleading-indentation -Wno-varargs -Wno-implicit-fallthrough -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -c -o lj_opt_fold.o lj_opt_fold.c
AR        libluajit.a
/usr/bin/ar rcus libluajit.a lj_vm.o lj_gc.o lj_err.o lj_char.o lj_bc.o lj_obj.o lj_buf.o lj_str.o lj_tab.o lj_func.o lj_udata.o lj_meta.o lj_debug.o lj_state.o lj_dispatch.o lj_vmevent.o lj_vmmath.o lj_strscan.o lj_strfmt.o lj_strfmt_num.o lj_api.o lj_profile.o lj_lex.o lj_parse.o lj_bcread.o lj_bcwrite.o lj_load.o lj_ir.o lj_opt_mem.o lj_opt_fold.o lj_opt_narrow.o lj_opt_dce.o lj_opt_loop.o lj_opt_split.o lj_opt_sink.o lj_mcode.o lj_snap.o lj_record.o lj_crecord.o lj_ffrecord.o lj_asm.o lj_trace.o lj_gdbjit.o lj_ctype.o lj_cdata.o lj_cconv.o lj_ccall.o lj_ccallback.o lj_carith.o lj_clib.o lj_cparse.o lj_lib.o lj_alloc.o lib_aux.o lib_base.o lib_math.o lib_bit.o lib_string.o lib_table.o lib_io.o lib_os.o lib_package.o lib_debug.o lib_jit.o lib_ffi.o lib_init.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libluajit.a(lj_opt_split.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libluajit.a(lj_gdbjit.o) has no symbols
[ 12%] Built target libluajit
[ 13%] Linking C static library libzstd.a
/usr/local/Cellar/cmake/3.13.2/bin/cmake -P CMakeFiles/zstd.dir/cmake_clean_target.cmake
/usr/local/Cellar/cmake/3.13.2/bin/cmake -E cmake_link_script CMakeFiles/zstd.dir/link.txt --verbose=1
/usr/bin/ar qc libzstd.a  CMakeFiles/zstd.dir/third_party/zstd/lib/common/zstd_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/entropy_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/error_private.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/pool.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/xxhash.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/fse_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/zstd_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/huf_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_double_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_lazy.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_opt.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o
/usr/bin/ranlib libzstd.a
[ 13%] Built target zstd
make: *** [all] Error 2

**Comment by opomuc** [comment] 2019-12-05 15:16
The fix from #4664 seems to do the trick

**Comment by Totktonada** [comment] 2019-12-05 15:38
Thanks for the verification.

Duplicate of #4664.

**Closed by Totktonada** 2019-12-05 15:38 UTC
