### ISSUE TITLE
Assertion with syslog log

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3329] opened 2018-04-08 16:34 UTC
I have Ubuntu 14.04.
I have Tarantool 2.0, pulled from source today.
I get an assertion with box.cfg{log = 'syslog ...'}
Example:
tarantool> box.cfg{log = 'syslog:identity=tarantool'}
tarantool: /home/pgulutzan/tarantool-2.0/src/diag.h:222: void diag_raise(): Assertion `e != __null' failed.
Aborted (core dumped)

**Comment by kyukhin** [comment] 2018-04-16 08:46
@pgulutzan , does this issue for 2-0 only?

**Comment by pgulutzan** [comment] 2018-04-16 21:35
It happens in Tarantool version 2.0.4. In an earlier version, nothing interesting happens:
"
Tarantool 1.10.0-123-g130cb45
type 'help' for interactive help
tarantool> box.cfg{log = 'syslog:identity=tarantool'}
started logging into a syslog, SIGHUP log rotation disabled
"

**Comment by kyukhin** [comment] 2018-07-05 15:14
Duplicate of #3502

**Closed by kyukhin** 2018-07-05 15:14 UTC
