### ISSUE TITLE
Incorrect datetime output in tuple if printed or logged

### ISSUE THREAD

**Issue by extde** [tarantool/tarantool#9349] opened 2023-11-09 09:00 UTC
**Incorrect datetime output in tuple if printed or logged**

This issue affects tuple datetime printing via ```print()``` or ```log.info()```.
Date expected but ```null``` printed.

* OS: [e.g. Linux]
* OS Version: [Alpine 3.15.6]
* Architecture: [amd64]

```
Tarantool 2.11.1-0-g96877bd35
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-10.3.1
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/usr/src/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/usr/src/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Run tarantool instance iteractively. Log into console.

1. Type in console ```datetime = require('datetime')```
1. Type in console ```date, len = datetime.parse('2023-11-09T07:56:18.971455Z')```
1. Type in console ```tuple = box.tuple.new({d})```
1. Type in console ```print(tuple)```
1. Type in console ```tuple```
1. Result printed in console ```['2023-11-09T07:56:18.971455Z']```

**Actual behavior**

Check log file printed ```2023-11-09 11:37:49 [null]```

**Expected behavior**

Log file should print ```2023-11-09 11:37:49 ['2023-11-09T07:56:18.971455Z']```

**Comment by olegrok** [comment] 2023-11-09 09:04
Duplicate of https://github.com/tarantool/tarantool/issues/7219

**Closed** 2023-11-10 07:39 UTC
Labels: bug
