### ISSUE TITLE
build: port autoconf to cmake in curl build

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4968] opened 2020-05-13 06:36 UTC
Tarantool version:
All

OS version:
All

Bug description:
Need to port autoconf to cmake usage in curl build

Patch with changes (checked with third_party/curl/CMakeLists.txt file):

0.
```
diff --git a/cmake/BuildLibCURL.cmake b/cmake/BuildLibCURL.cmake
index 02f7ef95f..40a850027 100644
--- a/cmake/BuildLibCURL.cmake
+++ b/cmake/BuildLibCURL.cmake
@@ -57,98 +57,7 @@ macro(curl_build)
         TMP_DIR ${LIBCURL_BINARY_DIR}/tmp
         STAMP_DIR ${LIBCURL_BINARY_DIR}/stamp
         BINARY_DIR ${LIBCURL_BINARY_DIR}/curl
-        CONFIGURE_COMMAND
-            rsync -a <SOURCE_DIR> <BINARY_DIR>/.. &&
-            cd <BINARY_DIR> && ./buildconf && ./configure
-                # Pass the same toolchain as is used to build
-                # tarantool itself, because they can be
-                # incompatible.
```
changed:
```
0. Do we really needed, seems yes: -DBUILD_TESTING=OFF
```

1.
```
-                CC=${CMAKE_C_COMPILER}
-                LD=${CMAKE_LINKER}
-                AR=${CMAKE_AR}
-                RANLIB=${CMAKE_RANLIB}
-                NM=${CMAKE_NM}
-                STRIP=${CMAKE_STRIP}
-
```
changed:
```
1. no need
```

2.
```
-                # Pass -isysroot=<SDK_PATH> option on Mac OS, see
-                # above.
-                # Note: Passing of CPPFLAGS / CFLAGS explicitly
-                # discards using of corresponsing environment
-                # variables.
-                CPPFLAGS=${LIBCURL_CPPFLAGS}
-                CFLAGS=${LIBCURL_CFLAGS}
-
```
changed (after review removed, check comments in discussion below):
```
2.1. ${CPPFLAGS}=${LIBCURL_CPPFLAGS} -> -DCPPFLAGS=${LIBCURL_CPPFLAGS}
2.2. ${CFLAGS}=${LIBCURL_CFLAGS} -> -DCFLAGS=${LIBCURL_CFLAGS}
```

3.
```
-                # Pass empty LDFLAGS to discard using of
-                # corresponding environment variable.
-                # It is possible that a linker flag assumes that
-                # some compilation flag is set. We don't pass
-                # CFLAGS from environment, so we should not do it
-                # for LDFLAGS too.
-                LDFLAGS=
-
```
changed:
```
3.1. ${LDFLAGS}= -> -DLDFLAGS=
```

4.
```
-                --prefix <INSTALL_DIR>
-                --enable-static
-                --disable-shared
-                --disable-symbol-hiding
-
```
changed:
```
4.1. --prefix -> -DCMAKE_INSTALL_PREFIX
4.2. --enable-static -> -DCURL_STATICLIB=ON
4.3. --disable-shared (changed during review, check comments in discussion below) -> -DBUILD_SHARED_LIBS=OFF
4.4. --disable-symbol-hiding (added during review, check comments in discussion below) -> -DCURL_HIDDEN_SYMBOLS=OFF
```

5.
```
-                --with-zlib=${FOUND_ZLIB_ROOT_DIR}
-                ${LIBCURL_OPENSSL_OPT}
-                --with-ca-fallback
-
```
changed:
```
5.1. --with-zlib==${FOUND_ZLIB_ROOT_DIR} -> list(APPEND LIBCURL_CMAKE_FLAGS "-DZLIB_ROOT=${FOUND_ZLIB_ROOT_DIR}")
+    list(APPEND LIBCURL_CMAKE_FLAGS "-DCURL_ZLIB=OFF")

5.2. ${LIBCURL_OPENSSL_OPT} ->
           -DOPENSSL_ROOT_DIR=${FOUND_OPENSSL_ROOT_DIR}     
           -DCMAKE_USE_OPENSSL=ON

5.3. --with-ca-fallback -> -DCURL_CA_FALLBACK=ON
```

6.
```
-                --without-brotli
-                --without-gnutls
-                --without-mbedtls
-                --without-cyassl
-                --without-wolfssl
-                --without-mesalink
-                --without-nss
-                --without-ca-bundle
-                --without-ca-path
-                --without-libpsl
-                --without-libmetalink
-                --without-librtmp
-                --without-winidn
-                --without-libidn2
-                --without-nghttp2
-                --without-ngtcp2
-                --without-nghttp3
-                --without-quiche
-                --without-zsh-functions-dir
-                --without-fish-functions-dir
-
```
changed:
```
6.1 (is default) --without-brotli -> -DCURL_BROTLI=OFF
6.2 (is default) --without-gnutls -> -DUSE_GNUTLS=OFF
6.3 (is default) --without-mbedtls -> -DCMAKE_USE_MBEDTLS=OFF
6.4 --without-cyassl -> NOT FOUND !
6.5 (is default) --without-wolfssl -> -DCMAKE_USE_WOLFSSL=OFF
6.6 --without-mesalink -> NOT FOUND !
6.7 (is default) --without-nss -> -DCMAKE_USE_NSS=OFF
6.8 (is default) --without-ca-bundle -> -DCURL_CA_BUNDLE=none
6.9 (is default) --without-ca-path -> -DCURL_CA_PATH=none
6.10 --without-libpsl -> NOT FOUND !
6.11 --without-libmetalink -> NOT FOUND !
6.12 (is default) --without-librtmp -> -DUSE_LIBRTMP=OFF
6.13 --without-winidn -> NOT FOUND !
6.14 (is default) --without-libidn2 -> -DHAVE_LIBIDN2=OFF
6.15 (is default) --without-nghttp2 -> -DUSE_NGHTTP2=OFF
6.16 (is default) --without-ngtcp2 -> -DUSE_NGTCP2=OFF
6.17 (is default) --without-nghttp3 -> -DUSE_NGHTTP3=OFF
6.18 (is default) --without-quiche -> -DUSE_QUICHE=OFF
6.19  --without-zsh-functions-dir -> NOT FOUND !
6.20  --without-fish-functions-dir -> NOT FOUND !
```

7.
```
-                ${ENABLED_DNS_OPT}
-                --enable-http
-                --enable-proxy
-                --enable-ipv6
-                --enable-unix-sockets
-                --enable-cookies
-                --enable-http-auth
-                --enable-mime
-                --enable-dateparse
-
```
changed:
```
7.1. ${ENABLED_DNS_OPT} ->
           -DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}
           -DENABLE_ARES=${ENABLE_ARES}
7.2. (is default) --enable-http -> -DCURL_DISABLE_HTTP=OFF
7.3. (is default) --enable-proxy -> -DCURL_DISABLE_PROXY=OFF
7.4. (is default) --enable-ipv6 -> -DENABLE_IPV6=ON
7.5. (is default) --enable-cookies -> -DCURL_DISABLE_COOKIES=OFF
7.6. (is default) --enable-cookies -> -DENABLE_UNIX_SOCKETS=ON
7.7. --enable-http-auth -> NOT FOUND !
7.8. --enable-mime -> NOT FOUND !
7.9. --enable-dateparse -> NOT FOUND !
```

8.
```
-                ${DISABLED_DNS_OPT}
-                --disable-ftp
-                --disable-file
-                --disable-ldap
-                --disable-ldaps
-                --disable-rtsp
-                --disable-dict
-                --disable-telnet
-                --disable-tftp
-                --disable-pop3
-                --disable-imap
-                --disable-smb
-                --disable-smtp
-                --disable-gopher
-                --disable-manual
-                --disable-sspi
-                --disable-crypto-auth
-                --disable-ntlm-wb
-                --disable-tls-srp
-                --disable-doh
-                --disable-netrc
-                --disable-progress-meter
-                --disable-dnsshuffle
-                --disable-alt-svc
```
changed:
```
8.1. (no need, opposite to ENABLE_ARES) ${DISABLED_DNS_OPT}
8.2. check list below -> -DHTTP_ONLY=ON (options set all below):
--disable-ftp -> set(CURL_DISABLE_FTP ON)
--disable-file -> set(CURL_DISABLE_FILE ON)
--disable-ldap -> set(CURL_DISABLE_LDAP ON)
--disable-ldaps -> set(CURL_DISABLE_LDAPS ON)
--disable-rtsp -> set(CURL_DISABLE_RTSP ON)
--disable-dict -> set(CURL_DISABLE_DICT ON)
--disable-telnet -> set(CURL_DISABLE_TELNET ON)
--disable-tftp -> set(CURL_DISABLE_TFTP ON)
--disable-pop3 -> set(CURL_DISABLE_POP3 ON)
--disable-imap -> set(CURL_DISABLE_IMAP ON)
--disable-smtp -> set(CURL_DISABLE_SMTP ON)
8.3. --disable-smb -> -DCURL_DISABLE_SMB=ON
8.4. --disable-gopher -> -DCURL_DISABLE_GOPHER=ON
8.5. --disable-crypto-auth -> -DCURL_DISABLE_CRYPTO_AUTH=ON
8.6. NOT FOUND ! list below:
--disable-manual
--disable-sspi
--disable-ntlm-wb (missing option _add_if("NTLM_WB"     NOT CURL_DISABLE_HTTP AND NTLM_WB_ENABLED))
--disable-tls-srp (missing option, depends on GNUTLS_SRP/OPENSSL_SRP)
--disable-doh
--disable-netrc
--disable-progress-meter
--disable-dnsshuffle
--disable-alt-svc
```

9. new options found in cmake blocked:
```
+    list(APPEND LIBCURL_CMAKE_FLAGS "-DPICKY_COMPILER=OFF")
+    list(APPEND LIBCURL_CMAKE_FLAGS "-DBUILD_CURL_EXE=OFF")
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment] 2020-05-13 08:06
Duplicate of #4444.

**Comment by avtikhon** [comment] 2020-05-21 09:25
Found that CURL cmake configuration file:
      third_party/curl/lib/CMakeLists.txt
    
    has installation part for built libcurl.a library:
      install(TARGETS ${LIB_NAME}
        EXPORT ${TARGETS_EXPORT_NAME}
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    
    where it changes CMAKE_INSTALL_LIBDIR to appropriate name with
    suffix of the architecture, like:
      lib
      lib64
      x86_64
    
    Found that find_library routine from the file:
      cmake/FindLibCURL.cmake
    
    returns only 'lib' value and it breaks the building of the depends
    binaries. To avoid of it the CMAKE_INSTALL_LIBDIR option was set to
    cmake call:
      -DCMAKE_INSTALL_LIBDIR=lib

**Comment by avtikhon** [comment] 2020-05-22 06:26
Only issue left that libcurl build doesn't support old CMake 2.*:
```
CMake Error at CMakeLists.txt:41 (cmake_minimum_required):
   CMake 3.0 or higher is required.  You are running version 2.8.12.2
```
discussion: https://github.com/jpbarrette/curlpp/issues/35
solution: https://github.com/jpbarrette/curlpp/pull/37

**Comment by tsafin** [comment] 2020-05-22 07:20
> Only issue left that libcurl build doesn't support old CMake 2.*:

It sounds like a non-issue to me - so just install `cmake3` on the build machine, and be done with it. No?

Why and where, on which targets os, we have to use `cmake` 2.*?
[FWIW, cmake 3.0 has been released in 2014, today is 2020 :)]

**Comment by avtikhon** [comment] 2020-05-22 12:38
> > Only issue left that libcurl build doesn't support old CMake 2.*:
> 
> It sounds like a non-issue to me - so just install `cmake3` on the build machine, and be done with it. No?
> 
> Why and where, on which targets os, we have to use `cmake` 2.*?
> [FWIW, cmake 3.0 has been released in 2014, today is 2020 :)]

That's not the issue in real, but we must save the backport ability to use the Tarantool build on both cmake version. In the patch I've found the simplest solution - I use that cmake that available and run autoconf either cmake appropriate found cmake version. This patch is not the target, it's just the bonus of implementing OOS build and in general we didn't want to port all builds to cmake - we just use it were it is possible.

**Comment by avtikhon** [comment] 2020-05-26 07:53
Depends on:
https://github.com/tarantool/tarantool/issues/5019
https://github.com/tarantool/tarantool/issues/5020

**Comment by Totktonada** [comment] 2020-09-15 02:18
2020-06-05 I saved some notes around those options, but had no time to look over all. Still no time for this, so I'll dump notes as is. Some of them are a bit obsolete: say, we already on curl-7_71_1 and we have explicit export list for curl symbols (so the dynamic library is not necessary).

----

Alexander, thanks for the detailed list of changes!

First of all, please target CMakeLists.txt from curl-7_71_1, since we'll update it in #4698. You can look the list of changes using `git log -p curl-7_66_0..curl-7_71_1 CMakeLists.txt` command (or [here](https://github.com/curl/curl/commits/curl-7_71_1/CMakeLists.txt) starting from `df85b86`, inclusive).

> 2.1. ${CPPFLAGS}=${LIBCURL_CPPFLAGS} -> -DCPPFLAGS=${LIBCURL_CPPFLAGS}
> 2.2. ${CFLAGS}=${LIBCURL_CFLAGS} -> -DCFLAGS=${LIBCURL_CFLAGS}

I had a hope that it will not needed at all when we'll move from autotools to CMake. I mean, CMake will add `-isysroot=<SDK_PATH>` for curl on its own as CMake do it for tarantool. @avtikhon Can you verify that it can be dropped?

> 3.1. ${LDFLAGS}= -> -DLDFLAGS=

I hope it will not needed if we will not pass LIBCURL_{C,CPP}FLAGS. See the explanation in 0bead6004b9eb8317bc8906122d305563a7dac0d. @avtikhon Please, verify it.

> 4.3. --enable-shared -> -DBUILD_SHARED_LIBS=OFF

You're right that the dynamic libcurl library is not used anywhere now. I left it in 7e51aebb9cd496b1b50b766ce00bf69a20a6d4b1 with the idea that we'll use it to collect symbols to export from the tarantool executable. It becomes less important with #2971 resolving, but even after this the list of surely exported symbols exists (`src/exports.[ch]`) and maybe it should be populated with libcurl.so symbols. So I think the decision whether we should build the dynamic libcurl library is out of scope of this issue. But let's disable it with a proper comment in the commit message, if it give some problems. Otherwise it would be better to keep it, IMHO.

> 6. no need

I'll comment per-option below.

> -                --without-brotli

I'll describe the background a bit. We would understand each other without it, but if someone else will read the discussion, it may be helpful.

----

When no `--with[out]-brotli` option is given, configure.ac enables brotli support if libbrotlidec.so (the decoding library) is found by default paths on a build system. As result, libcurl.a requires symbols that are defined in libbrotlidec.so. This is bad for us in different ways.

First, it'll lead to an `undefined reference to <...>` error at linking tarantool executable. A linker is unable to find symbols that are defined in libbrotlidec.so, but the linker see that code requires it. Why not just add libbrotlidec.so to libraries we link with?

Our executable should not depend on libraries we don't have in RPM / Deb package dependencies. Otherwise a user will observe `error while loading shared libraries` error if its system does not have brotli library installed. Why not to add the library to RPM / Deb dependencies?

As far as I see, this encoding is not widely used on HTTP servers, usual choice is gzip. It is not worth the work on verifying that it exists on all supported platforms or introducing extra complexity with conditional build with/without brotli support.

----

Back to the change. Curl's CMake logic is different: it has brotli disabled by default. We can remove the option or disable it explicitly: the result will be the same. At least for the current version of curl.

I would prefer to disable explitily everything that should be disabled, because I don't know how defaults will be changed in a future and I don't want to verify them each time we'll bump new libcurl version.

Another way is try to keep our CMake files as small as possible and lean on defaults, but see: it neither improves readability (one need to dive into curl's CMakeLists.txt to obtain exact list of enabled or disabled features), nor improves stability (as explained above).

So I vote to list all options explicitly even when our choice is the same as default.

**Comment by avtikhon** [comment] 2020-10-08 08:15
> 2020-06-05 I saved some notes around those options, but had no time to look over all. Still no time for this, so I'll dump notes as is. Some of them are a bit obsolete: say, we already on curl-7_71_1 and we have explicit export list for curl symbols (so the dynamic library is not necessary).
> 
> Alexander, thanks for the detailed list of changes!
> 
> First of all, please target CMakeLists.txt from curl-7_71_1, since we'll update it in #4698. You can look the list of changes using `git log -p curl-7_66_0..curl-7_71_1 CMakeLists.txt` command (or [here](https://github.com/curl/curl/commits/curl-7_71_1/CMakeLists.txt) starting from `df85b86`, inclusive).
> 
> > 2.1. ${CPPFLAGS}=${LIBCURL_CPPFLAGS} -> -DCPPFLAGS=${LIBCURL_CPPFLAGS}
> > 2.2. ${CFLAGS}=${LIBCURL_CFLAGS} -> -DCFLAGS=${LIBCURL_CFLAGS}
> 
> I had a hope that it will not needed at all when we'll move from autotools to CMake. I mean, CMake will add `-isysroot=<SDK_PATH>` for curl on its own as CMake do it for tarantool. @avtikhon Can you verify that it can be dropped?
> 

Right, no need for now.

> > 3.1. ${LDFLAGS}= -> -DLDFLAGS=
> 
> I hope it will not needed if we will not pass LIBCURL_{C,CPP}FLAGS. See the explanation in [0bead60](https://github.com/tarantool/tarantool/commit/0bead6004b9eb8317bc8906122d305563a7dac0d). @avtikhon Please, verify it.
> 

Right, no need for now.

> > 4.3. --enable-shared -> -DBUILD_SHARED_LIBS=OFF
> 
> You're right that the dynamic libcurl library is not used anywhere now. I left it in [7e51aeb](https://github.com/tarantool/tarantool/commit/7e51aebb9cd496b1b50b766ce00bf69a20a6d4b1) with the idea that we'll use it to collect symbols to export from the tarantool executable. It becomes less important with #2971 resolving, but even after this the list of surely exported symbols exists (`src/exports.[ch]`) and maybe it should be populated with libcurl.so symbols. So I think the decision whether we should build the dynamic libcurl library is out of scope of this issue. But let's disable it with a proper comment in the commit message, if it give some problems. Otherwise it would be better to keep it, IMHO.
> 

Right, no need for now, due to already changed in the trunk.

> > 1. no need
> 
> I'll comment per-option below.
> 
> > * ```
> >              --without-brotli
> >   ```
> 
> I'll describe the background a bit. We would understand each other without it, but if someone else will read the discussion, it may be helpful.
> 
> When no `--with[out]-brotli` option is given, configure.ac enables brotli support if libbrotlidec.so (the decoding library) is found by default paths on a build system. As result, libcurl.a requires symbols that are defined in libbrotlidec.so. This is bad for us in different ways.
> 
> First, it'll lead to an `undefined reference to <...>` error at linking tarantool executable. A linker is unable to find symbols that are defined in libbrotlidec.so, but the linker see that code requires it. Why not just add libbrotlidec.so to libraries we link with?
> 
> Our executable should not depend on libraries we don't have in RPM / Deb package dependencies. Otherwise a user will observe `error while loading shared libraries` error if its system does not have brotli library installed. Why not to add the library to RPM / Deb dependencies?
> 
> As far as I see, this encoding is not widely used on HTTP servers, usual choice is gzip. It is not worth the work on verifying that it exists on all supported platforms or introducing extra complexity with conditional build with/without brotli support.
> 
> Back to the change. Curl's CMake logic is different: it has brotli disabled by default. We can remove the option or disable it explicitly: the result will be the same. At least for the current version of curl.
> 
> I would prefer to disable explitily everything that should be disabled, because I don't know how defaults will be changed in a future and I don't want to verify them each time we'll bump new libcurl version.
> 
> Another way is try to keep our CMake files as small as possible and lean on defaults, but see: it neither improves readability (one need to dive into curl's CMakeLists.txt to obtain exact list of enabled or disabled features), nor improves stability (as explained above).
> 
> So I vote to list all options explicitly even when our choice is the same as default.

All default flags explicitly set for now.

**Closed** 2020-10-16 06:53 UTC
Labels: qa
