### ISSUE TITLE
Tarantool does not exit on `os.exit()` when there is a hanging fiber/thread

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#4334] opened 2019-07-10 12:53 UTC
```
local ffi = require('ffi')
local fiber = require('fiber')

ffi.cdef[[
    ssize_t call_my_function(void);
    /*
    #include <unistd.h>
    static ssize_t my_function() {
    	sleep(100);
    	return (ssize_t) 1;
    }

    ssize_t call_my_function(void) {
    	return coio_call(my_function);
    }
    */
]]

local y = ffi.load("./.rocks/lib/tarantool/driver.so")

local abc = function()
    y.call_my_function()
end

local f = fiber.create(function()
    fiber.create(abc)
end)

os.exit(-1)
```

Will hang for 100 seconds

**Comment by LaevusDexter** [comment] 2019-07-29 07:55
That's well defined, and is not a bug, I think.
 
os.exit waits until all fibers are yield to successfully exit

coio_call cannot be canceled, plus it may wait forever. https://github.com/tarantool/tarantool/blob/b6466ac7dc225ed9c70322eaf8c7eca746b54130/src/lib/core/coio_task.c#L289

coio_task_create/execute can be, and has timeout, but for some reason it weren't fit in public C API.
https://github.com/tarantool/tarantool/blob/b6466ac7dc225ed9c70322eaf8c7eca746b54130/src/lib/core/coio_task.c#L240

If I got sources right, even in last case we still should to cancel it manually, so issue is actual and may be considered as feature.

https://github.com/tarantool/tarantool/issues/1970

**Comment by opomuc** [comment] 2019-07-29 09:11
@LaevusDexter you may be right, but I discussed it with the team, and `os.exit` should not wait for every fiber to cancel. `coio_call` cannot be canceled, but it yields at least.

I, personally, think that `coio_task_create` should be published to API, at the same time it should not block Tarantool's exit

**Comment by Gerold103** [comment] 2019-11-24 17:02
The problem is not in the yield. Os.exit() hangs, when tries to terminate coio library. For that it waits until all worker threads terminate. And it can't be fixed. We can't just don't care about these threads, because they may use some resources, buffers from the main thread, which are freed after coio is considered destroyed.

If you want to exit immediately, you shouldn't use os.exit. Try ffi.cdef[[void exit(int status);]], and do ffi.C.exit(-1). This will exit immediately and ungracefully. Os.exit is for a graceful termination with proper resources deallocation, and threads termination.

**Comment by kyukhin** [comment] 2020-04-22 17:39
No feedback for months, closing.

**Closed by kyukhin** 2020-04-22 17:39 UTC
Labels: bug, need feedback
