### ISSUE TITLE
Adding space format does not affect existing tuples

### ISSUE THREAD

**Issue by yurikhan** [tarantool/tarantool#3209] opened 2018-03-02 11:18 UTC
```
$ tarantool --version
Tarantool 1.7.6-19-g9f35a12
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/lib/ccache/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline
CXX_FLAGS:-g -O2 -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof
```

```
tarantool> box.cfg{}
tarantool> box.schema.create_space('foo', {engine='memxt', temporary=true})
tarantool> box.space.foo:create_index('primary', {parts={1, 'string'}})
tarantool> box.space.foo:put{'bar', 1}
tarantool> box.space.foo:format{{name='id', type='string'}, {name='count', type='unsigned'}}
tarantool> box.space.foo:put{'baz', 2}
tarantool> box.space.foo:select('bar')[1].count
---
- null
...
tarantool> box.space.foo:select('baz')[1].count
---
- 2
...
```

Thus, adding a `format` to an existing space is a lot less useful than it might seem after reading the documentation. Basically, you cannot start using field names right away.

I understand that each tuple probably gets the field names when it’s created or updated; indeed, touching a tuple grants it field names:

```
tarantool> box.space.foo:update('bar', {})
tarantool> box.space.foo:select('bar')[1].count
---
- 1
...
```

At the very least, this should probably be mentioned in the documentation.

**Comment by kyukhin** [comment] 2018-03-05 08:25
This issue is duplicate of #3011, which was fixed recently.

**Closed by kyukhin** 2018-03-05 08:25 UTC
