### ISSUE TITLE
better fiber cancel error handling

### ISSUE THREAD

**Issue by bofm** [tarantool/tarantool#4395] opened 2019-07-30 15:16 UTC
Tarantool version: any

OS version: any

### Bug description:

In a fiber it is inconvenient to handle fiber cancellation errors.

### Steps to reproduce:
```lua
localhost:3301> f = fiber.create(function() _, err = pcall(fiber.sleep, 999) end)
---
...

localhost:3301> f:cancel()
---
...

localhost:3301> err
---
- fiber is cancelled
...

localhost:3301> type(err)
---
- cdata
...

localhost:3301> err == "fiber is cancelled"
---
- false
...

localhost:3301> tostring(err) == "fiber is cancelled"
---
- true
...

localhost:3301> err:unpack().type == "FiberIsCancelled"
---
- true
...

localhost:3301> _, err2 = pcall(error, "oh")
---
...

localhost:3301> err2:unpack()
---
- error: '[string "return err2:unpack()"]:1: attempt to call method ''unpack'' (a
    nil value)'
...

localhost:3301> err2
---
- oh
...
```

### Desired behaviour.

We need a simple generic way of checking whether an error is FiberIsCancelled error. Something like this:

```lua
errors = require("errors")

MY_APP_ERROR = { code = 42, message = "unknown error" }

ok, err = pcall(my_function)
if err == errors.FIBER_IS_CANCELLED then
    fiber_teardown()
elseif err == MY_APP_ERROR then
    handle_my_app_error()
end
```

**Comment by kyukhin** [comment] 2019-07-31 10:53
This is actually a duplicate of #1148

**Closed by kyukhin** 2019-07-31 10:53 UTC

**Comment by Totktonada** [comment] 2019-07-31 10:58
To make it clear: we plan to implement a way to check an error type (actually an error code) in the scope of #1148. Don't sure about an application level errors.

**Comment by Totktonada** [comment] 2019-08-01 11:56
See #4398 re application level errors.
