### ISSUE TITLE
tarantoolctl  2.10 doesn't connect to 2.11 tarantool

### ISSUE THREAD

**Issue by Hoodie-Huuuuu** [tarantool/tarantool#8728] opened 2023-06-01 13:34 UTC
I tried to connect to 2.11 tarantool using tarantoolctl 2.10.
local `tarantool` —` 2.10.6-0-g3990f97`
local `tarantoolctl` — `2.10.6-0-g3990f97`
`tarantool` to connect - `2.11.0-rc2-0-g535bac000-r545-gc64`

message: Connection is not established

Then I installed 
`tarantool` and `tarantoolctl` - `2.8.4-0-g47e6bd362`

And everything worked out.

**Comment by locker** [comment] 2023-06-14 11:01
Looks like duplicate of #8745.

**Closed** 2023-06-15 10:20 UTC
